### ISSUE TITLE
No connection between Pc Client and GO

### ISSUE THREAD

**Issue by kameka22** [polygraphene/ALVR#1]
Hello and thanks for your solution.

It's not functional on my GO. My specs : PC Win 10 on ethernet + Go on Wifi 5Ghz. the pc client does not find my GO and still remains in "finding the client" while the app Go is launched and displays me "press connect button on alvr server". I launched the client PC (it shows me "server is alive"). so that does not work ...

For info : Vridge is ok on my GO. It's not a network problem

I've test Wifi <-> Wifi. same result ...

**Comment by Tomozow** [comment]
awesome work!

I'm having the same problem.
my spec : PC Win 10 on ethernet + Oculus Go on Wifi 5Ghz.

I hope that client side also works on Ethanet.

**Comment by polygraphene** [comment]
Hi, kameka22 and Tomozow.
Thanks for the report!

Can you paste the result of following adb command?
`adb shell ping -c 5 (IP Address of PC)`

And please check the firewall settings.
ALVR server uses udp 9944 port (incoming).

If you can get work, a device is appeared like following screenshot.
![screenshot_gui](https://user-images.githubusercontent.com/2751376/40584993-1367f742-61e6-11e8-922c-4526e541b4ba.png)

**Comment by Tomozow** [comment]
thank you for reply!
My results here.

PING 10.0.1.11 (10.0.1.11) 56(84) bytes of data.
64 bytes from 10.0.1.11: icmp_seq=1 ttl=128 time=1001 ms
64 bytes from 10.0.1.11: icmp_seq=2 ttl=128 time=921 ms
64 bytes from 10.0.1.11: icmp_seq=3 ttl=128 time=7.42 ms
64 bytes from 10.0.1.11: icmp_seq=4 ttl=128 time=7.55 ms
64 bytes from 10.0.1.11: icmp_seq=5 ttl=128 time=292 ms

--- 10.0.1.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4007ms
rtt min/avg/max/mdev = 7.420/446.323/1001.988/434.445 ms

I set up a firewall, but It did not work well.

**Comment by kameka22** [comment]
This is ok for me. It's a problem with the firewall of Windows. After disable the firewall. The pc client find my Go. The quality is just OUAaaaah ... terrible !!!!! Thanks @polygraphene ! You are a boss !

**Comment by kameka22** [comment]
not the opposite, the performances are really great. Much better than Vridge (but it is not officially supported). It's really very good job!

**Comment by polygraphene** [comment]
Oh! It was a great news!
I misunderstood 😉
Thank you for report!

Enjoy the good VR life! 👍

**Comment by Tomozow** [comment]
I'm sorry @polygraphene !
I seem to have not installed the driver.
Now it's working perfectly !

Thank you for your support and very good work.

**Comment by polygraphene** [comment]
Congrats!
Installation of driver is a little bit confusing.
I will introduce auto driver installation on future release.

Thanks!
