### ISSUE TITLE
Trackpad not perfect on Oculus GO

### ISSUE THREAD

**Issue by davinux** [polygraphene/ALVR#10]
First of all, CONGRATS!. What a great project!. It works really well and it's amazing the improvement compared to any other solutions out there.

I'm using v1.7 and the control of my Oculus Go is working pretty well with some number of buttons limitations (I was expecting that), but seems like the trackpad is working, but not perfectly. The click is working perfectly, but the movement with the trackpad is not. You can see what I'm saying if you start Google Earth VR and try to move around. The trackpad seems to be working up and down backwards and just one small portion on the trackpad is usuable.

Again!, congrats on the project, really looking forwad to see how far you can get it!. THANKS!

**Comment by polygraphene** [comment]
Thank you for comment!
Trackpad position was wrongly reported to SteamVR.
Now this bug is fixed.
