### ISSUE TITLE
Black screen after "Connect" Galaxy S8

### ISSUE THREAD

**Issue by trexturtle** [polygraphene/ALVR#100]
When I press connect it's turn to black screen .
But, when open mirror mode on steam vr it's still tracking where i'm looking.

**Comment by polygraphene** [comment]
Please tell me following information.
1. Version of ALVR client/server
2. OS version of PC
3. Graphic card model

And if you can, please upload the output of `adb logcat`.

**Comment by trexturtle** [comment]
I'm using v2.2.1-alpha for server.
and tested both 2.1.5 and 2.1.4 on client side.
Windows 10 with GTX1060 6gb.
how to get adb log?

**Comment by vrokolos** [comment]
This usually happens because of packet loss. Check your packet loss on the server during streaming

**Comment by trexturtle** [comment]
how to check if something wrong with packet loss?

**Comment by vrokolos** [comment]
on the server tab there is packet loss info. also you need client 2.2 for newer servers

**Comment by polygraphene** [comment]
> 2.1.5 and 2.1.4 on client side.

That's too bad! v2.2.1-alpha is only compatible for client v2.2.0-alpha.
And I forgot to show error about it! Sorry.

**Comment by polygraphene** [comment]
Install v2.2.0-alpha client by adb or use v2.1.5 server.

**Comment by trexturtle** [comment]
oh.... you have the links to 2.2 client? I only seen 2.1.5 client.

**Comment by polygraphene** [comment]
here. https://github.com/polygraphene/ALVRClient/releases

But you need osig file and adb to install. You cannot install 2.2.0 on Store.
I recommend to use 2.1.5 server.

**Comment by trexturtle** [comment]
That's alright I found it. one more thing what the different between ARCore version and normal?

**Comment by trexturtle** [comment]
Thank you. it's working now!
