### ISSUE TITLE
SteamVR does not find ALVR as an Headset 

### ISSUE THREAD

**Issue by Keinhirnmensch** [polygraphene/ALVR#103]
SteamVR does not find ALVR as an Headset. The Display shows the Error Code 108. I dont know what to do pls help me 

thank you all in advance keinhirnmensch

**Comment by polygraphene** [comment]
Duplicate #58, #95?

**Comment by polygraphene** [comment]
Try update of NVIDIA graphic driver.
Please tell me the followings.
1. Windows OS version
2. 64bit/32bit
3. Graphic card model
4. Version of ALVR server
