### ISSUE TITLE
Using freepie trigger and trackpack click on the controller won't work - v2.2.1

### ISSUE THREAD

**Issue by davinux** [polygraphene/ALVR#104]
After updating to v2.2.1 the trigger and the trackpad click won't work. Not sure if it's related to the freepie implementation, but even without freepie running still not working.

BTW, Amazing work!, looking forward to playing more with freepie and ps move!.

**Comment by polygraphene** [comment]
Once you launch FreePIE, controller button assign is disabled until you restart SteamVR.
If you are using FreePIE script, you must implement button assign yourself.

**Comment by davinux** [comment]
Thanks!. I've made some changes to the FreePIE script and it's working now.
