### ISSUE TITLE
WAVE_FORMAT_EXTENSIBLE Init fail

### ISSUE THREAD

**Issue by sols000** [polygraphene/ALVR#105]
Hi,ALVR
AudioCapture.h in line  470 pwfx run the code below:
`		case WAVE_FORMAT_EXTENSIBLE:
		{
			// naked scope for case-local variable
			PWAVEFORMATEXTENSIBLE pEx = reinterpret_cast<PWAVEFORMATEXTENSIBLE>(pwfx);
			Log("PWAVEFORMATEXTENSIBLE: SubFormat=%d wValidBitsPerSample=%d"
				, pEx->SubFormat, pEx->Samples.wValidBitsPerSample);
			if (IsEqualGUID(KSDATAFORMAT_SUBTYPE_IEEE_FLOAT, pEx->SubFormat)) {
				pEx->SubFormat = KSDATAFORMAT_SUBTYPE_PCM;
				pEx->Samples.wValidBitsPerSample = 16;
				pwfx->wBitsPerSample = 16;
				pwfx->nBlockAlign = pwfx->nChannels * pwfx->wBitsPerSample / 8;
				pwfx->nAvgBytesPerSec = pwfx->nBlockAlign * pwfx->nSamplesPerSec;
			}
			else {
				throw MakeException("%s", L"Don't know how to coerce mix format to int-16");
			}
		}`

And hr = pAudioClient->Initialize(...)

there are serveral Audio device in my pc,And device name with ASCLL Chars works correctly,but device name with UTF-8 word Will Return  AUDCLNT_E_UNSUPPORTED_FORMAT.How to solve this issue.
ps.
Emm, I Tested other Device with UTF-8 word ,Works fine,Only One Device failed.

**Comment by polygraphene** [comment]
Is the error produced if you comment out following codes?
```
				pEx->SubFormat = KSDATAFORMAT_SUBTYPE_PCM;
				pEx->Samples.wValidBitsPerSample = 16;
				pwfx->wBitsPerSample = 16;
				pwfx->nBlockAlign = pwfx->nChannels * pwfx->wBitsPerSample / 8;
				pwfx->nAvgBytesPerSec = pwfx->nBlockAlign * pwfx->nSamplesPerSec;
```

I don't know what types of device you use, the device may not support 16bit sample format.
If that's true, we can use native sample format for the device and convert to 16bit by ourselves.

**Comment by sols000** [comment]
Hi, @polygraphene 
I solved is issue, but may not be a good way, 
RightClick the sound tray icon --> Sound Device --> Play(tab) --> Right click(the not work device)Property --> Advance(tab) --> In combox change into : 16bit,48000Hz(DVD) .
the previous selected item  is : 16bit,96000Hz(...).

**Comment by polygraphene** [comment]
96kHz or other sample rates are supported above v2.2.0-alpha.
If you are using v2.1.5, this issue will be solved on next stable release.
