### ISSUE TITLE
Crash H.265 in GTX 750 Ti

### ISSUE THREAD

**Issue by coponhub** [polygraphene/ALVR#106]
ALVR Crashed when start server with selected H.265 HEVC Codec
My GPU is Geforce GTX 750Ti Driver 398.36

This is Crash report

> NvEnc CreateEncoder failed. Code=8 NvEncoder::CreateEncoder :   m_nvenc.nvEncInitializeEncoder(m_hEncoder, &m_initializeParams) returned error 8 at c:\src\alvr\alvr_server\nvencoder.cpp:271

**Comment by polygraphene** [comment]
Thank you for report.
GTX 750 Ti does not support H.265.
https://forums.geforce.com/default/topic/894633/gtx-750-ti-nvenc-hevc/

**Comment by Haylefal** [comment]
I've got a 770gtx and get the same error. Checking the Nvidia list shows h.265 is supported. Any ideas?

**Comment by vrokolos** [comment]
https://developer.nvidia.com/video-encode-decode-gpu-support-matrix
No it doesnt support h265. Use h264
