### ISSUE TITLE
Oculus GO Black screen

### ISSUE THREAD

**Issue by Cantatos** [polygraphene/ALVR#107]
Hi,

After following this guide https://www.windowscentral.com/how-play-steamvr-games-oculus-go, all works SteamVR ready and green, server up and Oculus go client started
but once it starts and all is connected the screen does not show anything, black screen? I can start any app and it shows in the SteamVR app but not in the headset.
I have a Nvidia 970 GPU and I also added the port to my router.

Anyone know what might be wrong?

**Comment by polygraphene** [comment]
What version do you use? Please tell me both client and server version.
If you have installed client on Oculus Store, you must use server v2.1.5.

**Comment by Cantatos** [comment]
server v2.1.5. and client release date June 7

**Comment by Cantatos** [comment]
Also when I launch subnautica it plays on my pc instead of the oculus go

**Comment by Cantatos** [comment]
I can hear stuttering audio in the headset

**Comment by polygraphene** [comment]
You should use client v2.1.5. Please update client on Oculus Store.

**Comment by Cantatos** [comment]
I'm not able to see what client version it is , only release date June 7. When I click update it shows all Library up to date?

**Comment by Cantatos** [comment]
PC Client is 2.1.5

**Comment by Cantatos** [comment]
Oh it is 2.1.5 it shows when I start it..

**Comment by Cantatos** [comment]
Press connect done and black screen and stuttering sound on the headset... 
![error](https://user-images.githubusercontent.com/40702323/42112376-7f5e65fe-7bdf-11e8-9cdb-c8d5fb299a0d.JPG)

**Comment by polygraphene** [comment]
Oh. Sorry. I didn't know Oculus Store does not provide version info.

Hmm...
Your screen shot shows a bad packet losses...

**Comment by Cantatos** [comment]
![steamvr](https://user-images.githubusercontent.com/40702323/42112429-ad8a3200-7bdf-11e8-806d-d325a7e2ffff.JPG)

**Comment by polygraphene** [comment]
Please try small bitrate and large buffer size on Video tab.

**Comment by Cantatos** [comment]
![missed frames](https://user-images.githubusercontent.com/40702323/42112499-e3e5cabc-7bdf-11e8-9349-39ca7af8233d.JPG)

**Comment by polygraphene** [comment]
PC side has no problem.
I think this is a network issue.
Are you using 5GHz Wi-Fi?

**Comment by Cantatos** [comment]
No I didn't know I could use 5g with oculus go

**Comment by Cantatos** [comment]
Let me try

**Comment by polygraphene** [comment]
This issue is hard to debug...
Can you use 5G Wi-Fi on another devices? (like smartphone or PC)
How far your Wi-Fi router from Oculus Go?

**Comment by Cantatos** [comment]
Ok all done, and playing around with bitrate and buffer size and while I can get it a bit better it keeps dropping frames.

**Comment by polygraphene** [comment]
ALVR can not work properly on bad network environment.
I think you should solve 5GHz issue before trying to use ALVR.

**Comment by Cantatos** [comment]
I have it connected to 5Ghz now

**Comment by polygraphene** [comment]
Do you also get packet loss on 5GHz?

**Comment by Cantatos** [comment]
Yes, my wifi speed test in the headset is 30Mbps 
- my wired connection is 380Mbps
- I switch on DMC server on the Oculus GO IP 
- also turned on PC network and printer sharing 
- Youtube videos run fine even 4k
- Losing almost 300 packages per second

**Comment by Cantatos** [comment]
SentRate only 4.1 Mbps..
This is strange... also Bigscreen stream works fine.

**Comment by polygraphene** [comment]
Thank you for detailed information!

>Yes, my wifi speed test in the headset is 30Mbps
>my wired connection is 380Mbps

In a normal 5GHz Wi-Fi environment, you can get more high bandwidth in headset.
There is something wrong with your Wi-Fi.

>SentRate only 4.1 Mbps.. went up to 20Mbps

It is not a problem. NVENC sometimes does not fully use bitrate. If you see the simple picture like completely black screen, bitrate become lower than you specified.

The screen shot shows a bad latency, but this is not a problem if you ping from PC to Go. I think this is because of some Wi-Fi optimization function.
You can get more accurate result by ping from Go to PC using adb shell.

Did try to restart Wi-Fi router?
And, if you can, try another Wi-Fi router.

**Comment by Cantatos** [comment]
Thanks for your replies reply appreciate your help. (By the way ALVR version is v2.2.1 Alpha)

Rebooted the the Router, WiFi settings in the headset went from 100+Mbps to 800+Mbps however only getting around 40Mbps broadband speed test.

Still getting tons of frame drops. 
When performing a Ping test from the Oculus Go does not show any abnormalities.
Unfortunately no other router to test.

![result](https://user-images.githubusercontent.com/40702323/42121253-41956940-7c23-11e8-8f15-6864c7333c3c.JPG)

**Comment by polygraphene** [comment]
>Rebooted the the Router, WiFi settings in the headset went from 100+Mbps to 800+Mbps however only getting around 40Mbps broadband speed test.

Hmm... In your Internet environment, in general, you can get above 100Mbps even on Oculus Go.

>Ok I observed something strange, when I ping the Oculus GO when idle and asleep ping is Min 120 ms Max 377 ms, When on in normal active UI it improves from Min 3 ms Max 377 ms, however overall its improved a lot. Now here is the crazy bit when I ping test during ALVR connection it shows Min 2ms Max 8ms ....
Also note that not a single packet drops yet in the ALVR its dropping 40+%

I think that is standard behavior. On my Galaxy S8, I also get 3 ~ 100ms when normal and get 3~6ms when ALVR is working.
I think it is because of power saving function of Wi-Fi on Android. And not related on this issue.

**Comment by Cantatos** [comment]
Ok, installed ALVR-v2.1.5-portable.zip and its working ... Alpha 2.2.1 does not work on my Oculus Go

![test](https://user-images.githubusercontent.com/40702323/42121904-49ef239e-7c30-11e8-9018-4948ecd61cd3.JPG)

**Comment by Cantatos** [comment]
No problem at all :) Does that mean your latest version works as well? Also could you add the ideal Native resolution for the Oculus GO?

**Comment by polygraphene** [comment]
If you install client 2.2.0 with adb, I think you can use with v2.2.1 server.

>Also could you add the ideal Native resolution for the Oculus GO?

Video resolution? Video will be distoted on display in Go, so native resolution is meaningless.
Check #32

**Comment by wontolla** [comment]
Hi.

I´m getting the same issue in 2.2.1, black screen in Samsung Gear VR, test in a S7 & S8, change buffer an resolution parameters unsuccessfully . ALVR detects and connects but nothing is shown, lots a packages dropped too, my Wi-Fi is 5GHz only so I don´t believe the problem is the network.
