### ISSUE TITLE
Server running, VRsteam running, cannot find headset

### ISSUE THREAD

**Issue by Polarborn** [polygraphene/ALVR#108]
Cannot find headset.  SteamVR shows green octagon flashing, says to run room setup - can't of course without headset.  Uninstalled driver, installed driver - only one driver listed.  Pasting Debug log, Netstat printout.  Headset running 2.1.5 and sates hit connect button - no connect button  - headset not found. 

[driver.log](https://github.com/polygraphene/ALVR/files/2150822/driver.log)
[ALVR Netstat Printout.txt](https://github.com/polygraphene/ALVR/files/2150823/ALVR.Netstat.Printout.txt)

**Comment by polygraphene** [comment]
Please check firewall configuration on your PC. And confirm that the PC and headset are connected to same router.
#62 is similar issue. Please refer it.

**Comment by Polarborn** [comment]
Thank you for all your help.  Confirmed port is open - I think.  Attaching screenshot from Wireshark. Also latest log from ALVR.
[driver (1).log](https://github.com/polygraphene/ALVR/files/2151985/driver.1.log)
![capture](https://user-images.githubusercontent.com/40604372/42126920-9034692c-7c5d-11e8-85e1-1a39acfdceeb.PNG)
![image](https://user-images.githubusercontent.com/40604372/42126926-a51af220-7c5d-11e8-91d0-950ca560ddc8.png)

**Comment by polygraphene** [comment]
You can see the packet by WireShark and the log says ALVR server didn't get packet. I think it means firewall issue.
Please re-check firewall settings. Try to open UDP/9944 for "all" profile(private and public).

If you tried that, please check https://github.com/polygraphene/ALVR/issues/62#issuecomment-398796318

**Comment by polygraphene** [comment]
@Polarborn Great!

>BTW tried Star Trek Bridge Crew with Xbox Controller - works great.

Thank you for information!
