### ISSUE TITLE
Feature request: rotational offset

### ISSUE THREAD

**Issue by Lightsteed** [polygraphene/ALVR#110]
Hi, again brilliant work on this software! I have been testing ALVR in combination with driver4vr to get 6dof head tracking and controllers with vive lighthouse tracker/controllers. It works quite good, however it would be great to have a way to fine tune the horizontal rotation (yaw i think) so that the orientation in alvr exactly aligns with the driver4vr/vive orientation. The d4vr driver does not touch the hmd orientation as doing so causes bad tracking  and big black bars, i think due to the ATW you are using, so it would be better if you cam provide a rotation offset to fix that. I know that the reset position button does exactly this, however its quite hard to get it exactly right so a fine tune method would help. Thanks!

**Comment by polygraphene** [comment]
Thank you!

I think your request is reasonable and required, but I haven't implemented yet.
Because I couldn't implement conversion from quaternion to yaw,pitch,roll correctly.
That's a head aching mathematical issue for my brain...
Please be patient.

**Comment by gb2111** [comment]
hi.
i have same head aching problem. also best is to find one that work both ways.
this one worked for me
https://gist.github.com/aeroson/043001ca12fe29ee911e#file-myquaternion-cs-L122

**Comment by nrgapple** [comment]
Any update on this?

**Comment by BenWoodford** [comment]
I’d quite like to see this as well, it would be fantastic for when trying to setup a system for multiple players in one space (albeit a more automatic system would be amazing but a significant amount of work to get right)
