### ISSUE TITLE
automatically connect to headset ?

### ISSUE THREAD

**Issue by gb2111** [polygraphene/ALVR#112]
hi.
i am sure many people thought about it but I cannot find any issue reported :)
is there plan to make server automatically connected to headset when it is detected ?

Greg

**Comment by VRtinker** [comment]
That's already happening. Obviously the client must be running to auto-connect to the server. Once you establish the connection once, there is an option you can put a check-mark on to auto-connect that given device any time the client is running. Sorry, but you pretty much need to be blind to miss that! :-P It's right in the first tab of the server (the one named "Server"), where you get all the stats about the connection etc.

**Comment by gb2111** [comment]
thanks :)
