### ISSUE TITLE
Freepie conecction GOcontroller and possitional tracking.

### ISSUE THREAD

**Issue by chapeka** [polygraphene/ALVR#115]
Let's see the connection Freepie looks cool to me. I would like to know what applications you have used apart from the freepie itself and the hardware. For the positioning I think you will have used 3 ps3 cameras and one LED ball or a psmove, how do you connect the 3dof controller? Is it a GO controller or gear vr ?, the connection will be clear bluetooth, with what application? ?, what is the script to join it with freepie?

Thank you very much.

**Comment by chapeka** [comment]
Do you think is possible integrate this kit¿?¿??¿ is posbible works beeter than NOLO VR¿?

http://antilatency.com/

**Comment by vincerex71** [comment]
sorry if I have a Gear VR controller, can I connect it via FreePie with the oculus go controller?

**Comment by polygraphene** [comment]
There are no implementation of FreePIE plugin for Gear VR controller, i think.
I've found only [JavaScript implementation](http://jsyang.ca/hacks/gear-vr-rev-eng/) yet.
