### ISSUE TITLE
How do you Update the Headset Client?

### ISSUE THREAD

**Issue by cameronwiebe1** [polygraphene/ALVR#117]
I'm using 2.2.2 on PC, but 2.1.5 on Headset. How do I update it to the correct version?

**Comment by polygraphene** [comment]
Use adb to install apk.
If you can't use adb, please use server 2.1.5.

**Comment by Jbbrack03** [comment]
If you install it through the Oculus Store, is it supposed to automatically update as you push out new releases?

**Comment by polygraphene** [comment]
If I remember correctly, when the new release is available, you can see Start button is changed to Update button on Oculus Store.
I can't remember if you can continue to use old version after the release.

**Comment by gb2111** [comment]
what is the rule to keep versions aligned? they need have two numbers same?

**Comment by gb2111** [comment]
so minor update is 3rd number and it does not break compatibility. right? at least by purpose?
