### ISSUE TITLE
FPS changing to 60

### ISSUE THREAD

**Issue by fdinsdale** [polygraphene/ALVR#118]
Is anyone else seeing this happen?

When I'm connected and streaming to my OGo with Elite Dangerous for example. I can see in the server tab and also the debug tab that the connected FPS is 72. It displays that frame rate as long as I'm connected. If I remove the HMD to do something and it goes to sleep when I reconnect to the server the FPS falls  to 60. It will stay at that rate until I quit everything and relaunch.

I'm running v2.1.5 server and client and for the most part this app works really well. 
Thanks!

**Comment by polygraphene** [comment]
I think this is a bug of recovering connection on resume app.
And it is fixed in alpha version, i think.
Please try when next stable is released.

If correct, it is just a notation bug. Real FPS is 72 even when the bug occurs.

**Comment by saintkamus** [comment]
"When I'm connected and streaming to my OGo with Elite Dangerous for example. I can see in the server tab and also the debug tab that the connected FPS is 72. "

You mean the refreshrate right? because the FPS are not even close to 60 or 72 on the headset.

**Comment by fdinsdale** [comment]
On the server tab its called FPS and on the debug tab its called refresh rate. Either way I think you're right, what's getting to the headset display seems to be less than 60. I notice the chop more on Xplane 11 than ED.
My hardware setup for wifi is 802.11ac and a Ethernet connection from my PC to the n600 router

I imagine we will see improvements with forthcoming versions. For me I'm happy to have the use of my OGo for steam vr apps.

**Comment by polygraphene** [comment]
@saintkamus Yes. The value means refresh rate.

@fdinsdale Does the issue appear in all games?
I wrote how to check FPS on https://github.com/polygraphene/ALVR/issues/116#issuecomment-402032841
If you can use adb, please try.

**Comment by fdinsdale** [comment]
It did that running Xplane 11 also.  Even just running steam vr without an app/game it happens.
