### ISSUE TITLE
MalwareBytes Quarentine Triggered

### ISSUE THREAD

**Issue by redforeststudios** [polygraphene/ALVR#12]
Malwarebytes quarantines the exe via it's Machine Learning engine:
MachineLearning/Anomalous.94%

**Comment by redforeststudios** [comment]
I went ahead and submitted a false positive report for you to MB. Hopefully, this will help your future users.
https://forums.malwarebytes.com/topic/230815-possible-false-positive-alvr/

**Comment by redforeststudios** [comment]
They've fixed it for you, no more false positive for Malwarebytes users :)

**Comment by polygraphene** [comment]
Thank you so much for your great work!
