### ISSUE TITLE
failed to start audio capture.

### ISSUE THREAD

**Issue by ciddester** [polygraphene/ALVR#120]
Failed to start audio capture. Thread aborted before starting to loopback capture. message=IAudioClient::Initialize failed: hr = 0x88890008

I get that massage over and over.
Processor I7-7700
GPU 1070

**Comment by sols000** [comment]
see #105 .

**Comment by ciddester** [comment]
How can I fix it? I re-installed Steam several times and even reset my
computer. The problem just persist no matter what I try. Before the massage
came out I manage to connect but had a black screen. Several minutes after
that error started to show up.

On Jul 2, 2018 10:39 PM, "冉瑞元" <notifications@github.com> wrote:

see #105 <https://github.com/polygraphene/ALVR/issues/105> .

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/polygraphene/ALVR/issues/120#issuecomment-401995508>,
or mute the thread

**Comment by sols000** [comment]
RightClick the sound tray icon --> Sound Device --> Play(tab) --> Right click(the not work device)Property --> Advance(tab) --> In combox change into : 16bit,48000Hz(DVD) .
What's your ALVR version?  v2.1.5 has this problem.

**Comment by ciddester** [comment]
I do have version 2.1.5. After lowering the sound format to 16bit 48000hz I still have that problem. Plus now I get another: wrong version

**Comment by sols000** [comment]
To make sure the apk verision is v2.1.5.

**Comment by ciddester** [comment]
I got it to work. Thank you so much.

**Comment by ciddester** [comment]
Got it to work. Thank you for all the help.
Thanks

**Comment by silvertenchu** [comment]
Ciddester, mine has the same problem how you make it work teach me!!!

**Comment by BeckettOBrien** [comment]
I am also experiencing this issue on both the latest release and the latest stable release (2.31) where I also experience "SteamVR has encountered a critical error" from steam itself. Also, what do you mean by "the sound tray icon"? Please help

**Comment by rajkopk** [comment]
Un-check "enable audio enhancements"under Speaker properties\advanced

Worked for me
MSI GS75 stealth
