### ISSUE TITLE
How to adjust openvr distortion?

### ISSUE THREAD

**Issue by sols000** [polygraphene/ALVR#121]
I found that when I tilt my head to the side, the ground in Steamvr Home  distortion is obvious.
so, how to adjust the distortion in  vr::IVRDisplayComponent or other component.  I tested on Oculus Go.

**Comment by polygraphene** [comment]
What types of distortion? Can you get the screenshot of the issue?
I tried SteamVR Home but I didn't find the problem.

**Comment by polygraphene** [comment]
Okay, I experience the some sort of distortion on your setting.
I have Gear VR and I don't get any distortion on default settings.
So we may need to change that values for Oculus Go.

**Comment by sols000** [comment]
emm, I'v tested on sumsung S7, still have the same problem.
 tilt head side  to side.

**Comment by polygraphene** [comment]
Weird...
Did try another value like +-1.2?

**Comment by sols000** [comment]
Not yet,I will have a try.
