### ISSUE TITLE
ARCore Tracking

### ISSUE THREAD

**Issue by regnighc** [polygraphene/ALVR#123]
Is it possible to create some kind of printable labels or stickers that could be placed around the room to help ARCore to track better?

**Comment by regnighc** [comment]
There seems to be an issue for me where i get ported a few steps backwards from time to time, in relation to the above I managed to reduce the frequency that this happens by putting fluorescent post it notes around the area and adding additional light, I think this has helped ARCore to pick up on visible edges and object however it still pushes me backwards a little. Any tips to resolve this? I tried setting -1 on the debugging page but it just makes the content shake and stutter really badly.

**Comment by polygraphene** [comment]
I also want to know it if there is.

But I think it may be a limitation of ARCore. ARCore is made for AR and relies on single camera. It can't provide the performance like Mirage Solo or other inside-out tracking devices.

**Comment by sigmaxipi** [comment]
The core problem is that the field of view on phone cameras is much smaller than the field of view on inside-out headsets. HMDs have fisheye cameras with >100 degrees FOV. But phone cameras are designed for nice photographs. If all the camera sees is a blank wall, there is a high chance of it losing tracking. Using post it notes that are the opposite color of the wall can help. Valve's early prototypes used a [special room](https://youtu.be/itLuNFfrFW0?t=79) for inside-out tracking.

You can also install an ArCore app on your phone and see how well it tracks the various parts of your room. Having posters or unique images on your walls should help.
