### ISSUE TITLE
Great,I have made ALVR  suport 6Dof VR，thank you so much!

### ISSUE THREAD

**Issue by sols000** [polygraphene/ALVR#124]
Hei, @polygraphene 
 I have made ALVR suport 6Dof, and have a great experience. it is much better than Riftcat and Trinus.
My position tracker is nolo . and Hmd is Oculus Go.
Thank you so much, You are the greatest developer in the world!
Some small issue exist, I will try to solve that.

**Comment by Tux0Topo** [comment]
Mind to explain the steps for it?

**Comment by sols000** [comment]
@Tux0Topo  I‘v asked nolo for their controler driver and SDK，Alvr-client get hmd position and send hmd position to alvr driver. that will take effect.

**Comment by burhancam** [comment]
hello, you can tell me how you run oculus go with nolo vr.

**Comment by sols000** [comment]
Nolo provide a SDK  that can run on android os,we can get nolo devcie data from it. Cnnect the nolo hmd tracker and Oculus GO with a usb cable.

**Comment by Shannonb1** [comment]
so will this be in 1.4.1? When will this release?

**Comment by Woohaaa** [comment]
Can you explain the steps clearly?

**Comment by sols000** [comment]
As far as I know, Nolo will publish the release At the beginning of August,may be earlier.

**Comment by sols000** [comment]
1.Get the nolo android sdk
2.In Alvr client, get Hmd position data using nolo sdk and send to Alvr server.
3.Register nolo controller driver to enable their controller
