### ISSUE TITLE
Left eye only on S9+ GearVR

### ISSUE THREAD

**Issue by wreck145** [polygraphene/ALVR#125]
2.2.2 server works OK, finds, connects and streams SteamVR to headset.

However, the headset only displays the left eye. Right eye is completely black.

Same issue for both 2.2.2 ARCore client and normal client

Samsung S9+ and GearVR R325

**Comment by regnighc** [comment]
I have the same but when you launch a game its fine, have you tried launching something?

**Comment by wreck145** [comment]
Yes, I tried launching Subnautica, right eye is still completely black. What game did you try it with?

**Comment by polygraphene** [comment]
Can you get the output of `adb logcat`?

**Comment by wreck145** [comment]
Not sure if I'm doing this correctly, but I just used CatLog for Android. I don't have adb on my Windows10 PC

`07-05 14:41:16.007 D/ViewRootImpl@5c24c63[Please wait]( 9045): MSG_RESIZED_REPORT: frame=Rect(316, 1082 - 1124, 1680) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
07-05 14:41:16.032 D/ViewRootImpl@a0c61b1[ShowRecordLogDialogActivity]( 9045): MSG_WINDOW_FOCUS_CHANGED 0
07-05 14:41:16.038 D/ViewRootImpl@5c24c63[Please wait]( 9045): dispatchDetachedFromWindow
07-05 14:41:16.038 D/InputEventReceiver( 9045): channel 'cf19cf1 Please wait (client)' ~ Disposing input event receiver.
07-05 14:41:16.038 D/InputEventReceiver( 9045): channel 'cf19cf1 Please wait (client)' ~NativeInputEventReceiver.
07-05 14:41:16.042 E/propClient(19518): PropClient failed to load
07-05 14:41:16.070 D/ViewRootImpl@a0c61b1[ShowRecordLogDialogActivity]( 9045): MSG_WINDOW_FOCUS_CHANGED 1
07-05 14:41:16.073 E/ViewRootImpl( 9045): sendUserActionEvent() returned.
07-05 14:41:16.111 D/ViewRootImpl@4e02278[LogcatActivity]( 9045): MSG_WINDOW_FOCUS_CHANGED 1
07-05 14:41:16.112 V/InputMethodManager( 9045): Starting input: tba=android.view.inputmethod.EditorInfo@2605b78 nm : com.nolanlawson.logcat ic=null
07-05 14:41:16.112 I/InputMethodManager( 9045): startInputInner - mService.startInputOrWindowGainedFocus
07-05 14:41:16.113 D/ViewRootImpl@a0c61b1[ShowRecordLogDialogActivity]( 9045): MSG_WINDOW_FOCUS_CHANGED 0
07-05 14:41:16.147 D/ViewRootImpl@a0c61b1[ShowRecordLogDialogActivity]( 9045): Relayout returned: old=[0,961][1440,1800] new=[0,961][1440,1800] result=0x5 surface={valid=false 0} changed=true
07-05 14:41:16.151 D/ViewRootImpl@1e8f3b7[Toast]( 9045): setView = android.widget.LinearLayout{fbb724 V.E...... ......I. 0,0-0,0} TM=true MM=false
07-05 14:41:16.151 V/Toast   ( 9045): Text: Mog  in android.widget.Toast$TN@6d2228d
07-05 14:41:16.180 D/ViewRootImpl@1e8f3b7[Toast]( 9045): dispatchAttachedToWindow
07-05 14:41:16.186 V/Surface ( 9045): sf_framedrop debug : 0x4f4c, game : false, logging : 0
07-05 14:41:16.186 D/ViewRootImpl@1e8f3b7[Toast]( 9045): Relayout returned: old=[0,0][0,0] new=[361,2407][1078,2568] result=0x7 surface={valid=true 495991808000} changed=true
07-05 14:41:16.187 D/ViewRootImpl@1e8f3b7[Toast]( 9045): MSG_RESIZED_REPORT: frame=Rect(361, 2407 - 1078, 2568) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
07-05 14:41:16.246 D/ViewRootImpl@a0c61b1[ShowRecordLogDialogActivity]( 9045): dispatchDetachedFromWindow
07-05 14:41:16.246 D/InputEventReceiver( 9045): channel '4f4c48b com.nolanlawson.logcat/com.nolanlawson.logcat.ShowRecordLogDialogActivity (client)' ~ Disposing input event receiver.
07-05 14:41:16.246 D/InputEventReceiver( 9045): channel '4f4c48b com.nolanlawson.logcat/com.nolanlawson.logcat.ShowRecordLogDialogActivity (client)' ~NativeInputEventReceiver.
07-05 14:41:18.139 D/ViewRootImpl@1e8f3b7[Toast]( 9045): dispatchDetachedFromWindow
07-05 14:41:18.140 D/InputEventReceiver( 9045): channel '5dc47 Toast (client)' ~ Disposing input event receiver.
07-05 14:41:18.140 D/InputEventReceiver( 9045): channel '5dc47 Toast (client)' ~NativeInputEventReceiver.
07-05 14:41:21.102 D/ViewRootImpl@4e02278[LogcatActivity]( 9045): MSG_WINDOW_FOCUS_CHANGED 0
07-05 14:41:21.128 D/ViewRootImpl@4e02278[LogcatActivity]( 9045): Relayout returned: old=[0,0][1440,2678] new=[0,0][1440,2678] result=0x5 surface={valid=false 0} changed=true
07-05 14:41:21.203 D/ViewRootImpl@4e02278[LogcatActivity]( 9045): Relayout returned: old=[0,0][1440,2678] new=[0,0][1440,2678] result=0x1 surface={valid=false 0} changed=false
07-05 14:41:34.173 V/Configuration( 9045):  needToUpdateOverlays
07-05 14:41:34.174 V/Configuration( 9045):  needToUpdateOverlays
07-05 14:41:58.053 V/Configuration( 9045):  needToUpdateOverlays
07-05 14:41:58.053 V/Configuration( 9045):  needToUpdateOverlays
07-05 14:42:00.203 D/ViewRootImpl@4e02278[LogcatActivity]( 9045): Relayout returned: old=[0,0][1440,2678] new=[0,0][1440,2678] result=0x1 surface={valid=false 0} changed=false
07-05 14:42:00.219 V/Surface ( 9045): sf_framedrop debug : 0x4f4c, game : false, logging : 0
07-05 14:42:00.220 D/ViewRootImpl@4e02278[LogcatActivity]( 9045): Relayout returned: old=[0,0][1440,2678] new=[0,0][1440,2678] result=0x7 surface={valid=true 496042061824} changed=true
07-05 14:42:00.226 D/ViewRootImpl@4e02278[LogcatActivity]( 9045): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1440, 2678) ci=Rect(0, 84 - 0, 0) vi=Rect(0, 84 - 0, 0) or=1
07-05 14:42:00.233 D/ViewRootImpl@4e02278[LogcatActivity]( 9045): Relayout returned: old=[0,0][1440,2678] new=[0,0][1440,2678] result=0x3 surface={valid=true 496042061824} changed=false
07-05 14:42:00.260 D/ViewRootImpl@4e02278[LogcatActivity]( 9045): MSG_WINDOW_FOCUS_CHANGED 1
07-05 14:42:00.266 V/InputMethodManager( 9045): Starting input: tba=android.view.inputmethod.EditorInfo@f1453 nm : com.nolanlawson.logcat ic=null
07-05 14:42:00.266 I/InputMethodManager( 9045): startInputInner - mService.startInputOrWindowGainedFocus
07-05 14:42:02.604 D/ViewRootImpl@4e02278[LogcatActivity]( 9045): ViewPostIme key 0
07-05 14:42:02.671 D/ViewRootImpl@4e02278[LogcatActivity]( 9045): ViewPostIme key 1
07-05 14:42:02.675 D/ViewRootImpl@66ca2af[LogcatActivity]( 9045): setView = DecorView@49aafd9[LogcatActivity] TM=true MM=false
07-05 14:42:02.677 V/InputMethodManager( 9045): Not IME target window, ignoring
07-05 14:42:02.678 D/ViewRootImpl@66ca2af[LogcatActivity]( 9045): dispatchAttachedToWindow
07-05 14:42:02.686 V/Surface ( 9045): sf_framedrop debug : 0x4f4c, game : false, logging : 0
07-05 14:42:02.686 D/ViewRootImpl@66ca2af[LogcatActivity]( 9045): Relayout returned: old=[0,0][0,0] new=[0,2172][1440,2678] result=0x7 surface={valid=true 495991808000} changed=true
07-05 14:42:02.711 D/ViewRootImpl@66ca2af[LogcatActivity]( 9045): MSG_WINDOW_FOCUS_CHANGED 1
07-05 14:42:02.711 V/InputMethodManager( 9045): Not IME target window, ignoring
07-05 14:42:02.712 D/ViewRootImpl@66ca2af[LogcatActivity]( 9045): MSG_RESIZED_REPORT: frame=Rect(0, 2172 - 1440, 2678) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
07-05 14:42:02.715 D/ViewRootImpl@66ca2af[LogcatActivity]( 9045): Relayout returned: old=[0,2172][1440,2678] new=[0,2172][1440,2678] result=0x3 surface={valid=true 495991808000} changed=false
07-05 14:42:02.741 D/ViewRootImpl@4e02278[LogcatActivity]( 9045): MSG_WINDOW_FOCUS_CHANGED 0
07-05 14:42:03.745 D/ViewRootImpl@66ca2af[LogcatActivity]( 9045): ViewPostIme pointer 0
07-05 14:42:03.825 D/ViewRootImpl@66ca2af[LogcatActivity]( 9045): ViewPostIme pointer 1
`

**Comment by polygraphene** [comment]
Thank you!
But the log is too short so we can't show the error.
Please try `adb logcat -d > logcat.txt` and then you can see logcat.txt on some folder.
Please upload the logcat.txt.

**Comment by ch3vr0n5** [comment]
Hopefully this logcat helps. I have the same issue on my S9+. Any of the alpha releases beyond 2.1.5 have a blank right eye.

[logcat.txt](https://github.com/polygraphene/ALVR/files/2193970/logcat.txt)
