### ISSUE TITLE
VR disconnects randomly and says connected on pc but says press connect in VR

### ISSUE THREAD

**Issue by JamieWarnerr** [polygraphene/ALVR#126]
Please help with my issue. I play vr games in alvr then it randomly disconnects and says press connect. I look at my pc, says connected and shows there it only 1 packet. I restart the program and reboot my pc but nothing its doesnt work. Please help

**Comment by vincerex71** [comment]
I also found the same problem I solved by stopping Revive but I do not know why from this.

**Comment by polygraphene** [comment]
Can you play games normally before the issue occur?
Please tell me what version you use on client and server.

**Comment by JamieWarnerr** [comment]
I use 2.1.5 and yeah for a bit with visual glitches (because I don’t use Ethernet cable) then it all just stops. Today I found out if I reboot both my pc and oculus go it works but then goes off. Also when this happens I don’t have very good connection to WiFi on the oculus I don’t know if this is caused by this or not, thanks for investigating 😀
