### ISSUE TITLE
Not working at all, and also kills my WMR controllers...

### ISSUE THREAD

**Issue by Tux0Topo** [polygraphene/ALVR#127]
Hi!! I´m having a big problem here.... Every time i try to launch ALVR, it never start the VR server, i can get a 108 or 308 error.
The connect button never appear, and also kill my controllers in WMR. My controllers don´t ever show up. My only fix is to uninstall and reinstall WMR.

My system is running Windows 10 insider build 17704 and ALVR 2.2.2 + S7 ( ARCORE and non-ARCORE).
I´m using a notebook with optimus. Tried with automatic switching and forced gpu and no change...

**Comment by polygraphene** [comment]
Can you see crash log file on `logs` folder in install folder?
If you can't see it, check `DebugLog` on debug tab and restart server.
Then please upload C:\Program Files\ALVR\logs\driver.log file.

**Comment by Tux0Topo** [comment]
Okay... The log folder was empty. No debuglog on the debug tab. Nothing at all...
So, after reinstalling the wmr (veryfied that everything worked fine), tried again alvr. No use. When used again wmr, the same issue (no controllers, but hmd was there). So without closing the wmr software, try again alvr, and this time the steamvr worked with alvr... but with horrible delay in the movements, and the black borders were chasing the image. Also for no apparent reason, my virtual self started to move out of the steam home, passing through the wall (not really concern about this). Closed the wmr software, and alvr with steamvr were still working (the same delay in movement still present as the border chasing). Not sure if this is an alvr issue, or some windows 10 insider thing... but this way, alvr became a problem... Any ideas?

**Comment by polygraphene** [comment]
Does WMR mean Windows MR?

Is the driver of WinMR installed on SteamVR?
Please check the result of "List drivers" on about tab.

It is hard to help you because I have no WinMR devices. But StreamVR log file (C:\Program Files (x86)\Steam\logs\vrserver.txt) may help you.

**Comment by Tux0Topo** [comment]
@polygraphene Yes, WMR mean Windows MR... Yesterday morning my windows updated to build 17711, and now ALVR started to work again. So, seems like there are some issuess from windows itself 😠 .
The missing hand controllers didn´t fixed.... but at least this is an update.

@gb2111 Not needed that now... but will try a few more things, like uninstalling all the other apps, like riftcat and nolo, and check if that way i can fix the problem....

**Comment by Tux0Topo** [comment]
Okay... new update. After uninstalling all drivers manually, reinstall steamvr and wmr, all seems to be fixed. The arcore positioning still behaves like crazy, moving all the way around...
Also @polygraphene , is this you?: https://www.youtube.com/channel/UCUpw0I7HycvK7taQ4Zpcxdw

**Comment by polygraphene** [comment]
@Tux0Topo Good! It was difficult to fix the compatibility issue by our side. I'm glad that was fixed by WMR side.

>The arcore positioning still behaves like crazy, moving all the way around...

I haven't hear that issue. Can you use another app uses ARCore (like IKEA app)?
We can investigate the issue from `adb logcat`.

>https://www.youtube.com/channel/UCUpw0I7HycvK7taQ4Zpcxdw

No, it's not me. I appreciate those instruction movies.

**Comment by Tux0Topo** [comment]
I´ve tried with "Just a line" app... and have the same issue with movement... so, is a problem with arcore 😢. 
Interesting is that in different rooms i get different behaviors... in my room everything moves, but in other places can be very stable... Sadly that arcore can´t use optical markers like aruco...

**Comment by polygraphene** [comment]
ARCore detects flat plane which has some features.
To put some marker on the floor may help.
https://developers.google.com/ar/discover/
>ARCore's motion tracking technology uses the phone's camera to identify interesting points, called features, and tracks how those points move over time.

**Comment by Tux0Topo** [comment]
Okay... just a kind of a finding.... I take an aruco cube over the table (made for other project), close to my play area, so it can be seen easy by the phone. I´ve found that when the cube is out of sight, the phone moves at his own will... but stops when the cube is at sight...
Tomorrow will test further with multiple aruco markers... Maybe this is the way to go...
