### ISSUE TITLE
Oculus Go. SteamVR Home works, games don't.

### ISSUE THREAD

**Issue by ncksol** [polygraphene/ALVR#128]
I am having a weird problem. Not sure if it's because I don't understand something in setup or smth in my environment. I've downloaded 2.1.5 both app and server. Connected successfully. I launch the app and can see myself in SteamVR Home. Everything is perfect.
But when I run the game from my PC, the screen inside Oculus just goes grey-blue and I have nothing. Here is the screenshot from Headset Mirror:
https://i.imgur.com/cVbinRo.png

I've tried this on Subnautica, which is in the list of supported games, so I assume it's not the problem with the game itself.

**Comment by Tux0Topo** [comment]
Did you tried other steamvr games? Also you said oculus... The subnautica is the oculus version? If so, maybe is a problem with revive....

**Comment by saintkamus** [comment]
run the room setup on steamvr.

**Comment by polygraphene** [comment]
Does Subnautica work in desktop mode?
And please try other games.

**Comment by ncksol** [comment]
Seems like the problem was that I didn't run room setup. Thanks for the tip @saintkamus
