### ISSUE TITLE
How to calibrate games with Xbox (or others) controller ?

### ISSUE THREAD

**Issue by Talhynor** [polygraphene/ALVR#129]
Hello,

I was wondering how can you calibrate games which require you to use the touch trackpad ?
For example in Batman VR at the beginning they ask you to use the trackpad to confirm your position, and it seems  impossible to use a Xbox controller's buttons or even Oculus Go controller instead (tried to emulate all the buttons configuration in ALVR interface but it did not work)

**Comment by vrokolos** [comment]
batman vr works fine here with an Xbox controller

**Comment by Talhynor** [comment]
Thank you for your answer. Finally it seems it worked !
By rebooting the computer, put the enable controller on "off" and starting the Xbox controller before launching the game I were able to use my controller.
It seems if you launch the game while having the enable controller on "on", the game will think your are using a touch controller and the Xbox controller will not be usable.
