### ISSUE TITLE
Samsung S7 + Gear VR firewall permit 

### ISSUE THREAD

**Issue by ManuelGDA** [polygraphene/ALVR#13]
Hello first of all this is incredible it works "flawless" and with the gearvr controller too :D !!! 

But I have a problem, I am no computer savy/pro :_(  ... Windows firewall prevents the detection of the device. If I turn it off it works perfectly but it is not advisable to do so since it puts the computer at risk... and it is not clear how to permit the exception.  Could you explain with more details on the procedure/steps to allow the connection throught windows firewall? 

Many thanks and keep the good work good ;)

**Comment by Tomozow** [comment]
Here will be helpful for you.
https://www.online-tech-tips.com/windows-10/adjust-windows-10-firewall-settings/

You should read "Advanced Firewall Settings" section.
Please do "Allow the connection" instead of "Block the connection".

**Comment by ManuelGDA** [comment]
Ok I read the guide (https://www.online-tech-tips.com/windows-10/adjust-windows-10-firewall-settings/) and I finally discovered what it was, **my network was configured as public instead of private** and it was not allowing connections with other devices, and somehow the true culprit of the mischief was a permission from the client for SteamVR I feel dumb XD But now it works without having to create a new rule or anything special THANK YOU :D!!!!!! I think this is great, its genius. I am studying a VR degree and this I believe to be a gigantic achievement in VR posibilities for a ton of reasons.You have my admiration, I hope to see more progress and new things/functionalities for this client/server as it is what many have been waiting for years! Thanks a lot :D!!!
