### ISSUE TITLE
Starting server doesn't work.

### ISSUE THREAD

**Issue by parzivaall** [polygraphene/ALVR#130]
When I try to click Start Server it begins working then after a few seconds quits the server and goes back to before I pushed the button.
using version 2.1.5. if it makes any difference.

**Comment by polygraphene** [comment]
Try to disable audio streaming.

If you get same error, please upload driver.log.
https://github.com/polygraphene/ALVR/wiki/Debugging#how-to-enable-server-driver-log-output
