### ISSUE TITLE
How to launch games from Dashboard

### ISSUE THREAD

**Issue by satyaloka93** [polygraphene/ALVR#131]
I must be missing something-how do I launch the Dashboard to run games? I can't get any overlay to come up, only the SteamVR background. If I run home beta, I also cannot get a game listing-clicking on the wall does nothing.

**Comment by satyaloka93** [comment]
ALVR is passing some input to Steam VR home from the Go controller (I can teleport around, I have pointer control). The dashboard has also come up randomly, and I can interact with it. If not now, request some way to bring up the dashboard and launch games remotely.

**Comment by TheOneRing** [comment]
As far as I can tell the back button isn't mappable, it would be nice to be able to use it as system button. We will obviously need the trigger button as the trigger ;)

**Comment by polygraphene** [comment]
@TheOneRing Yes. I will add back button mapping on next alpha release. You can also assign back button using FreePIE on latest alpha.

**Comment by TheOneRing** [comment]
Nice, now with remapping the back button I was able to play some of the "The Lab" worlds
