### ISSUE TITLE
Failed to get CUDA device

### ISSUE THREAD

**Issue by Tony2357** [polygraphene/ALVR#132]
Hi,
ALVR show me this(the pic) and headset not found after I clicked the start server button. My ALVR version on my PC and Oculus Go  is V2.2.2-alpha.  I already installed cuda_9.1.85 and set up my firewall to permit UDP/9944 but still doesn't work. My OS and display card is Windows 7 and NVIDIA GTX960. Anyone know how can solve this?

![server crashed](https://user-images.githubusercontent.com/40972211/42428907-c800be16-8368-11e8-83fd-ab6d9247873f.jpg)

**Comment by polygraphene** [comment]
Are you using multiple GPU?
ALVR use default GPU, and you cannot select GPU now.

Windows 7 support is not done yet. So you may get another issue even if this issue is solved.
Refer #27

**Comment by Tony2357** [comment]
I haven't select anything about GPU, could you let me how I can know I'm using multiple or default GPU?

**Comment by Tony2357** [comment]
The "dxdiag" show one display card/driver only. I will try again if I update my OS to windows 10. Thanks for your help.

**Comment by Tony2357** [comment]
HI poly graphene, I am using Windows 10 and the server have no problem now, but ALVR can't found my headset, I even tried to set up the port 9944 and turn off the firewall. The version is 2.2.2 and I'm using Oculus GO.

Defender:
![defender](https://user-images.githubusercontent.com/40972211/42623799-5d9458ae-85f6-11e8-9e92-f6de00d01ef1.jpg)
![issue1](https://user-images.githubusercontent.com/40972211/42623801-5dc67e74-85f6-11e8-920d-3bb172b3b73b.jpg)

Anyone have idea to solve this?

**Comment by polygraphene** [comment]
Try `ping "IP address of Go"` from command prompt and tell me the result.

**Comment by Tony2357** [comment]
Ping statistical data:
Packet: Sent = 4, Received = 0, Lost = 4 (100% lost)

**Comment by polygraphene** [comment]
Hmm... That is a bad result.
Go and PC couldn't communicate each other.
Are both devices connected on same router?
Please tell me IP address of PC and Go.

**Comment by Tony2357** [comment]
I have two routers. One is from my ISP, I get internet through this router. Another one is wifi router which uses for converting my internet to wifi signal. Are these is same network?
I would not like share my IP address here and I can't found any way to send a private message or set reply to private. These IP are different.

**Comment by polygraphene** [comment]
If you configure the router to bridge mode, the two router belongs to same network.
Your Wi-Fi router is perhaps not configured so.
Try to open router configuration page and set to bridge mode, or try to connect PC to Wi-Fi router.

**Comment by Tony2357** [comment]
Thanks! Finally ALVR found my headset, but the graphic quality too bad when I start to move my headset. There are too much broken graphic, I even can't see anything. Has that been because my slow network speed? Has there been any setting/method can fix this?

**Comment by Tony2357** [comment]
The problem was fixed. I set up my wifi router to allow all devices connect the mac address.
Thank you.

**Comment by asd25898636** [comment]
Hi,@polygraphene
I just encounter the same "cannot find cuda device" error with ALVR 2.3.1 on windows7.
My Log file is listed below.
[ALVR_CrashLog_20181204_105026.log](https://github.com/polygraphene/ALVR/files/2642188/ALVR_CrashLog_20181204_105026.log)
My deviceQuery cmd log:
![image](https://user-images.githubusercontent.com/15455944/49415932-311d2380-f7b3-11e8-95c9-6f4fa7e82544.png)
My dxdiag shows only one GPU. 
I don't know what goes wrong since you says that 2.3.1 supports windows7.
It will be GREAT appreciated to receive your reply.
Thank you.
