### ISSUE TITLE
trackpad press always recenter

### ISSUE THREAD

**Issue by gb2111** [polygraphene/ALVR#133]
hi.
i am trying version 2.2.2 alpha.
seems like touchpad press always recenter position. i can see also recenter label on overlay.
i tried to change action to other like 'none' in application but it don't help.

**Comment by polygraphene** [comment]
Recenter is working properly on my environment.
Did you use FreePIE?

**Comment by gb2111** [comment]
i don't use freepie.
i don't really want recenter but to have press act as touchpad press.
is this possible ?
