### ISSUE TITLE
apply offset does not accept fractions...

### ISSUE THREAD

**Issue by gb2111** [polygraphene/ALVR#134]
hi,
i was trying to set height of headset
when I enter 1.8 (dot separator) it turns in to 0 on UI.
when I enter 1,1 or 1,9 (comma separator) it all is treated as 1.
:/

**Comment by gb2111** [comment]
yes.

**Comment by gb2111** [comment]
perhaps you use current pc settings while they should be provided explicitely?

**Comment by polygraphene** [comment]
>current pc settings

What do you mean?
Locale or language settings changes behaviour of parsing float?

**Comment by polygraphene** [comment]
https://stackoverflow.com/questions/27722032/c-sharp-float-parse-string
>float.Parse(string) method uses your current culture settings by default. Looks like your CurrentCulture's NumberDecimalSeparator property is , not .
...
float number = float.Parse("0.54", CultureInfo.InvariantCulture);

Oh... You are right.
