### ISSUE TITLE
sound to oculus go

### ISSUE THREAD

**Issue by judethecat** [polygraphene/ALVR#136]
HI I wonder if any one can help me trying to get alvr connection to stream that I now have working but cant get sound to go thru oculus go headset

tried most of the settings any ideas 
be great help

steve

**Comment by polygraphene** [comment]
Did you try to change sound device and restart SteamVR?
Please check the game is really output the sound to the device you selected.

**Comment by mironal** [comment]
Hi!

I had the same problem.

I was connecting the USB headset to the PC (for PUBG :smile:).

I pulled out the USB headset and a sound came out from oculus go.
