### ISSUE TITLE
Far modem

### ISSUE THREAD

**Issue by vincerex71** [polygraphene/ALVR#137]
Hi and sorry if I worry you I have a small problem: as my modem is placed in a room away from my PC, for I have many problems of delay on the connection, according to you taking an extender ac1200 to put in my room I could solve this problem?
thank you and sorry for my bad english.

**Comment by polygraphene** [comment]
I can't guarantee that the problem will be solved, but in general, Wi-Fi repeater will provide a bit better  performance.
In addition, if you can use ethernet cable to connect new Wi-Fi AP to modem, it will provide better quality than Wi-Fi repeater.

**Comment by vincerex71** [comment]
Grazie!
