### ISSUE TITLE
2D Streaming

### ISSUE THREAD

**Issue by TheOneRing** [polygraphene/ALVR#138]
Quality and latency are obviously much better compared to BigScreen.
Streaming 2D games would be a nice addition to the streaming of VR games.

**Comment by vrokolos** [comment]
2 solutions for you:  
a) Use vorpx with ALVR (costs $) to play 2D games + 2D->3D games in cinema mode.
b) Download phonecast + moonlight on your phone. Run moonlight from within phonecast and play 2D games without ALVR.

**Comment by TheOneRing** [comment]
As I only own a Oculus GO solution a sounds cool. Have you tested vorpox with ALVR?

**Comment by vrokolos** [comment]
Try this with the GO: https://www.reddit.com/r/OculusGo/comments/8mc64q/moonlight_for_go_stream_your_pc_gamesdesktop_to_a/

**Comment by polygraphene** [comment]
This is not the scope of ALVR. I recommend to use other apps (with or without ALVR).

Virtual Desktop works well with ALVR for me. And you can also use Oculus TV with SteamLink or Splashtop.
https://www.reddit.com/r/OculusGo/comments/8wrn2v/since_steam_link_runs_sideloaded_on_oculus_tv_we/

It is said that vorpx works with ALVR. #51

**Comment by crimson-woof** [comment]
Best free option was using ALVR with Bigscreen VR mode, not making a room but turn on bigscreen checkbox, turn off all other monitors.  Good quality, low latency.  Bigscreen alone isn't good quality and has a lot of lag the way they want you to use it with the app.

**Comment by TheOneRing** [comment]
Thx for info :)
