### ISSUE TITLE
カメラの方向をリセットするボタンを設定できませんでしょうか？

### ISSUE THREAD

**Issue by Tomozow** [polygraphene/ALVR#14]
Ver1.7の更新お疲れ様です！ありがたく利用させて頂いております。

表題の件ですが、VRidge for GearVRをOculusGoで使用するとコントローラーのトリガーを引くことで
今向いている方向を正面にリセットすることができます。
この機能がとても便利なので、差し支えなければ今後の実装を検討していただけませんでしょうか。

**Comment by polygraphene** [comment]
正面方向のリセットはとりあえずですが実装できました。
まだちょっとバグがあるので注意が必要です #18 

コントローラーの優先順位？とかをつける方法があるんでしょうか…
SteamVRはまだまだ分からないことだらけなので、もっと調査が必要そうです。

**Comment by Tomozow** [comment]
開発お疲れ様です。いつもお世話になっております。
真っ先に対応していただいたようで大変恐縮です...!
ありがとうございます。

VRidgeではOculusGoとSteamControllerの２つのコントローラーが同時に認識されていたのですが、
どのように処理がされていたんでしょう...
完全に素人なのでお力添えできずに申し訳ない限りです。
