### ISSUE TITLE
can steamvr action be assigned to back button

### ISSUE THREAD

**Issue by gb2111** [polygraphene/ALVR#140]
seems back button does nothing right now. can it be assigned to steamvr button?
like grab or menu ?

**Comment by polygraphene** [comment]
Are you using v2.1.5?
back button assignment is available in alpha release.
Please wait for next release if you want to use stable release.

**Comment by Woohaaa** [comment]
Thank you guy, you solve my same problem. Owner is working hard, thank you very much!

**Comment by gb2111** [comment]
i take this opportunity to tell how great it works with good wifi :)
i was bit surprised really. if no small black borders I would think it is almost like my oculus cv1!

**Comment by RealMG** [comment]
@gb2111 I think this is inevitable by using Asynchronous TimeWarp, for better experience.
