### ISSUE TITLE
Black screen on my Galaxy S6 GearVR

### ISSUE THREAD

**Issue by CarlKenner** [polygraphene/ALVR#145]
Head rotation and sound work, but the screen is always completely black.

Client and server are version 2.2.3 (not ARCore).

Moonlight works perfectly.

**Comment by polygraphene** [comment]
Can you show me the output of "adb logcat"?
Did you try v2.1.5?

**Comment by CarlKenner** [comment]
2.1.5 server always crashed

**Comment by CarlKenner** [comment]
https://pastebin.com/Wrh179F8

**Comment by CarlKenner** [comment]
I posted my logcat. Any idea what's wrong? Anything else you want me to try?
