### ISSUE TITLE
More Controller Options

### ISSUE THREAD

**Issue by GaussianGuaicai** [polygraphene/ALVR#146]
It seems like the Controller menu in ALVR only have four options i can setting.I am using Oculus Go to playing Google Earth VR , some of the manipulation on controller require side bottom like Vive, hope to develop more controller options for these bottom. If i can set my controller trackpad left and right bottom as Vive two side bottom, it would be great~ ;)

**Comment by polygraphene** [comment]
Your request can be solved by FreePIE integration.
Refer: https://github.com/polygraphene/ALVR/wiki/FreePIE-Integration
Install FreePIE and try exmaple3.py script.
The script have functionality of emulate all button on Vive controller.

**Comment by DavidJelinek** [comment]
But the script has no comments how mapping works. The controller setup section is little confused, for e.g. yuu have here the same "Back" label for different actions and controllers buttons and it's not clear when you mean "Back" button on Oculus Go controller, Vive controller or Gamepad.

**Please** try setup like VRidge by RifTcat in http://blog.riftcat.com/2018/07/dev-update-41-vridge-22-beta.html it works wery well.

**Comment by AltoRetrato** [comment]
> Install FreePIE and try exmaple3.py script.
> The script have functionality of emulate all button on Vive controller.

Took me a while to figure out what sample3.py does, and how good it is! I think it is a must for all Oculus Go / Gear VR users! I'd suggest to add a few instructions (as comments) in the script source, as well as a (strong) suggestion to use the script right after installing ALVR.
