### ISSUE TITLE
camera passthrough issue

### ISSUE THREAD

**Issue by audiquattro86** [polygraphene/ALVR#147]
Hello, firstly, well done!  I agree with others- best streamer out there!
I had a strange issue where the gearVR with S9 2.2.3 arcore apk, where the streaming image was replaced with the camera view (slightly distorted - but similar to the camera output option in oculus home video pasthrough)

I had to restart ALVR to get the stream back.

**Comment by polygraphene** [comment]
This is an intended behaviour.
You can get the camera preview by swiping touchpad of Gear VR HMD.
Swiping left or right to change transparency of preview.
