### ISSUE TITLE
Oculus Go App does not Update automatically

### ISSUE THREAD

**Issue by mrdaredevil** [polygraphene/ALVR#148]
Hi,
I downloaded the Oculus Go App over the Key-Distribution-Page. 
When I start the App it shows me that its current version is 2.1.5-client. 
But i have already installed the 2.2.3 server. Do I have to manually update the app with the apk or are there updates to come for the Oculus-App-Store?

**Comment by hatabbich** [comment]
yep if you wanna newer version make manual osig file and put in apk on your phone

**Comment by polygraphene** [comment]
v2.3.0 is now available on Store.
I'm sorry to kept you waiting.

**Comment by petermg** [comment]
polygraphene you are super talented and I am sorry if any of the people
complaining are discouraging you.  There are many people who act like
everyone owes them something.  Please keep up the good work, you have
established a ground breaking app and even if you never update it again it
will go down in history as such an amazing accomplishment!  Thank you!
Just thought I'd tell you that after seeing this post here:
https://www.reddit.com/r/OculusGo/comments/929cmm/development_of_alvr_will_be_slowing_down/
