### ISSUE TITLE
Working great but the app crashes randomly - Hardware is Oculus GO

### ISSUE THREAD

**Issue by TheTarantula** [polygraphene/ALVR#15]
Seems like it crashes when i would look down at the go controller, which i wasn't using, I using a gamepad, and the app stops on the GO, but then I relaunch the app from the unknown apps area, reconnect on the pc, and we're working again.

Any logs you want me to try and pull or find when it happens?

Otherwise, great job, runs very well on the targeted devices, I haven't tried it yet on my S8+.

**Comment by polygraphene** [comment]
I've fixed some issue on controller in version 1.8.
Please check it.

If you experience same issue after update, please send the output of `adb logcat`.
