### ISSUE TITLE
connect via USB

### ISSUE THREAD

**Issue by hatabbich** [polygraphene/ALVR#150]
Hello guys im newbie  devices can't     chose type of connecting USB or WIFI my WIFI connection is soooo laggy every 10 second disconnections ((( Gear VR Note 8 Windows 10

**Comment by Tux0Topo** [comment]
You cant. The GearVR device don´t support tethering. It´s only for OTG. Your best bet is to use an external usb to ethernet adaptor... but not sure if works in ALVR.
Some people tested that with an S8 and Vridge....

**Comment by Eltomato22** [comment]
Ordered usb c to ethernet adapter. I am gonna report on monday.

Btw, fantastic job alvr crew! Multiplies gear vr value!

**Comment by Eltomato22** [comment]
Works very well. Max bitrate possible. looks significantly better then my (unoptimized) 5ghz wifi with 30mbit, especially in Dark scenes
S9
Gear vr 324

**Comment by Tux0Topo** [comment]
Great news! I wish that Samsung add the ethernet driver to the s7...
