### ISSUE TITLE
Is this project still being upgraded?

### ISSUE THREAD

**Issue by RealMG** [polygraphene/ALVR#151]
Hi @polygraphene , 
  I just want to confirm whether you are still working on this project, will alvr be upgraded in the future?

  Thanks for your great working.

**Comment by Tux0Topo** [comment]
I understand you... I´m anxious too... but only passed 16 days... Job, Family, Life, or even not any ground-breaking development was made yot... Let him be!! Hi alreday did awesome work... And even if polygraphene decided to end his work, is his right... (let´s hope that he decided not to).
If you want to thank him, donate... (don´t confuse donation with salary)

**Comment by polygraphene** [comment]
I'm sorry. I'm unmotivated for developing now.
I want to continue to develop, but its speed will slow down.

**Comment by Tubeliar** [comment]
I just had my first ALVR experience and I am blown away! I wrote a blog post about it. I'm posting it here not for self promotion but to hopefully give polygraphene a boost in morale :-)
https://timvanoosterhout.wordpress.com/2018/09/06/streaming-desktop-vr-to-gearvr/
