### ISSUE TITLE
Redeeming key code not working on Go or GearVR

### ISSUE THREAD

**Issue by machenmusik** [polygraphene/ALVR#153]
For me, when I try to use the codes generated by alvr-dist.appspot.com, the Oculus store app gives a generic something-went-wrong error.

**Comment by machenmusik** [comment]
I did try:
GearVR app on Android
Go app on Android
Website (which is the link you mention)

And with multiple generated codes.

Maybe the 2.3.0 update changed something about code redemption?  IDK

**Comment by polygraphene** [comment]
I tried with new oculus account and works correctly.

If you get the error continuously, I recommend to contact support of Oculus.
https://forums.oculusvr.com/community/discussion/52428/cannot-redeem-code
