### ISSUE TITLE
first setup: bad video quality, distortion, packet loss, headtracking laggy

### ISSUE THREAD

**Issue by coolambo129** [polygraphene/ALVR#154]
hi. ive just established the connection Ogo-pc and i get problems as mentioned above:
loss rate 30%, ca. 20 packets/s,total delay >400ms

ive already increased the buffer to 2MB but no change. also tried different codec etc, no change (after closing all apps/restarting).
has anyone used this method with the go for iracing etc?

any help is greatly appreciated. ^^

PS: used this guide: https://www.windowscentral.com/how-play-steamvr-games-oculus-go

**Comment by polygraphene** [comment]
It is perhaps an issue of Wi-Fi.
If you are using 2.4GHz Wi-Fi, try 5GHz.
And lowering bitrate may mitigate the problem.

**Comment by coolambo129** [comment]
pleasure meeting you ^^ thanks for this great app. changing to 5 GHz worked. what other wifi settings do you recommend, eg. bandwidth, mode (n,a,ac), bitrate ,multicast rate?
whats the difference between the codecs? 
go supports 2560 right? so i should be able to increase the qulity? what bitrate?i got a 500Mbit connection. 
higher buffer size increases latency? thx

**Comment by dusan-t** [comment]
Use AC, it's the newer and faster standard.
H.265 compared to H.264 codec provides about double the image quality at the same bit rate.
Try finding the sweet spot between image quality (bit rate) and latency.
