### ISSUE TITLE
Freeze stream when resume from sleep on Oculus Go

### ISSUE THREAD

**Issue by southws** [polygraphene/ALVR#155]
Thanks for your nice app.
It's freeze problem on 2.3.0 when Oculus Go is going sleep, I wear it and click volume button(developer mode), then it stop stream and freeze. When I play VRChat, head tracking is fine but video streaming is freeze.  Reconnection by manual operation can recover this, but I everytime do that.

I try to "adb logcat", I found those line.

> 6477 7161 D ALVR Native: NAL Queue is too large. Discard. Size=10 Limit=10

It found every frame was Started. Then I roll up log and I find "Start new frame"s without discard message at 11 times. The first is forward:

> 07-30 14:16:04.242  6477  8695 V FrameTracking: [Frame 172938] Start new frame. frameByteSize=47399 fecPercentage=5 m_totalDataShards=18 m_totalParityShards=1 m_totalShards=19 m_shardPackets=2 m_blockSize=2732
> 07-30 14:16:04.244  6477  8699 V FrameTracking: [Frame 172963] Sending tracking info.
> 07-30 14:16:04.246  6477  8695 V FrameTracking: [Frame 172938] Frame was successfully recovered by FEC.
> 07-30 14:16:04.247  6477  8709 V FrameTracking: [Frame 172938] Got NAL Type=1 Length=47399 QueueSize=0
> 07-30 14:16:04.247  6477  8709 V FrameTracking: [Frame 172938] Feed P-Frame. Size=47399 PresentationTime=17705013779
> 07-30 14:16:04.247  6477  8709 V FrameTracking: [Frame 172938] Wait next input buffer.
> 07-30 14:16:04.251  6477  8705 I VrApi   : FPS=75,Prd=0ms,Tear=0,Early=0,Stale=62,VSnc=1,Lat=0,Fov=0,CPU2/GPU=3/3,1286/401MHz,OC=F,TA=F/F/0,SP=N/N/N,Mem=1804MHz,Free=1308MB,PSM=0,PLS=0,Temp=28.2C/25.0C,TW=2.15ms,App=0.35ms
> 07-30 14:16:04.258  6477  8699 V FrameTracking: [Frame 172964] Sending tracking info.
> 07-30 14:16:04.272  6477  8699 V FrameTracking: [Frame 172965] Sending tracking info.
> 07-30 14:16:04.286  6477  8699 V FrameTracking: [Frame 172966] Sending tracking info.
> 07-30 14:16:04.300  6477  8699 V FrameTracking: [Frame 172967] Sending tracking info.
> 07-30 14:16:04.314  6477  8699 V FrameTracking: [Frame 172968] Sending tracking info.
> 07-30 14:16:04.319  6477  8707 I UtilPoller: GPU Util 0.140510 / CPU Util 0.583333 (avg 0.478121)
> 07-30 14:16:04.328  6477  8699 V FrameTracking: [Frame 172969] Sending tracking info.
> 07-30 14:16:04.341  6477  8699 V FrameTracking: [Frame 172970] Sending tracking info.
> 07-30 14:16:04.345   569  8723 D NuPlayerDriver: notifyListener_l(0xf0e2aa80), (2, 0, 0), loop setting(0, 0)
> 07-30 14:16:04.347   569  1426 D NuPlayerDriver: reset(0xf0e2aa80) at state 6
> 07-30 14:16:04.347   569  1426 D NuPlayerDriver: notifyListener_l(0xf0e2aa80), (8, 0, 0), loop setting(0, 0)
> 07-30 14:16:04.355  6477  8699 V FrameTracking: [Frame 172971] Sending tracking info.
> 07-30 14:16:04.355   569  8723 W AMessage: failed to post message as target looper for handler 0 is gone.
> 07-30 14:16:04.357   569  8723 D NuPlayerDriver: notifyResetComplete(0xf0e2aa80)
> 07-30 14:16:04.369  6477  8699 V FrameTracking: [Frame 172972] Sending tracking info.
> 07-30 14:16:04.383  6477  8699 V FrameTracking: [Frame 172973] Sending tracking info.
> 07-30 14:16:04.397  6477  8699 V FrameTracking: [Frame 172974] Sending tracking info.
> 07-30 14:16:04.411  6477  8699 V FrameTracking: [Frame 172975] Sending tracking info.
> 07-30 14:16:04.425  6477  8699 V FrameTracking: [Frame 172976] Sending tracking info.
> 07-30 14:16:04.427  6477  8695 V FrameTracking: [Frame 172954] Start new frame. frameByteSize=62837 fecPercentage=5 m_totalDataShards=16 m_totalParityShards=1 m_totalShards=17 m_shardPackets=3 m_blockSize=4098
> ...

**Comment by polygraphene** [comment]
Thank you for reporting.
I found that similar issue is caused on my device.
I will fix it.

**Comment by southws** [comment]
I hope to solve this problem at next update.

**Comment by southws** [comment]
It's still happen on 2.3.1.
