### ISSUE TITLE
Terrible packet loss, unplayable 

### ISSUE THREAD

**Issue by horizynn** [polygraphene/ALVR#157]
So I figured I'd give AL VR a go, since I just got my Go. I installed it and once I connect to the server it's all good... except it's so awfully choppy on the Go and I get bad packet loss when I try to load up Beat Saber. I made sure I'm on 5ghz wifi... Nothing is working. I have a GTX 1060 card so I should have no issues. Any advice appreciated. :/

**Comment by polygraphene** [comment]
Try to raise buffer size like 2000kB.
What bitrate are you using?

**Comment by liyiiamh** [comment]
Hi, thanks for your great APP.
It works very well through WiFi but we have bad experience on Internet by adding a public IP to broadcast list.
We tried to reduce the bitrate to 3M and raise buffer to 2000kB but still many mosaics on the screen.
How can we do to optimize it?
Thanks very much~

**Comment by horizynn** [comment]
Tried 2000kb buffer, still really bad.

**Comment by horizynn** [comment]
Bitrate is at 30
