### ISSUE TITLE
How can I run ALVR without Nvidia?

### ISSUE THREAD

**Issue by fabian290** [polygraphene/ALVR#158]

**Comment by polygraphene** [comment]
Currently ALVR only support NVIDIA. Sorry.
I heard Riftcat works on Go/GearVR.

**Comment by fabian290** [comment]
can I play ALVR with this computer?

 https://www.amazon.com/Acer-Chromebook-CB5-311-T9B0-Certified-Refurbished/dp/B01H3SQX66/ref=olp_product_details?_encoding=UTF8&me=

**Comment by fabian290** [comment]
what else do i need to play steam vr games? DO i need to buy something else?

**Comment by polygraphene** [comment]
#160
