### ISSUE TITLE
72fps, ATW/ASW in tandem

### ISSUE THREAD

**Issue by eneo1** [polygraphene/ALVR#16]
Hi, first of all, great software you have here! Working stellar with my PC and OGO.

I was wondering if you are planning to introduce 72fps mode for Oculus GO? 

Also, what about Asynchronus Space Warp together with your implementation of ATW? My thinking is that with ASW, you only have to stream 50% of the frames to the HMD, reducing latency and requirements even further. Maybe as a toggle in ALVR server.

**Comment by eneo1** [comment]
Yeah you may be right, AWS does seem to be available in mobile SDK.

This is what I've found on 72fps mode: [https://developer.oculus.com/documentation/unity/latest/concepts/unity-advanced-go/](https://developer.oculus.com/documentation/unity/latest/concepts/unity-advanced-go/)

`OVRManager.display.displayFrequency = 72.0f;`

**Comment by chapeka** [comment]
Its possyble 72FPS i any mode of configuration¿?¿?
something like this¿?
vrapi_SetDisplayRefreshRate( app->GetOvrMobile(), 72.0f );

**Comment by polygraphene** [comment]
Thank you for the information.
I have release v1.9 which support 72Hz mode!
I can not test because I don't have Go, so please check yourself.

**Comment by chapeka** [comment]
Perfect my friend an incredible work for your part it works perfect

**Comment by polygraphene** [comment]
Great!
Thank you for report!
