### ISSUE TITLE
can I play ALVR with this computer? 

### ISSUE THREAD

**Issue by fabian290** [polygraphene/ALVR#160]
https://www.amazon.com/Acer-Chromebook-CB5-311-T9B0-Certified-Refurbished/dp/B01H3SQX66/ref=olp_product_details?_encoding=UTF8&me=

**Comment by TheJaeger** [comment]
Nope, this notebook is running Chrome OS. If you read the Readme file, you'll see that ALVR only supports Windows 10. Even if installing Windows 10 is possible, there's no way that notebook can handle SteamVR games decently or encode them for streaming to ALVR.

**Comment by polygraphene** [comment]
As @TheJaeger said, ALVR and SteamVR only run on Windows PC.
And need NVIDIA Geforce GPU.

In general, we need Windows PC which cost about $1,000~ to run games and ALVR comfortably.
https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords=geforce+gaming+pc
