### ISSUE TITLE
Connects for 5 Seconds then disconnects

### ISSUE THREAD

**Issue by Petron5000** [polygraphene/ALVR#161]
I followed through all of the instructions to set up the ALVR connection for my oculus go.  When I start the server and connect, it appears to connect on the ALVR readout but the SteamVR flashes the headset icon and says "The headset is connected but not tracking.  Be sure it can see a base station".  I have the fake base station option checked.  For the 5 seconds the headset appears to be connected on ALVR, the readout says "TotalPackets:  1 Packets" and everything else says 0.  The Headset simply shows "ALVR client 2.3.0   Press connect button on server".  Any advice?!

**Comment by polygraphene** [comment]
https://github.com/polygraphene/ALVR/issues/20#issuecomment-394108598
Please try this.

**Comment by jh360** [comment]
I am having the same issue. I can see the headset and I can connect to the headset, but the "Press CONNECT button on ALVR server" message remains on the headset and after a few seconds it disconnects. I tried running the command suggested, but the problem remains. Here is the output:

PING 10.0.0.240 (10.0.0.240) 56(84) bytes of data.
64 bytes from 10.0.0.240: icmp_seq=1 ttl=128 time=279 ms
64 bytes from 10.0.0.240: icmp_seq=2 ttl=128 time=6.75 ms
64 bytes from 10.0.0.240: icmp_seq=3 ttl=128 time=119 ms
64 bytes from 10.0.0.240: icmp_seq=4 ttl=128 time=141 ms
64 bytes from 10.0.0.240: icmp_seq=5 ttl=128 time=164 ms

--- 10.0.0.240 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 6.750/142.243/279.407/87.379 ms

Is there something else that I can try next?

**Comment by jh360** [comment]
I think I fixed my problem! 

My desktop was connected using an ethernet cable and the headset was obviously over wifi. When I switched the desktop to be wifi as well it started working.

**Comment by munchiesm** [comment]
Hi,

i am  facing the same issue and I am unable to stay connected. It does not bring me to Steam VR Home. I was able to do that previously, but not now. 

It shows 0 packet. I had tried to run #20 abd shell ping -c 
ran it under cmd prompt but it returns adb is not recognized as an internal or external command.

What do i do next?
<img width="960" alt="alvr error" src="https://user-images.githubusercontent.com/42352718/44045980-c835bad4-9f5c-11e8-91ae-6c51f4c07f11.png">

**Comment by polygraphene** [comment]
@munchiesm The command need adb (android platform tools) is installed. Please try another command "ping (IP Address of Go)".

**Comment by munchiesm** [comment]
@polygraphene do you mean just 
"ping 192.168.3.1:9944" in command prompt?

**Comment by polygraphene** [comment]
Try "ping 192.168.3.1" in command prompt if the address is 192.168.3.1.
But the address is 192.168.31.185 according to your screenshot. If so, "ping 192.168.31.185"

**Comment by munchiesm** [comment]
@polygraphene  I tried to ping, and it shows pretty much the same, nothing changed.
<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/42352718/44046624-8f82b258-9f5e-11e8-9a9a-4e2dd07d14e9.png">

**Comment by polygraphene** [comment]
Your Go and PC can't seem to communicate each other.
Go and PC are connected on the same Wi-Fi router?

**Comment by munchiesm** [comment]
@polygraphene yup, I am on the same network system. 

When I drop to wifi on my PC and disable my ethernet, it doesn’t show any “connect” but when I stay on ethernet it shows the connect.

**Comment by polygraphene** [comment]
Hmm... It's weird.
Some separation/isolation feature on router may interfere with the communication.
Please check configuration of router to ensure the feature like "privacy separation" or "guest mode" is disabled.

**Comment by munchiesm** [comment]
Sorry, but how do I do that? Please guide me through? Thanks

**Comment by polygraphene** [comment]
Can you open router configuration page?
If your router address is 192.168.31.1, open http://192.168.31.1/ on web browser.
Please tell me router model.
