### ISSUE TITLE
alvr.head_position[] does not update head position in while loop.

### ISSUE THREAD

**Issue by nrgapple** [polygraphene/ALVR#162]
I created this script to grab a controller's position in my tracking space and `diagnostics.debug(str(unpacked_data[0]))` prints a valid position for an x coordinate, but the oculus go headset does not change position. My client code grabs valid positions and orientations for my controller. Any thoughts?

## Server Code Running in FreePIE

``` python
import socket
import sys
import time
import struct

UDP_IP_ADDRESS = "127.0.0.1"
UDP_PORT_NO = 6789
serverSock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
serverSock.bind((UDP_IP_ADDRESS, UDP_PORT_NO))

if len(sys.argv) == 1:
    interval = 1/30
elif len(sys.argv) == 2:
    interval = 1/float(sys.argv[0])
else:
    print("Invalid number of arguments")
    interval = False

alvr.override_head_position = True
alvr.override_head_orientation = True
#print "Start Server on port:", UDP_PORT_NO
while True:
    start = time.time()
    s = struct.Struct('f f f f f f')
    data  = serverSock.recv(s.size)
    unpacked_data = s.unpack(data)

    multiplier = 2

    alvr.head_position[0] = unpacked_data[0] * multiplier
    alvr.head_position[1] = unpacked_data[1] * multiplier
    alvr.head_position[2] = unpacked_data[2] * multiplier
    #alvr.head_orientation[0] = unpacked_data[3]
    #alvr.head_orientation[1] = unpacked_data[4]
    #alvr.head_orientation[2] = unpacked_data[5]
    diagnostics.debug(str(unpacked_data[0]))
    #diagnostics.debug("x: " , str(unpacked_data[0]) , " y: " + str(unpacked_data[1]) , " z: " , str(unpacked_data[2])
    #diagnostics.debug("Pos x: {0} y: {1} z: {2}" unpacked_data[0], unpacked_data[1], unpacked_data[2])
    sleep_time = interval-(time.time()-start)
    if sleep_time>0:
        time.sleep(sleep_time)

```

## Client Code getting OpenVR infomation

``` python
import time
import sys
import socket 
import struct
import triad_openvr

v = triad_openvr.triad_openvr()
v.print_discovered_objects()

UDP_IP_ADDRESS = "127.0.0.1"
UDP_PORT_NO = 6789

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
server_address = (UDP_IP_ADDRESS, UDP_PORT_NO)

if len(sys.argv) == 1:
    interval = 1/250
elif len(sys.argv) == 2:
    interval = 1/float(sys.argv[0])
else:
    print("Invalid number of arguments")
    interval = False
    
if interval:
    while(True):
        start = time.time()
        
        data = data =  v.devices["controller_3"].get_pose_euler()
        print("\r" + "sending data=" + str(data),  end="")
        packer = struct.Struct('f f f f f f')
        packed_data = packer.pack(*data)
        try:
            sent = sock.sendto(packed_data, server_address)
        except:
             print("error")
        #print("\r" + binascii.hexlify(packed_data), end="")
        sleep_time = interval-(time.time()-start)
        if sleep_time>0:
            time.sleep(sleep_time)
```

**Comment by nrgapple** [comment]
Ok so I did no realize that FreePIE runs your python script in a loop. So I modified the code and will try it later. Check it out [here](https://github.com/nrgapple/alvr-freePIE-tracking)

**Comment by polygraphene** [comment]
That's right. FreePIE plugin applies the changed value (head position or other values) only when the script exits.

And you also need "global serverSock" after "def loop():"

**Comment by nrgapple** [comment]
So everything works. Its pretty cool. With my openvr socket set up I was able to move based on a vive tracker. It bothers me though that to position of the camera is arbitrary. It needs to base relative to a steamvr reference object (light house)

**Comment by nrgapple** [comment]
The headsets orientation is all messed up in the steamVR space.

**Comment by nrgapple** [comment]
I need to understand to vector math [for these two spaces](https://imgur.com/a/WDvwN5r). How do I position the headset so that it is in the position of the tracker when the tracker is relative to the lighthouse and the headset is relative to nothing?

**Comment by nrgapple** [comment]
Also could you add a rotational offset for the headset? I don't want to change the rotation. Just apply an offset. Currently the headsets rotation is in a different direction than the tracking space

**Comment by nrgapple** [comment]
So after further research, if you send [0,0,0] to the headsets position using FreePIE, you get the position of the first reference object (light house) in SteamVR. Also the orientation of the headset is in relation to the direction the light house is pointing.
