### ISSUE TITLE
Packet loss? What do I Do

### ISSUE THREAD

**Issue by horizynn** [polygraphene/ALVR#163]
I'm really frustrated. I just want to play Beat Saber on my Oculus Go. I've tried everything suggested. Still have terrible packet loss. I tried every setting. My internet is fine. This sucks.

**Comment by polygraphene** [comment]
Are you using 5GHz Wi-Fi?
If you aren't, try to switch to 5GHz.
And please try lower bitrate and higher buffer.

**Comment by horizynn** [comment]
I am using 5GHz Wi-Fi. Unfortunately lowering bitrate and raising buffer still don't make it work.

**Comment by kuhiobay** [comment]
Hi horizynn! Try changing the channel of the WiFi connection, entering the router configuration. Try working on channel 11. For me, it worked, but I only have a 2.4 Ghz connection, so I don't know if this will work with a 5 one...
