### ISSUE TITLE
Crash Report / Not starting

### ISSUE THREAD

**Issue by ThiagoHMartinez** [polygraphene/ALVR#164]
I'm using the new version 2.3.0 but when i going to connect the oculus go and alvr this msg shows and it dont connect: 

First message: NvEnc CreateEncoder failed. Code=8 NvEncoder::CreateEncoder : m_nvenc.nvEncInitializeEncoder(m_hEncoder, &m_initializeParams) returned error 8 at c:\src\alvr\alvr_server\nvencoder.cpp:271

Than this message shows too: Unhandled Exception.
ExceptionCode=C0000005
Address=00007FFA1E12D796 (00007FFA1E110000 + 000000000001D796)

Please help me, I need to play beat saber!! :)

**Comment by polygraphene** [comment]
Did you try to update NVIDIA graphic driver?

**Comment by ThiagoHMartinez** [comment]
I use GTX 765M, but I did what u said and it worked! Thank you :)

Buuut, i'm having many lag/distorcion when i play beat saber and any other application. There's something I can do to make it better?

**Comment by polygraphene** [comment]
Good!

That issue is perhaps caused by network problem or GPU load.
If you are using 2.4GHz Wi-Fi, try 5GHz. And try to lowering resolution and graphic settings.

**Comment by ThiagoHMartinez** [comment]
Thank you, I will try it, it must be my Wi-Fi.
