### ISSUE TITLE
Autostart server feature request

### ISSUE THREAD

**Issue by cmtec** [polygraphene/ALVR#165]
It would be great to be able to autostart the ALVR server when ALVR starts. I'm running a headless streaming server and right now I use teamviewer only to press the "Start Server" button in ALVR.

**Comment by polygraphene** [comment]
Please try https://github.com/polygraphene/ALVR/issues/57#issuecomment-398291954
You can achieve that by launching vrmonitor.exe manually.

**Comment by cmtec** [comment]
Thanks!

I didn't realize that "Start Server" was the same as start SteamVR.
