### ISSUE TITLE
can we connect oculus touch controllers?

### ISSUE THREAD

**Issue by fabian290** [polygraphene/ALVR#166]

**Comment by nrgapple** [comment]
Yes. See my [post](https://github.com/polygraphene/ALVR/issues/162). I am currently working on setting the headset to a tracked object in steamvr. This will work for rift also if you want to use a controller as your head position. 

The main problem currently is that the position and rotation of the oculus go is arbitrary relative to the controllers and reference objects (cameras/lighthouses). so you will find that the headset is just positioned up and to the right of the tracking space. and you can offset this in the settings of alvr but this does not fix the rotational problem

**Comment by fabian290** [comment]
ok thank you

**Comment by audiquattro86** [comment]
So does this mean it's possible to use oculus rift moon controllers without without the headset? I know this is possible with the vive controllers and usb dongle, but not with rift.🤔
