### ISSUE TITLE
Will it work with this computer?

### ISSUE THREAD

**Issue by fabian290** [polygraphene/ALVR#167]
https://www.bestbuy.com/site/acer-nitro-5-15-6-laptop-intel-core-i5-8gb-memory-nvidia-geforce-gtx-1050-ti-256gb-solid-state-drive-black/6204553.p?skuId=6204553

**Comment by nrgapple** [comment]
If your computer is VR compatible it will work

**Comment by fabian290** [comment]
Do all games work??

**Comment by nrgapple** [comment]
Yes all games work. The issue is that a lot are not playable with one controller and no position tracking

**Comment by Eltomato22** [comment]
My pc is less powerfull, gtx 660 amd fx 8350, far from vr ready and i can play subnautica and skyrim (limited modding but still beautiful )quite well. But of course you won't get a 90 fps -stutterfree smooth vr expirience. That of course hurts immersion and will get you motion sick easier. Nevertheless i played skyrim and sunnautica for hours and i am still having tons of fun, far more then any flat games. Ethernet adapter + ethernet cable + 300mbit boosts image quality immensly, no artifacts no packetloss
