### ISSUE TITLE
Add option to update hmd orientation quaternion based in FreePIE

### ISSUE THREAD

**Issue by nrgapple** [polygraphene/ALVR#169]
updating the headset with euler angles create gimble lock.

**Comment by nrgapple** [comment]
Here is a little write up about gimbal lock:


>The Problem with Roll, Pitch, and Yaw
Most readers are likely aware that objects that rotate through space can be described by their angle of rotation along three axes. Any rotation in space can be described by a combination of these rotations.
![image](https://user-images.githubusercontent.com/10817537/43688436-7a78e5ca-98b6-11e8-8542-ee45eda38e09.png)
*Gimbals above provide yaw, roll, and pitch movements. Image credit: Mark Hughes (made with Mathematica)*
The rotation axes are not always independent, and solutions are not always unique. It is possible for the plane of two gimbals to align, and a condition known as gimbal lock occurs. In gimbal lock, two of three gimbals are parallel or very nearly parallel, and what began as three degrees of freedom (yaw, pitch, and roll) reduces to two degrees of freedom—two axes of rotation can describe the same rotational motion. At the same time, one degree of freedom is lost and that information disappears. Once gimbal lock occurs, it is impossible to reorient the axes without an external reference.
![image](https://user-images.githubusercontent.com/10817537/43688443-ae0b8410-98b6-11e8-84f6-d4dac49a0861.png)
*When the green circle is aligned or close to aligned with the red circle, movements of the red circle and the blue circle coincide and "gimbal-lock" occurs. Image credit: Mark Hughes.*

[source: allaboutcircuits](https://www.allaboutcircuits.com/technical-articles/dont-get-lost-in-deep-space-understanding-quaternions/)

**Comment by nrgapple** [comment]
This is why it is important that when I send orientations through FreePIE, they are either a standard 3x4 position/rotation matrix or a quaternion. So that when your server goes to interpret the values it does not gimbal lock when I look straight up or cross the 180 mark in the y-axis.

**Comment by nrgapple** [comment]
I'm really trying to understand how your program works because I really love how well this works over my 5Ghz wifi connection and the potential for wireless VR is so close. 

Would you mind giving a basic flow of how values are streamed to client on the headset?

**Comment by polygraphene** [comment]
The function quaternion2euler provide conversion from quaternion to euler angle.
If this implementation is correct, you can use any rotation (=quaternion) as input for FreePIE plugin.
Isn't it sufficient to avoid gimbal lock?

The values you provided for FreePIE plugin are only sent for VR game. They are not sent for client.
https://github.com/polygraphene/ALVR/blob/master/alvr_server/alvr_server.cpp#L1188
https://github.com/polygraphene/ALVR/blob/master/alvr_server/RecenterManager.h#L102
