### ISSUE TITLE
Samsung S7 tested and working!!

### ISSUE THREAD

**Issue by Tux0Topo** [polygraphene/ALVR#17]
Just to comment that. The S7 with gearVR sm-324 works awesome.
The controller in the headset does nothing.

Also, there shold be some fix to use other drivers at the same time with alvr, like the oficial nolo, to get the 6dof tracking.
Also, the use of alvr disables the use of other headset... please fix that...

**Comment by polygraphene** [comment]
> Just to comment that. The S7 with gearVR sm-324 works awesome.
Thank you for reporting!
I've added S7 to tested devices.

> The controller in the headset does nothing.
Gear VR headset touchpad is not supported now.
I will add recentering function on touchpad in future release.

>Also, there shold be some fix to use other drivers at the same time with alvr, like the oficial nolo, to get the 6dof tracking.
I have no idea about this issue. I need to learn on SteamVR driver system.
Please be patient.

**Comment by Tux0Topo** [comment]
Thanks!!
The 1.8 version seems to be as good as the previous releases...
