### ISSUE TITLE
ALVR compatibilty with SteamVR openvr-inputemulator-temporary

### ISSUE THREAD

**Issue by timorsohc** [polygraphene/ALVR#174]
Hi there,
I would like to asking to make ALVR compatible with SteamVR openvr-inputemulator-temporary version. Since the current SteamVR version (The Opt. out of all beta and The newest Beta version) is not running my PS Move properly. All buttons and pointers seem not work in some certainly apps (e.g SteamVR Home, etc). 

The PS move service only run properly with the SteamVR openvr-inputemulator-temporary version, but the problem is  the SteamVR openvr-inputemulator-temporary crash with ALVR (or cannot detect Heatset ~ my Oculus Go)
When i was test SteamVR openvr-inputemulator-temporary with RiftCat (with my android phone), everything run so well (and my PS Move buttons full function in every apps.) 

Therefore, please make ALVR compatible with SteamVR openvr-inputemulator-temporary version.

Thanks in advance,

Warm regards
Timorsohc

**Comment by Olinkses** [comment]
I have the same problem. Thaks for your work @polygraphene.

**Comment by polygraphene** [comment]
I tried openvr-inputemulator-temporary and always get "Headset not detected" message.
I couldn't see crash error. But I will try to fix it.

Could you really use RiftCat?
Riftcat 2.2.7 beta produces same error as ALVR on my environment.

**Comment by timorsohc** [comment]
@polygraphene 
Oops, after my daughter update her Riftcat 3 days ago, now it's getting "Headset not detected"too :(

**Comment by timorsohc** [comment]
@Olinkses 
Woww... Thanks man! That SteamVR beta "hotfix" solved my PSMove problem. Now all buttons and pointers work again! I'm so glad with this. Once again, Thank you! 👍 

Too bad, I don't have Kinect to test Driver4VR.
