### ISSUE TITLE
Newbie Question: Is it possible t have ALVR and Oculus Rift installed on the same PC?

### ISSUE THREAD

**Issue by boessu** [polygraphene/ALVR#178]
What happens if I install ALVR and Oculus Rift on the same PC (not using the same time, just installed and occasionally use the one or another)? Are there any conflicts with both installations or with Steam VR itself?

That's for sure a newbie question. I already have a Rift. I just thinking about to have a Go too as it needs less effort to play some VR games shortly (I need to install the sensors and cables for the Rift). Beside of that there are games which are only playable seriously with the Rift.

**Comment by DavidJelinek** [comment]
Yes, no problem.
