### ISSUE TITLE
ALVR visual issues

### ISSUE THREAD

**Issue by evan25lee** [polygraphene/ALVR#181]
When i try and connect to ALVR on the PC steam vr and everything is working fine and ever thing is tracking correctly including my controller. but on the app i just see the "press connect on pc" and "connected stream will begin shortly" just flash back and forth. i waited for a while and no crashes or anything append. i'm on a note 5 and am using version 2.3.0

**Comment by evan25lee** [comment]
I tested the app and stuff on my S7 and didnt have this issue

**Comment by evan25lee** [comment]
I tested the app and stuff on my S7 and didnt have this issue

**Comment by polygraphene** [comment]
Did you try both H.264 and H.265? And try to lowering resolution of video.
If it didn't solve, please show me the output of `adb logcat`

**Comment by evan25lee** [comment]
both 264 and 265 didnt work. And where do i run adb logcat? when i run it in cmd i get "'adb' is not recognized as an internal or external command"

**Comment by evan25lee** [comment]
This is a video of what happens on the phone when I do connect. https://youtu.be/5bzomqwAOhE

**Comment by evan25lee** [comment]
usually it flashes from connected to please connect but it seems like its staying connected more often now

**Comment by polygraphene** [comment]
Hmm... I haven't see that issue.

Please detach your Note5 from GearVR and then connect USB cable to your PC and follow this instruction.
1. Open [this page](https://developer.android.com/studio/releases/platform-tools)
2. download "SDK Platform-Tools for Windows"
3. extract zip on desktop
4. open command prompt
5. put "C:\Users\\(username)\Desktop\platform-tools_r28.0.0-windows\platform-tools\adb logcat -d > C:\Users\\(username)\Desktop\logcat.txt"
Please replace C:\Users\\(username)\Desktop to your extracted folder.
6. put logcat.txt on this issue.

**Comment by evan25lee** [comment]
im just stuck on waiting for device when trying to put that into cmd. im going to try and restart my computer. it seems like its just trying to charge the devices and not actually connect to them

**Comment by evan25lee** [comment]
[logcat.txt](https://github.com/polygraphene/ALVR/files/2300013/logcat.txt)
here it is

**Comment by polygraphene** [comment]
Thank you!
Unfortunately, the log of ALVR is flowed and disappered from the logcat.
Can you retry to launch ALVR Client and get the log?
I appreciate your help.

**Comment by evan25lee** [comment]
sure. Do i need to connect my phone again? also where do i go in alvr to get the log?

**Comment by polygraphene** [comment]
Yes. You need to connect USB from phone to PC after launch client. You can get the log by same command I wrote.
Please launch client and immediately detach phone from GearVR and connect USB.

**Comment by evan25lee** [comment]
[logcat.txt](https://github.com/polygraphene/ALVR/files/2300030/logcat.txt)
I ran the command again after i connected to the client. this is the new logfile

**Comment by polygraphene** [comment]
Thank you.
I have found an error on graphic. But I couldn't found the exact cause.
I want to see the log on startup of client.
Can you retry with following instruction?
1. Restart your phone
2. Launch client (Please don't click connect on server)
3. Immediately detach GearVR
4. Get the log

Sorry for bothering you many times.

**Comment by evan25lee** [comment]
[logcat.txt](https://github.com/polygraphene/ALVR/files/2300169/logcat.txt)
i understand how hard it is to troubleshoot

**Comment by polygraphene** [comment]
Thank you for helping debug.

>08-19 03:31:42.952  9329  9341 E ALVR Native: 1:1: P0003: Extension 'GL_OES_EGL_image_external_essl3' not supported
08-19 03:31:42.952  9329  9341 E ALVR Native: 0:1: Warning: GL_OES_EGL_image_external is deprecated in ESSL 3 and later versions

I found the cause. Probably this is the same issue as https://github.com/Samsung/GearVRf/issues/755
I will try to fix. Please wait a while.

**Comment by evan25lee** [comment]
ok thank you for your help

**Comment by evan25lee** [comment]
While testing this on my S7 i get this strange thing where there is a delay to when i look around. here is a video of what im talking about: https://youtu.be/vPMSK0PlRAE the artifacting at the beginning also happens but other then that video quality is great. Should i open a new issue for this?

**Comment by polygraphene** [comment]
That's a strange behavior. What video bitrate and encoding are you using?
It is possibly caused by large decoding latency or network latency.
Please tell me the latency value displayed in server side.
Generally, the TotalLatency shows 70~100ms and DecodeLatency shows 30~50ms and TransportLatency show 1~10ms.
It is okay to open new issue.

![](https://raw.githubusercontent.com/wiki/polygraphene/ALVR/installation/room-setup-1.png)

**Comment by Parker3434** [comment]
Hi polygraphene,

I am also facing a similar visual issue (https://youtu.be/5bzomqwAOhE) that has been reported in the first post while using latest build of ALVR on a Galaxy S6 (android version 5.0). I've also tried running the previous build (2.3.0) but to no avail.

My PC specs are as follows:

i3-4150
GTX 1070
16 RAM

I saw that your were able to identify the exact cause of this issue and you were working on a fix. If there is indeed a workaround to this, please do share.

> Thank you for helping debug.
> 
> > 08-19 03:31:42.952  9329  9341 E ALVR Native: 1:1: P0003: Extension 'GL_OES_EGL_image_external_essl3' not supported
> > 08-19 03:31:42.952  9329  9341 E ALVR Native: 0:1: Warning: GL_OES_EGL_image_external is deprecated in ESSL 3 and later versions
> 
> I found the cause. Probably this is the same issue as [Samsung/GearVRf#755](https://github.com/Samsung/GearVRf/issues/755)
> I will try to fix. Please wait a while.

Besides, from the video tutorials that I have seen regarding ALVR, you have indeed created an amazing software.

All the best  and Kind regards,
