### ISSUE TITLE
ARCore Positional tracking jumping around

### ISSUE THREAD

**Issue by Eltomato22** [polygraphene/ALVR#182]
When using the acore edition the positional tracking does not seem to work properly. Every minute or so it jumps around on the axis. Only roomposition axis seem to be affected. Normal Version works flawlessly. Any ideas to reduce this effect or a way to rencenter?
Thanks for so great work! 
Gear vr, s9

**Comment by Tux0Topo** [comment]
I experienced the same issue. Try looking/moving around, to see if get fixed.
Try other ARCORE app, and the tracking should get a crazy in the same way...

As far as i know, its an issue with ARCORE technology with only onew camera (like the S9, S8 and S7 like mine). The S9+ should behave better. Also, if you could stick multiple trackers (like the aruco, but a chess table should work) to the room, that should also help.

**Comment by Eltomato22** [comment]
Arucomarkers, cleaned room and improved lighting did not help. Other arcore apps seem to work fine, projected ar objects jitter a little but nothing drastic. In steam vr i am relocated quiet often.

**Comment by Shifter2600** [comment]
The new arcore 1.5 released today fixed the known issue with arcore on my samsung s9+

**Comment by Eltomato22** [comment]
Fixed it for me too. Thanks!
