### ISSUE TITLE
Wrong Version with Oculus Go

### ISSUE THREAD

**Issue by WasabiThumb** [polygraphene/ALVR#186]
Both client and server are listed as v2.3.0

The server says that either the client or server is out of date, which is not true.

I'm not sure what else to add to this, but I will happy to provide additional info.

**Comment by polygraphene** [comment]
I haven't heard that issue.
Have you ever installed the older version before?
Did you use Oculus Store to install client?

Check if StreamVR is using correct driver version.
1. Enable debug log. [Check here](https://github.com/polygraphene/ALVR/wiki/Debugging#how-to-enable-server-driver-log-output)
2. Open "C:\Program Files\ALVR\logs\driver.log" in notepad
3. Check the following lines.
```
[23:51:21.978 573] Serial Number: ALVR-001
...
[23:51:21.979 570] Startup: ALVR Server Driver 2.3.0
```

**Comment by WasabiThumb** [comment]
Thanks for your response! It generated the .log file and the serial number and startup driver are the same as you posted there.

`[22:48:22.730 585] Serial Number: ALVR-001`
and
`[22:48:22.731 086] Startup: ALVR Server Driver 2.3.0`.

Although this time, for seemingly no reason, I encountered an error and the server refused to start. I believe this is what caused it:

`[22:48:22.872 510] NvEnc CreateEncoder failed. Code=15 NvEncoder::CreateEncoder : m_nvenc.nvEncInitializeEncoder(m_hEncoder, &m_initializeParams) returned error 15 at c:\src\alvr\alvr_server\nvencoder.cpp:271`

I am aware that this would belong in a seperate issue thread, but solving it may be the solution to the original problem.

To answer your first two questions though, yes I installed an older version of the server, but I fully uninstalled it (although the new installer remembered the install directory, so clearly i did not remove ALL of it), and I used the key code generator to install it on my Oculus Go client.

Thank you for your response!

**Comment by WasabiThumb** [comment]
(After reloading ALVR, the error no longer shows up and I get a much longer log file. It still states that the Oculus Go is out of date.)

**Comment by polygraphene** [comment]
Thank you.
It is good that the NvEnc problem is disappeared.

The version on the server side looks good.
If you can see update button on Oculus library, please update.
If client is also latest, I have any more idea about debugging...

You see following display and "Connect" button is replaced to "Wrong version", is it right?
![img](https://github.com/polygraphene/ALVR/wiki/installation/select-device.png)

**Comment by WasabiThumb** [comment]
Yes, it says Wrong Version instead of Connect. I am not sure how to force update on Oculus Go, I can only update when it prompts me to. Is there a way to force update it?

**Comment by WasabiThumb** [comment]
Update: The error mentioned before is back, sometimes it triggers and sometimes it doesn't. I tried a full reinstall but the problem persisted. Also, a new error is appearing on trying to connect.

![image](https://user-images.githubusercontent.com/29989488/45589461-cebf3000-b8f3-11e8-9acf-d833eb399a64.png)

**Comment by WasabiThumb** [comment]
That is very much possible. I need to find the correct drivers for my GTX 1050TI. Now that I think about it, ALVR stopped working ever since my NVidia Control Panel disspeared.

**Comment by WasabiThumb** [comment]
Been a while, sorry. Found the drivers, I installed them a while ago. I'll tell you the results when I am able to use my Oculus Go again.
