### ISSUE TITLE
Vireio Perception 3.0 compatibility

### ISSUE THREAD

**Issue by AlmightyFrog** [polygraphene/ALVR#187]
Hi,

I was thinking of using Vireio + OGO + ALVR for playing older dx9 games (e.g. Fallout New Vegas) in 3D with SBS.
For the first without any special controller besides keyboard and mouse.

There are videos and instructions on youtube doing it with vorpx and "real" oculus rift/htc vive.
Is it possible to use such a virtual stereo injector like Vireio with ALVR?
I only get steam to run the game in cinema mode displaying the SBS picture there on "big screen".

BTW: I had partially success with using moonlight only, but it not only is unstable (with an old apk which still supports SBS) but also as there then is no headtracking you get sick quite fast.

For reference, I am speaking about version 3 (https://www.mtbs3d.com/downloads-section/viewdownload/21-vireio-perception-3-0/72-vireio-perception-3-0-1-vr-boost) as version 4 seem to only be working for dx11 games.

Best Regards, Greenfrog

**Comment by polygraphene** [comment]
vorpx can work with ALVR. https://github.com/polygraphene/ALVR/issues/51
ALVR is a driver of SteamVR. You may get it to work in a similar way for Vive.

**Comment by AlmightyFrog** [comment]
I am aware that vorpx is working with ALVR. I have no Vive, otherwise I would not need ALVR. But there are Videos, that you can play with a Oculus Rift over S

My question is, if there is a way to get Vireio to work with ALVR, so for example if there is a missing link where ALVR could tell steam that the video shall be streamed directly like it is rendered to the oculus go or so without using cinema mode; picture is already SBS.

I guess, it is vireio which is not working together with SteamVR (as it is quite old) but using some other older way to use Oculus Rift directly.

**Comment by DavidJelinek** [comment]
Vireio is driver for run game in SBS 3D mode, then you can stream game to OgO with [Moonlight for Go](https://www.reddit.com/r/OculusGo/comments/92lpfx/moonlight_for_go_updated_remote_desktop_app_up_to/) and watch on "big screen" like in big 3D Tv.

If you want play game in full 3D environment, then you must buy VorpX and you can use ALVR to streram game to OgO.

**Comment by polygraphene** [comment]
That's a difficult issue.
We need one of the following solutions:

1. Create driver which bridges between SteamVR and old Rift driver.
2. Add features to get SBS output from Vireio and pass headtracking data to the Vireio.

Whichever method is chosen, it need a lot of difficult work.
It is difficult to newly develop those software.

Isn't Revive compatible for Vireio3?

**Comment by AlmightyFrog** [comment]
It's already some time passed. I didn't have any success with it so far and as I am not able to develop a bridge driver or such I'm closing this ticket now.

Using Moonlight for Go and normal Moonlight I already did, but instead of that I could also just use SteamLink or ALVR using SteamVR displaying 2D so there is no real benefit when it comes to "3D" gaming. My desktop Monitor is also big enough so I'd prefer that over a virtual big screen even though it might feel smaller.

Thank you very much for your answers, @polygraphene and @DavidJelinek .
