### ISSUE TITLE
Xiaomi MI VR version of ALVR? with Nolo?

### ISSUE THREAD

**Issue by Tux0Topo** [polygraphene/ALVR#188]
Hi polygraphene!!
Just a question, and maybe some help...
In the wechat Nolo group, there are mentions of a Xiaomi MI VR version of ALVR, which seems to be compatible with Nolo and seems to work mainly with the Nolo Home for windows app... Do you know anything about it? Maybe there is some workaround for other oculus powered devices? Thanks!!

**Comment by polygraphene** [comment]
Hi.
I haven't heard of it. It is very interesting.
Mi VR is compatible with Oculus Go/Gear VR so that we can use same apk for Oculus.

It would be great if we can collaborate with that community.

**Comment by Tux0Topo** [comment]
I´m trying to get some forums... But it´s only in chinese, and the translation is a real pain in the ass...
This one seems the bbs forum of Xiami: http://bbs.xiaomi.cn/f-459

Also, some people tells me that the Nolo team should be able to help more... but don´t know.

Hope this helps us!

**Comment by Tux0Topo** [comment]
Translation is a pain!!! Reading and asking a lot, proves me wrong. ALVR is used as you made it No modifications. The nolo support seems to be made else where... Still trying to figure more... 😠

**Comment by Tux0Topo** [comment]
I just send you an email to polygraphene@gmail.com. Check it asap please!

**Comment by Tux0Topo** [comment]
When checked it, please tell me...

**Comment by polygraphene** [comment]
I got information from Nolo's member.
Nolo official has developed Mi VR version of ALVR, and invited some users for test.
But it is only a prototype version. Nolo is now supporting me to deploy official version. (https://github.com/polygraphene/ALVR/issues/142#issuecomment-409164746)

I don't know the prototype version is really suitable for distribute to all users.
Please wait for release of my new version.

**Comment by Tux0Topo** [comment]
Awesome great news! Can´t wait for your version!

**Comment by Lightsteed** [comment]
hey i think i might have suggested you to get in touch with nolo a while back, thats great news, hopefully it all works cos my nolo has been useless to me for ages cos their software is kinda trash.

**Comment by WJRev** [comment]
Hi, new to the site but cannot rate ALVR highly enough, Riftcat just doesn't cut it for me.

The NOLO VR controllers are seen in ALVR but always behind me and sometimes inverted, is this the problem everyone else is facing?
