### ISSUE TITLE
Trojan:Win32/Powessere.G Found?

### ISSUE THREAD

**Issue by rosscarlson** [polygraphene/ALVR#190]
Trying to install the driver Windows Defender claims to find the driver "Trojan:Win32/Powessere.G" when I run the installer.  It's happening when mshta is trying to register the ActiveX object - looking at the error I'm going to guess (and hope) that it's a false reading - but hoping you can confirm (as I'm about to ignore it and do it anyway)

**Comment by rosscarlson** [comment]
Well even when I tell Windows Defender to allow it I get "Access Denied" whenever I try to run the driver installer - again specifically on the mshta line.  Any ideas?

VC redist is at it's latest version

**Comment by rosscarlson** [comment]
And another update - fully disabled Windows Defender and it installed - would still like confirmation it's all safe ;-)

**Comment by newflavour** [comment]
didn't have any issues installing 8hrs ago and updating Nvidia drivers. no virus flags from defender or avast

**Comment by polygraphene** [comment]
This was fixed on #144
But I haven't yet released the patched version.

**Comment by polygraphene** [comment]
new release v2.3.1 includes patch to fix it.
