### ISSUE TITLE
Support for Oculus Go native resolution

### ISSUE THREAD

**Issue by TyborAUT** [polygraphene/ALVR#193]
Please add native Oculus Go resolution (2560x1440) to video settings.

**Comment by polygraphene** [comment]
Native resolution is meaningless. We must use 2:1 resolution.
See https://github.com/polygraphene/ALVR/issues/32#issuecomment-399526553

**Comment by Colonel-Izzi** [comment]
That's not actually the Go's effective native resolution.  It doesn't utilize it's entire display so the actual [rendered viewport for each eye is ~1230x1230](https://imgur.com/ssahJoF), but you send one video stream, not two, and the viewport extends right to the edges of the display (if not the top and bottom), so you'd need 2560x1230, which is so close to 2560x1280 that it doesn't matter.  And ALVR has an option for 2560x1280.  
  
But all that aside you'll generally get better quality stream if you choose a higher resolution anyway.

**Comment by TyborAUT** [comment]
I tested my Go with higher resolution and as you have recognized too (https://github.com/polygraphene/ALVR/issues/32#issuecomment-395308092) it is more clear display.

On this comment https://github.com/polygraphene/ALVR/issues/32#issuecomment-399527299 you are unsure about how Oculus Go is working. Do you have an answer now?

My experience when testing would suggest, that there is a stream scaling. So my thought was to optimize stream bandwidth and processing power and just use the native Go resolution.

**Comment by polygraphene** [comment]
@Colonel-Izzi Thank you for information. Go seems have same barrel distortion like GearVR.

@TyborAUT Yes. As @Colonel-Izzi showed, Go doesn't use whole screen and does use barrel distortion. It is same as GearVR.

**Comment by TyborAUT** [comment]
@polygraphene I'm little confused now :-D
When I set ALVR video resolution to 1024x512 I see that there is scaling done in the Oculus Go.
But what is the target size for this scaling? Is this the native 2560x1440 resolution ?!? When this is the case, you get the best quality when using a 1:1 pixel mapping which would be the 2560x1440 resolution.

Am I wrong?

**Comment by polygraphene** [comment]
Maybe we can assume target size is about 1536x1536.
Oculus API requests 1:1 texture (for each eye) and then distorts it into barrel form.
Normally it requests 1024x1024 texture for performance reason, but it is said that maximum meaningful size is 1536x1536.

See: https://github.com/polygraphene/ALVRClient/blob/master/app/include/VrApi_Types.h#L243

**Comment by TyborAUT** [comment]
Yes, I think you are right. With a texture size of 1536x1536 per eye you would get best quality at center of screen after the barrel distortion.

Have you looked into the 5K tech (https://developer.oculus.com/blog/behind-the-tech-with-john-carmack-5k-immersive-video/)?
This would allow bandwidth reduction of high quality streams.

**Comment by polygraphene** [comment]
That technology is for 360 degree video. ALVR doesn't draw the entire sphere but draw only player's FoV. So it is not applicable for ALVR.
