### ISSUE TITLE
bigscreen

### ISSUE THREAD

**Issue by grhluna** [polygraphene/ALVR#194]
first of all this is mainly athank u to the developer
so thanks
second this is the single thought i have around vr so i hope it will help 

alvr works with bigscreen custom screens if u use the steamtray
and launch first from alvr into steam 
and second use the tray to launch bigscreen
otherwise u end up with lack of options in bigscreen or u end up with two avatars
great program! elite dangerous and labwriting works great
u need 5ghz tho 

perhaps mine is an enduser comment:   somewhere down the line  there is a progress in software that still needs to develop around vr where something like ALVR becomes an automated process
my remark is that facebook will end up with customized headsets with the chip ON the headset  while using a patented oculus softwares
they are facebook after all and others will use nifty little hacks like ALVR
there is room for improvement there cross platform
and altho bigscreen is great and innovative the only software i see with such great potential is ALVR! 

so mine is not a bug but an enduser comment: as VR develops around more light hardware and people look to develop more demanding games and applications
what is holding VR back is cross platform integration and customization!
ALVR should come with the oculus go.......  but it didnt! this is my point
u have ur hardware and u have ur app store rolling but ur missing out on cross platform development!  holding many customers back from buying for two reasons
1   lack of pc knowledge 

2 lack of highend pc *example to run alvr with good nvidia and good wifi*
what you need is what apple has done to the smartphone  you need the same
but for the VR!  apple worked because of android
VR doesnt have that cross platform useability yet otherwise i wasnt hacking my oculus go with the ALVR server workaround!  so u need to invent it!
its silly to walk on one leg 
integration is what vr needs and this is overlooked
schools   hospitals   ur fridge in ur house what do i know

i hope it will help future software developers!

**Comment by polygraphene** [comment]
Thank you!
I didn't understand the whole of your comment. I'm sorry if I miss your point.
You mean ALVR should support multiple platforms, right?

@sigmaxipi is currently working on Daydream support.
And if other platforms attract me, I will port ALVR to it.

**Comment by grhluna** [comment]
yep!  that was my point! seems like u got the whole point!

**Comment by grhluna** [comment]
its only because apple and its closed source were in competition with android they managed to sell a lot of phones!  hence vr needs toys like ALVR!
