### ISSUE TITLE
ALVR server has crashed. Sorry for the inconvenience.

### ISSUE THREAD

**Issue by brentjohnston** [polygraphene/ALVR#195]
After I click connect for the IP to connect to the Oculus go I get the message:

ALVR server has crashed. Sorry for the inconvenience.
Unhandled Exception.
ExceptionCode=C0000005
Address=00007FF711DC0C04 (00007FFC69610000 + FFFFFFFAA87B0C04)

My specs are Windows 10, 1080ti, 5820k cpu. I used to have an Oculus Rift.
Any ideas? I followed the instructions to the letter.

**Comment by brentjohnston** [comment]
Here you go, I tried 4 times. I tried reinstalling the Nvidia drivers (i had newest ones, tried older ones) tried uninstalling oculus runtime. Nothing seems to work.

[ALVR_CrashLog_20180929_162328.log](https://github.com/polygraphene/ALVR/files/2432730/ALVR_CrashLog_20180929_162328.log)
[ALVR_CrashLog_20180929_162729.log](https://github.com/polygraphene/ALVR/files/2432731/ALVR_CrashLog_20180929_162729.log)
[ALVR_CrashLog_20180929_164329.log](https://github.com/polygraphene/ALVR/files/2432732/ALVR_CrashLog_20180929_164329.log)
[ALVR_CrashLog_20180929_171741.log](https://github.com/polygraphene/ALVR/files/2432733/ALVR_CrashLog_20180929_171741.log)

**Comment by polygraphene** [comment]
Thank you.

Hmm. I haven't seen this error. NVIDIA driver seems work properly.
Did you install the tools like OpenVR-Input-Emulator or openvr-advancedsetting?
Please show me the result of "List drivers" button on About tab.

**Comment by brentjohnston** [comment]
I just reformatted the entire PC, fresh install. Same crash. Here is the results when I click on List driver:

ALVR
Installed driver list:
C:\User\NewPC\Downloads\ALVR-portable-v2.3.1\ALVR\driver\

I do use OpenVRadvanced settings, I'll try to uninstall it and see what happens.
Attached
[ALVR_CrashLog_20181003_025914.log](https://github.com/polygraphene/ALVR/files/2441142/ALVR_CrashLog_20181003_025914.log)
 is the new log on the fresh PC install

**Comment by brentjohnston** [comment]
It just prompted an update in the ALVR app on the Oculus go, I updated it and it seems to be working now! The only issue is when I look around it takes 3 seconds for the camera to move. Any ideas?

I have fast 5gz router.

**Comment by bbeaver157** [comment]
I also had a server crashed, but it said the reason was "Failed to initialize CEncoder"
Crash log included

[ALVR_CrashLog_20190313_230403.log](https://github.com/polygraphene/ALVR/files/2964585/ALVR_CrashLog_20190313_230403.log)

**Comment by SuperSuperPepper** [comment]
I also had a server crashed, but it said the reason was "Failed to initialize CEncoder"
Crash log included.metoo.

**Comment by FlamingDuck04** [comment]
Just got a new GPU and now a crash error code comes up saying "Unhandled Exception.
ExceptionCode=C0000005" it used to work but it doesn't ever since the new GPU. Any fixes?
