### ISSUE TITLE
Turn delay

### ISSUE THREAD

**Issue by buttpain** [polygraphene/ALVR#2]
One issue I can't overcome is when I look around too fast you can see the black area outside of the screen space for a split second before it catches up to where you are looking.

**Comment by polygraphene** [comment]
Thank you for your report.
I experienced the same issue.
This may be caused by too large buffer size on client side.

I will add buffer size configuration on next release.
Please retry when it released.

**Comment by polygraphene** [comment]
I have released new version right now.
Please check it.
It contains some fixes to reduce latency.

**Comment by buttpain** [comment]
oh cool, do you know any workaround for the crashing. I was able to briefly get it working yesterday but ever since it either instantly crashes on connecting or a few seconds after.

**Comment by polygraphene** [comment]
Did you update both server and client?
To update server, you should simply overwrite the whole install directory.
To update client, put the command `adb install -r (apkname)`.
Mismatch of version may cause a crash.

If update does not solve the crash,
could you send me an output of adb logcat?

**Comment by kameka22** [comment]
@polygraphene you really do a great job! I will test the new version tonight after work!

**Comment by Thaurin** [comment]
I can only see the blacks at the sides when I turn my head too quickly when I have my router set to 2.4Ghz. On 5Ghz, I see no delay of catching up whatsoever. It's pretty much perfect. Could the router have something to do with it?

**Comment by polygraphene** [comment]
Yes.
5Ghz Wi-Fi has more speed and is more stable than 2.4Ghz.
Please refer: https://www.howtogeek.com/222249/whats-the-difference-between-2.4-ghz-and-5-ghz-wi-fi-and-which-should-you-use/

So, if you can use 5Ghz, you should always use it.
