### ISSUE TITLE
Intel Graphics Support

### ISSUE THREAD

**Issue by ICURSEDANGEL** [polygraphene/ALVR#200]
hey is there support for intel graphics even tho it doesnt support vr but it can play a few vr titles like vr chat and it works for me on vr chat perfectly. just wanna know if it indeed does support vr chat

**Comment by polygraphene** [comment]
I have a plan to support Intel GPU. But I don't know when I can start to work.

**Comment by ICURSEDANGEL** [comment]
@polygraphene so for now it wont work on intel GPU?

**Comment by ICURSEDANGEL** [comment]
or any experimantal testing version?

**Comment by polygraphene** [comment]
@ICURSEDANGEL No. Currently ALVR won't work on Intel GPU. No testing version.
