### ISSUE TITLE
Oculus Go + PS Move Controller

### ISSUE THREAD

**Issue by TyborAUT** [polygraphene/ALVR#201]
I want to thank @polygraphene for his great work with ALVR  :thumbsup: and share my work for an Oculus Go + PS Move Controller setup.
https://github.com/TyborAUT/ALVR_FreePIE_scripts

I previously tried the Driver4VR solution which works good, but I like the flexibility of FreePIE more.

After you have setup [ALVR](https://github.com/polygraphene/ALVR/wiki/Installation) + [FreePIE](https://github.com/polygraphene/ALVR/wiki/FreePIE-Integration), you have to get [PSMoveService](https://github.com/cboulay/PSMoveService/wiki#initial-setup) and [PSMoveFreepieBridge](https://bitbucket.org/hawkinse/psmovefreepiebridge/src/master/).
Be sure you fully calibrate your PS Move controller before using it in VR!

1. enable Bluetooth & PS Move controller
2. run PSMoveService
3. run PSMoveFreepieBridge (when your controller is detected it lights up)
4. run FreePIE and load & run [go_single_psmove.py](https://github.com/TyborAUT/ALVR_FreePIE_scripts/blob/master/go_single_psmove.py)
5. run ALVR, start server
6. start ALVR in your Oculus Go and connect with your server
7. enjoy a low cost VR solution!  :smile:  :smile:

**Comment by nerionx** [comment]
Awesome, used your code and created a version which uses
3 Move controllers, 2 for hands, 1 for head with 6dof tracking

Awesome because it allows us to use our controllers on the menu again the actual psmovebridge being broken.

**Comment by TyborAUT** [comment]
@nerionx Do you mind sharing your script and some instructions? I want to add it to https://github.com/TyborAUT/ALVR_FreePIE_scripts .

**Comment by Peng180** [comment]
I would like use led ping pong ball for my oculus go head position tracking instead of the third psmove. Do I need to make some change to the freepie script (Go_Dual_PSMove_Plus_head_6dof.py)?

**Comment by nerionx** [comment]
You could change the ID numbers for the devices. HMD is usually marked as 0
So HMD = 0 LEFT_CONTROLLER = 1 RIGHT_CONTROLLER = 2

However, im not sure PSMoveFreepie bridge lets you track controllers and HMD at the same time

**Comment by SleightYT** [comment]
Yo man I'm completly new to this stuff but have an oculus go and psmove controller and would like for them to work together. If you have discord, maybe you could guide me through it?

**Comment by TyborAUT** [comment]
@SleightYT Please take a look at the wiki: https://github.com/TyborAUT/ALVR_FreePIE_scripts/wiki/Oculus-Go-with-Go-Controller-and-PSMove
In case you still have questions, you can ask them here.

**Comment by pupphelper** [comment]
He

> @SleightYT Please take a look at the wiki: https://github.com/TyborAUT/ALVR_FreePIE_scripts/wiki/Oculus-Go-with-Go-Controller-and-PSMove
> In case you still have questions, you can ask them here.

Hi TyborAUT, I have 2 quick questions.  I tried your ver 3 single controller script to add a move controller to my gearvr ALVR (ARCORE) but the elevation on my move controller is wrong, its under the floor, I can see it working, but how do I re-center it like i can with the gear controller.  I tried start+Select and it just changes mode. I'm using the FreepieforALVR scripts.   

Also is it possible to use 2 move controllers, and ARCORE for the positional tracking without having to have 3/4 Playstation eye cameras?   Or do I need ps eye cameras to get the elevation of the move controller?

**Comment by Lyks-tech** [comment]
> @SleightYT Please take a look at the wiki: https://github.com/TyborAUT/ALVR_FreePIE_scripts/wiki/Oculus-Go-with-Go-Controller-and-PSMove
> In case you still have questions, you can ask them here.

Does it work with Gear VR ? :/

**Comment by BublikTor** [comment]
Hello! Please tell me what you need to leave in the script to track the positioning of only the head, and remove the controllers.

**Comment by TyborAUT** [comment]
> 
> 
> Hello! Please tell me what you need to leave in the script to track the positioning of only the head, and remove the controllers.

Hi @BublikTor ,
There is no need to use the script if you don't use any controllers!
The script is only used to add additional controller.
