### ISSUE TITLE
Unhandled Exception  on displaying special character with alvr.message

### ISSUE THREAD

**Issue by TyborAUT** [polygraphene/ALVR#203]
[ALVR_CrashLog_20181009_205548.log](https://github.com/polygraphene/ALVR/files/2461821/ALVR_CrashLog_20181009_205548.log)

Occurs when using following code within FreePIE script (degree character causes exception):
`alvr.message = "Arm " + "%.0f°" % math.degrees(g_arm_roll) `

**Comment by polygraphene** [comment]
Thank you for reporting.
I could reproduce the crash.

ALVR uses "Inconsolata" font for text rendering.
It only contains ascii characters. So special characters can't be rendered.
I will fix the crash bug, but another rendering method is needed to support various characters.

https://github.com/polygraphene/ALVR/blob/master/alvr_server/resources/inconsolata.spritefont
https://fonts.google.com/specimen/Inconsolata
