### ISSUE TITLE
Can i play games outside of steamVR with ALVR ? My own i do with unreal editor?

### ISSUE THREAD

**Issue by KreatiVR** [polygraphene/ALVR#204]
Hi,
thank you for your time, work and support for this amazing program. 
It works in steamVR perfectly for me, but i wanted to start my own "games" or "apps" i am doing in unreal editor and start it on PC. Is it possible to get the game to the steamVR "window" so ALVR is recognize it and playing it? 
When i do it now, steamVR says my game is not response and is not starting. When i did try it with the PSVR emulator (so it is a second windows screen)  i could start it and it is working. You have to send the "own" game to this second screen and it is showing up in steamVR.. 
Is that the problem it won´t show up, because there is no second screen windows recognize?
Thanks for clearing this out..

Martin.

**Comment by polygraphene** [comment]
Is this the same issue?
https://answers.unrealengine.com/questions/585278/vr-vive-ready-but-unresponsive-only-with-ue4editor.html
>Fixed it by simply executing console command "stereo on" (which is not done in the VR example scene of Unreal).
