### ISSUE TITLE
Extreme Packet Loss

### ISSUE THREAD

**Issue by ralph1993** [polygraphene/ALVR#205]
I have a Steam Link that works fine, and I am no expert, but I think it's the same concept. I set SteamVr to mirror to my desktop,and that looks great, but on my Go it's a blocky mess. It's the same on my brother's Go. I messed with the video bitrates, but it all looks just as bad. Does anyone have any ideas?

**Comment by TyborAUT** [comment]
Are you referring to ALVR?
What WiFi router technology are you using (802.11b, g, n, ac)?

**Comment by ralph1993** [comment]
Yes, ALVR. Im on b/g/n

**Comment by ralph1993** [comment]
I locked it to N and increased bandwidth on the router from 20 to 40Mhz. I also forgot to mention that video streaming is set to max in ALVR. Still crappy.

**Comment by blueeagle69** [comment]
I'm no expert. But I'm not surprised it is terrible on your Router. My mate had a N router and VR streaming was unusable. I got him to contact his ISP and demand an 5ghz AC router. Problem solved.

**Comment by TyborAUT** [comment]
Get a WiFi network scanner (e.g. https://play.google.com/store/apps/details?id=com.farproc.wifi.analyzer ) and check your environment. In case of many AP's around, your performance is reduced because of collisions.
But it is recommended to use a 5 GHz WiFi.

**Comment by ralph1993** [comment]
I just remembered a lighting strike took out m router a month or two ago, and my current modem/router only broadcasts @2.4 GHz. Hopefully this is the issue. I just order a new router on Amazon. I will update this again when I'm on 5GHz.

**Comment by blueeagle69** [comment]
Yeah 5ghz AC makes a big difference (as long as you have a strong signal). Good luck :)

**Comment by ralph1993** [comment]
UPDATE: I setup my new router to run @5GHz AC, and it's working flawlessly.

**Comment by blueeagle69** [comment]
Great news bud. It's amazing the difference it makes.  For instance on my S8 Plus on 2.5ghz N my connection is 150mbps. 5hhz AC connects around 866mbps. You can kinda see why 2.5 sucks for this type of 2 way streaming. Especially as the throughput is usually much less than the connection speed.
