### ISSUE TITLE
Issues on Running ALVR on Virtual Machine With NVIDIA vGPU M60

### ISSUE THREAD

**Issue by mxy00** [polygraphene/ALVR#209]
Hi, 
I have run ALVR on windows PC with NVIDIA GPU. Great experience.
But, recently I worked on a virtual machine with nvidia vGPU M60, unfortunately there are issues when I run ALVR on it. It always gave me the error on NVCODEC.
So, I think there is something wrong with NVCODEC module in ALVR. For further research,  I download and run the Video Codec SDK 8.1, 8.0 and 7.0 on virtual machine, only 7.0 can work  normally such as "NvEncoderD3DInterop" project.
As a result, I want to run ALVR  on virtual machine such as mentioned above, do you have any advice or can help me?
Thanks.

**Comment by fxsrt10** [comment]
Depending on OS, did you install all of the Nvidia Drivers? I think for that card you need to get the Grid Driver as well
