### ISSUE TITLE
How can i enable Arcore positional Tracking on ALVR 2.3.1?

### ISSUE THREAD

**Issue by ICURSEDANGEL** [polygraphene/ALVR#210]
Hello.

i cant find the option to enable arcore positional tracking with ALVR 2.3.1 using my Exynos S7E with my gear vr.

anyone please tell me how can i enable arcore positional tracking?

Thank You.

**Comment by BossBolognese** [comment]
+1 to this, i would love to play around with this option after trying it in quakevr but i don't see any option to enable this. please help

**Comment by ICURSEDANGEL** [comment]
@BossBolognese ikr me too how do we enable this anyone please help us.

**Comment by BossBolognese** [comment]
I've figured out how to make it work. you need to grab the newest client apk from https://github.com/polygraphene/ALVRClient/releases and install it manually. the oculus store version lacks the positional tracking. i used gearvr injector to sighn the apk and it worked fine, however the tracking is very inaccurate (as to be expected) and my phone gets hot very quickly. still fun to mess around with though.

**Comment by ICURSEDANGEL** [comment]
@BossBolognese omg ima try it right now tysm

**Comment by ICURSEDANGEL** [comment]
@BossBolognese also would recommend you to get a fan i bought my fan from aliexpress for like almost 20$ and it keeps my phone cool while using gear vr

**Comment by BossBolognese** [comment]
could you maybe give me a link to that fan?

**Comment by ICURSEDANGEL** [comment]
@BossBolognese my app on my exynos s7 edge keeps crashing now have u experienced that?
