### ISSUE TITLE
UI Bug: Incorrect Offset behavior in cultures that use decimal comma

### ISSUE THREAD

**Issue by baratgabor** [polygraphene/ALVR#213]
This relates to the **Apply offset** feature on the **Other** tab of the app's UI.

There was a commit that was supposed to fix incorrect parsing of floats:
[Fix the wrong parsing of float on some locale.](https://github.com/polygraphene/ALVR/commit/ab39abb9ee09c12bcb28815b017cd9cb498f75fe)

But it seems this didn't solve the issue for cultures that use decimal comma instead of decimal point (German, Polish, Hungarian, etc.).

**Observed incorrect behavior in version 2.3.1:**

1. The user enters e.g. "1.5" into the **Y** text box, then selects the **Save** button.
2. The "1.5" value entered gets replaced by "1,5".
3. The server receives this incorrect value, which results in the fractional part being ignored (it seems).
4. The new "1,5" value in the text box will get parsed again upon app exit, which converts it into "15", and as a result the server will start with a one order of magnitude incorrect value the next time.

**Reason for the bug:**

- The app culture is not set explicitly to one that uses "." as decimal separator, and the `Launcher.SaveSettings()` method replaces the text box content with the return value of a parameterless `ToString()` method called on the parsed floats, which uses the system's default decimal separator (e.g. ",").
- Also, since the parsing is currently done with `CultureInfo.InvariantCulture`, it strips out the generated "," when it parses the value the second time.

As a quick solution (but probably I'm being captain obvious), you can just set the app culture explicitly to `en-us` (e.g. `CultureInfo.DefaultThreadCurrentCulture`, `CultureInfo.DefaultThreadCurrentUICulture` and `Thread.CurrentThread.CurrentCulture`, `Thread.CurrentThread.CurrentUICulture`), **or**
add `IFormatProvider` parameter to the `ToString()` calls to make sure it uses dot, and not comma.

(But probably it would be better to add proper support for comma separated floats.)

**Comment by Yoshidk** [comment]
Im having the same issue and cannot believe this is not fixed yet, should be an easy fix.
