### ISSUE TITLE
WARNING: ABIs [arm64-v8a,armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI' not targeted by this project.

### ISSUE THREAD

**Issue by fujiangren** [polygraphene/ALVR#214]
WARNING: ABIs [arm64-v8a,armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI' not targeted by this project.

一打开就奔库

**Comment by jacgsaw** [comment]
Hola como vas 

Tuve ese error en dos proyectos en uno la solución estaba en este link

https://stackoverflow.com/questions/50286817/warning-abis-armeabi-v7a-armeabi-set-by-android-injected-build-abi-gradle-f/50286973

En otro proyecto me salió y el link no me funciono lo corregí cambiando una clase a privada la tenia si 

public class ViewHolder{
//codigo 
}

la deje así y el warning se fue

public static class ViewHolder{
//codigo 
}
