### ISSUE TITLE
Server 2.3.1 crashing - Failed to start audio capture

### ISSUE THREAD

**Issue by gb2111** [polygraphene/ALVR#218]
the error message is below. I downgraded server to 2.3.0 and it works very well. so I created other issue as other were I think related to 2.3.0.

`Failed to start audio capture. Thread aborted before starting to loopback capture. message=IAudioClient::Initialize failed: hr = 0x88890008`

**Comment by bairdj4** [comment]
Having this issue on both V2.3.0 AND 2.3.1. Any new development on resolving this? I've tried changing the sound format to 16bit, 48000 HZ (DVD Quality) and no joy.
