### ISSUE TITLE
Steam Motion Smoothing

### ISSUE THREAD

**Issue by vrokolos** [polygraphene/ALVR#221]
So the new steam vr has something called motion smoothing. Does this work with ALVR? Should I disable it?

**Comment by ICURSEDANGEL** [comment]
@vrokolos it only works with vive and vive pro now but it depends of how ALVR is implemented.

for example trinus vr is implemented to be detected as a vive headset, you could try to use a ource code and implement it with ALVR to be detected as a vive. as far as i know i dont think ALVR is implemented to appear as a vive headset like trinus but i will try to do that.
