### ISSUE TITLE
Old android Smartphone  as Vive controller emulator

### ISSUE THREAD

**Issue by tynxPL** [polygraphene/ALVR#223]
Hello.
Thanks Polygraphene for Your great job.
I think there is many of people without account on github who want thank You for this awesome job :)

I want to ask is there a solution  to use old android phone for 3dof controllers like in Trinus hand or daydream controller emulator to use in ALVR ?

Sorry for my English.

Thanks in advance for any reply.

**Comment by ICURSEDANGEL** [comment]
@tynxPL  its possible to implement trinus hands for use with ALVR but it will take me sometime to figure it out as i need to get the source code from trinus hands so i could implement and test it with ALVR
