### ISSUE TITLE
ALVR Code=1

### ISSUE THREAD

**Issue by KookyCrazyBob** [polygraphene/ALVR#224]
Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc NvEncoderD3D11 failed. Code=1 NvEncoder::LoadNvEncApi : NVENC library file is not found. Please ensure NV driver is installed at c:\src\alvr\alvr_server\nvencoder.cpp:70

How do I fix this

**Comment by UnderCraft42** [comment]
i dont know
