### ISSUE TITLE
ALVR start server isnt working

### ISSUE THREAD

**Issue by ThatPanduh** [polygraphene/ALVR#225]
So I'm trying to connect my Oculus Go onto my steamvr and downloaded ALVR because some youtuber goes by the name of "RaMarcus" uses it and was doing a tutorial and stuff but when he clicked "Start Server" it didn't work for me. I don't know how but I got it some how to work for like a split second, like it said "Server Is Live" and then when my SteamVr popped up it stopped working. And my SteamVr said "Disable Safe Mode" or something like that but it doesn't work too. Any ideas on why it doesn't work?

**Comment by Tollanador** [comment]
Are you using psmoveservice at all?

**Comment by yms20** [comment]
I had the same problem, try installing the latest nvidia drivers. Hope that
helps.

Am Fr., 14. Dez. 2018 um 14:18 Uhr schrieb Tollanador <
notifications@github.com>:

**Comment by ICURSEDANGEL** [comment]
@ThatPanduh whats Your GPU

**Comment by ThatPanduh** [comment]
@ICURSEDANGEL my pc is a gaming laptop. This is the cite for it https://www.newegg.com/Product/Product.aspx?Item=N82E16834234979&cm_re=GTX_1060_laptop-_-34-234-979-_-Product
@yms20 i think my nvidia is all updated
@Tollanador Its not that it crashed it just doesnt want to work, what i meant is that i try to reboot my steamvr and it pops up as "Starting Server" for like a split second and goes back to "Start Server"
