### ISSUE TITLE
ALVR compilation error: FreePIE.Core.Contracts couldn't be resolved

### ISSUE THREAD

**Issue by rishi-rranjan** [polygraphene/ALVR#227]
1>------ Build started: Project: ALVRFreePIE, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "FreePIE.Core.Contracts". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>D:\sw\Temp\alvr\ALVR\ALVRFreePIE\ALVRFreePIEPlugin.cs(1,7,1,14): error CS0246: The type or namespace name 'FreePIE' could not be found (are you missing a using directive or an assembly reference?)
1>D:\sw\Temp\alvr\ALVR\ALVRFreePIE\ALVRFreePIEPlugin.cs(12,38,12,45): error CS0246: The type or namespace name 'IPlugin' could not be found (are you missing a using directive or an assembly reference?)
1>D:\sw\Temp\alvr\ALVR\ALVRFreePIE\ALVRFreePIEPlugin.cs(239,6,239,12): error CS0246: The type or namespace name 'GlobalAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>D:\sw\Temp\alvr\ALVR\ALVRFreePIE\ALVRFreePIEPlugin.cs(239,6,239,12): error CS0246: The type or namespace name 'Global' could not be found (are you missing a using directive or an assembly reference?)
1>D:\sw\Temp\alvr\ALVR\ALVRFreePIE\ALVRFreePIEPlugin.cs(239,13,239,17): error CS0246: The type or namespace name 'Name' could not be found (are you missing a using directive or an assembly reference?)
1>D:\sw\Temp\alvr\ALVR\ALVRFreePIE\ALVRFreePIEPlugin.cs(11,6,11,16): error CS0246: The type or namespace name 'GlobalTypeAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>D:\sw\Temp\alvr\ALVR\ALVRFreePIE\ALVRFreePIEPlugin.cs(11,6,11,16): error CS0246: The type or namespace name 'GlobalType' could not be found (are you missing a using directive or an assembly reference?)
1>D:\sw\Temp\alvr\ALVR\ALVRFreePIE\ALVRFreePIEPlugin.cs(11,17,11,21): error CS0246: The type or namespace name 'Type' could not be found (are you missing a using directive or an assembly reference?)
1>D:\sw\Temp\alvr\ALVR\ALVRFreePIE\ALVRFreePIEPlugin.cs(36,44,36,59): error CS0246: The type or namespace name 'IPluginProperty' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by 2H0U** [comment]
Make sure you have FreePIE.Core.Contracts.dll in ALVRFreePIE\bin\Debug and ALVRFreePIE\bin\Release.

**Comment by Eg0Jemima** [comment]
I am unable to find the FreePie.Core.Contracts.dll file, even within the FreePIE & ALVR github repositories. Is there a direct link where I can find this file?

**Comment by 2H0U** [comment]
You need to download msi installer here:
https://github.com/AndersMalmgren/FreePIE/releases

Then you can find FreePie.Core.Contracts.dll in the installed directory.



 - 周鹏 Zhou Peng
 
From: EJ Mann
Date: 2019-05-02 00:26
To: polygraphene/ALVR
CC: peng; Comment
Subject: Re: [polygraphene/ALVR] ALVR compilation error: FreePIE.Core.Contracts couldn't be resolved (#227)
I am unable to find the FreePie.Core.Contracts.dll file, even within the FreePIE & ALVR github repositories. Is there a direct link where I can find this file?
