### ISSUE TITLE
Support Bluetooth Controllers (connected to headset)

### ISSUE THREAD

**Issue by Naatan** [polygraphene/ALVR#233]
It would appear that bluetooth controllers connected to the headset do not work, which is to say I've tried it and found that it does not work.

It would be great if support for this could be added, that way the Oculus GO can remain portable even when using it with ALVR.

Thanks!

**Comment by Paulus88** [comment]
I am facing the same problem, the oculus controller works great but when I link the xbox one s controller it does nothing.

I saw tutorials that you have to link the xbox controller to the PC, that does work but I tend to be in other rooms in my house with my oculus go then the controllers bluetooth doesn't reach the PC.

**Comment by Werns** [comment]
Same issue here, tested with a Nintendo Switch Pro controller. Thought it was an issue with the controller, since it kept making the lights flash the same way as when searching for a connection. Glad I saw this thread to save headache.
