### ISSUE TITLE
Packet loss every 6-7seconds

### ISSUE THREAD

**Issue by apan65** [polygraphene/ALVR#238]
This video is demonstrate the issue. https://www.youtube.com/watch?v=j8mS2klajeY
One time i fix it by removing steam vr and reinstall alvr. now its not helping at all.
Think this is issue on the client side or smartphone.
Previously alvr works perfectly fine on my galaxy s6 and rx480

**Comment by Tymec** [comment]
I get that as well, I use h.264, 30mpbs and 2kb buffer size.

**Comment by SiriusCCG** [comment]
I get the same issue, could you help me to solve it?
Many thanks
regards

**Comment by apan65** [comment]
Its periodically resolve by itself. I don't know the reason of this behaviour

**Comment by SiriusCCG** [comment]
What is the correcto settings forma Steam vr?.
