### ISSUE TITLE
New user, I need help - without resolving

### ISSUE THREAD

**Issue by Freif12** [polygraphene/ALVR#239]
I am a new user, I downloaded yesterday the application to test it. but I started and he gave me an error. I was looking at other posts but I could not solve it, at the beginning I got this error

![asdas](https://user-images.githubusercontent.com/46296987/50573051-cae4ea00-0dcc-11e9-86fe-038d78a814ad.PNG)
"Uncontrolled exception in the application If you click continue, the application will ignore this error and try to continue, if you click exit, the application will close immediately."

Then, I gave it to continue, but when starting server, I gave error

I looked if it was the drivers, but I did not find the location

![captura](https://user-images.githubusercontent.com/46296987/50573108-c10fb680-0dcd-11e9-90ae-4381ddea56a6.PNG)

**Comment by apan65** [comment]
install steamvr firstly

**Comment by Freif12** [comment]
I installed it, but now I get this accident report

![captura](https://user-images.githubusercontent.com/46296987/50574308-7ea6a380-0de6-11e9-8e2d-945882524d58.PNG)

**Comment by CptK66** [comment]
Update your graphics driver, I had the same issue before I updated
