### ISSUE TITLE
ALVR server crashing

### ISSUE THREAD

**Issue by Shillelagh-Hummus** [polygraphene/ALVR#244]
Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc NvEncoderD3D11 failed. Code=15 NvEncoder::LoadNvEncApi : Current Driver Version does not support this NvEncodeAPI version, please upgrade driver at c:\src\alvr\alvr_server\nvencoder.cpp:88

**Comment by Ashes2007** [comment]
@sitagy Hmm, ill have to try that.
