### ISSUE TITLE
What version of .net used to build ALVR? (I'm trying to run it in linux, using WINE)

### ISSUE THREAD

**Issue by hradec** [polygraphene/ALVR#245]
Hi Polygraphene....

Thank you so much for this amazing piece of software, before anything!! Really appreciate your effort and talent in put this all together!!

I'm trying to make ALVR work in Linux under WINE (ALVR server), since there's loads of games running in linux theses days. 

I myself play Elite:Dangerous in linux this way. 

Although SteamVR beta runs fine in wine, I can't seem to make ALVR UI to run... it crashes with a StackOverflowException exception. 

I have tried with .net 4.0, 4.5 e the latest, 4.72... no luck! 

alvr steamvr driver seems to load correctly inside steamvr, but since I cant run the .net UI, steamVR says theres no device attached. 

Is there any other dependency for ALVR.exe apart from .net that you can think of? 

I'm thinking in port ALVR.exe to python, so it would run correctly in any platform... at least the UI. 

I believe the steamVR driver also probably could be compiled natively in linux since it uses NVIDIA  and OpenVR APIs, which are multi-platform... But If I can at least figure out the ALVR UI to instruct the driver what to do, I can make this work... 

anyhow, any help would be awesome!!

**Comment by HoshiYamazaki** [comment]
Do you fixed that? It works now?

**Comment by hradec** [comment]
nope!  Sorry!

**Comment by ComLarsic** [comment]
@hradec heya, I am trying too achieve the same thing. I figured out that it uses .net framework 4.6.1. but the master branch doesn't compile.

Also, how did you install the drivers on linux? I can't seem to get it to work.

**Comment by hradec** [comment]
I've installed steam itself with wine (and also dxvk), and then after having steam up and running, steamvr installs and just works. 

After having steam and steamvr working in wine, I copied over the `driver_alvr_server.dll` file to `"$WINEPREFIX/drive_c/Program Files/ALVR/driver/bin/win64/driver_alvr_server.dll"`. 

after that, I restarted steam and steamvr, and steamvr shows up the ALVR headset icon as it does in windows. 

But without the ALVR frontend app, there's no way to talk to the `driver_alvr_server.dll` software running inside steamvr, to accept the connection from the Oculus Go. 

I started look at the code, but life is hectic and I didn't manage to find enough "continuous" time to actually understand something there. 

Since then I ended up running windows 10 on a VM with gpu passthrough, and used ALVR that way. 

But I still plan on coming back to ALVR linux porting (not only the frontend, but also the driver itself) at some point, because I'm very interested on learning more about the very efficient low latency streaming it does, basically to use it for a low-latency remote desktop application for linux, allowing 60fps at 1080p and hopefully 4k 60fps remote access to linux desktops... like parsec for linux!

**Comment by hradec** [comment]
In case you're interested in install steam with wine like I did, here is a little sum up: 

I've downloaded wine version `tkg-4.0-x86_64` using Lutris (Lutris have a functionaly to download pre-compiled versions of wine that run on most distros)

after downloaded, I created a `steamwine` folder somewhere, and inside I created a `WINE` folder, and moved the `tkg-4.0-x86_64` to the `WINE` folder. 

then I created a little startup script called `start.sh`, with this: 
```
#!/bin/bash

CD=$(dirname $(readlink -f $BASH_SOURCE))
cd $CD

V=tkg-4.0-x86_64

export DXVK_HUD=frametimes
export __GL_THREADED_OPTIMIZATION=1

#export WINEDEBUG=+all
export LC_ALL=C
export WINEARCH=win64
export WINEPREFIX=$CD/WINEPREFIX64B/
export PATH=$(pwd):$CD/WINE/$V/bin/:$PATH
export LD_LIBRARY_PATH=$CD/WINE/$V/lib64:$CD/WINE/$V/lib:$LD_LIBRARY_PATH

export WINEPATH=$WINEPREFIX/drive_c/Program\ Files\ \(x86\)/NOLO\ HOME/:$WINEPREFIX/drive_c/Program\ Files\ \(x86\)/NOLO_HOME/NoloAllDrivers/driver/bin/win64/:$WINEPREFIX/drive_c/Program\ Files\ \(x86\)/NOLO_HOME/NoloAllDrivers/nolo/bin/win64/:$WINEPREFIX/drive_c/Program\ Files\ \(x86\)/NOLO_HOME/NoloAllDrivers/huaweinolo/bin/win64/
export WINEPATH=$WINEPATH:$WINEPREFIX/drive_c/Program\ Files\ \(x86\)/Steam/steamapps/common/SteamVR/bin/win64/
export WINEPATH=$WINEPATH:$WINEPREFIX/drive_c/Program\ Files\ \(x86\)/Steam/steamapps/common/SteamVR/bin
export WINEDLLPATH=$WINEPATH

if [ "$@" == "" ] ; then
    arg=./WINEPREFIX64B/drive_c/Program\ Files\ \(x86\)/Steam/Steam.exe
    $CD/WINE/$V/bin/$w "$arg"
else
    echo $CD/WINE/$V/bin/$w "$@"
    $CD/WINE/$V/bin/$w "$@"
fi
```
after creating the `start.sh`, make it executable with `chmod a+x ./start.sh`.

Run `./start.sh winecfg` and set the windows version to "windows 7".

After this, you'll find a WINEPREFIX folder inside you `steamwine` folder, created by running wine `tkg-4.0-x86_64`. 

Run `./start.sh winetricks` (assuming you have winetricks installed in your distro already) and install dotnet40, dxvk, msxml3, msxml4, msxml6, quartz and vulkanrt.

After that, you run `./start.sh /<path to downloaded steam setup file>/SteamSetup.exe` to install steam, and after installed, just run `./start.sh` to start steam up! 

After that, install steamvr, run it. close it all down, copy `driver_alvr_server.dll` to your WINEPREFIX folder:  `./WINEPREFIX64B/drive_c/Program Files/ALVR/driver/bin/win64/driver_alvr_server.dll`

Run `./start.sh` again, start steamvr and you should see the ALVR headset icon on steamvr! 

That's pretty much it!

**Comment by hradec** [comment]
After writing this little "how to" for you, I tried to run steamvr again, (it was a while since the last time I tried and it worked fine), and after updating (off course... it's so freaking annoying the amount of updates this thing gets), steamVR crashes at startup now under my wine setup! (thanks Valve)

So, maybe trying a new version of wine will work, or maybe there's someting new that needs to be installed from winetricks now... Unfortunately I can't look into it right now!! 

If you do, please let me known how it goes... and the steps you did, in case you fix it! (make sure to make a copy of your WINEPREFIX after having steam up and running, just so you can revert back in case something gets screwed by installing winetricks stuff... it happens all the time! )

**Comment by jarrard** [comment]
We need ALVR or VD for Linux, such a shame the developers have no interest in Linux :(

**Comment by ComLarsic** [comment]
> We need ALVR or VD for Linux, such a shame the developers have no interest in Linux :(

Well, maybe once .net 5 comes out we will be able to compile it for linux.

**Comment by jarrard** [comment]
Hmm, that will be interesting to see happen.

**Comment by CoffeeBoi47** [comment]
The ALVR client opens in wine6.0. I cant get it to see that steamVR is installed tho even if I install it in the same prefix. If anyone could tinker with this
