### ISSUE TITLE
Controls Not Working

### ISSUE THREAD

**Issue by Jack-Rickwood** [polygraphene/ALVR#246]
How can i connect a controller? Do i have to enable it in settings somehow? How can i do that if i cant select any options? Everything else works fine but i just dont know how to use a controller. Please help, and thank you for making this awesome app. I am fine with using my gearvr controller, or i also have an xbox 360 ripoff one, but i cant get either to work. I can get the gear vr one to connect, but pressing the buttons doesnt do anything.

Also do you think if we used https://github.com/matzman666/OpenVR-InputEmulator we wouldnt need the game to support gamepad controllers?

**Comment by pupphelper** [comment]
Test your Xbox 360 controller in Steam, or Steam Big mode first using any regular 2d game thats available on steam. Look for a demo or free games.  Resident evil 2 just released a demo and it should work with a controller.  Once you know your controller is working fine in steam, it should just work in VR provided the game supports it.  

If you want to use a motion control, just check the box for enable controller in ALVR, and your controller will appear, and you can point and click, once again you will need to make sure the game you are trying supports a 3dof motion control.  For example Beat Saber will work, but only 1 saber mode.  There is a compatibility tested list available. So try games that have been documented to work.
