### ISSUE TITLE
Video glitchy, no problems with computer or headset otherwise.

### ISSUE THREAD

**Issue by ThaneGreyhaven** [polygraphene/ALVR#247]
The video goes completely wonky.  Sorry, I don't know the technical term.
Here's a screenshot:
https://c2.staticflickr.com/8/7843/46604305192_a76eb997a9_o.jpg

The computer is WAY more powerful than it needs to be, my network connection get over 80MB/s transfer speeds easily.  I'm using an Oculus Go and it has no problem with any other app.

Any ideas?

**Comment by Lainier** [comment]
Check if there are other Wi-Fi signals using the same channel as yours. You can use a mobile app for that. Change your Wi-Fi channel if needed. If you still have problems after that, maybe there is some interference from another device.

**Comment by fdinsdale** [comment]
yeah, thats definitely a wifi issue

in addition to Lainier recommendations:

1. use 5ghz band preferably AC
2. Hard wire PC to wifi router
3. In ALVR video settings use 30-40 Mbps stream
4. Increase buffer as needed to reduce packet loss

see if that clears it up

**Comment by ThaneGreyhaven** [comment]
Yeah, I switched it to the 5G and it was fine.  Not sure how I got onto the other, I don't remember setting it up for that.  It sure is bandwidth intensive. :)
