### ISSUE TITLE
Is there a way to Re-center without using the controller?

### ISSUE THREAD

**Issue by pupphelper** [polygraphene/ALVR#249]
Is there a way to toggle re-centre with a keyboard shortcut, or even better a gesture on the headmounted trackpad.    I can see it can be done when the controller is active, however I am using 2 move controllers for 6dof with the gearvr controller disabled.   ALVR is working great with ARcore, however the playfield often gets shifted around a bit, and I often need to recenter to my ps eye cameras and adjust my small play area. 
It would be amazing to have a button or touch to the trackpad on the headset  for recentering

**Comment by dpluigi** [comment]
Hi,
I have experienced some positional shifts too while testing ALVR (client v2.3.1) + ARCore with GearVR fitted with Samsung S9 in a flight simulator in VR mode (Condor Soaring).  

Would it be possible to implement a re-center shortcut on a keyboard or joystick button for:
1) Re-center to initial (neutral) pose defined at startup?
2) Define a new default pose from current head pose, i.e. which can be deferent from initial pose, but useful to re-center the view to user defined pose?

I will check the re-center option using the Gear VR controller pupphelp referred to above.

In a related note, when is ALVR_ARCore capturing the initial pose?  Would it be possible to display a warning message that it is being measured?

Regarding the ALVR server, I using version 2.3.1 and I am wondering if there are explanations about the listed features in this "Other" menu (Fake Base Station, Apply Offset, Run Command, …)?
I can guess what some are (Apply Offset for starting height), but I am curious about others.

Thank you again for a great Project.
Donat

**Comment by maurixyz** [comment]
Same problem for me, I use 2 psmove and can't use the recenter button on the original controller. Would be great if we can have a re-center shortcut on the keyboard this will make all the VR experience much better.
Anyway thank you this great software.

**Comment by wonson** [comment]
Same.

Would it be possible that:
1. Use combo key on controller work as "Recenter" button 
e.g. back and trackpad click(i found it possible!);
or some button + trigger (but this may slow down its trigger respond for 100-200ms?)

2. Long press back button or trackpad click
2. trackpad tap as trackpad click, and trackpad click as recenter
