### ISSUE TITLE
Possible to make a version that runs on any android or linux device and outputs video to hdmi?

### ISSUE THREAD

**Issue by Lightsteed** [polygraphene/ALVR#25]
If you are able to do that, you may be have a program that can run on any sufficiently powered device that can supply wireless video to a vive or rift. Tracking info can run over virtual here on the same device and that would make a diy and open source solution for wireless vr, a much cheaper alternative to tpcast.. im one of the devs that made opentpcast, hit me up on the discord if u want to discuss!

**Comment by polygraphene** [comment]
It can be done, but we lose smooth head-tracking on other devices.
ALVR's smooth head tracking is achieved by ASW which provided by Oculus Go.
So we can't use AWS on other devices.

**Comment by dusan-t** [comment]
Well maybe you should it give it a shot and release it anyway. Let users decide if tracking is acceptable.

Btw, I use this to play SteamVR on Android: https://github.com/r57zone/OpenVR-OpenTrack
Freepie IMU sends tracking data from phone to Opentrack and then to SteamVR and then you use Moonlight to stream the image to the phone. It works in SteamVR extended mode only.
