### ISSUE TITLE
How to increase the bitrate to 1000Mbit / s to get better video quality.

### ISSUE THREAD

**Issue by maurixyz** [polygraphene/ALVR#250]
First of all congratulations for this wonderful software. I connected my GearVR directly to the PC using a 1000Mbit USB type-c ethernet adapter (IF YOU HAVE CONNECTION PROBLEMS DISABLE THE FIREWALL OF WIN7). So the connection of ALVR to my PC, which has a 1000 Mbit / s network card, has a bandwidth of 1000Mbit / s. With the current settings of ALVR at most (bitrate at 250 Mbit / s and Buffer size at 2000Kb) when I set the video resolution at 2880x1440 with codec H265 (and also with H264) ALVR starts to have big problems because the band of 250mbit is not enough and huge latencies are created with the value of transport latency that reaches thousands of ms while that of decode latency remains on 10-20ms. I assume that if I would be able to use all the 1000Mbit / s of my connection the problem could be solved, since the problem does not seem to depend on the hardware at my disposal because the CPU (W3680) remains around 30% and the gpu (RTX2080) around 40%. So I ask you how can I go beyond the 250mbit / s limit? Can you suggest me some hacks somewhere in ALVR to set a 1000Mbit as maximum bitrate? As operating system I have WIN7, the transition to WIN10 could improve something in terms of performance with ALVR. I have visual c ++ 2017 I do not know if this is important. If I lower the resolution ALVR works fine but it's a shame as with my S8 I can have a higher resolution which greatly improves the experience. I hope you can help me thanks in advance.

**Comment by pupphelper** [comment]
I don't know that you will see any benefits of encoding at gigabit, bitrates.  Your gearVR won't be able to decode such a big stream and you wouldn't see any visual quality increases.  Your gear is probably running 2560x1440.  Most blu-ray movies are encoded at 20-30Mbit and you don't notice any quality loss or artifacts.   Once you hit that 30-50Mbit range each increase will give you a virtually negligible difference.  If you want uncompressed quality and are willing to be tethered to your computer with a cord, you might want to consider getting a Full Oculus or Vive, so you get direct HDMI.  I've played with a number of different bit rates and I can hardly see any difference. 

You also don't want to increase the buffer size as now you are adding latency to your gaming.  You want the lowest buffer for the lowest lag in the game.

**Comment by maurixyz** [comment]
Pupphelper thanks for the reply. I'm trying to get as much as I can from what I have. At the moment ALVR is stable only at a resolution of 2048x1024, my S8 has a screen with a resolution of 2960x1440. By setting ALVR to a resolution of 2880x1440 , I can see a great improvement in the image compared to the 2048x1024 resolution. Now the problem is that setting the resolution of ALVR to 2880x1440 (but also 2560x1280) makes ALVR is unusable for the latency. I would like to know if any of you managed to use ALVR at the resolution of 2880x1440 with a smartphone that has a processor comparable to that of my S8 and then a CPU like the 8895 SAMSUNG Exynos and a GPU like the Mali-G71 MP20, because as rightly points out Pupphelper it could be the smartphone that does not make it to manage the data that come to it. Also if someone has succeeded to use ALVR at 2880x1440 can please indicate the settings used since all the tests I have done so far have gone wrong? Thanks in advance to those who will respond.

**Comment by pupphelper** [comment]
There are a couple of things, you need to confirm that your galaxy S8 is Exynos or Snapdragon 835.  Exynos is able to decode much higher resolution  than a snapdragon, however snapdragon is better at VR and ARcore.  knowing your processor will help you determine what resolutions you can decode properly.  I'm running an S9 with a Snapdragon 845 and I can run at 2560x1280 and 2800x1440, at the recommended 30Mbit and 200k buffer over 5G wifi.  Resolution you will see the biggest difference, all bitrates about 20/25 will be mostly negligible as far as quality.   I think you'll find with VR performance > resolution or visual, as its easy to get motion sick when the frame-rates aren't keeping up and we're already running at 60fps vs 90fps on a proper headset.    Do some research on the native decoding of your S8 and you should be able to find an answer.  You can always download videos at 2880x1440 and try to play them in skybox to see how they play.   You should be able to quickly determine your phones capabilities.   Also remember that the more decoding pressure you add + ARcore if you use it will cause your phone to overheat faster.  So at some point you'll need to find a balance between playtime, motion sickness and visual quality.  I'm extremely satisfied with 2560x1280 at 30Mbit on ALVR.

**Comment by ileile** [comment]
I guess there is a bug in ALVR. I am using a mod version of ALVR made by nolo vr. It can run with 2560x1440 and 30Mbps with acceptable performance, but with same resolution, if I set the bitrate higher, I will see a "huge latency" about several seconds, black edges, extremely slow, etc. And unless I restart my phone, it won't properly work again even if I kill the app and restart it.

I won't open a new issue because I'm not using the official ALVR. But I think the bug exists in both versions.

On the other hand, pupphelper is right. The problem is not your connection, but the capabilities of decoding.
