### ISSUE TITLE
Can't get above 15Mbps on 5Ghz Gigabit Internet.

### ISSUE THREAD

**Issue by Aaaaaaaaaaaaagh** [polygraphene/ALVR#255]
Hey, What's up. I have a R71700/GTX1070 gigabit hardwired to my router, which is a WNDR3400. It's streaming wirelessly to my phone, and can definitely hit gigabit speeds. However, I have extreme packet loss if I go to 30mbps. I see a lot of dropped packets, like 40 a second. Is there a way to fix this? Increasing buffer doesn't seem to help.

**Comment by fdinsdale** [comment]
I had the same router as you and it usually worked well (some chop and lag) at the settings you are using. 
I recently upgraded to an AC1750. Better performance although I keep the alvr settings the same; 
30 Mbps, buffer at 480, h.265 and 3072x1536. 

The new router has very little lag and chop at these settings and i saw little or no improvement at increased stream or buffer rates.
I prefer the 3072x1536 setting, it clears up the image/text even more

as long as your pc is hardwired to the router and are using the 5ghz band you should be Ok with the n router. Are you within a few meters of the router?

**Comment by vitskr** [comment]
Whats the purpose of running 3072x1536 resolution? Does it really improve performance?

**Comment by fdinsdale** [comment]
Yes resolution/quality. And it doesn't seem to give a frame rate hit as much as cranking up ss in steam

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
