### ISSUE TITLE
I can't get ALVR to work except wheni run as administrator.

### ISSUE THREAD

**Issue by Lightsteed** [polygraphene/ALVR#26]
am i missing something?

**Comment by polygraphene** [comment]
Generally, ALVR doesn't require admin privilege.
It is strange.

Where did you install ALVR (extract zip)?
I recommend that you install under user directory like Desktop or Documents.
If you get an error after checking it, can you explain how ALVR can't work?

**Comment by Lightsteed** [comment]
i put it on my desktop and it works now, it wasnt working before when in my program files folder for some reason, if i get the error again i will update you. thanks!

**Comment by polygraphene** [comment]
Great!
