### ISSUE TITLE
Null Reference Exception and 64bit Nvidia Driver Error while building from source

### ISSUE THREAD

**Issue by fxsrt10** [polygraphene/ALVR#263]
So I'm able to get run the application from the installer just fine, but I tried building it from source and I get the following issues

This is the gui error
![error](https://user-images.githubusercontent.com/4075097/52378111-7288b400-2a2c-11e9-89bf-5364272081db.PNG)

But this is what I get while trying to debug it
![image](https://user-images.githubusercontent.com/4075097/52378084-600e7a80-2a2c-11e9-8333-c7843017d28a.png)

Anyone have any advice?

**Comment by Eg0Jemima** [comment]
I am also currently getting this error after pointing to CUDA 10.1 and generating the shared files
