### ISSUE TITLE
Does ALVR works with Steam + Proton via Wine?

### ISSUE THREAD

**Issue by HoshiYamazaki** [polygraphene/ALVR#264]
I ask because I'm curious and want to move to Linux.
Game I play is VR Chat, I own Oculus Go, until I will buy Rift I want to use ALVR.
Thanks!

**Comment by parkerlreed** [comment]
I'm interested too. There's NOTHING for streaming VR games from a Linux machine. Steam Link in the Oculus TV is the closest thing e have and that's still just 2D.

**Comment by safijari** [comment]
Did anyone end up testing this?

**Comment by parkerlreed** [comment]
@safijari I think it's relying way too heavily on Windows APIs for everything. I never got it to run past maybe the installer.

**Comment by HoshiYamazaki** [comment]
> I'm interested too. There's NOTHING for streaming VR games from a Linux machine. Steam Link in the Oculus TV is the closest thing we have and that's still just 2D.

Sadly, even propiertary Virtual Desktop is not supporting Linux and Steam Link is running in Oculus TV with limited resolution (not even FullHD, if I remember correctly 1280x720)... Nah.
