### ISSUE TITLE
Is there a Camera passthrough option for ALVR Normal Client similar to ALVR ARCore?

### ISSUE THREAD

**Issue by dpluigi** [polygraphene/ALVR#265]
Is there a Camera passthrough for ALVR Normal Client similar to ALVR ARCore Client?

This feature is really useful with ALVR ARCore client, if it is not included in the Normal ALVR client, can it be added?

Some might also like the height adjustment going up and down on trackpad for the normal client.  A dead zone might be increased to avoid vertical offset when one wants only to switch between camera passthrough and VR view.

Thank you again for a great project.

**Comment by ICURSEDANGEL** [comment]
@dpluigi hey my ALVR ARCore client becomes passthrough after like a min of playing and I don't know how to return it back I have tried to reinstall the app clear AppData and even reset my phone but nothing works :(.

please, how can I switch from passthrough to VR view?
P.S: my device is an Exynos S7 Edge Duos (SM-G935FD)

**Comment by dpluigi** [comment]
@ICURSEDANGEL on the Gear VR headset there is a trackpad on the right side.  With the ALVR ARCore client (apk), sliding your finger backward or forward transitions the view from VR to passthrough camera ( i.e. cellphone front camera) with a transparency gradient, and back when sliding in the opposite direction.  Are you touching the trackpad and inadvertently sliding into passthrough view?  If so try sling backwards your finger on the trackpad.

My mobile device is a Samsung S9 with the newer Gear VR headset and I did not experience any "drift" into passthrough view" without me touching the trackpad.  I am not familiar with the previous version of the Gear VR  headset nor your S7 Edge Duos device.  Others might be able to clarify if you are facing some bugs,  artifacts or limitations.

Note that the normal client does not have this option as far as I can tell.  I am a user like you and not one of the developer though.  I am just starting to get my feet wet with Visual Studio to look at the code and possibly try to tinker with the ALVR Normal source code for my own use. 
I started this post because the option found in the ALVR ARCore Is useful but the tracking process is too much for my intended use; I am hopeful this feature (and user viewing height adjustment) could be added to ALVR Normal Client.

Hopefully you can figure out the quirk on your setup.

**Comment by ICURSEDANGEL** [comment]
@dpluigi Thanks it works, i would like to also know if u
your having problems with the app itself when im using it the Screen area (were you look at) feels like its lagging as it crops out when im using the ap same thing the the original app but with other apps it works normally. 

did this happen to you/found a way to fix it?
![smartselect_20190225-065852_az screen recorder](https://user-images.githubusercontent.com/40498348/53313560-fa930880-38ca-11e9-96e6-d23654812057.jpg)

here as u see (used gear vr dev mode to show) it laggs when im moving while other apps lens stay the same size.
