### ISSUE TITLE
Is there a zoom option along head pose axis (foward looking) in ALVR Normal client?

### ISSUE THREAD

**Issue by dpluigi** [polygraphene/ALVR#266]
Gear VR fitted with Samsung Galaxy S9 streaming with ALVR 2.3.1 Normal provides a 3DOF mobile headset solution.

Is there an option to  zoom along head pose axis (forward looking) in ALVR Normal client bound to a keyboard, mouse, controller keypress?

It would be useful for application where limited DOF tracking does not allow to say lean forward to zoom.  There is ALVR + ARCore client, which could do this, but it is more demanding on the mobile phone and adds more DOF than is needed, and hence a Normal Client would be a lighter and more effective approach. 
In my application I am using ALVR to stream a flight simulator in my mobile headset.  The instrument panel or map are a little difficult to read but a slight zoom makes it possible.

Thank you,
Donat

**Comment by numpad0** [comment]
I don't think one's ever supposed to disconnect head movement or view distortion from body movement or native eyesight in VR as inconsistencies are the source of VR sickness...
