### ISSUE TITLE
ALVR Server Crashed

### ISSUE THREAD

**Issue by rpkane** [polygraphene/ALVR#268]
Hello,
I am unable to get ALVR to work with my S7 and Gear VR. I am using a MSI GS65 with GTX1070 and i7-8750. I plug the s7 into my headset and start ALVR in gear VR, then open the desktop app. When I load it, I get an error that says 

"Failed to start audio capture. Thread aborted before starting to loopback capture. message=IAudioClient::Initialize failed: hr = 0x88890008" 

I have installed GeForce drivers, as well as looked at other threads on here, but cannot figure out how to get it to work (not sure how to disable audio streaming). 
Any help would be greatly appreciated!!

**Comment by Aelcyx** [comment]
Unchecking "Steam Sound" worked for me.
https://github.com/polygraphene/ALVR/issues/280
