### ISSUE TITLE
Looking into the ground

### ISSUE THREAD

**Issue by ghost** [polygraphene/ALVR#269]
When I startup any game on SteamVR it will 'spawn' me into the ground or just lower than the normal view.

**Comment by MrSnakie** [comment]
> When I startup any game on SteamVR it will 'spawn' me into the ground or just lower than the normal view.

Have you configured the **SteamVR Room Setup Wizard**?

If not, start it on SteamVR and follow this step:
1. Click on "_Standing Only_".
2. Then next button (headset need to be connected).
3. Click on "_Calibrate center_" and next button.
4. Put your size in text area (for me I put 160 cm). Click on "_Calibrate Floor_" and next button.
6. Done.
