### ISSUE TITLE
S10 and S10+ predicted performance with ALVR-ARCore?

### ISSUE THREAD

**Issue by dpluigi** [polygraphene/ALVR#272]
Hi,

Will the increased power of both CPU and GPU in the S10 and S10+ allow higher FPS in Gear VR (say 72 or 90fps)?
Also, with the announced ARCore support for the S10 phones, will the increased CPU power help overcome the CPU bottleneck and heating-up issue during extended AR app use encountered with S9?

The use of ALVR-ARCore is limited to about 1h without additional cooling with my S9.

I am trying to rationalize the cost of $300 of an S10 upgrade (with trade-in of my S9), Gear VR and AR with ARCore applications.

Thank you for you for your inputs.
D

**Comment by TheJaeger** [comment]
1. Your FPS is determined by your computer, not your phone. Content renders on your computer and your phone merely mirrors it via ALVR. The FPSes you listed are commonly used as refresh rates of the screen on various HMDs. If you're talking about achieving this then it's not possible. The S10 screen refreshes at 60 Hz. Even if you can render your content at 144 Hz, it will only display at 60 Hz.

2. ARCore is computationally intensive, so you'll still experience heating. As to how hot your phone gets remains to be seen.
