### ISSUE TITLE
black borders in ALVR 3.2.1

### ISSUE THREAD

**Issue by stefanospaccavento** [polygraphene/ALVR#273]
I installed ALVR 2.3.1 on both PC and oculus go. As soon as I start the ALVR client on oculus go I noticed that by making quick rotations of the head from right to left and vice versa laterally black borders are created which disappear when I stop the rotation. This happens even if I have not connected oculus go to the PC through wifi and that tell me that is a client problem. I mean that this flaw is present both in the home of ALVR in oculus go when the writing appears to connect it to the PC, both inside the cars when I use project cars 2. all inside of the game menus this defect is not present. From what can depend. Thanks in advanc

**Comment by fdinsdale** [comment]
I also had that problem when i first started using alvr. Through a lot of trial and error i finally realized the bit rate was turned up to high. I had it at about 55 and when i set it at the recommended 30mbps the black borders went away. I saw no degradation of image quality at 30mbps only a huge reduction of lag and stutter.
I see those borders also when just launching the client without connecting to the server but it stops when i connect.
I strongly recommend using an AC router and stay on the 5g band. Also hard wire your pc to router if you haven't already done so

**Comment by ileile** [comment]
ALVR uses Reed Solomon algorithm to correct package loss/error and to reconstruct frames, but this algorithm is not suitable for streaming purpose, especially on mobile device like GearVR or Oculus go. It's too heavy and it's a monster that eats CPU on the client side. 

Personally I think that this algorithm should be replaced by a lightweight method. Before that, we could make our network connection much stronger by using a separate 5G router only for streaming and use a lower bit-rate. Then package losses/delays is decreased and the stress on CPU is also decreased. The black borders, artifacts and glitch should go away if we have found a proper setup suitable for the CPU of the HMD/mobile device.

**Comment by ileile** [comment]
No problem with 30mbps doesn't mean ALVR uses properly algorithm. 

A perfect network means that we even don't need a FEC or any correction. Then the RS code/algorithm just waste more bandwidth, heat the CPU, and drain the battery. Even TCP (with its own mechanisms) will do better with a perfect network.

The FEC in ALVR doesn't resolve the problems come from a imperfect network, but itself is the problem. RS code is good for satellites but it's not good at streaming in a network on earth, especially there are real-time demands.
