### ISSUE TITLE
USB to ethernet tether not working

### ISSUE THREAD

**Issue by Xavrockbeats** [polygraphene/ALVR#274]
I have gotten ALVR to work mostly well with wifi, but I want the better connection of a USBc to ethernet gigabit connection.  The problem is ALVR seems to not detect the GearVR device when I connect it to the computer, and I cant figure out if there's a setting I'm missing or not.  An I doing this right, or is this not as supported as it said?  Thanks.

**Comment by maurixyz** [comment]
Turn off the windows firewall, I had the same problem and this did work for me.
