### ISSUE TITLE
is ALVR CPU demanding ? QuickSync support ?

### ISSUE THREAD

**Issue by Lyks-tech** [polygraphene/ALVR#275]
Hey!

Fantastic project, thank you first of all.

I run on a S9 Gear VR and I have a terrible PC on the server side: 
666MHz 16go ram, i5 760 (yes 3 digits), GTX 770 (kinda ok)

I have a 866Mbps WiFi bitrate with 5GHz ac, but still, I have HUGE packet losses when going over 2048x1024 on ALVR, even with large buffer and low bitrate (20Mbps), SIMPLY on SteamVR Home, which makes me think the graphic card alone can't be the issue, and CPU + speedrate RAM is crucial.

Would a significant upgrade on my CPU resolve this issue, is it normal so far ?

Other question, on some CPU it's possible to enable QuickSync which basically will make use of the iGPU to help the GPU if I'm not mistaking, it's largely useful for H.264 encoding, like for streamers with OBS, but is it supported by ALVR ? Couldn't find this out.

Thank you a lot for your precious help

**Comment by Lyks-tech** [comment]
Hey, I upgraded to a i5 9400f, new Mobo ofc and 2666MHz ram, but I see no improvement in encoding.

I think this is because ALVR only uses NVENC, both in h.264 and h.265, which is the GPU encoder, so that may be normal and I'll need to buy a solid graphic card.

Can you confirm please? :)

**Comment by Lyks-tech** [comment]
Just to say that I've now upgraded to a gtx 1070 OC and it works flawlessly... I've got everything to max 3050x1554 res, low buffer, bitrate at 35mbps in HVEC / h.265 and ultra settings to games like Subnautica.

Waow hopefully ALVR isn't discontinued and will work with the Oculus Quest <3

**Comment by NeeXxoR** [comment]
I have GT 840M and it simply not start, i searched everywhere, nothing helped me... i opened issue but the developer doesn't seem to be interested in people's issues anymore...
He should add the possibility to choose the encoder like Riftc*t
