### ISSUE TITLE
ALVR Crash Report, Code = 2

### ISSUE THREAD

**Issue by mandevillean** [polygraphene/ALVR#277]
I've been trying to set up ALVR with my Oculus Go. I received the following crash report: 

. Code=2 NvEncoder::NvEncoder : m_nvenc.nvEncOpenEncodeSessionEx(&encodeSessionExParams, &hEncoder) returned error 2 at c:\src\alvr\alvr_server\nvencoder.cpp:51

I suspect the NVencoder not working. Yet I've updated my graphics drivers and confirmed that my GPU (GTX 1070) has NVENC support. 

I can't figure out what's going wrong.

**Comment by Lyks-tech** [comment]
Hey, dunnot if I can help you, but of course your gpu can do video encoding, have you tried in h.264 ? Although I would be very surprised if the gtx 1070 didn't support HEVC

**Comment by mandevillean** [comment]
Thanks for the suggestion, but I tried h.264. Didn't work.

**Comment by TrumX** [comment]
uninstall programm, reinstall, also make sure graphic drivers are updated, run in admin mode

**Comment by schooltoons** [comment]
Error message in ALVR

Unhandled Exception.
ExceptionCode=C0000005
Address=00007FF98D4DA036 (00007FF98D4C0000 + 000000000001A036)
[ALVR_CrashLog_20190323_184750.log]

Crash Log

(https://github.com/polygraphene/ALVR/files/2999897/ALVR_CrashLog_20190323_184750.log)

If I launch ALVR I get the ALVR error message above and the crash log. ALVR remains open.

If I close the error messages, the device shows as recognized. If I press the connect button Steam VR crashes with a Fatal Error message

Windows 10, nVidia 1070, tried h264 and h265 with recommended settings for everything else.

**Comment by mandevillean** [comment]
I ended up getting ALVR working after I connected my monitor to the video graphics card instead of the motherboard.
