### ISSUE TITLE
Issues with AMD GPU 

### ISSUE THREAD

**Issue by GreyWaffle** [polygraphene/ALVR#278]
I have a Gear VR, an S8 and a decent connection, so I don't suppose there's a problem there. Using H.265 HEVC gives an error and won't start. Using H.264 AVC will start the server, and i am able to connect my phone, but it gets stuck on "Connected! Streaming will begin shortly". When I lower the resolution, it works perfectly as it should, but the low resolution gives me a headache after a minute.
Please help

**Comment by shodgson88** [comment]
Didn't want to create a new topic as I am having exactly the same issue. I can go no higher than 75% resolution when streaming to my Quest from my AMD PC. The bitrate can be adjusted really high with no issues and the latency is fine but anything higher than 75% Res gets stuck on the white waiting to connect screen. The movement of the headeset and controllers is still showing ok on the PC, just no image within the HMD.

Any advice would be greatly appreciated!

**Comment by Molotow77** [comment]
i have almost the same issue have you found any thing that could help me
