### ISSUE TITLE
Server is down 3 seconds after it's live

### ISSUE THREAD

**Issue by CaptainMalk** [polygraphene/ALVR#28]
I have an amd radeon rx 480, so if that's the problem I'll go cry in a corner. If that's not the case, then here's my problem:
when I start the server it opens steamVR and goes live, but after a few seconds it dies. 
I sometimes get this message: 
openvr.tool.steamvr_room_setup.Error:
VRApplicationError_IPCFailed.
Others I get this .NET Framework Error:

> Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
> Just-In-Time (JIT) en lugar de a este cuadro de diálogo.
> 
> ************** Texto de la excepción **************
> System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
>    en ALVR.ControlSocket.<ReadNextMessage>d__11.MoveNext()
> --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
>    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    en ALVR.ControlSocket.<SendCommand>d__10.MoveNext()
> --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
>    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    en ALVR.Launcher.<UpdateClients>d__14.MoveNext()
> --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
>    en System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
> 
> 
> ************** Ensamblados cargados **************
> mscorlib
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2661.0 built by: NET471REL1LAST_C
>     Código base: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> ALVR
>     Versión del ensamblado: 1.9.1.0
>     Versión Win32: 1.9.1.0
>     Código base: file:///C:/Program%20Files%20(x86)/ALVR/ALVR.exe
> ----------------------------------------
> System.Windows.Forms
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2556.0 built by: NET471REL1
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2556.0 built by: NET471REL1
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2556.0 built by: NET471REL1
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> MetroFramework
>     Versión del ensamblado: 1.2.0.3
>     Versión Win32: 1.2.0.3
>     Código base: file:///C:/Program%20Files%20(x86)/ALVR/MetroFramework.DLL
> ----------------------------------------
> System.Configuration
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2556.0 built by: NET471REL1
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2661.0 built by: NET471REL1LAST_C
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2612.0 built by: NET471REL1LAST_B
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.Windows.Forms.resources
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2556.0 built by: NET471REL1
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
> ----------------------------------------
> MetroFramework.Fonts
>     Versión del ensamblado: 1.2.0.3
>     Versión Win32: 1.2.0.3
>     Código base: file:///C:/Program%20Files%20(x86)/ALVR/MetroFramework.Fonts.DLL
> ----------------------------------------
> Microsoft.CSharp
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2556.0
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
> ----------------------------------------
> System.Runtime.Serialization
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2612.0 built by: NET471REL1LAST_B
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ----------------------------------------
> System.Xml.Linq
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2556.0 built by: NET471REL1
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
> ----------------------------------------
> SMDiagnostics
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2612.0 built by: NET471REL1LAST_B
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
> ----------------------------------------
> System.ServiceModel.Internals
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2612.0 built by: NET471REL1LAST_B
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
> ----------------------------------------
> System.Dynamic
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2556.0
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
> ----------------------------------------
> Microsoft.CSharp.resources
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2556.0
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_es_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll
> ----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     Versión del ensamblado: 0.0.0.0
>     Versión Win32: 4.7.2661.0 built by: NET471REL1LAST_C
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
> ----------------------------------------
> System.resources
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2556.0 built by: NET471REL1
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.resources.dll
> ----------------------------------------
> mscorlib.resources
>     Versión del ensamblado: 4.0.0.0
>     Versión Win32: 4.7.2556.0 built by: NET471REL1
>     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
> ----------------------------------------
> 
> ************** Depuración JIT **************
> Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
> aplicación o equipo (machine.config) debe tener el
> valor jitDebugging establecido en la sección system.windows.forms.
> La aplicación también se debe compilar con la depuración
> habilitada
> 
> Por ejemplo:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
> se enviará al depurador JIT registrado en el equipo
> en lugar de controlarlo mediante el cuadro de diálogo.

I'm sorry it's in spanish, but you get the point. I've installed the drivers in the same drive as SteamVr, my AMD drivers are up to date and when I tryed to install vc_redist.x64.exe, windows told me that I already had a superior version.
I really dont know what else to do.

**Comment by polygraphene** [comment]
I'm sorry.
Currently, ALVR only supports NVIDIA graphic card.

**Comment by CaptainMalk** [comment]
Sad to hear, since this seems to be by far the best VR streamer for oculus go users.
Are you guys considering adding AMD support in future versions?
