### ISSUE TITLE
Audio Failure

### ISSUE THREAD

**Issue by Tphamille** [polygraphene/ALVR#280]
Ive seen similar issues to this on different versions but i cant seem to fix it on version 2.3.1 

Unhandled Exception.
ExceptionCode=C0000005
Address=00007FFB4D71A036 (00007FFB4D700000 + 000000000001A036)

and 

Failed to start audio capture. Thread aborted before starting to loopback capture. message=IAudioClient::Initialize failed: hr = 0x88890008

**Comment by kaasszje** [comment]
I had to uncheck steam audio. Then use sound from my pc.
