### ISSUE TITLE
Alvr crash

### ISSUE THREAD

**Issue by korncob** [polygraphene/ALVR#282]
I just attempted to use the newest version of alvr, first time using this program so I might have missed something but I get thus error when I press connect to headset:

Unhandled Exception.ExceptionCode=C0000005Address=000007FED88AA036(000007FED8890000 + 000000000001A036)

I updated drivers, set the video res and encoder to AVC and tried disabling streaming sound. I also noticed steamVR gets a 301 error when alvr gets its' error and weirdly enough it doesnt crash I just hit okay and the server still runs but I get the error again when I hit connect. I also tried reinstalling steamvr but no luck. Where would I find the error log if I need to attach that here?

**Comment by Nataliecatchat** [comment]
I'm getting the same error, ran fine the first time but came back a week later and I'm now seeing this error

**Comment by polygraphene** [comment]
Can you provide crash log file?
The file is located on `C:\Program Files\ALVR\logs`.

**Comment by Nataliecatchat** [comment]
I updated my graphics driver via Device Manager and the issue is now resolved
