### ISSUE TITLE
How to move forward in Skyrim VR with the trigger of the GO

### ISSUE THREAD

**Issue by justUmen** [polygraphene/ALVR#284]
Hi all,
I'm testing ALVR now with Skyrim VR on the Oculus GO. but i can't get the trigger to do the same as the key 'W', aka moving forward.
In the controller options of ALVR i have a list of events that can be linked to "trigger" but none of them is moving forward.

**Comment by Separisa** [comment]
Same here.

**Comment by justUmen** [comment]
Still don't know how to do that, but I now use a gamepad instead of the remote. (To have the crosshair always in the middle of the screen, change the option in the main menu. - not the one after loading a save)
