### ISSUE TITLE
OMFG I have seen a video with ALVR partially working on Quest!!! will it be fully available???

### ISSUE THREAD

**Issue by ManuelGDA** [polygraphene/ALVR#288]
It seemed that the issues are that the side-by-side was incorrect and that it tracked only one hand but it tracked the head and that hand (left) apparently in full 6DOF! I suposse there are more adjustments needed, tweakings etc (buttons, stability)... Are you going to work on a version for Oculus Quest? I know it´s been asked, Im sorry if this post is not necessary, I dont know besides github where to contact you. Please make it happen... you would be a god amongst developpers, consummers and companies XD!

**Comment by FingrMastr** [comment]
Please post the link to the video and possibly the dev name. I can help with that

**Comment by AltVRat** [comment]
I'm in for Quest!

**Comment by AltVRat** [comment]
@polygraphene do you have a Patreon so we can support more coding time?

**Comment by polygraphene** [comment]
@AltVRat I don't have Patreon. If you want to support me, I will be glad if you donate by PayPal. But I can't guarantee coding time for ALVR.

**Comment by jc-langevin** [comment]
where is that video?

**Comment by ManuelGDA** [comment]
The video was taken out of YouTube that same day by the autor of it, who did not wish for his test to be taken into account. Being that said, in just 2-3 days the quest will be available + the Alvr autor suggested he will be taking a look at it. We just have to wait.

**Comment by steviedale** [comment]
I just picked up my Oculus Quest today. Is it safe/possible to try the ALVR GO setup procedure on my Oculus Quest? I assume the worst that can happen is the app doesn't work. At the same time, I don't really understand how the Oculus Quest or GO work, so I'm a little afraid of destroying my headset.
