### ISSUE TITLE
NvEnc CreateEncoder failed

### ISSUE THREAD

**Issue by av8tr1** [polygraphene/ALVR#29]
![alvrerror1](https://user-images.githubusercontent.com/39891154/40894120-286e1d58-675c-11e8-8ac9-c1e377a254c8.jpg)

I get this error message every time I start ALVR.  

If I click ok it lets me click connect and launches both Oculus and SteamVR.  

Then server goes down as soon as Oculus and SteamVR start.  

Then it throws this Unhandled Exception error.  

![alvrerror2](https://user-images.githubusercontent.com/39891154/40894177-9b9f33e8-675c-11e8-940f-55bdc3ba0e5e.jpg)

Suggestions?

**Comment by gregann** [comment]
I think your drivers are outdated or not nvidia...
