### ISSUE TITLE
Cant run, Cant uninstall... so bad.

### ISSUE THREAD

**Issue by TebitoSan** [polygraphene/ALVR#292]
When i try to run ALVR ( any version ) , recive:

![image](https://user-images.githubusercontent.com/31389390/57442405-3abc2300-724c-11e9-881c-fdddd2ae7b6a.png)

And when i try to uninstall, cant do it, Just stay on "Uninstalling..." and no progress.

Windows 10, GTX 760.

**Comment by polygraphene** [comment]
For error message:
Did you install SteamVR? And if you moved install location of SteamVR to other drive, try to move C: drive.

For uninstall:
I'm sorry for inconvenience. Uninstaller seems broken...
Please remove `C:\Program Files\ALVR\driver\driver_uninstall.bat`.
Then kill process named `cmd.exe` or restart your PC.

**Comment by TebitoSan** [comment]
Yes, i can fixed. But, my problem now is with 2.3.0.

https://i.gyazo.com/9bac5e7b8a7d52b15571a8fdac5f0a9a.png

**Comment by polygraphene** [comment]
Try to choose H.264 on Video tab if you have not try.

Same issue?
https://github.com/polygraphene/ALVR/issues/206#issuecomment-431317164

**Comment by TebitoSan** [comment]
Issue is fixed when choose h.264 but... "finding headset" all time, "Headset not found". I have same version on headset, 2.3.0.

**Comment by polygraphene** [comment]
Please check the firewall settings (Permit UDP/9944 port)

**Comment by TebitoSan** [comment]
Yep!, when make my firewall off, server works!, thanks, ill go to see how to open my 9944 port.
