### ISSUE TITLE
Is it possible to connect multiple VR to Alvr? 

### ISSUE THREAD

**Issue by Maalgendy** [polygraphene/ALVR#294]
Hello,

I was wondering if it possible to use Alvr to stream vr video to multiple VR headset

**Comment by polygraphene** [comment]
Are you talking about sharing the same view (and head rotation) between two men?
It will cause bad VR sickness...

Can your demand be achieved by multiple PCs?

**Comment by Maalgendy** [comment]
No, I want to stream video from pc to multiple headset in a class room. So that the teacher can stream same video to all students.

**Comment by polygraphene** [comment]
The situation is difficult for ALVR.
Perhaps you can achieve by youtube 360 live.

2019年5月11日(土) 2:56 Maalgendy <notifications@github.com>:
