### ISSUE TITLE
Unable to find headset

### ISSUE THREAD

**Issue by pikkuu** [polygraphene/ALVR#295]
As the title says i'm struggling finding my oculus go.

I have tried re-installing both steam vr and alvr multiple times but still cant find my headset.

I have updated my nvidia drivers
running windows 10 64 bit
graphics card is gtx 970
ALVR version V2.3.1

[driver.log](https://ufile.io/6j6iglqb)
[vrmonitor.txt](https://ufile.io/fkem3yns)
[vrserver.txt](https://ufile.io/b2d8reop)

[Current installed ALVR drivers](https://i.gyazo.com/7d4c4bfe41cbfbb2d3f6d4fce628e1c2.png)

I have created a rule for 9944

 [vrserver.exe]
  TCP    127.0.0.1:9944         0.0.0.0:0              LISTENING
 [vrserver.exe]
  TCP    127.0.0.1:9944         127.0.0.1:52128        ESTABLISHED

there are other connections to vrserver.exe

both alvr and steam vr are located on my c: drive

any help would be appreciated.

**Comment by polygraphene** [comment]
It seems server is correctly listening the ports.

Did you try to change firewall settings?
You need to open 9944/udp port for private and public profile.

In addition, check if both Go and PC are connected under the same router.

**Comment by pikkuu** [comment]
yes i have changed my firewall settings to open 9944 for both public and private.

both the go and pc are on the same router too.

**Comment by polygraphene** [comment]
Are you able to use Wireshark?
If so, please check following.
https://github.com/polygraphene/ALVR/issues/62#issuecomment-398347915

Also, check if ping from PC to Go is working.

**Comment by pikkuu** [comment]
thanks, just checked that comment and I had created the rule but not activated it.
