### ISSUE TITLE
Add the ability to emulate VR controller buttons

### ISSUE THREAD

**Issue by aaronfranke** [polygraphene/ALVR#296]
It sucks that I am unable to play things like Google Earth VR simply because of not having enough buttons on my Oculus Go controller. Please allow us to emulate buttons that would exist on a Vive controller by pressing keys on my keyboard. Thanks!

**Comment by polygraphene** [comment]
You can achieve it by FreePIE.
https://github.com/polygraphene/ALVR/wiki/FreePIE-Integration
Try sample3.py which maps key to controller button in following mapping.
>map = [["system", Key.G], ["application_menu", Key.X], ["trigger", Key.T], ["a", Key.V], ["b", Key.B], ["x", Key.N], ["y", Key.M]
, ["grip", Key.F1], ["trackpad_click", Key.F2], ["back", Key.F3], ["guide", Key.F4], ["start", Key.F5]
, ["dpad_left", Key.F6], ["dpad_up", Key.F7], ["dpad_right", Key.F8], ["dpad_down", Key.F9], ["trackpad_touch", Key.F10]]
