### ISSUE TITLE
ALVR randomly stopped working.

### ISSUE THREAD

**Issue by katatime** [polygraphene/ALVR#299]
Had ALVR for over a year, no issues at all. A few days ago, upon booting up the program and clicking the start server button, Steam launches and is unable to find headset.  

Version is 2.3.1 both on PC and the Oculus GO. Didn't change anything at all when it comes to settings. reinstalled both ALVR and Steam VR. Please Halp!

**Comment by polygraphene** [comment]
Do you see "Server is alive" on ALVR launcher after launch steamvr?
Did you check firewall settings?

**Comment by katatime** [comment]
No. I have tried everything in the other issues. It used to work fine, until one day with no changes at all, it stopped. Steam shows headset not detected. I tried resetting. I tried reinstalling. I cannot get to server is live.

**Comment by katatime** [comment]
If it gives you any clues, skyboxvr seems to work no problem

**Comment by polygraphene** [comment]
Can you provide following information?

1. Screenshot of SteamVR
2. Result of "List drivers" button on About tab.
3. Debug log file `C:\Program Files\ALVR\logs\driver.log`. -> [How to enable debug log](https://github.com/polygraphene/ALVR/wiki/Debugging#how-to-enable-server-driver-log-output)
4. log of SteamVR. `C:\Program Files (x86)\Steam\logs\vrserver.txt`

**Comment by katatime** [comment]
you wont believe this, but as soon as i checked the debug log to enable, it started working. Would you still like me to provide the info?

**Comment by POTATOChrisscar** [comment]
Same thing happened to me. Worked perfectly but now all of a sudden it stopped working?? It happened to me a day ago, I just turned off WiFi on my Quest and turned it on again and started working? It seem's like it just works when it wants to.
