### ISSUE TITLE
日本からの寄付について

### ISSUE THREAD

**Issue by Tomozow** [polygraphene/ALVR#3]
日本から寄付する際なのですが
"PayPalでは、現在JPの買い手からの寄付支払いはサポートされません。ご迷惑をおかけしますことをお詫びいたします。"
といいたエラーが出てしまい支払いすることができませんでした。

以下wikiに日本から寄付をする方法が紹介されているのですが、polygrapheneさんの公開されてるメールアドレスなのが見当たりませんでした。
http://seesaawiki.jp/odyssey1/d/%B4%F3%C9%D5(Donate)

もし差し支えなければ、PayPal送金用のメールアドレスなどを公開していただけませんでしょうか？

**Comment by polygraphene** [comment]
寄付のご希望ということで、ありがとうございます。

あまりよく調べずにPayPalのリンクを貼ってしまいました。失礼いたしました。
メールアドレスを貼ればよかったんですね。
PayPalのメールアドレスはgithubと同じ
`polygraphene@gmail.com`
を使っています。
これで送金できますでしょうか？

**Comment by Tomozow** [comment]
無事支払いができたようです！

**Comment by polygraphene** [comment]
早速のご寄付ありがとうございます。
こちらでも確認が取れました。
大事に使わせて頂きたいと思います！
開発もがんばります！
