### ISSUE TITLE
Certificate Error when installing 1.9.1

### ISSUE THREAD

**Issue by Jbbrack03** [polygraphene/ALVR#30]
When I try to install the 1.9.1 release on Oculus Go via adb, I get the following:

Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vm1993922286.tmp.apk: Attempt to get length of null array]

**Comment by polygraphene** [comment]
Weird...
I have signed the apk...
Please retry to download apk and uninstall ALVR app if you already installed.
Or please try older version.

**Comment by Jbbrack03** [comment]
It worked today. Not sure why it didn’t two days ago. Thank you for replying!
