### ISSUE TITLE
Oculus Quest already working with ALVR in 6dof

### ISSUE THREAD

**Issue by FingrMastr** [polygraphene/ALVR#301]
First of all I want to say thanks for the awesome work in ALVR. Indeed it is an incredible piece of software. I’m a mobile developer, so I know what I’m saying.

Then, I found this video on YouTube, showing ALVR working out of the box with Quest, with 6dof, with some FOV problems and without controllers (Elite Dangerous).

https://m.youtube.com/watch?v=VaGjyT8GDx0

Please Polygraphene, continue your awesome work!! I will test it on my upcoming Quest and report you a detailed buglist and impressions...

**Comment by SpookyBear0** [comment]
Hopefully he can get out a ALPHA ALPHA ALPHA barley works version.

**Comment by polygraphene** [comment]
https://github.com/polygraphene/ALVR/issues/287#issuecomment-495337038

**Comment by moallan03** [comment]
Hi are you aware of the image issue? I have seen people report "warped images" and some say the eyes looked to be flipped
