### ISSUE TITLE
Image quality error

### ISSUE THREAD

**Issue by moallan03** [polygraphene/ALVR#302]
Hi are you aware of the image issue? I have seen people report "warped images" and some say the eyes looked to be flipped and perspective being off

**Comment by Woohaaa** [comment]
Same problem for me.

**Comment by polygraphene** [comment]
I think it was fixed. https://github.com/polygraphene/ALVR/issues/287#issuecomment-495533973
Please try it.
https://github.com/polygraphene/ALVR/releases/tag/v2.4.0-alpha2

**Comment by evertec82** [comment]
> I think it was fixed. [#287 (comment)](https://github.com/polygraphene/ALVR/issues/287#issuecomment-495533973)
> Please try it.
> https://github.com/polygraphene/ALVR/releases/tag/v2.4.0-alpha2

Thanks, the image error is now fixed! However, there doesn't seem to be a mapping for touchpad clicks, so there is no way to play many games as they require this.

**Comment by machenmusik** [comment]
See https://github.com/polygraphene/ALVR/issues/287#issuecomment-495773998
