### ISSUE TITLE
Steam vr not detecting controllers or headset

### ISSUE THREAD

**Issue by moallan03** [polygraphene/ALVR#308]
Title. Here is some screenshots. Im pretty sure i downloaded it right. Steam vr not detecting anything http://prntscr.com/ntdd76 Some server stuff http://prntscr.com/ntddif and drivers page http://prntscr.com/ntddn3 i have no clue why riftcat is showing when i deleted it

**Comment by Midnightmaster** [comment]
Same here. Both check boxes are set in the firewall window. I tried the current and the last version.

**Comment by ekode** [comment]
Same here.

Sometime last year I tried to use ALVR and GO to connect to my PC and I gave up. Now I am trying the same with Quest and it seems I have exactly the same problem.

ALVR server app is not reporting any issues. It shows it is connected to client (Quest) and it shows my Quest IP address. Client app on Quest is just showing message to press connect button in server app which I did. In the process, ALVR triggers SteamVR Room Setup which is supposed to recognize quest and controllers. That's where party stops for me. Steam is not seeing anything.

I checked my router settings, completely removed firewall, checked windows 10 port forwarding to make sure proper ports are open (as author suggested). It just refuses to work. I tried Moonlight app to stream PC to my phone and that worked fine. I have GTX 970, so ALVR should work.

One thing I noticed, when I ping both, Quest and GO, I get message "Destination host unreachable". I don't know why. I can ping any device on my network, but just not Quest and Go. I wonder if that is an issue.

**Comment by fjleon1980** [comment]
i had this problem when i was close to my computer (thus not in my guardian zone). went back to my guardian zone and it was detected

**Comment by ekode** [comment]
> i had this problem when i was close to my computer (thus not in my guardian zone). went back to my guardian zone and it was detected

I tried that. Headset was within guardian, but tried to take it out and in. Didn't help.

**Comment by Midnightmaster** [comment]
It runs well, when i disable my Firewall. What are the recommended settings for the firewall (UDP port in and out/TCP port in and out)?

**Comment by Fixkey** [comment]
Had the same problem, I gave firewall permissions to SteamVR and that fixed it.

**Comment by polygraphene** [comment]
ALVR needs 9943/udp and 9944/udp.
Alpha5 has `add_firewall_rules.bat` script to allow ALVR and SteamVR to communicate with client. (Need to be run as adminstrator.)
I recommend to use this script for firewall issues.

**Comment by POTATOChrisscar** [comment]
I've tried everything mentioned and nothing has worked at all. I even did what was mentioned above. Nothing. I'm kinda on the verge on giving up already.

**Comment by polygraphene** [comment]
That's is maybe a network issue.
Try to [use Wireshark](https://github.com/polygraphene/ALVR/wiki/Troubleshooting#1-you-need-to-debug-network-issue) to deconstruct the issue.
