### ISSUE TITLE
Will it ever work with lesser GPUs?

### ISSUE THREAD

**Issue by ChicknGawd** [polygraphene/ALVR#309]
I would like to use ALVR with my laptop, but it will not let me because it doesn't have an NVIDIA Gpu wit NVENC. My current laptop is by HP, has an Intel Core i3 processor, 8 gb of ram, and Intel UHD Graphics 620, and it can run vr games fine when I use my friend's VR with it, yet ALVR cannot work correctly because there is no NVENC. I was wondering if ALVR will ever be able to run without it.

**Comment by moallan03** [comment]
Your laptop cant handle vr

**Comment by simonk83** [comment]
So I have a Quest on the way, and at the moment just have a fairly recent Mac laptop, but it still only has a Radeon Pro 460. I ran the SteamVR test app and it failed pretty hard 👍 

I'm actually considering building a small PC just to get ALVR working for the Quest with Steam games. Can anyone tell me the minimum GPU and CPU I should go for?

**Comment by numpad0** [comment]
I think the recommended and minimum specs are still 1660/1060/970 and 1050Ti(framerate impacted) respectively across the board. Microsoft technically allows integrated Intel GPU for WMR but I believe that's due to corporate politics.

**Comment by polygraphene** [comment]
It could be possible to support Intel QSV to encode in ALVR. (I have a plan)
But I don't think Intel iGPU can comfortably run VR applications.

**Comment by trabedaboi** [comment]
i hope it works with my temp card which is an amd r9 290x xfx
