### ISSUE TITLE
Any way to bypass positional sensor restrictions?

### ISSUE THREAD

**Issue by TyrannicalBlade** [polygraphene/ALVR#31]
Like vridge with Fake SteamVR sensor's(freetrack) option to bypass sensor req on games that require  but don't demand it (if using a xbox controller) but won't let you past it? ( i.e. Chronos)

**Comment by polygraphene** [comment]
I don't know what the Fake SteamVR sensor option does and what that games requires.
But ALVR provides a position which is calculated by head-neck model of Oculus Mobile SDK to SteamVR.
Is the position not sufficient for that games?

**Comment by TyrannicalBlade** [comment]
![steamvr sensors](https://user-images.githubusercontent.com/39897558/41016552-ae6d201a-6915-11e8-8662-571b07724d60.jpg)

This is what i see on steamVR, with vridge they detect as a base station and a head tracker, and with ALVR only see a headset .

On Vridge options says "Tracking source and lets you choose between "Phone sensors only" "Freetrack position and orientation" and " Phone orientation and freetrack position" But then also as another option it lets you choose  "SteamVR safe mode" and "SteamVR fake sensor"

What i am guessing they do, is they enable a positional tracking device that takes Freetrack as input and if you do not use freetrack, it'll just detect it as if you aren't moving... 
![chronos](https://user-images.githubusercontent.com/39897558/41016788-474a2746-6917-11e8-84a9-c3aafccb50d4.jpg)
as for the game (that's spanish, it says "please make sure your headset and your sensor are connected"
Its an oculus store bought from the oculus store, run with revive.

I was able to play it with Vridge, but ALVR is so much better since using ATW. 
I'll try figure out exactly how they emulate the base station, or if i can bypass this since, it might come in handy for other people who play with xbox controller instead of motion controller.

And honestly, amazing work you're doing here, its hands down the best app for gear vr!

**Comment by LebretonGreg** [comment]
Maybe you could try to bypass this trough a command line when you start the game or with the revive injector (https://github.com/LibreVR/Revive), I saw there: https://github.com/LibreVR/Revive/issues/140 that they succedeed.
Good luck!

**Comment by polygraphene** [comment]
Thank you for detailed information!
I managed to implement "fake base station" in new release.
Please try it!

Thank you!

**Comment by TyrannicalBlade** [comment]
Hey, it works great! thanks for the quick update! and sorry it took a bit to reply.
