### ISSUE TITLE
Offloading nvenc to secondary GPU

### ISSUE THREAD

**Issue by SaibotC** [polygraphene/ALVR#311]
I have a system with two Nvidia P6000 GPUs. Is it possible to offload NVENC to a second GPU, and run the regular VR rendering from the main GPU? This could potentially help with performance, but would this make the latency even worse?

edit: sorry, i see this has been asked previously in #300.

**Comment by Colonel-Izzi** [comment]
The hardware encoder is discrete dedicated silicon so even when it's being utilized the GPU proper is free for normal graphics processing tasks.

**Comment by polygraphene** [comment]
That is interesting feature. But as @Colonel-Izzi said, NVENC is not large load for GPU.
I'll consider the feature to utilize multiple GPUs in some way or other.

**Comment by SaibotC** [comment]
@polygraphene I think as others have mentioned, using a RTX gpu with the latest nvenc chip will likely help with the performance a tiny bit. Another thing would be to used a wired USB to Ethernet connection. I have heard it works on the Go, but I have not been able to get any USB Ethernet adapter to work on the Quest. USB drives seem to work fine, but not Ethernet.

**Comment by polygraphene** [comment]
@SaibotC 
I think Quest doesn't support USB-Ether adapter. I couldn't get it work.
