### ISSUE TITLE
Make triggers work for In Death for alpha3

### ISSUE THREAD

**Issue by machenmusik** [polygraphene/ALVR#313]
With 2.4.0-alpha3, In Death is almost playable
- orientation of controllers is not consistent with Oculus Touch expectations (known issue)
- triggers require custom input mapping to function (what this issue is about)

I suspect that the analog trigger value is not being sent correctly 
(perhaps always zero?), 
because the way to make the triggers work is to use custom mappings in SteamVR as follows;
instead of "Use as Trigger", make each trigger button do both 
- "Use as Set Analog Action" with Left/Right Trigger Value (as appropriate) X Value When On 1.0
- "Use as Button" with Left/Right Trigger Press and Touch (as appropriate)

**Comment by machenmusik** [comment]
It appears that I had it backwards, 
https://github.com/polygraphene/ALVRClient/commit/871ba4241e5759b14733d134cf8b6faf94fbdb08

so this fix also works for alpha3... 
make each trigger button do both
- "Use as Trigger" but set Click and Press to none
- "Use as Button" with Left/Right Trigger Press and Touch (as appropriate)

**Comment by machenmusik** [comment]
Reopening, as running the 2.4.0-alpha3 server with a client that has the above patch still needs the mentioned fixes for triggers to work with In Death

**Comment by polygraphene** [comment]
Is the problem still there on alpha4?
Issues on specific game is difficult to debug. We need sample(small) application to reproduce the bug for easier debug.

**Comment by ejwilburn** [comment]
I had this issue in Star Shelter and Alpha 4 fixed it.

**Comment by machenmusik** [comment]
Indeed this appears to be fixed with alpha4, triggers now work without the custom mapping - but the angle of the controller is still wrong.
