### ISSUE TITLE
Trigger Button not working

### ISSUE THREAD

**Issue by Dulcidi** [polygraphene/ALVR#314]
Hello, I try to play VR Vacate the room, and he trigger to enter the game doesn't work.
With Riftcat ( HTC vive controller showing) it works with the trigger... What can I do ?
Thank you

**Comment by leo60228** [comment]
This was fixed in https://github.com/polygraphene/ALVRClient/commit/871ba4241e5759b14733d134cf8b6faf94fbdb08, the next alpha will have it

**Comment by machenmusik** [comment]
maybe or maybe not, see #313

**Comment by ejwilburn** [comment]
This is fixed in Alpha 4 and I've tested it in Star Shelter which uses the trigger to grip and wasn't working previously.
