### ISSUE TITLE
App install issue on quest

### ISSUE THREAD

**Issue by jackfruh** [polygraphene/ALVR#316]
Hi, following these directions:

> **From Oculus Store**
> You can download ALVR Client from Oculus Store with key.
> Open the key distribution page on your smartphone and follow the instruction.

I entered the code on my phone, and it seemed to be stuck downloading forever.

Now it does not show in my library,  but if I re-add the code I get an error on my phone saying I already own that item.

Do I need to have a developer Account on oculus to do this?

**Comment by polygraphene** [comment]
Key distribution is for GearVR and Go.
For Quest, you need to register as developer and install apk.
Follow this guide. https://uploadvr.com/how-to-sideload-apps-oculus-go/

2019年5月27日(月) 9:04 Jack Fruh <notifications@github.com>:
