### ISSUE TITLE
Throwing not working on Oculus Quest

### ISSUE THREAD

**Issue by POEDaley** [polygraphene/ALVR#317]
Most things seem to work great for me on the quest.  The only real show stopper I've found for some games is that throwing isn't working at all.  The object always drops straight down when the grip/trigger is released during the throw.

Fantastic software btw!

**Comment by zxsdklfhskyrvk** [comment]
I'm having a similar issue in Superhot VR (Steam).  I'm unable to even let go of objects.  Using the Quest Alpha 2 version.

**Comment by SCheeseman** [comment]
Possibly due to ALVR not passing through velocity data from the controllers? I remember a similar issue appearing with the SteamVR Razer Hydra driver.

**Comment by sbrierly** [comment]
Same here, trying to play Pipejob.  :)  Did play Brookhaven Experiment for an hour or so and am in awe of how impressive this software is.  Looks better than on my original Vive.

**Comment by polygraphene** [comment]
Same issue? #196
I will check it when I have time.

**Comment by ejwilburn** [comment]
Yeah, looks like the same issue.

**Comment by ejwilburn** [comment]
Just opened a PR that fixes this.

**Comment by babybasher** [comment]
I noticed this too.  Both in Rec Room and Echo arena.  Can't throw anything.

**Comment by POEDaley** [comment]
@babybasher It looks like ejwilburn added a PR for this so it should be fixed in the next update.

**Comment by polygraphene** [comment]
@ejwilburn
alpha5 includes your PR.
Thank you!
https://github.com/polygraphene/ALVR/releases/tag/v2.4.0-alpha5

**Comment by POEDaley** [comment]
Appears to be fixed in Alpha 5.  Thanks!!
Closing this issue.
