### ISSUE TITLE
Confused about video resolution

### ISSUE THREAD

**Issue by vrokolos** [polygraphene/ALVR#32]
Is it resolution per eye or full thing?
I'm on a s9+. Shouldn't I be able to choose the native resolution?

**Comment by polygraphene** [comment]
The resolution means full (for both eyes).

Oculus Mobile SDK recommend using 1024x1024 texture per eye (2048x1024 for both eyes) as mentioned in https://github.com/polygraphene/ALVR/issues/8#issuecomment-394162387 .
This is also applied for latest devices like S9 or Go.
So if you choose 2048x1024, you got the same resolution as other Gear VR games.

I have a plan to add higher resolution, but its effect is limited.

**Comment by vrokolos** [comment]
Nice!
BTW I tested it on S9+ and it works perfectly fine you can mention that on your page.
I love this app! Keep up the good work. Might contribute in the near future if I get some free time on the c# part.

**Comment by polygraphene** [comment]
I have added higher resolutions in new release!
Please check it.

I said that "its effect is limited", but this was wrong.
Higher resolution provides more clear display for me.

**Comment by vrokolos** [comment]
Awesome! Thank you I'll check it out this evening.

**Comment by vrokolos** [comment]
Quick question: My s9+ is 2960x1440. The resolution I choose is 2880x1440 on ALVR. Do you stretch the image or just center it? I'm trying to achieve 1:1 pixel match. Just making sure

**Comment by polygraphene** [comment]
Gear VR does not use full of phone's screen like this picture. And Oculus Mobile SDK suggests us to use 2048x1024 for default resolution.
So I'm using 2:1 resolution to follow this.

![sc](https://user-images.githubusercontent.com/2751376/41791410-a54432f2-7690-11e8-8b89-0e4e4fabd25f.png)

**Comment by vrokolos** [comment]
So you're probably not stretching the pixels and just map 1:1 from the video to the screen pixels

**Comment by polygraphene** [comment]
Yes.
