### ISSUE TITLE
Doesn't find my Quest no matter what I do ...

### ISSUE THREAD

**Issue by LarssonMartin1998** [polygraphene/ALVR#322]
So, I've sideloaded the APK to my Quest, version v2.4.0-alpha3, and I've run it. I've also installed the program on my PC, run it and installed the drivers. Additionally, the PC is ethernet-connected and the Quest is obviously WiFi connected. I've also double checked the ports in my firewall, both UDP and TCP for Private and Public are opened. Yet, it won't find my Quest, how can I troubleshoot this further?

**Comment by polygraphene** [comment]
Did you open 9943(not 9944) udp port for ALVR.exe?
Alpha version also need this port.

**Comment by fjleon1980** [comment]
most routers have separate subnets for wifi and ethernet (after all, in most scenarios you don't want the wifi clients to be able to reach the wired clients for security reasons). your pc needs to be on the same subnet as the quest, meaning that you actually have to connect the pc over wifi as well. i had this exact same problem yesterday

**Comment by LarssonMartin1998** [comment]
@polygraphene Yes, I did that, sorry I forgot to mention it.

**Comment by LarssonMartin1998** [comment]
@fjleon1980 Alright, I'm not too experienced with networking, can I by any means change my router settings so my wifi and ethernet share subnet? Otherwise, I'll have to go shopping for a dongle!

**Comment by polygraphene** [comment]
Does the ping command succeed?
If you can use Wireshark, it will help debugging.
See: https://github.com/polygraphene/ALVR/issues/62#issuecomment-398347915

**Comment by fjleon1980** [comment]
you will have to login to your router's web interface and see if you can change that. in mine (an old netgear) the feature to put wifi on a different subnet is called "wifi isolation" so i had to make sure it was disabled.

MAYBE you can get them to work in different subnets if you add a static route, but that would be somewhat hard for me to explain. try googling your router and see if someone had the same question

**Comment by LarssonMartin1998** [comment]
@fjleon1980 Thanks, will look into it!

**Comment by LarssonMartin1998** [comment]
@polygraphene Yes, ping succeeds!

**Comment by fjleon1980** [comment]
if ping works i don't think you have to do anything networking wise

**Comment by LarssonMartin1998** [comment]
I managed to solve it, it works with a wifi dongle in my PC, but I also tried afterwards with the WiFi Isolation, and now it works with ethernet as well. Thanks for the help :)
