### ISSUE TITLE
Fake base station support not working with ALVR/Revive on Quest (alpha 5)

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [polygraphene/ALVR#324]
I've managed to use ALVR to play a few games with revive, as well as steamvr games.

**CLOSE**:  This was fixed by Revive making a fix for older games (https://github.com/LibreVR/Revive/issues/1222) 

**UPDATE**: This is now an issue about "fake base station" support,  which doesn't seem to be working fully. See https://github.com/polygraphene/ALVR/issues/324#issuecomment-497959969_
-------------------------------------------------
I'm trying to open The Climb with Revive (for the first time), but it is failing to launch with a desktop popup error.

"Hardware issue: Flags: 30c3-HMD(On) Trackers(0)
You have a pending hardware issue that is preventing you from entering VR.   Please check that your headset and sensor are connected."

Obviously revive is working fine with other games.

Anyone else able to launch this specific game successfully with current software versions (not a previous config or versions of the software)?

**Config:**
Steam & SteamVR - latest (all updates installed)
Revive - latest (1.6.4)
ALVR - latest Oculus Quest alpha 3 and 4 tested (Windows client, Driver and apk)

Let me know if you think this is a ALVR issue or resides elsewhere.  I can grab logs given some direction.

**Comment by zxsdklfhskyrvk** [comment]
Someone pointed out to try using the fake base station option.  This allowed me to launch the game,  but it quickly halts at a screen displaying all of the VR components.  All the components are green except for the base station. 

**Any ideas how to trick that?**

**Comment by zxsdklfhskyrvk** [comment]
I've tried testing an older version of revive 1.3.0 specifically and it also doesn't work.  As I have no experience playing The Climb, with this 1.3.0 version I noticed that the VR component status icons appear on the "skin tone" selection window, and again show the sensor red.

**Comment by polygraphene** [comment]
Is The Climb working correctly with Vive+Revive?

**Comment by zxsdklfhskyrvk** [comment]
I'm using a Quest via Revive and it functions,  but with stutter.  Sorry I didn't update here.  There was a fix from Revive that made it work.

**Comment by xchdave** [comment]
the fix for this is adding a second fake sensor! I have the same issue and from the research I've done it looks like it requires two oculus sensors to play, now with revive it changes base stations to oculus sensors but alvr only adds one not two, I believe adding a second fake sensor should resolve this issue
