### ISSUE TITLE
Will ALVR benefit from lower latency with an RTX GPU?

### ISSUE THREAD

**Issue by kellabyte** [polygraphene/ALVR#325]
Since the main contributor to latency with ALVR and wireless VR to the Oculus Quest is the cost of video encoding, would the experience feel much better using an RTX GPU?

I believe the RTX GPU has a faster and more clear x264 encoder as seen here.
[https://www.nvidia.com/en-us/geforce/news/geforce-rtx-streaming/](https://www.nvidia.com/en-us/geforce/news/geforce-rtx-streaming/)

Does ALVR use the built in nvidia encoder already? Has anyone tested this to see if total latency goes down?

**Comment by machenmusik** [comment]
My understanding is that ALVR is using NVENC, but in HEVC (H265) mode by default.

**Comment by polygraphene** [comment]
Yes. ALVR always uses NVENC for Nvidia GPU.
Maybe ALVR already utilize new generation(?) NVENC on RTX. (I haven't test yet)
