### ISSUE TITLE
Oculus Quest controllers have no hardware menu button mapped.

### ISSUE THREAD

**Issue by ejwilburn** [polygraphene/ALVR#326]
The menu button on the left controller is mapped to the SteamVR system button and the right button remains the Oculus button, I haven't found any other button that works as an in-game menu button and I don't see any way to configure that on the controller options screen in ALVR.

This is on 2.4 alpha 4

**Comment by machenmusik** [comment]
I think this may depend on the game; when playing In Death, the application menu seems to be mapped to B or Y buttons

**Comment by ejwilburn** [comment]
I've tried both Star Shelter and VR Dungeon Knight and both games have no button bound to in-game menu.

**Comment by polygraphene** [comment]
I know this is a problem.
Please wait for FreePIE support. If we got FreePIE support, we can remap input in various way.

**Comment by khaniqshahid** [comment]
Has this been done?
