### ISSUE TITLE
Can't pass Steam VR Room Setup

### ISSUE THREAD

**Issue by ekode** [polygraphene/ALVR#328]
I reported this issue last year when I was trying to make ALVR work with Oculus Go. It seems I have the same issue with Quest.

Server app successfully connects to Quest and launches SteamVR Room Setup. After I pick Standing option, I am not able to proceed further as Steam is not able to detect my headset. "Next" button is grayed out.

Some  facts:
- I have NVidia GTX 970 GPU 
- Moonlight works very good. Couldn't perceive any latency.
- PC is connected to router by cable.
- Quest is connected to 5GHZ wifi spot.
- I had some issues with my networks settings, fixed that and now I am able to successfully ping Quest on local network.
- In Windows 10 Firewall settings, for Inbound Rules, all ports are allowed for ALVR (UDP and TCP) in public and private networks. There is nothing for ALVR in outbound rules.
- Tried turning off firewall on my PC and on wi-fi router. Didn't help. 
- Server app is able to see Quest and IP address is correct. After I "Connect" and "Start Server" buttons I can see all the stats about connection. Numbers are not changing. It is showing 1 packet for Total Packets and 5% for FecPercentage. All other values are zeroes.
- On debug screen, Client value is constantly alternating between 0.0.0.0 and Quest's IP address.
- It looks like ALVR client app is crashing often in Quest when I try to close it.
- And the last thing, I have no issues with other streaming apps (BigScreen, VirtualDesktop)

**Comment by SSSTREDDD** [comment]
I have the exact same issue. Server connects, but client shows no sign of a connection.

steamvr sees the headset but flashes green and cannot proceed past room setuip.

**Comment by SSSTREDDD** [comment]
I was able to fix this by disabling my windows firewall completely. There must be something strange going on as all udp and tcp ports are enabled on the firewall for alvr.

**Comment by polygraphene** [comment]
I think you should open 9944/udp port on firewall.
> In Windows 10 Firewall settings, for Inbound Rules, all ports are allowed for ALVR (UDP and TCP) in public and private networks. There is nothing for ALVR in outbound rules.
This is needed, but not sufficient.
ALVR.exe (Launcher) uses 9943/udp.
vrserver.exe (ALVR server) uses 9944/udp.
You should allow both ALVR.exe and vrserver.exe.
Or allow both 9943,9944/udp.

**Comment by SSSTREDDD** [comment]
@polygraphene thank you for the additional info. I allowed all ports and protocols (in and out) for **vrserver.exe** on my private network. This allowed me to turn my firewall back on and connect properly. So for anyone experiencing this issue make sure to do this _(or at least 9943/udp & 9944/udp)_ for both vrserver.exe's:

C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64\vrserver.exe
C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win32\vrserver.exe

**Comment by ekode** [comment]
Unfortunately it doesn't work. I did allow all ports polygraphene mentioned and on the end turned off firewall completely. Something else is issue here.

**Comment by LarssonMartin1998** [comment]
I'm having the exact same issue, I've established the connection between my PC and Quest, and started the server. However, as you said, SteamVR launches and asks me to set up a room, which I cannot do because it's not recognizing my headset (in SteamVR room setup). I've also tried faking a base-station just to try and trick the room setup, but it's just not working. I've also allowed all ports, even tried disabling windows firewall, still nothing. Some people said they didn't have to set up their SteamVR room, it just automatically jumped into Steam home when they started the server. Did anyone get any updates on this? Thanks.

**Comment by POTATOChrisscar** [comment]
I'm also having the same issue. Nothing has worked at all. I've tried everything people have listed here, even in other threads.

**Comment by polygraphene** [comment]
Try to [use Wireshark](https://github.com/polygraphene/ALVR/wiki/Troubleshooting#1-you-need-to-debug-network-issue) to deconstruct the issue.
I want to clarify you properly get packet from client.

**Comment by POTATOChrisscar** [comment]
> Try to [use Wireshark](https://github.com/polygraphene/ALVR/wiki/Troubleshooting#1-you-need-to-debug-network-issue) to deconstruct the issue.
> I want to clarify you properly get packet from client.

This is what I got 
![image](https://user-images.githubusercontent.com/34051027/58999663-a9dd5680-87bb-11e9-884a-4d4e134a67ec.png)

**Comment by POTATOChrisscar** [comment]
Nevermind, I fixed it by having a bigger guardian???

**Comment by LarssonMartin1998** [comment]
@polygraphene I'll try to get time to profile it with Wireshark later today!

**Comment by LarssonMartin1998** [comment]
@POTATOChrisscar How did you manage to change guardianspace without getting through steam room setup to begin with? :O
