### ISSUE TITLE
ALVR alpha4 error on server startup

### ISSUE THREAD

**Issue by machenmusik** [polygraphene/ALVR#329]
```
Unhandled Exception.
ExceptionCode=C0000005
Address=00007FFC5574A5E3 (00007FFC55730000 + 000000000001A5E3)
```

Sometimes this is harmless and everything works anyway.
Other times SteamVR fails with error 301.

(This is with 2.4.0-alpha4, but was also happening with prior alphas.)

**Comment by polygraphene** [comment]
I want to see more details on the issue.
ALVR produces crash log file in `C:\Program Files\ALVR\logs`.
Please upload this file.

**Comment by Darkended** [comment]
Hey i'm having the same issue. Here's some info that might be useful

- GPU's an RTX 2080 Founders Edition
- Like machen said above, SteamVR launches but gives the 301 error
- Nvidia driver's 430.86 and I've also tried the previous version
- If it matters, I'm using an Asus z390 motherboard with an i9-9900k
- I've tried using alpha 4 and 2 with no luck, even going as far as mismatching the client and server

I'm not sure if this is a hardware issue or what as i've been looking for a solution for a while to this with no luck. Log is also attached.
[ALVR_CrashLog_20190528_071940.log](https://github.com/polygraphene/ALVR/files/3227619/ALVR_CrashLog_20190528_071940.log)

**Comment by WesleyvHaren** [comment]
have the same issue with AMD Radeon HD 7850 on Windows 10 (this videocard is so old I don't expect any support, but I seem to have the same issue) 

[ALVR_CrashLog_20190528_211748.log](https://github.com/polygraphene/ALVR/files/3229340/ALVR_CrashLog_20190528_211748.log)

**Comment by zxsdklfhskyrvk** [comment]
I have multiple crashes on  2.4.0-alpha4.   Seemingly at startup.

RTX2080
Latest Nvidia driver
Steam/SteamVR - latest
Oculus Quest

[ALVR_CrashLog_20190527_185444.log](https://github.com/polygraphene/ALVR/files/3229899/ALVR_CrashLog_20190527_185444.log)

[ALVR_CrashLog_20190527_143145.log](https://github.com/polygraphene/ALVR/files/3229900/ALVR_CrashLog_20190527_143145.log)

**Comment by polygraphene** [comment]
Thank you for information!
Maybe I've found the problem on code.
It will be fixed on next release.

**Comment by Darkended** [comment]
No thank you for all the work you've put into this.

**Comment by rossarmer** [comment]
> Thank you for information!
> Maybe I've found the problem on code.
> It will be fixed on next release.

I thank you as well but just FYI, this broke all previous versions I had downloaded, including portable, as well for some reason.  All drivers removed and even deleted the ALVR appdata folder.

Thanks again though

**Comment by machenmusik** [comment]
Have not seen anymore with alpha5.  Anyone else?  If no one, will close later today.
