### ISSUE TITLE
Will we get an AMD compatible version in the future?

### ISSUE THREAD

**Issue by CaptainMalk** [polygraphene/ALVR#33]
I really dont wanna be stuck with Vridge, so if AMD support is added I might buy a 5ghz router. Else, i'll just save for a cv1.

**Comment by polygraphene** [comment]
I have a plan to support AMD, but the schedule is not fixed yet.
Please be patient.

**Comment by CaptainMalk** [comment]
That's great news!
I'm still hyped for hl3, so patience is my middle name.
Thanks for your response and keep up the good work :D

**Comment by polygraphene** [comment]
I created the page about this issue on the Bountysource which is a crowdfunding service for open source projects.
https://www.bountysource.com/issues/59270271-will-we-get-an-amd-compatible-version-in-the-future

If the amount reaches $300, I will buy RX580 GPU and start working on AMD support.
If someone send us a pull request solves this issue, the bounty will be sent to him or her.

**Comment by thoughtfix** [comment]
Subscribing and added $20 to the bounty. I have access to a Hades Canyon NUC (RX Vega M GH) and wouldn't mind trying to test it. That Vega is about 3/4 of the way from a 1050 Ti to a 1060.

**Comment by adromir** [comment]
I am not entirely sure if, but maybe this project can be useful with Developing for AMD Based Graphic Cards: https://github.com/rigaya/VCEEnc

**Comment by adromir** [comment]
I know you slowed down your programming on this.. In the Next few days ill get a new graphik card, so ill have a spare AMD RX 480, which id be willing to donate. Just give me a private Message if interested

**Comment by TonyShenxd** [comment]
Added $265 in the name of NOLO team. ALVR is a great product. Hope you can make it better and better.

**Comment by polygraphene** [comment]
@adromir Thank you for nice offer. But that will cost shipping fee and take your time. In addition, the crowdfunding is achieved now. I will buy GPU myself. Thank you.

@TonyShenxd Thank you for big contribution! It will greatly help the users waiting for Radeon support.

I will buy RX580 GPU and start working on Radeon support. Thank you!

**Comment by ThatCheze** [comment]
This would be really awesome
an alpha version that barely works would do

**Comment by ThatCheze** [comment]
how long until you respond

**Comment by polygraphene** [comment]
I am sorry to have kept you waiting.
I'm working on Nolo support and I will start to work on AMD support after that.
Nolo support will be done in a few days.
Please be patient.

**Comment by shadoxx** [comment]
@polygraphene If you need any support for beta testing for this feature when you do start working on it, I have an RX580 and an Oculus Go and a nice amount of free time to dedicate to this.
When you do start working on it. No rush from me. Just lending my support as I can!

**Comment by polygraphene** [comment]
@shadoxx I uploaded experimental version now. Please try it.
https://github.com/polygraphene/ALVR/releases/tag/v2.3.1

**Comment by shadoxx** [comment]
> @shadoxx I uploaded experimental version now. Please try it.
Initial testing is great! I've been playing around in VRChat for about half an hour and it's just as smooth as a wired headset on the same PC. I'm using a 5GHz router for reference, streaming at 50mbps.

Is there anything specifically you'd like me to try out? Thanks again! This completely changes the way I interact with VR.

**Comment by polygraphene** [comment]
@shadoxx Great! I want to know whether both H.264/H.265 work.

**Comment by mycowx** [comment]
@polygraphene I tested this build with my Gear VR and S6 streaming via 5GHz (my GPU is an RX 470).  Everything worked perfectly.  Tested and confirmed both H.264 and H.265 are working at 35mbps playing Project Cars 2.  I am blown away!  Excellent work!

BTW, does the IPD setting (driverConfig.IPD = 0.064) in ServerConfig.cs modify the software IPD display?  Would love to adjust for my larger IPD in software despite the fixed hardware IPD of the GearVR.

**Comment by apan65** [comment]
> 
> 
> @polygraphene I tested this build with my Gear VR and S6 streaming via 5GHz (my GPU is an RX 470). Everything worked perfectly. Tested and confirmed both H.264 and H.265 are working at 35mbps playing Project Cars 2. I am blown away! Excellent work!
> 
> BTW, does the IPD setting (driverConfig.IPD = 0.064) in ServerConfig.cs modify the software IPD display? Would love to adjust for my larger IPD in software despite the fixed hardware IPD of the GearVR.

Awesome i have almost the same rig, rx480 and s6, need to test it.

**Comment by polygraphene** [comment]
@mycowx Thank you for testing. I'm glad it work fine!

IPD setting is only passed in SteamVR. I don't know how SteamVR use that setting, but it will not work properly now.
I'm wonder if we can implement IPD config properly for GearVR. Riftcat has the IPD setting, but is it properly implemented?

**Comment by CaptainMalk** [comment]
I got a 5gh router and the streaming quality is amazing on my Radeon RX 489.
I had some problems with the H.265 compression at first, but after updating my drivers it all went smooth with no crashes or drops in streaming quality.
I'm using oculus go, and I'm streaming at 2880x1440p.
I tryed out Zone of the enders, vr chat and lucky's tale.
The menus on ZoE where troublesome for some reason, but the game itself runs perfect.
You are amazing man, thx for all the effort and dedication :D

**Comment by ThatCheze** [comment]
Hey, I am trying to use it and it gives me the error 'Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc NvEncoderD3D11 failed. Code=1 NvEncoder::LoadNvEncApi : NVENC library file is not found. Please ensure NV driver is installed at c:\src\alvr\alvr_server\nvencoder.cpp:70'
Can you please help

**Comment by shadoxx** [comment]
Hi @ThatCheze,
What video card do you have and what driver versions do you have installed?

**Comment by rene1977** [comment]
Your AMD patch works very well here on my PC.
Its an 3570K with AMD RX480 and 8 GB RAM. Played several days now Elite Dangerous and had no issues with H.265at 50Mbp 5Ghz. Did donate you 10€ to say thank you for bringing VR into my life. :-)

**Comment by jake6597** [comment]
Hi @polygraphene , I find that I am getting an error very similar to that of ThatCheze, shown below:
_Exception: Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 10. g_AMFFactory.GetFactory()->CreateComponent(amfContext, pCodec, &m_amfEncoder), NVENC: NvEnc NvEncoderD3D11 failed. Code=1 NvEncoder::LoadNvEncApi : NVENC library file is not found. Please ensure NV driver is installed at c:\src\alvr\alvr_server\nvencoder.cpp:70_
I have attempted with the two most recent AMD drivers for my HD 8770M GPU, 18.9.3 and 18.11.2. My laptop has switchable graphics; the other card is an Intel HD Graphics 4000. Interestingly, after a few tries, my laptop has started blue-screening either with Kernel Security Check Failure or Driver Corrupted Expool, which I understand can both regard corruption in the drivers. The latter actually occurred with VRidge/RiftCat, so this might exclusively be a problem on my end. I really appreciate your hard work in making VR streaming more practical!

**Comment by gwdp** [comment]
Hi all! 
I'm getting exactly the same error as @jake6597 . 
I have a weird setup, my Intel NUC has an integrated Intel Iris 650 and an external GPU case with my AMD RX580. Reading carefully @jake6597 post, we can definitely match the integrated graphic's unit as the most probable reason for the issue.
I can guess that Intel GPU is not supported and the encoder is always trying to run on adapter at idx 0, which is the integrated adapter. 

Probably if you change this line https://github.com/polygraphene/ALVR/blob/6cd404898a7ca280404a7596663bf5e5ac2c0e60/ALVR/ServerConfig.cs#L126 and recompile, things will work :)

Should create an issue for that? Multiple GPUs are unhandled and the program should allow us to choose at runtime before server execution?

**Comment by gwdp** [comment]
@polygraphene , I can see the same issue here https://github.com/polygraphene/ALVR/issues/199
Waiting for confirmation of dual GPU setup there..

**Comment by MadMonk48** [comment]
Here's my situation:  I run the ALVR server, then the ALVR client on my Oculus Go.  Connection is good, but nothing happens.  So I turn down the resolution, streaming begins, and I get a blue screen.  I start a game -- "Alien Isolation" -- on SteamVR, see the game's splash screen, and then -- nothing.  One other oddity, when I look off to my left on the Go, I see a house-shaped black structure.  Anyone have any idea what that is?

**Comment by chibisuke1219** [comment]
how do I enable the experimental amd video

**Comment by MollyWat3r** [comment]
I used a RX580 and im having an issue where the grey server is down button shows after I start server. SteamVR loads up but doesn't detect a headset. please help
