### ISSUE TITLE
Using alpha4, SteamVR games such as In Death and Moss do not seem to recognize controllers as Oculus Touch.

### ISSUE THREAD

**Issue by machenmusik** [polygraphene/ALVR#330]
For example:
- Moss still prompts you to click on the right side of the touchpad to continue past seated notice, which is not possible with the controller mappings in alpha4.
- In Death uses the trackpad click to select teleport arrow just like Vive, even though Oculus version maps teleport to the (right?) Touch grip button.  Also, the controller angle is off.

**Comment by machenmusik** [comment]
(I wonder if those games are checking the HMD information to detect Oculus Rift, and not the controller information to detect Oculus Touch)

**Comment by machenmusik** [comment]
Will check later tonight with alpha5

**Comment by machenmusik** [comment]
with alpha5, I still get stuck with Moss in the same place, for example;
there is no Touch controller input I have found that can dismiss that message

![com polygraphene alvr-20190606-013100](https://user-images.githubusercontent.com/2080738/59009409-73273080-87fb-11e9-826e-47431e8c65c7.jpg)

**Comment by jackfruh** [comment]
I can confirm it doesn't work either - my copy of moss is already past the above dialog, but when I bring up the menu it does show the left/right trackpad for forward/back - I hadn't even thought of it as detecting vive controllers but maybe that's what's happening since the Oculus touch controllers don't have trackpads.

**Comment by machenmusik** [comment]
OK so I was able to fix using SteamVR only:
- in Steam list, right click entry for Moss and choose Properties
- for Steam Input Per-Game Setting, change to Forced On
- in SteamVR while VR is running, pick Devices / Configure Controller from the SteamVR window's app menu
- set up the Moss mapping as described at https://steamcommunity.com/sharedfiles/filedetails/?id=1545634111#2763677 (see section 3 on Moss specifically)

So may be OK to close, unless/until ALVR gets native Oculus support working rather than SteamVR.
