### ISSUE TITLE
Quest alpha and AMD VCE/AMF

### ISSUE THREAD

**Issue by kaisparkle** [polygraphene/ALVR#331]
Hey, just curious if the Quest alpha has AMD VCE/AMF support in any way? When attempting to stream, my encoding latency is around 90ms with HEVC.

**Comment by kaisparkle** [comment]
Just checked, it's about 400ms with AVC, and my transport latency is only around 4ms with no dropped packets.

**Comment by kaisparkle** [comment]
Seems to be fine (i.e ~50ms -total latency-, 11ms encode) up to 75% resolution. Once it's turned up to 100%, it turns into a lagfest.

**Comment by polygraphene** [comment]
I think alpha version supports VCE.
If VCE did not work properly, SteamVR just fails at startup.

Perhaps it is not Quest specific issue. What's GPU are you using?
If you change bitrate, do you see different result?

It could be possible that VCE on your GPU doesn't support above 2k resolution of hardware encoding.

**Comment by polygraphene** [comment]
https://github.com/obsproject/obs-amd-encoder/wiki/hardware-support#video-coding-engine-20
VCE 2.0 seems to support at most 1920x1920 resolution.

**Comment by kaisparkle** [comment]
I'm using an RX 570, so VCE 3.4. Bitrate doesn't seem to change much (at least, between 1 and 30Mbps). Even 100% res @ 1Mbit has the same latency.

**Comment by Thomas-6freedom** [comment]
Hello.
my graphic card is a T9 290X which supports only VCE2.0. Will it work ?

https://en.wikipedia.org/wiki/Video_Coding_Engine

Thank you
