### ISSUE TITLE
Some words don't display  in steam vr home with Rx580 display card and

### ISSUE THREAD

**Issue by Woohaaa** [polygraphene/ALVR#332]
![QQ图片20190528170733](https://user-images.githubusercontent.com/40816223/58466014-74a58880-816b-11e9-8c4d-4ea846f101de.png)

WIN10 64bit, I tried diffirent ver display drivers and didn't solve it.

**Comment by polygraphene** [comment]
Please try:
1. Open C:\Windows\Fonts in Explorer.
2. Click "Download fonts for all languages" in left panel.
3. Restart SteamVR.

**Comment by Woohaaa** [comment]
Master is a master, the problem is solved! Love you!
