### ISSUE TITLE
Latency calculations are missing info / incorrect?

### ISSUE THREAD

**Issue by jd-3d** [polygraphene/ALVR#334]
I've been investigating ALVR w/ my Oculus Quest and trying to reduce latency. However, one issue I've found is the total latency reported isn't the same as adding up the individual latencies. Some typical numbers for me are: Encode latency is around 8.3ms, Transport Latency is 5.7ms, and decode latency is 18.9ms for a total of 32.9ms. However, the total latency is 66.5ms, meaning there's a missing 33.6ms. Does anyone know where that is coming from? Does the transport latency include all Wifi latency, or is that where the missing lag is coming from?

If I switch to a really low 25% resolution, then the encode/transport/decode latencies only add up to about 12ms, yet the total latency is around triple that at 33ms. It would be very useful to understand if there is simply missing latency not accounted for or if this is a bug.

**Comment by GregGodin** [comment]
Here is my take on the different latency measure, @polygraphene should be able to confirm/complete.

Latency is computed in client (AlvrClient).

**TotalLatency** 
Each time tracking information are sent (ovrContext.fetchTrackingInfo), there is a FrameIndex which is incremented. This will be the key for all latency computation, and ovrContext.fetchTrackingInfo will also mark the beginning of the TotalLatency.
So TotalLatency = Submit - Tracking, where submit is after vrapi_SubmitFrame (i.e. after rendering)

**EncodeLatency**
? (I didn't dig a lot in the alvr server side).

**TransportLatency**
TransportLatency = ReceivedLast - EstimatedSent
We can't timestamp server side just before sending packets and use this timeStamp client side to determine how much time we spent in the network. The clock isn't synchronized enough between client and server (i think NTP exists and is used on Android, but we can have several ms of difference between pc clock and android).
So transport latency has to be adjusted. This is done I think with a (pingpong time)/2 with the ALVR_PACKET_TYPE_TIME_SYNC packets.
EstimatedSent is the send estimation of the first packet of the frame. 
ReceivedLast is after we have been able to reconstruct frame (so after we received the last udp packet for a NAL).

**DecodeLatency**
DecodeLatency = DecoderOutput - DecoderInput
DecoderInput is when NAL is pushed to MediaCodec, and DecoderOutput is when MediaCoder has finished :)

**Summary**
So what is the difference between the TotalLatency and the sum(DecodeLatency, EncodeLatency, TransportLatency) :
   * Server-side: Capture latency
   * Server-side: FEC encoding ?
   * Client-side: copy of NAL from c++ to java
   * Client-side: Part of rendering latency
   * ?

Is remaining latency mostly in client side or in server side ? No clue right now.

**Comment by polygraphene** [comment]
I'm sorry I didn't reply.
@GregGodin Thank you for good explanation! That is totally correct.
Encoding means video encoding by NvEnc or AMD VCE. It is measured on server.

Following steps are taken.

1. Client: fetchTrackingInfo
2. Client: Send it to server
3. Server: Send it to SteamVR
4. Server: Get rendered image from game
5. Server: Encoding it --- start EncodeLatency
6. Server: Encode end --- end EncodeLatency
7. Server: Send encoded packets --- start TransportLatency
8. Client: Receive all packets --- end TransportLatency
9. Client: Decode start --- start DecodeLatency
10. Client: Decode end --- end DecodeLatency
11. Client: Buffering
12. Client: Submit(Wait VSync)

Missing latency is from 1-5 and 11-12.
TotalLatency is since get your head position until image is rendered.
It still has missing latency, but you can assume TotalLatency is nearly close to your perceptual latency.

**Comment by polygraphene** [comment]
FEC encoding time was negligible, so I ignored it.

My estimation about missing latencies:
1-5: 10~20ms?
11-12: 0~24ms (at most 2frame)

**Comment by jd-3d** [comment]
Thank you @GregGodin and @polygraphene. It is interesting that the latencies of steps 1-5 and 11-12 can exceed the latencies of 5-10. I'm completely estimating here, but let's take my scenario on my RTX2070:

We know: 
Encode latency = 8.3ms
Transport Latency is 5.7ms, 
Decode latency is 18.9ms 
Total latency is 66.5ms

Estimates:
Client: fetchTrackingInfo  ~1-2ms
Client: Send it to server - 1/2 the transport latency (~3ms)
Server: Send it to SteamVR - <1ms
Server: Get rendered image from game - possibly significant based on frame timing, i.e., up to 14ms?
Server: Encoding it --- start EncodeLatency
Server: Encode end --- end EncodeLatency - 8.3ms
Server: Send encoded packets --- start TransportLatency
Client: Receive all packets --- end TransportLatency - 5.7ms
Client: Decode start --- start DecodeLatency
Client: Decode end --- end DecodeLatency - 18.9ms
Client: Buffering
Client: Submit(Wait VSync) - 14-28ms
Total adds up to: 50 - 81ms (lower and upper bounds)

Based on these numbers I see the refresh rate of the headset significantly increases perceived latency over wifi. On something like a Valve index @144hz you could potentially cut 10-20ms off total latency just due to the faster refresh (assuming your graphics card could pump out the FPS and you don't saturate the bandwidth).

**Comment by GregGodin** [comment]
Thanks for the details.

There is one thing that bug me off with the total latency. 
Tracking is on its own thread/timer, ticking every frame (1/75s), and I think that's receiving tracking is not a trigger on the server for the rendering which has its own timer and will use the last knwon tracking.
So am i right to say that in the worst case, we can end-up using tracking informations that are one frame late.

Wouldn't it make more sense to update tracking very frequently (every ms for instance) ?

**Comment by polygraphene** [comment]
@GregGodin In Quest alpha5, I used 200Hz for tracking frequency.
https://github.com/polygraphene/ALVRClient/blob/v2.4.0-alpha5/app/src/main/java/com/polygraphene/alvr/TrackingThread.java#L11

And I will change it to display refresh rate * 3 in next release.
For example, When on 72Hz, use 72*3=216Hz (every 4~5ms).
