### ISSUE TITLE
HEVC + 125% resolution causes distortions in Oculus Quest

### ISSUE THREAD

**Issue by jd-3d** [polygraphene/ALVR#335]
Something about using H.265 HEVC + 125% resolution causes distortions in Oculus Quest. Almost like vertical tears in the picture. Using 100% or 150% does not have the issue and AVC is also fine at any resolution. Any chance we could get more granularity on the resolution options?

**Comment by Osudoni** [comment]
I think I noticed this as well

**Comment by Niceman35** [comment]
Yes, 125% don't work correctly with H.265.  Also, why ALVR reports some strange Quest resolution?

**Comment by abpages** [comment]
Yes. 125% does it for me too. Horizontal tears for me. 100% and 150% is fine.
