### ISSUE TITLE
Windows 10 5ghz mobile hotspot issues

### ISSUE THREAD

**Issue by brentjohnston** [polygraphene/ALVR#336]
I was wanting to turn on the "Mobile Hotspot" feature in windows 10, which will turn the 5ghz wireless adapter into the PC into an access point.

I have the desktop plugged into the router. The issue is ALVR won't see the headset when I connect it to the QuestWifi hotspot I created. The hotspot  has a gateway at 192.168.137.1, while my router is at 192.168.29.1. I tried to change the router to match the same .137 number and tried both .2 and .1 at the end but ALVR still doesn't see the headset. Is there a way to manually type the IP in ALVR or does anyone have any ideas for how to fix that?

May router is very far away and has a network cable running to it, this would be an awesome solution if I could get ALVR on the quest to see the server software on the desktop.

**Comment by machenmusik** [comment]
I have heard others say
- disabling Windows firewall (or, presumably, otherwise making the firewall pass through ALVR traffic) fixes this 
- standalone router performance is generally better than PC as mobile hotspot

**Comment by brentjohnston** [comment]
disabled firewall and it worked! I am actually able to set the resolution to 150% now and it feels more clear than the native home environment and running really well. Definitely recommend people try this if their 5ghz router isn't working well for whatever reason.

**Comment by Osudoni** [comment]
> disabled firewall and it worked! I am actually able to set the resolution to 150% now and SteamVR home feels as clear as the native quest home environment and running really well. Definitely recommend people try this if their 5ghz router isn't working well for whatever reason.

Can you tell me what your mpbs is? When I tried mobile hotspot, it didn't work as well for me, I got only 173 mpbs, and it was blurry at times.
