### ISSUE TITLE
No audio coming from the headset

### ISSUE THREAD

**Issue by GandalfTheGreen101** [polygraphene/ALVR#337]
When I load up a game in ALVR (which works great with my connection etc.) the game works great but there’s no sound :(

**Comment by slydog43** [comment]
Did you check the option to stream sound, I think its off by default.

**Comment by user23498723452** [comment]
Also,  I've found that at least Steam games do not play (PC sourced) sound unless the game window has focus.

**Comment by GandalfTheGreen101** [comment]
Whenever I have the steam sound box checked the app crashes when I start the server, I have been playing with it off. Is there any fix for this?
