### ISSUE TITLE
Green screen in Oculus Quest, but there is sound

### ISSUE THREAD

**Issue by Thaurin** [polygraphene/ALVR#338]
I'm trying to get my Quest to work with alpha4, but I'm having no luck. I used to use ALVR with my Go, so maybe there's some old mess that's causing trouble?

The strange thing is, I am able to start the SteamVR server, and the ALVR app reports that the Quest is connected. On my Quest, all I see is green everywhere. However, pushing the B and Y buttons and playing around a bit does produce sounds and I hear the birds chirping.

I could not find anyone else reporting a green screen. Is this a new bug with Quest? Is there anything I can do to troubleshoot this for you?

**Comment by Thaurin** [comment]
I should add that I had some trouble with SteamVR crashing earlier. I reinstalled it, removed some files, and it seems to be fine now, as far as SteamVR goes. When I get some more information, I'll post it below.

**Comment by ejwilburn** [comment]
Try closing out steam completely and making sure no Steam executables are running in Task Manager under details.  Then uninstall and re-install the ALVR driver via the batch files in \Program Files\ALVR\driver.  Also, in Steam go to SteamVR properties and then the Betas tab and switch to the beta branch.  Verify local files for SteamVR and reboot.

**Comment by Thaurin** [comment]
I solved this issue. It was my own mistake. I was controlling my PC from my laptop through a remote desktop connection. ALVR (and other streaming software) needs an active, logged in session for it to work. After physically logging into my PC, everything worked.

I finally got to try Google Earth and the experience was pretty flawless, excusing a few stutters and compression artifacts. Amazing!

**Comment by Mikental** [comment]
Thanks for the solution. You can use tightVNC to use remotly.
