### ISSUE TITLE
Picture turns all black when starting the Server (Quest)

### ISSUE THREAD

**Issue by dschoetz** [polygraphene/ALVR#339]
Hi,

As soon as I start the server my screen on the oculus seems to freeze (I can still move but i only have the "Connect to the Server" picture in the front of me and otherwise only black instead of the other 3 "Connect to the Server" messages).

SteamVR is working fine (it tracks the movement without a problem or latency) besides that not a single button seems to work.

I already tried to configure the Steam Roomscale but it won't work because i can't press the trigger button.

Somebody got a idea?
I get no crash message at all.

I connected my Quest via 5ghz Wifi and i opened the requested ports within my firewall (I deactivated it - no change)

**Comment by BlaxHazHax** [comment]
i have the same issue plz help PolyGraphene!!!!!!!!!!!!!

**Comment by ejwilburn** [comment]
Might try the steps I posted here, I had issues initially and these steps fixed it for me: https://github.com/polygraphene/ALVR/issues/338#issuecomment-496766455

**Comment by dschoetz** [comment]
I already reinstalled the driver with the bat file.
I don't seem to get as far for even the buttons to work.

I have an AMD r390 gpu. Could this cause the problems? Even the button one?

**Comment by midorikuma** [comment]
Some here with gtx960.
When connected Quest, driver.log says "sendto error: 10035".
I tried to reinstall, but it could not be resolved.
(streaming with Riftcat/Vridge was successful)

**Comment by dschoetz** [comment]
I found the problem.

it seems that ALVR has problems displaying resolutions higher than 1080p on some AMD cards.
I have a 2K Monitor. If I set the resolution to 75% in the Server settings it works.
