### ISSUE TITLE
Oculus Update Required

### ISSUE THREAD

**Issue by TheJaeger** [polygraphene/ALVR#34]
Getting this weird "Oculus update required" message when starting the app on Gear VR 2017 with Galaxsy S8+. I injected my OSIG file and reinstalled the app two or three times still no luck.

I checked the Oculus app for updates and it's fully updated. Not sure whether something wrong with my installation or the app itself, though I believe it's the former.

**Comment by polygraphene** [comment]
Hmm...
I didn't hear that issue...
Please try those links.
https://forums.oculusvr.com/community/discussion/54495/a-new-update-is-required
>Usually uninstalling all the Oculus/GearVR services apps will allow you to update. See here:
https://support.oculus.com/help/oculus/1772668642989617

https://support.oculus.com/1421297807899373/

**Comment by TheJaeger** [comment]
Fixed it. Had to uninstall and reinstall all Oculus apps like the ones you linked to.
