### ISSUE TITLE
Gear VR controller remapping for Steam VR

### ISSUE THREAD

**Issue by BalazsAdorjan** [polygraphene/ALVR#347]
I would like to remapp a Gear VR controller key to function as a "Menu" button, beacuse I can't get through "The Lab" 's tutorial without one. I tried steam's controller remapping feature, but I couldn't get it to work.

**Comment by polygraphene** [comment]
Did you try Controller tab to remap button?
Assigning "ApplicationMenu" on Trigger(or whatever you like) would help you.

**Comment by BalazsAdorjan** [comment]
It did work, but every button is pretty important on these small controllers, it would be the best if we could remap buttons for pressing different parts of the touch pad like in this VRidge video: https://www.youtube.com/watch?v=Kq629e_Gnew
Do you think it's possible?

**Comment by polygraphene** [comment]
Use FreePIE. https://github.com/polygraphene/ALVR/wiki/FreePIE-Integration
freepie-samples\sample3.py has a functionality you wish.
Current alpha version has broken FreePIE support. Please use v2.3.1.

sample3.py has mode 0,1,2 and you can toggle it by back button.
On mode 0, trackpad right/left/top/bottom parts are assigned to buttons like menu or system.

**Comment by BalazsAdorjan** [comment]
Thanks for the suggestion, I'm trying to get it to work. but I don't have a "C:\Program Files (x86)\FreePIE\plugins" folder to copy the "ALVRFreePIE.dll" into. Should I just create one?

**Comment by polygraphene** [comment]
Did you installed FreePIE?
https://andersmalmgren.github.io/FreePIE/
