### ISSUE TITLE
Experiencing shuttering in quest headset

### ISSUE THREAD

**Issue by YeetSkillet** [polygraphene/ALVR#349]
2.4ghz router
Windows 10
Geforce GTX 1070 TI

Quest headset shutters during game play, id blame it on my router if i wasn't averaging 60 ms in latency

**Comment by saintkamus** [comment]
It's stutter man. And don't worry, we all have it. The problem seems to be that the video encoder or decoder (most likely the decoder) can only do 60 FPS, but the display is at 72hz.

**Comment by foobyte** [comment]
My quest is connected to my PC's internal 5GHz hotspot. 
I also have stuttering/skipping in the headset tracking.

**Comment by fdinsdale** [comment]
Like saintkamus said it is the 60 FPS of the video card encoder being processed by the 72 FPS of the Quest.  It simply creates stutter.

Last year when ALVR was introduced for GO we had the same problem. The solution was to force 60 FPS on the Go and the stuttering ended.

I read on another post that currently the Quest doesn't support 60 FPS.  Yet

**Comment by MaLeVoLenT1** [comment]
Update coming adding 60fps to the quest:

https://uploadvr.com/oculus-quest-upcoming-updates/
