### ISSUE TITLE
Can we have an auto-connect checkbox

### ISSUE THREAD

**Issue by vrokolos** [polygraphene/ALVR#35]
That will constantly try to connect to the first headset it finds. Whenever I get my headset off, the connection is lost and have to go to my PC and click "connect" again.

This would be better.

Also do you guys know of any steam VR launcher that works with gamepads since my steam VR home doesn't work with the gamepad?

**Comment by vrokolos** [comment]
#37

**Comment by polygraphene** [comment]
Thank you for the comment!
As I said in #37, please wait for a while.
Sorry for inconvenient.

**Comment by vrokolos** [comment]
https://github.com/polygraphene/ALVR/blob/754085133cc301216109de1c2f0615acaa101c9b/ALVR/ClientList.cs#L113

Why this line? Now every time I get my phone off and on the gear VR I have to go to another room to repress connect :(

**Comment by polygraphene** [comment]
We need to avoid "infinite loop" of auto connect. But it was too much.
I'm trying to write more aggressive auto connect.

**Comment by vrokolos** [comment]
Yeah you could make it so that whenever you press the "Remove" button on the server it also unchecks the "auto-connect" checkbox

**Comment by polygraphene** [comment]
Please check v2.1.0.
https://github.com/polygraphene/ALVR/releases/tag/v2.1.0

**Comment by vrokolos** [comment]
new version only shows black screen on my exynos s9+

sound streams fine though

awesome release when it works!! I'm pumped

**Comment by polygraphene** [comment]
Can you see "Press connect button" message?
Can you show me the output of `adb logcat`?

**Comment by vrokolos** [comment]
adb logcat show a stream of countless info

how to filter it?

**Comment by vrokolos** [comment]
https://gist.github.com/vrokolos/e2fdcc2de8c0d10f73d5a2147f961820

**Comment by vrokolos** [comment]
It connects fine and sound streams fine. There is no picture however

**Comment by polygraphene** [comment]
Thank you!
I wanted a client startup log.
The log says compile error on fragment shader.
I will try to fix. Please wait a moment!

**Comment by polygraphene** [comment]
Please check this version.
I reverted the fragment shader on non ARCore version.
So ARCore version has same issue.
https://github.com/polygraphene/ALVRClient/releases/tag/v2.1.1

**Comment by polygraphene** [comment]
I added log output to get detail information of issue.
I would appreciate it if you could send logcat of ARCore version, if you have time.

**Comment by vrokolos** [comment]
The non ARCore version works perfectly fine with sound and picture

The ARCore version has the same problem but I can't retest it using adb currently so I'll let you know when I do.

**Comment by polygraphene** [comment]
Thank you for quick reply!
>The non ARCore version works perfectly fine with sound and picture

Great!

>The ARCore version has the same problem but I can't retest it using adb currently so I'll let you know when I do.

Thank you! You don't need to hurry.

**Comment by vrokolos** [comment]
https://gist.github.com/vrokolos/1ef4b76f589b16837cd6defab9246e73

I think I got it.

**Comment by polygraphene** [comment]
It seems startup log has gone away. I could only see the log after start.
Please restart the app by following command and re-get the log.

- `adb shell am force-stop com.polygraphene.alvr.ar`
- `adb shell am start -n com.polygraphene.alvr.ar/com.polygraphene.alvr.MainActivity`
- Wait for 5~10seconds
- `adb logcat -d > logcat.txt`

**Comment by vrokolos** [comment]
https://gist.github.com/vrokolos/1579a6969b53f13377991a816771e4a8

Sorry I think I got the wrong file
This was the start I think check it out and tell me if it's wrong

**Comment by polygraphene** [comment]
Thank you so much.
I could find the shader error on the log and maybe fixed.
Please try this version.
https://github.com/polygraphene/ALVRClient/releases/tag/v2.1.3

**Comment by vrokolos** [comment]
Yes it works fine. Thanks! Although now that I tried it I prefer the normal version :)

**Comment by polygraphene** [comment]
Thank you!
