### ISSUE TITLE
slow sent rate over 5ghz wifi connection (OCULUS QUEST)

### ISSUE THREAD

**Issue by Arcabyte** [polygraphene/ALVR#350]
i have a 5ghz wifi router which is connted to my pc using an Ethernet cable. so when i connect my oculus quest to alvr my transfer speed doesn't go above 10Mbps. my router is a dlink router AC1200 DIR 825.

**Comment by fdinsdale** [comment]
Where are you seeing the 10Mbps reported? On the Quest WIFI selection? 
With your router and on 5ghz you should see  a reported speed of more than 800 Mbps.

I assume you are using your quest close to the router?  Sometimes a single dividing wall can seriously degrade a 5 ghz signal.

**Comment by iceener** [comment]
Same here. I have router which supports 1167 mbps speed (RT-AC1200G+) and Quest reports only ~170. 

What is wrong?

**Comment by iceener** [comment]
> Same here. I have router which supports 1167 mbps speed (RT-AC1200G+) and Quest reports only ~170.
> 
> What is wrong?

Fixed: Updated router software helped. Now it's on full speed and works flawlessly.
