### ISSUE TITLE
Will Oculus Store download keys come to the Quest?

### ISSUE THREAD

**Issue by Mountaineer64** [polygraphene/ALVR#353]
This option would make alvr much more user friendly and easier for newcomers. Thank you for your amazing development so far!

**Comment by evertec82** [comment]
What do you mean by this? What do you want to happen with download keys? You can already redeem download keys on the oculus store for quest if a dev gives you one.

**Comment by Mountaineer64** [comment]
Evertec82, yea. The go version could be redeemed through the store with a key instead of  sideloading. This made it easier to get up and running and receive updates!

**Comment by FricoRico** [comment]
I'm afraid this won't happen any time soon, but I could be mistaken.

At the moment you need to pitch your game/app to Oculus before getting access to their so called 'Platform' SDKs and store toolset. For now you won't be able to generate keys.

I don't think there is a workaround

**Comment by polygraphene** [comment]
As @FricoRico said, I have no luck with it.
https://github.com/polygraphene/ALVR/issues/287#issuecomment-492935056

Because store policy is definitely different from Go, we can not expect it in near future.
