### ISSUE TITLE
No picture in headset, but everything else seems to work?

### ISSUE THREAD

**Issue by JDavis1186** [polygraphene/ALVR#355]
Trying to run v2.4.0-alpha4 on/with my Quest, and it seems that everything is working except the display.

The software runs, the computer and the headset appear to be talking to each other just fine. I can hear the computer audio through the Quest if I have Steam sound turned on. If I turn on the display mirror window in SteamVR I can see that it is tracking the headset and hand controllers properly. But inside the headset I'm stuck with the "Press CONNECT button on ALVR server" screen. More specifically, whatever angle the headset was pointed when the server started remains in view, but looking anywhere else is black.

I've tried uninstalling and reinstalling the ALVR software, the apk, and SteamVR. I've tried running the portable version instead of the installed version. I've rebooted both the computer and the Quest with each attempted solution. I'm just not having any luck, and I'm not sure what else to try.

**Comment by clinton-origin** [comment]
I had the same issue but it was because I installed v2.4.0-alpha1. I then unistalled the PC version (using control panel) and installed the alpha4 one. I then copied over the updated apk to the headset and it all started working.

If you run out of ideas maybe try to install alpha1 and follow my process.

Sorry not great advice but it's something!

**Comment by midorikuma** [comment]
Exactly the same issue here.
I tried various things but did not solve.
Same problem in alpha5.

**Comment by polygraphene** [comment]
Same issue: #364
Try it: https://github.com/polygraphene/ALVR/issues/364#issuecomment-497702922

**Comment by midorikuma** [comment]
Thanks. I solved this problem!
After all it was a network issue.
If you have same problem, try changing Network and Sharing Center>Properties>Configure>Advanced settings.
A wonderful experience should be waiting for you!

**Comment by Glorfindal83** [comment]
Midorikuma: What specifically did you change in Network and Sharing to get it to work? I'm having the exact same issue as you, and i'm completely stumped. I've uninstalled and reinstalled everything, then changed settings in the Network and Sharing Center...but no luck.
The ALVR serve will run on my PC, i can see from Steam VR that the headset is looking around when i move it...but through the headset all i see is darkenss or the white screen frozen on "press trigger to launch steam vr"

**Comment by BlaxHazHax** [comment]
@midorikuma which settings did you change?
