### ISSUE TITLE
Trying to find the choke point

### ISSUE THREAD

**Issue by bdodroid** [polygraphene/ALVR#358]
I'm having terrible performance on my Oculus Quest (totally unusable no matter what settings I change) and I'm trying to pinpoint why.

Here's my specs, maybe someone here can point me in the right direction?

i74770k
8gb ddr3 ram
980 TI 
Wired Connection (though it only gets a max of about 250mbps out of the 600 my other devices get)
Google Mesh Wifi Routers

any obvious fail points? I know its an old system but I have played vr with a Lenovo Explorer (windows mixed reality) and it handled that very well.

**Comment by FricoRico** [comment]
Did you check connection does on the Oculus Quest itself? Maybe it's not connected at 5Ghz network

**Comment by polygraphene** [comment]
For debugging network issue, I usually use iperf to measure bandwidth.
Otherwise, see logcat output of client.

**Comment by abpages** [comment]
Its your google mesh routers. I had them, had same issue. Oculus Quest would randomly connect to 2.4ghz network, even when I had the quest in same room as router. I tried everything, moving them around to different places in the house nothing worked.

Cannot separate 2.4ghz and 5ghz networks, so only way I fixed it was to sell the Google Mesh Network and get a new router (non mesh).

The one I picked up is the Netgear Nighthawk AX3000/RAX40 
https://www.netgear.com/home/products/networking/wifi-routers/RAX40.aspx

It allows me to make a separate network for 5ghz and Quest is MUCH better on that.

**Comment by bdodroid** [comment]
Thanks all for your help! It is indeed the google mesh unfortunately :( 

I was able to get usable results by unplugging all google mesh nodes except the one my computer was hooked up to and was able to play Windlands pretty well. 

@abpages how can you tell what wifi frequency your Oculus Quest was on? I havent seen anything to indicate 2.4 or 5ghz but I could totally be missing something obvious.

**Comment by abpages** [comment]
You can go into google devices and see if it's connected on 2.4 or 5ghz.

Alternatively, go into oculus quest, click on wifi, then click on the access point and it will show up what frequency it's connected to.

**Comment by bdodroid** [comment]
And yup, missing something obvious. Story of my life lol. Thanks!
