### ISSUE TITLE
ALVR Alpha 4 Blade and Sorcery

### ISSUE THREAD

**Issue by Talwar85** [polygraphene/ALVR#359]
Button Mapping does not work ingame with ALVR Alpha 4.

The buttons A,B,X,Y have no function ingame.
Im Steam,VR Menu they seem to work.
I cannot access the ingame menu or cast spells.
Is there a solution? I tried to remap in steamvr, but it did not.

Anything else seems to work pretty fine. 
Is this a problem with alvr or steamvr?

Good Job.

**Comment by ICURSEDANGEL** [comment]
How did u get alvr alpha?

**Comment by SecretHippo1** [comment]
@ICURSEDANGEL it's in the releases

**Comment by polygraphene** [comment]
I will add support for FreePIE to remap buttons in near future.

**Comment by Talwar85** [comment]
ALVR alpha-5 its working fine.
