### ISSUE TITLE
Wrong version error

### ISSUE THREAD

**Issue by Lightsteed** [polygraphene/ALVR#36]
On 1.9.2 its telling me i have the wrong client version but im definitely using 1.9.2. I rolled back to the 1.9.1 client and it can connect however i cant use the new resolution feature as the image is all distorted.

**Comment by vrokolos** [comment]
Works fine here

**Comment by Lightsteed** [comment]
Weird. Ill try again

**Comment by Lightsteed** [comment]
okay its working now... i think for some reason the 1.9.1 drivers didnt uninstall correctly, it actually broke the tracking on my Vive because of it, i installed and uninstalled the 1.9.1 drivers and it fixed my vive tracking and the wrong version issue went away too :) you can close this issue!

**Comment by polygraphene** [comment]
Sorry for inconvenient.
Coexistence of multiple ALVR driver cause many bad issues. (#19, #23)
I will add the safer driver installation on the next release.
