### ISSUE TITLE
Touch controllers laggy and jittery after Alpha 5

### ISSUE THREAD

**Issue by codyrowan** [polygraphene/ALVR#362]
Touch controllers feel like they have some sort of predictive physics instead of following my hands 1:1 after Alpha 5, also very jittery while they worked fine in Alpha 4.

**Comment by slydog43** [comment]
Throwing is indeed better with alpha5 vs previous versions. I have tried 1st person tennis and throwing the ball up to serve was impossible before. Now it just works, yeah. Seems like the hand tracking is much faster but with little stutters (I think its better this way). This program just gets better and better. I check everyday, multiple times for updates as I think this is the best program for the quest or at least has the most potential.  Thank you poly!!!!. 

Is there any chance of changing the rotation of the controllers before you run steam so some games are just "adjusted" for games with guns and specifically Golf Club VR?  In golf club vr the controller has to be held in a very unnatural angle.  Not sure if something like that is possible (I'm thinking like the x,y,z offset section in ALVR but for controller angle?  what do you think?  Did you get your late delivery of the quest yet?

**Comment by qruxtapose** [comment]
I have the same issue. Surprised some people are saying it's better. Maybe it is working as intended for them I'm not sure. For me it's as you described, there is some lag as well as jitter (laser pointer in steam vr is jumping all over the place).

**Comment by simphax** [comment]
Same thing here! Both the controllers and the head tracking have some kind of rubberband effect. Like, after a quick movement it will continue for a while and then return. It's o-kay for the controllers but the head tracking makes me nauseous. But other than that I am soo impressed by the latency and video quality! I run steady on 100% resolution and 80Mbit/s and I see no frame drops or artifacts (except for when my computer is working hard). And this is from an 2017 iMac on Boot Camp :D

**Comment by babybasher** [comment]
I too confirm the jittery controllers and laser pointer in SteamVR using alpha5 now.  However having tried Rec Room and EchoVR, they appear normal as per Alpha4.  Throwing is working great in both those titles thanks!

This program is coming along really quickly/well.  I think the most important thing now is getting the controller tilt right.  Can't really enjoy games when you have to tilt the controllers at awkward angles.

**Comment by squizzeak** [comment]
Confirming I'm experiencing hand controller jitter under a5 that I did not experience under a4

**Comment by samvila** [comment]
> Same thing here! Both the controllers and the head tracking have some kind of rubberband effect. Like, after a quick movement it will continue for a while and then return. It's o-kay for the controllers but the head tracking makes me nauseous. But other than that I am soo impressed by the latency and video quality! I run steady on 100% resolution and 80Mbit/s and I see no frame drops or artifacts (except for when my computer is working hard). And this is from an 2017 iMac on Boot Camp :D

What router are you using to achieve 80Mbit/s? What is your total latency from the ALVR window?

**Comment by donaldjosephsmith** [comment]
> Both the controllers and the head tracking have some kind of rubberband effect. Like, after a quick movement it will continue for a while and then return.

Interesting; I was seeing this with the controllers, but I didn't notice it with the head tracking. I was testing with Thrill of the Fight - made for some easy knockouts (haha)

**Comment by urbenlegend** [comment]
I definitely feel that there's some additional motion prediction going on with the Touch controllers. If I shake my controllers rapidly but in small arcs, the virtual hands seem to rotate way more than my hands are actually rotating. It's like the virtual hands are mounted on a really loose suspension system or something.
This issue makes playing Beat Saber almost impossible.

**Comment by simphax** [comment]
> What router are you using to achieve 80Mbit/s? What is your total latency from the ALVR window?
I'm just using the router that came with the ISP - Technicolor TG799vacXTREAM
Actually it seems like the stream doesn't go above 20Mbit/s when looking in the ALVR window
The total latency is 67-73ms . Transport latency is something like 2-3ms . The majority comes from encoding the video.

I might be mistaken about the rubber band effect of the headset but rather it's probably the latency that I am experiencing.
