### ISSUE TITLE
Headset not found - Oculus Quest for ALVR

### ISSUE THREAD

**Issue by MartZOZ** [polygraphene/ALVR#363]
I've read through a lot of threads at this point, but I can't seem to find an answer. I'm using the Oculus Quest for your new ALVR release.

I've installed adb and command prompt lists my headset if I put in the command "adb devices"
I've installed SteamVR but it says "headset not detected" with (108) in brackets. 

I've loaded ALVR.apk in my adb folder and once I open the program under "unknown sources" it says "Press CONNECT button on ALVR server"
but my headset doesn't show.

I should mention that my ALVR is installed C:\ALVR\driver
My adb is installed under C:\adb
and SteamVR C:\Program Files (x86)\Steam\steamapps\common\SteamVR

**Comment by SSSTREDDD** [comment]
Does the Server see the device? Is it just the client software on the Quest having the issue?

**Comment by MartZOZ** [comment]
![bilde](https://user-images.githubusercontent.com/51233825/58704797-7a8aac00-83ad-11e9-9c22-97b5acc0fcfa.png)
This is how it looks, even while in the ALVR application in the oculus quest

**Comment by SSSTREDDD** [comment]
Try temporarily disabling windows firewall. Usually these issues are due to the firewall not allowing ALVR through.

if it works with the firewall off then ill pass you some additional info to help you out.

**Comment by MartZOZ** [comment]
I've turned off the firewall too before I posted here. didn't work :(

**Comment by polygraphene** [comment]
I added firewall script on alpha5.
Please try installer version of alpha5. It will automatically add firewall settings.

**Comment by Niceman35** [comment]
Make sure you not running some VPN. Also check, what your Quest is connected to your local WiFi and same network as your PC.

**Comment by MartZOZ** [comment]
Great news, I downloaded the .exe and not the portable version. Now it says "Server is alive!" but It still doesn't recognize the headset

**Comment by MartZOZ** [comment]
okay so I have to uninstall my previous ALVR version from my headset. 
how?

**Comment by polygraphene** [comment]
You don't need to uninstall.
You should re-install by `adb install -r (apk path)`

**Comment by MartZOZ** [comment]
ok I re-installed the ALVR to the alpha 5 version, going to try now

**Comment by MartZOZ** [comment]
it still doesn't show the headset :/

**Comment by MartZOZ** [comment]
there are no error messages, nothing that pops up.
Not sure what it can be

**Comment by polygraphene** [comment]
Confirm that `ping` command properly works.

**Comment by MartZOZ** [comment]
how should the results look, my headset is supposed to be disconnected from my pc. right?

**Comment by MartZOZ** [comment]
![bilde](https://user-images.githubusercontent.com/51233825/58707768-1b7d6500-83b6-11e9-8546-639954779f09.png)
with and without having it plugged in

**Comment by MartZOZ** [comment]
![bilde](https://user-images.githubusercontent.com/51233825/58707793-36e87000-83b6-11e9-8e6d-d6c03bc2dbbb.png)
with and without it being plugged in

**Comment by polygraphene** [comment]
Is the `192.168.1.165` IP address of PC?
`ping` seemed to fail.
You should check your headset and PC are connected under same router.

And please tell the result of:
1. `ipconfig` command
2. `adb shell ip a` command

**Comment by MartZOZ** [comment]
![bilde](https://user-images.githubusercontent.com/51233825/58708082-0e14aa80-83b7-11e9-9dce-23f18aacdcba.png)
what part of ipconfig do you want to see?

**Comment by polygraphene** [comment]
Thank you. PC and headset are under same subnet. It seems right settings.
`ping` from PC side fails too?
Please try `ping 192.168.1.39`

**Comment by MartZOZ** [comment]
![bilde](https://user-images.githubusercontent.com/51233825/58708447-1d482800-83b8-11e9-84e7-09bd62be308e.png)
this.. doesn't seem too good :(

**Comment by MartZOZ** [comment]
I should say my firewall is still inactive, I've turned it off a while ago.
if you want me to turn it on or try something along the lines there I can

**Comment by polygraphene** [comment]
Hmm...
If you can't get `ping` work, you should check router configuration.
You may need to disable "privacy separator" feature.

**Comment by MartZOZ** [comment]
I'll have to see what I can do about that, I've had some issues with router stuff in the past :/

**Comment by MartZOZ** [comment]
I can't really access the router at the moment, however, I should be in not too long. I'll update this in a little bit once I've tried to change the "privacy separator" feature on my router.
Thank you for the help so far. Hopefully this will be the only thing I need before it's fixed

**Comment by bwadejs** [comment]
Hi Guys. im having the exact same problem, im at work so tried to set this up on their wifi but alvr just doesnt see my quest. so i set my phone up as a wifi hotspot and connected my laptop and quest to that. still doesnt find it :/    please let me know if you come up with anything to try

**Comment by DiMarzio84** [comment]
I think l actually had to have the Quest on my head before it could find my headset. Trigger the sensor to keep the display on maybe.

**Comment by bwadejs** [comment]
Yer I did try that.  No use. So I tried riftcat... That searches then straight away pops up is thisquest your device. But when I say yes it says connecting for about 30 seconds then goes back to searching. So for some reason they can connect. Maybe it is firewalls so I'll try in a few weeks when I go home

**Comment by MartZOZ** [comment]
I'll try riftcat before I come to any conclusions. If that doesn't work... I'll just have to wait for future updates, maybe a patch will come along :P

**Comment by zxsdklfhskyrvk** [comment]
> 
> I can't really access the router at the moment, however, I should be in not too long. I'll update this in a little bit once I've tried to change the "privacy separator" feature on my router.
> Thank you for the help so far. Hopefully this will be the only thing I need before it's fixed

I wonder if this is an issue with "client isolation" features on your wifi network(s).  That could easily prevent access between your PC and the Quest.  You should have both devices on a network that does not have this enabled.

**Comment by tuesday8877** [comment]
I'm having the same issue, ALVR just doesn't recognize my quest. could it be a headset specific issue?

**Comment by bwadejs** [comment]
It's most likely your antivirus. I have comodo and until I added alvr as an exception to that it wouldn't find it. Works fine now.

**Comment by Haghbarth** [comment]
I had the same problem. 
Not sure how to explain that (mediocre english =.=) but what router do you use?
I "kinda" use two routers. The one i got from my provider and another WLAN-router which i bought to boost my wlan to 5ghz, which is recommended if you want to stream from pc to quest.

So when i first connected my wlan router to the providers router i got the same problem of alvr not recognizing my quest anymore. 
But then i made my wlan router an "ip client" and now it works. 

Polygraphenes comment earlier about having pc and quest connected to the same router kinda helped me out here. So maybe this helps you as well?

I hope you understand what im tried to explain ^^"

Greetings

**Comment by bwadejs** [comment]
I doubt it as i had these issues and i fixed them all bz turning off all my
antivirus software

**Comment by tuesday8877** [comment]
Can confirm that allowing it through my firewall did work

**Comment by urbanescabrous** [comment]
If you are installing the Alpha programs and it is not working for you,  Maybe try the stable / regular versions

**Comment by urbanescabrous** [comment]
Also change the codec that might work for you

**Comment by ronakjain89** [comment]
Hi @polygraphene 

I am also facing a similar kind of issue.

I am able to ping from the PC to the Oculus Quest device but somehow ping from device to PC fails. The device and PC both are connected on the same network. Also when I try to ping to the gateway from the device then it works but fails with the PC. so don't know what's happening.

Can you please give some input on it.

Thanking you in advance...!!!

Thanks
Ronak

**Comment by plumbus2020** [comment]
> It's most likely your antivirus. I have comodo and until I added alvr as an exception to that it wouldn't find it. Works fine now.

Hi @bwadejs, could you please give a short tutorial, which settings you made in Comodo? I tried a lot, but the headset is still not found. Would be great! Thanks 🙏

**Comment by Alejarciy** [comment]
we are having the same issue. Is the riftcat a good alternative?

**Comment by justposted** [comment]
> we are having the same issue. Is the riftcat a good alternative?

Riftcat is worth a go, yes. But I have the connection problem on ALVR beta too and the last stable version works fine. Try that one.

**Comment by Fizelche** [comment]
I had the same problem, and it looks like it is an issue with the firewall. It also doesnt work with FW deactivated. But i found an easy Workaround:

1. Go to the last release in the old main repo https://github.com/polygraphene/ALVR/ and install alvr with the setup.exe. The Setup does the corret FW-Changes.

2. Download the newest release and extract the zip to the same installation directory like the setup and overwrite the files and install the matching apk on th quest

Now start with the new version and it works. hopefully ;-)

**Comment by dkimber122** [comment]
I am getting the same results. I tried what you said @Fizelche, but it didn't work for me. I turned my firewall off as well, just in case. It says I am connected but it says server is down and then disconnects altogether. Any other ideas?

**Comment by Fizelche** [comment]
I found the reason, why it doesnt work on my first trys. Windows prevents to launch apps with special FW-requierements from desktop(maybe complete user directory). I moved the unziped copy to any other direction and it asks for firewall permissions at launch. When FW-Rule is applied, it works fine.

**Comment by Fizelche** [comment]
I found another possible blocker. ALVR was deactivatet in steamvr. To change this property: Open SteamVR-> Klick on the BurgerMenu -> Settings -> Start/Stop -> Manage Add-Ons -> activate alvr_server -> try to start again
