### ISSUE TITLE
Frozen screen on quest after starting server

### ISSUE THREAD

**Issue by BlaxHazHax** [polygraphene/ALVR#364]
the server says im connected and in the headset viewer in steam vr shows my headset and controllers tracking fine but in the actual headset itself its just stuck on the "press trigger to start steamvr" screen, i had the same issue in alpha 4 and 3, alpha 5 didn't seem to help, i have tried changing the video codec, changing the sound settings, uninstalling and reinstalling ALVR, disabling firewall with absolutely no luck i don't know what else to try plzzzz help

**Comment by polygraphene** [comment]
Perhaps you couldn't get first video frame because of bad network state.
Try lower bitrate like 5~10Mbps.
And confirm that you are using 5GHz Wi-Fi.

**Comment by BlaxHazHax** [comment]
oh im using a 2.4ghz wifi that might be the problem :(

**Comment by BlaxHazHax** [comment]
i am now using a 5ghz wifi but still no difference

**Comment by Glorfindal83** [comment]
I'm having this same issue. Anyone find a resolution?
