### ISSUE TITLE
SteamVR not detecting connected headset Oculus Quest

### ISSUE THREAD

**Issue by crusenusa** [polygraphene/ALVR#368]
I've connected my headset in ALVR but when SteamVR tells me to run Room Setup it doesn't detect that there's a headset and in the Quest it's still telling me to hit connect in ALVR. Screenshots attached for reference,
![alvr](https://user-images.githubusercontent.com/51252719/58742359-5ef5c480-83f2-11e9-8930-a2b9e0ef9210.PNG)
![steamvr](https://user-images.githubusercontent.com/51252719/58742362-62894b80-83f2-11e9-9d16-85ab9211ab29.PNG)

**Comment by DigitalStyx918** [comment]
This happened once for me and SteamVR was in safe mode for some reason.

**Comment by crusenusa** [comment]
> This happened once for me and SteamVR was in safe mode for some reason.

I've tried rebooting Steam itself and SteamVR and the same thing happens. Doesn't appear to be in safe mode.

**Comment by Nugzy420** [comment]
I'm having similar issues. ALVR connects just fine but SteamVR says "Searching..." and says it cant find my headset, and to make sure it's in view of a base station.

**Comment by Nugzy420** [comment]
Just got mine to work by connecting my headset to Windows Mobile Hotspot rather than my Wifi. Must be a router issue?

**Comment by polygraphene** [comment]
It may be caused by firewall. Please try to allow 9944/udp port.

Or maybe the server driver is not properly loaded by SteamVR.
Try to enable DebugLog and make sure you get driver.log file.
See: [Debug Information](https://github.com/polygraphene/ALVR/wiki/Debugging#how-to-enable-server-driver-log-output)

**Comment by DigitalStyx918** [comment]
I used Alpha 4 with no problem with a comtrend router.  Now I'm connected
to a 5ghz Netgear router and did a fresh install of Alpha 5 and I am having
this problem.  Enabling the UDP port forwarding for 9944 did not make a
difference.

I was actually attempting to test something to let someone else know if it
would work.  So I can't justify a lengthy debug effort, but I am interested
in knowing solutions when they are found.

**Comment by cots-xd** [comment]
same problem here, quest connected safely, but could not get past room setup headset was not detected at all.


any help / fixes for this?

**Comment by Corfiot** [comment]
Confirm: when safe mode disabled, it works again. I restarted steamVR and it notified me of safe mode being on, then gave me a button to turn it off. I did so and it worked.

**Comment by cupayuri** [comment]
How do find the disable safe mode manually because I did restart steamVR but it didn't come up automatically

**Comment by Corfiot** [comment]
If it starts in safe mode it usually just tells you and gives you the option to disable it. I Guess if it's not asking you, you're not in safe mode.
