### ISSUE TITLE
AMD PC Maximum 75% Resolution to Quest

### ISSUE THREAD

**Issue by shodgson88** [polygraphene/ALVR#369]
I can go no higher than 75% resolution when streaming to my Quest from my AMD PC (R9 390). The bitrate can be adjusted really high with no issues and the latency is fine but anything higher than 75% Res gets stuck on the white waiting to connect screen. The movement of the headeset and controllers is still showing ok on the PC, just no image within the HMD.

Anything 75% resolution or below works perfectly. Any advice would be greatly appreciated!

**Comment by polygraphene** [comment]
Your GPU may support only FullHD resolution.
You can check the capability of AMD GPU. Try it and please tell me the result.
[AMF-CapabilityManager.zip](https://github.com/polygraphene/ALVR/files/3243801/AMF-CapabilityManager.zip)
Usage: Run the run.bat and see CapabilityManager-output.txt.

**Comment by shodgson88** [comment]
Thanks for such a speedy reply. Sorry but when I am running that tool I get a few errors...does it need to be run in a particular place?
![1](https://user-images.githubusercontent.com/51263321/58749513-264ffc80-847f-11e9-94a3-6c046b631a9b.png)
![2](https://user-images.githubusercontent.com/51263321/58749514-264ffc80-847f-11e9-8ac7-39dd1b191575.png)
![3](https://user-images.githubusercontent.com/51263321/58749515-264ffc80-847f-11e9-9039-ffd83c3514b0.png)

**Comment by polygraphene** [comment]
Sorry! I made a mistake.
Try this.
[AMF-CapabilityManager.zip](https://github.com/polygraphene/ALVR/files/3243831/AMF-CapabilityManager.zip)

**Comment by shodgson88** [comment]
Thanks a lot, please see attached
[CapabilityManager-output.txt](https://github.com/polygraphene/ALVR/files/3243836/CapabilityManager-output.txt)

**Comment by polygraphene** [comment]
Thank you. Unfortunately, your GPU can encode 1920x1920 texture at most.

```Querying video encoder capabilities...
	Codec AMFVideoEncoderVCE_AVC
		Acceleration Type:Hardware-accelerated
		maximum profile:100
		maximum level:51
		Number of temporal Layers:1
		IsBPictureSupported:1

		Max Number of streams supported:16
		Number HW instances:1
		Encoder input:
			Width: [64-1920]
			Height: [64-1920]
			Vertical alignment: 32 lines.
			Interlaced support: NO
			Total of 6 pixel format(s) supported:
				0: NV12 (native)
				1: YUV420P 
				2: YV12 
				3: BGRA 
				4: RGBA 
				5: ARGB 
			Total of 4 memory type(s) supported:
				0: DX11 (native)
				1: OPENCL 
				2: OPENGL 
				3: HOST 
```

**Comment by shodgson88** [comment]
Thanks a lot, I really appreciate you having a look as it was driving me mad trying to work out what the issue was.

Will look at picking up a newer GPU. Cheers!

**Comment by shodgson88** [comment]
Just to add, is there a way to set a custom resolution? Could I somehow set a 1920 x 960 resolution or do I have to use the presets? Thanks.

**Comment by polygraphene** [comment]
I'm sorry that I could not be helpful.
Currently, it doesn't have custom resolution. I will add that feature.

**Comment by shodgson88** [comment]
> I'm sorry that I could not be helpful.
> Currently, it doesn't have custom resolution. I will add that feature.

No problem at all, I really appreciate the help. I will close this as an issue. Thanks!

**Comment by bonsaiheldin** [comment]
On top of custom resolutions i would suggest smaller percental steps, 5% steps maybe. People often use 80% or 90% on PC Headsets to save some GPU speed and say that it practically looks the same. But 75% looks visibly worse than 100%.

**Comment by speckm** [comment]
I have the same problem with a RX5700. 75% work perfect, but at 100% I get no connection to the quest. I the output of CapabilityManager lists

Width: [112-4096]
Height: [16-2176]

for all encoders, this does not seem to be the only problem. Do you have any hint what I could check furthermore?

[CapabilityManager-output.txt](https://github.com/polygraphene/ALVR/files/3882894/CapabilityManager-output.txt)
