### ISSUE TITLE
Recommended Setting for Oculus Quest

### ISSUE THREAD

**Issue by aaronrryan** [polygraphene/ALVR#370]
I thought it would be nice to add to the docs the recommended setting for 
using with the Oculus Quest.  

I noticed a huge improvement moving to 5Ghz wifi.  
but I'm not sure if the default 30Mbps and H.265 is the best settings. 

Once everyones played with it a while, we should consolidate the wisdom down.

**Comment by POEDaley** [comment]
I've experimented very little, but what I've found so far is increasing the render resolution very nice.  I'm running at 150% and 27MB/s bitrate on H.265 and it looks great.  I've very curious to hear as well what others are running to see if I can further tweak it.

Specs:
dedicated 5ghz network
i7 6700k
GTX 1080

**Comment by Annomatg** [comment]
You can get lower latency with H.264, H.265 has better video quality but this isn't as important as low latency.

**Comment by rene1977** [comment]
If you use a AMD RX400 or RX500 series take for sure the H.265. The hardware encoder for 265 is way stonger than 264. In my installation it did render 264 even in Software increasing the latency from around 60ms to 220ms with all components on the limit.

**Comment by Muhlawor** [comment]
Using H.264 with 30Mbps and 150% scaling, work ok but occasionally will get drops and picture is all wrong, 5Ghz obviously.

**Comment by ischicopter** [comment]
I found H.264, 100mbps @ 150% worked best for my setup in Elite Dangerous with 2.0 Supersampling. 
Ryzen 5 2600x, 16GB, RTX2070

H.265 looks way better but the latency kills it for me unfortunately.

The intermittent Picture Arfifacts every 5 minutes or so are beig discussed in another thread right now and seem to be a common problem.

**Comment by Muhlawor** [comment]
> I found H.264, 100mbps @ 150% worked best for my setup in Elite Dangerous with 2.0 Supersampling.
> Ryzen 5 2600x, 16GB, RTX2070
> 
> H.265 looks way better but the latency kills it for me unfortunately.
> 
> The intermittent Picture Arfifacts every 5 minutes or so are beig discussed in another thread right now and seem to be a common problem.

What buffer size are you using?

**Comment by ischicopter** [comment]
standard 200

**Comment by omenyayl** [comment]
I achieved a 20-30ms latency with H.265, 50Mbs bitrate, and 150% resolution by first enabling the Windows 10 mobile hotspot (5Ghz only), and then connecting the Quest to it. I did this with a Lenovo X1 Extreme Laptop.
