### ISSUE TITLE
Can't grab objects on Oculus Quest

### ISSUE THREAD

**Issue by chema8132** [polygraphene/ALVR#372]
I've been testing deeply alvr on oculus quest, and It works pretty well. But i'm having problems with the triggers, which fires ok, but it doesnt get hold, so i cant gran any objects.

Btw i'm running the Alpha v5.

Thanks.

**Comment by polygraphene** [comment]
What's application?

**Comment by chema8132** [comment]
Recently tested some Scape Rooms games like Tales of Escape or We were here. In any of them you just can't grab things, it's like the trigger buttom works, but it doesn't detect the buttom pressing.

**Comment by jorgeazevedo** [comment]
Like this one? https://store.steampowered.com/app/587860/Tales_of_Escape/

**Comment by chema8132** [comment]
> Like this one? https://store.steampowered.com/app/587860/Tales_of_Escape/

Indeed, that's an example, but it looks like the issue isn't related with a game, it looks like it would happen with any SteamVR game where you have to hold the triggers.

**Comment by jorgeazevedo** [comment]
I could swear that in the games I tried I was holding stuff just fine by holding the triggers. It could be that I misunderstood how the game controls worked in the first place!

**Comment by chema8132** [comment]
After some more tests, i can confirm that:
1.- You can notice the issue on Alpha4 and Alpha5
2.- You can grab things on SteamVR Home, for example, but for some reason not in some games, like these I said before.

So it looks like it's something related with both games.

**Comment by squizzeak** [comment]
Could this be related to the controller jitter in a5?

**Comment by chema8132** [comment]
I don't think so, as it happens the same way in a4

**Comment by Godatplay** [comment]
It's likely to be an input mapping issue. There are actually different inputs for the capacitive touch vs the analog input. So when you do a grab, you usually test for the given trigger being pushed in beyond some threshold like 0.5 or 0.8 or whatever. I'm guessing it's the axis input / trigger analog input that's not mapped correctly. That could also explain why Home would work, as that could be based on Vive controllers, which has buttons for the grip instead of triggers. It may not implement grip by testing if the trigger is beyond a threshold.

**Comment by jhaleit** [comment]
I think the best solution is to trick Steam into thinking you're using the Rift S. Same controllers and is fully supported by Steam.

**Comment by jorgeazevedo** [comment]
I've been able to replicate the issue on that escape room game. Like @Godatplay said above, I think it's either a bug in the game or an input mapping problem unrelated to ALVR. There's a few people complaining about the same issue on the forums
https://steamcommunity.com/app/587860/discussions/0/1694918539665277054/
https://steamcommunity.com/app/587860/discussions/0/1733216893873360448/
> I'm having the same problem in The Mine. At first I thought it was my equipment, but today I went into The Mine solo and found I could pick items up ,,, I think this may be a multiplayer glitch.

Give more polished experiences a try like [the lab](https://store.steampowered.com/app/450390/The_Lab/) and [accounting](https://store.steampowered.com/app/518580/Accounting_Legacy/?utm_source=newsletter&utm_medium=email&utm_campaign=campaign_subject) a try (they're free) and you'll see it works fine.

@jhaleit I actually wanted to try and do that, but steam only shows me the option of selecting rift, vive and index controllers. Did you have to install anything to make Rift S controllers available as an option?

**Comment by jhaleit** [comment]
> I've been able to replicate the issue on that escape room game. Like @Godatplay said above, I think it's either a bug in the game or an input mapping problem unrelated to ALVR. There's a few people complaining about the same issue on the forums
> https://steamcommunity.com/app/587860/discussions/0/1694918539665277054/
> https://steamcommunity.com/app/587860/discussions/0/1733216893873360448/
> 
> > I'm having the same problem in The Mine. At first I thought it was my equipment, but today I went into The Mine solo and found I could pick items up ,,, I think this may be a multiplayer glitch.
> 
> Give more polished experiences a try like [the lab](https://store.steampowered.com/app/450390/The_Lab/) and [accounting](https://store.steampowered.com/app/518580/Accounting_Legacy/?utm_source=newsletter&utm_medium=email&utm_campaign=campaign_subject) (they're free) and you'll see it works fine.
> 
> @jhaleit I actually wanted to try and do that, but steam only shows me the option of selecting rift, vive and index controllers. Did you have to install anything to make Rift S controllers available as an option?

I wouldn't know how to get Rift S controllers to work.. I was just tossing an idea to the devs.
