### ISSUE TITLE
Unhandled Exception. ExceptionCode=C0000005 Address=00007FF7DA03CBD4 (00007FFC23550000 + FFFFFFFBB6AECBD4)

### ISSUE THREAD

**Issue by marcob2178** [polygraphene/ALVR#374]
Please help. I am having this error message while steamvr is being launched by alvr

Unhandled Exception. ExceptionCode=C0000005 Address=00007FF7DA03CBD4 (00007FFC23550000 + FFFFFFFBB6AECBD4)

[ALVR_CrashLog_20190602_091255.log](https://github.com/polygraphene/ALVR/files/3244843/ALVR_CrashLog_20190602_091255.log)

thanks !

**Comment by polygraphene** [comment]
I have never seen this error...
Can you upload `C:\Program Files (x86)\Steam\logs\vrserver.txt` file?
In addition, please tell me the result of "List drivres" button on About tab.

If you are using OpenVR-InputEmulator or something similar, try to disable(uninstall) it.

**Comment by marcob2178** [comment]
Hi. Thanks for the reply. 
I can not find that file you mentioned me , in steam folder. 

The loaded drivers are these

https://ibb.co/nkCL3vg

I have done some driver disinstallign and I found out that your drivers and walkovr drivers are not getting along well at the moment . I have a test unit for walkovr.
I am looking forward that you guys and walkovr , work together to make both your drivers compatible together :)

Thanks!

**Comment by marcob2178** [comment]
How can I help you to fix this error and looking into the compatibility of walkovr software, with your software?
