### ISSUE TITLE
Jittery Pointer on Quest with new Alpha 5

### ISSUE THREAD

**Issue by jrdcode** [polygraphene/ALVR#375]
Been using Alpha 4 on my quest to run Bigscreens on my PC/Steam to my Quest wireless.  Its been working fairly well with only a few jitters for some apps occasionally.  

But the new Alpha 5 makes my pointers jitter like crazy its really odd.  Not sure why.  I had to uninstall the Alpha 5 and go back to Alpha 4 and it works fine again.  Please fix this.  Thanks.

**Comment by Muhlawor** [comment]
Didn't use previous versions but alpha 5 controllers are jittery for me as well.

**Comment by CoderCoderCoder** [comment]
Not tested alpha 4, but alpha 5 is indeed very jittery. It's highly annoying. Besides of it I need to hold the controllers in a different position during a gameplay (with a different angle) to achieve the same type of pointing as in the main Steam VR window. Not sure how to explain it better, I hope it's clear.
But generally speaking - huge thanks for this awesome streaming app!!! Good luck with all further work on it!

**Comment by jrdcode** [comment]
Try alpha 4 and be amazed how everything works perfect.  Alpha 5 is bad for quest....
