### ISSUE TITLE
(workaround inside) Copy guardian play space to steam vr?

### ISSUE THREAD

**Issue by safijari** [polygraphene/ALVR#376]
Title pretty much says it. Would it at all be possible?

**Comment by Muhlawor** [comment]
Would be nice

**Comment by safijari** [comment]
So, the reason I wanted this was because the quest forgets the guardian too much, and any re-setup completely screws up the chaperone in steam VR causing my gorn sessions to be significantly less pick up and play. I sort of found a fix though, it's not perfect but it's fast. There's a unity tool someone built called Chaperone Tweak that lets you fix up your chaperone in VR. So you can just use that to match the boundaries of the chaperone with the guardian (links below).

For the quest: hold the A key to bring up the menu of things you can do (move walls, move floor, save, and undo). Move hand into the setting you want and let go. If it's walls, you can reach into the walls and hold trigger to then move that vertex (some times it deletes it, unsure why), so just move a bunch of them into the guardian wall to make the shapes match.

Some times the floor will be screwed up, just use the floor mode and then use the grip while pointing at the various parts of the floor to either scale it (sides), move it (center), or rotate it (corner). You can also change the floor's elevation.

DON'T BE LIKE ME AND REMEMBER TO SAVE :D

https://github.com/Xavr0k/ChaperoneTweak/releases
https://www.youtube.com/watch?v=m7k1fgWuRBw
