### ISSUE TITLE
Oculus Quest casting.

### ISSUE THREAD

**Issue by jhaleit** [polygraphene/ALVR#377]
Casting/broadcasting has been disabled... Can you enable it?

**Comment by SSSTREDDD** [comment]
I have had this issue with all sideloaded Quest applications _(even official oculus apps sideloaded)_. I believe it is a limitation that Oculus imposes in the OS itself. I could be wrong though.

**Comment by SaladFork** [comment]
If you already have adb set up, take a look at [scrcpy](https://github.com/Genymobile/scrcpy); works great with the Quest.
