### ISSUE TITLE
Packet loss and image artifacts every 5-6 min

### ISSUE THREAD

**Issue by Djneo134** [polygraphene/ALVR#378]
Hi, I've tried all your alpha versions for Quest from now and I must thank you for your excellent work. What you have done is amazing !

Almost everything run very smooth except one thing.
I can't manage to solve one big issue which is a real immersion killer in VR.

Every 5-6 min I've got a huge image freeze and visual artifacts certainly caused by packet loss. I've tried everything to avoid this but I don't succeed. Maybe you could help me find the solution.

I've tried h.264 AVC and h.265 HEVC codec : same issue.
I've tried to change the bitrate from 10 Mbps to 100Mbps : same issue.
I've tried to lower the resolution, to increase buffer size even to the maximum : same issue.

My specs are : 
i7 7700k 4.2 Ghz
16 Go Ram
Nvidia GeForce Rtx 2080 Ti
Win 10 64 Bits
My pc is connected by ethernet to the router which is FTTH (optical fiber). I've got a normal Internet speed of 900-950 Mbps.

The Oculus Quest is connected using Wifi 5Ghz to the router.
I've have also tried to change the router position, to put it higher in my room, with no object between it and the quest, to reduce the distance between the router and the quest... nothing has changed. The issue is still there.

When I look in the "Server" tab of ALVR software, I've got some PacketslostTotal and at the line FecPercentage I've got 30% and FecFailureTotal 124 Packets after a 10-15 min of play session.

The weird part is that I can put a 150% resolution with 100 Mbps bitrate and the games are very sharps and smooths. Except every 5-6 min with this huge freeze which last 2 seconds and after that, the game works again normally for 5-6 min then it freezes again and so on.

And it does the same freeze issue with a resolution of 75% and a bitrate of 10 Mpbs. The image is much more blurry and compressed but the issue is still there every 5-6 min.

It reminds me when a computer is searching other Wifi networks around it. Maybe it's the quest which searchs other wifi networks around every 5-6 min and causes these packets loss ?
Is there a way to turn off the wifi search on the quest when it's already connected to one good network ?

Every help'll be very appreciated.
Thanks

**Comment by ischicopter** [comment]
Exact same for me. 

I noticed that sometimes during the freeze, i will get a system Message in the headset. One of the kind you get when it asks you to confirm the Guardian for example, but way too briefly that I could even start reading it before the image restores to normal. It says something about network though.

**Comment by Djneo134** [comment]
No message of this kind for me. Just the freeze for 2 seconds, the visual artifacts and sometimes the sound which makes some crackles.

**Comment by ischicopter** [comment]
The messages only happened yesterday for the first time. But the rest of your description perfectly matches my experience. 
Does it happen on GearVR and Go as well?

**Comment by Djneo134** [comment]
I don't have a Go to be honest. I'll try later on Gear Vr.

**Comment by babybasher** [comment]
> When I look in the "Server" tab of ALVR software, I've got some PacketslostTotal and at the line FecPercentage I've got 30% and FecFailureTotal 124 Packets after a 10-15 min of play session.

I just tested 15 mins of Roborecall (Rift version not quest) at 50Mbps 150% resolution.  No PacketlostTotal with a FecFailureTotal of 1.

My PC specs:
i5 6600k
16 Go Ram
Nvidia GeForce 1070
Win 10 64 Bits
AC2900 router, PC connected via AC1750 wireless (waiting on network cable still).

Could it be your router? Maybe some inbuilt AV software there?  What speeds is your quest connecting at in the router client info? Mines at 866 Mbps.

Off topic.  I have to test more with other games, but Robo recall stutter is pretty brutal.  I set my settings to 10Mbps and 75% resolution but that 'jitter' doesn't go away.  Starting to think an i7 with its extra cores would be helpful.  I'm assuming extra stress is put on the PC to encode/decode right?

Once more off topic.  Anyone noticed the resolution modifier always reverts back to the original '100%' option on ALVR restart?

**Comment by Djneo134** [comment]
@ischicopter: I have tested with the Gear Vr version of ALVR, and it makes the same issue. Every 5-6 min, the image freezes on my Samsung Galaxy s9 causing artifacts for 2 seconds then it returns to normal speed.

The Galaxy S9 is connected in 5Ghz at 585 Mbps and the Quest is connected at 866 Mbps.

@babybasher: You're right, the resolution always reverts back to 100%.

**Comment by ischicopter** [comment]
Ok. 

I have to correct myself regarding the system message pop-up. Apparently it was telling me that tracking was lost instead of network. So it might be a tracking problem that causes the artifacts.

@djneo you should try roborevive it will fix the stutter/judder

**Comment by babybasher** [comment]
> @djneo you should try roborevive it will fix the stutter/judder

Wow, just tried it and you're right.  Fixes it completely.  Will avoid getting any more games from the Oculus store if this is common.  Thank you.

**Comment by sbrierly** [comment]
First couple days with the quest I was getting disconnected from Recroom every 5 minutes or so due to network issues. I resolved it by moving my 5ghz wifi network to a different ssid.  Seems the quest didn't handle it well having the same ssid for both 2.4 and 5ghz.  Perhaps this is related?

**Comment by Djneo134** [comment]
@sbrierly Already tested and no change. My 2.4Ghz and 5Ghz wifis are on different SSID but thanks for your help ;)

**Comment by Muhlawor** [comment]
> First couple days with the quest I was getting disconnected from Recroom every 5 minutes or so due to network issues. I resolved it by moving my 5ghz wifi network to a different ssid. Seems the quest didn't handle it well having the same ssid for both 2.4 and 5ghz. Perhaps this is related?

Yes, noticed that too. 
Changed my SSID for 5Ghz to different one and speed is always 866Mbps.
Does Not fix the issue though.

**Comment by Myhamof** [comment]
Have any of you tried to use weird connection on the pc, maybe your router processor can't handle the amount of packets, also try to use your phone hot spot, idk if your phone hotspot is 5 or 2.4 ghz but your phone have much more processing power then your router so maybe its will work also new android phones have share wifi option on the hot spot menu just remember to charge your phone to prevent your phone from turning off.

**Comment by Djneo134** [comment]
Yeah, I succeeded ! :)

The solution was to create a hotspot on my pc with an old wifi usb key that I have ([TL-WDN3200](https://www.tp-link.com/fr/home-networking/adapter/tl-wdn3200/)).

I create the hotspot using the TP-link software, by using the "Soft Ap" function of this software.
With that, I have a 300 Mbps hotspot in 5Ghz bandwith.
Then I have connected the Oculus Quest to the hotspot created.

And Abracadabra ! The freezes disappeared ! 
I have played 1 hour with very very few amount of packets loss. The artifacts aren't visible when I played.

The freezes must be caused by my web provider router (the french provider Orange). Maybe its wifi chipset is not good enough to stream games with a good quality.

Hope this can help some of you ;)

The last problem which persists are the stutters in the Oculus Rift games with Revive when you move your head. It seems that these stutters are linked to the 72Hz of the Quest. Maybe when a real 60Hz mode'll be released they'll disappear. Fingers crossed !

**Comment by ischicopter** [comment]
Thanks for the tip! I will certainly try that. My router also came from my provider too and might just not be powerful enough.

**Comment by bonsaiheldin** [comment]
At me the image artefacts get worse the longer i have ALVR running, to the point where i can't see anything anymore. And then not even restarting ALVR helps because the streaming seems to be still hapenning in the background somehow.

**Comment by tonair** [comment]
I had the same issue too, but now it is solved.
I decreased the link speed to 400Mbps by using only 20MHz and 40MHz channel bandwidth.

**Comment by polygraphene** [comment]
Possibly caused by DFS?
Try to change channel to W52 (36/40/44/48ch).
If you are using W53 or W56 channels, Wi-Fi stops working when router detect radar signals.
https://www.tp-link.com/us/support/faq/763/

Before change channel, you should check Wi-Fi environment around you to avoid interference.
Try to figure out channel map by [WiFi Analyzer](https://play.google.com/store/apps/details?id=com.farproc.wifi.analyzer) or something else.

**Comment by cosmonaut102** [comment]
I also have a cable modem and have the 5min freeze melting screen artifact problem. I'm thinking that is the problem. I heard it somewhere else too. I think on here somewhere. Any ideas to fix it?
