### ISSUE TITLE
not working in unity testing

### ISSUE THREAD

**Issue by fs9389** [polygraphene/ALVR#379]
Hey, thanks so much for this program, awesome work.
I'm wondering if others have managed getting ALVR with the Oculus Quest working while developing in Unity, or if it's just not possible at the moment. I've tried a couple different versions (2018.3.14f1, 2019.1.4f1) and it's the same. The only thing I can get working is teleport (joystick click, aim, release), no other button inputs seem to be detected (except the Oculus home button, which of course takes me out of ALVR). The 3D models of the controllers reflect the buttons being compressed, the commands just aren't going through, and it doesn't detect when I hold a controller up to an interactable object etc. ALVR is working just fine in other programs. Anything special I could be doing to get this working?

**Comment by carlodelmazo** [comment]
did you got any luck making it work? im also trying to make unity run with oculus quest to avoid building all the time.

**Comment by fs9389** [comment]
Sadly, no. Gave up on it. It seemed to work as intended at random, maybe 1/20 tries, more often if the attempt was the first since I opened Unity. Nothing consistent or reproducible. Would love to hear from anyone who managed though.

**Comment by MyelinsheathXD** [comment]
Hello there! I used STEAM VR unity plugin + ALVR.
And Editor runs in my Quest 2 via WIFI. 😊👌
