### ISSUE TITLE
Can we use the gear VR trackpad for some functions?

### ISSUE THREAD

**Issue by vrokolos** [polygraphene/ALVR#38]
Like you do with the controller?
It's got a trackpad, a back button and a home button.

**Comment by thehurtmaster** [comment]
[ALVR Client.](https://i.imgur.com/SFG8Zic.png) Does the controller work in the Gear VR itself?

**Comment by vrokolos** [comment]
yes

**Comment by thehurtmaster** [comment]
What game did you try the trackpad on?

**Comment by vrokolos** [comment]
I'm sorry but what is it supposed to do? Emulate a gamepad or a mouse?

**Comment by thehurtmaster** [comment]
Emulate the vive controller. Try VRChat and swipe your finger across the trackpad. It should do different gestures

**Comment by thehurtmaster** [comment]
Or Steam Home. Clicking it should allow you to teleport around.

**Comment by vrokolos** [comment]
I get an options screen on server with these:
"Trigger", "Trackpad click" and "Recenter button"
What should I set these up as so that it works on steam home because it didn't work currently?

**Comment by thehurtmaster** [comment]
Set it to what I have it set to.

**Comment by thehurtmaster** [comment]
Also make sure the "controller enabled" is ticked AND make sure just incase that the driver is installed in the "About" section. If you want, add me on steam and it'll be easier for us to talk. TheHurtmaster, should be the only one.

**Comment by vrokolos** [comment]
Thanks I'll try in a couple of hours when I get home!

**Comment by vrokolos** [comment]
Just to clarify I was talking about the onboard trackpad on the goggles. not the controller

**Comment by polygraphene** [comment]
Currently, ALVR only supports the "Controller".
The trackpad on the GearVR goggle is not supported now.

**Comment by Kroktar** [comment]
Controller VR works like charm.

Trackpad click and touch depending on the game.

A dream setup would be usable Volumen, Home/Back Buttons so its similar to HTC... and being able to pair a second Gear VR Controller but maybe thats just crazy :p
