### ISSUE TITLE
ALVR launches Rift, cant detect Quest

### ISSUE THREAD

**Issue by cloudkake** [polygraphene/ALVR#380]
So everything is connected on the ALVR side, sees the quest. When i start the server all it does is launch my oculus rift and detects that in steam vr but the alvr server never moves to 'alive' and the quest isnt doing anything. Anyone have an idea whats causing this? We tried it at my friends and it all worked fine, his connected rift didnt launch, but for some reason mine does.. driving me nuts trying to figure out what it is.

**Comment by Niceman35** [comment]
Rift has higher driver priority in SteamVR. Just disconnect your Rift from USB.

**Comment by cloudkake** [comment]
> Rift has higher driver priority in SteamVR. Just disconnect your Rift from USB.

Thanks for the fast response. Ok did that and now Steam VR says headset not detected. Again, ALVR is connected and working just not talking to steam..

**Comment by cloudkake** [comment]
reinstalled the driver, its working. thanks again

**Comment by Hanappi** [comment]
Thanks from me to, but to unplug the Rift is not an easy thing to me, because the backside of my pc is very uncomfortable to reach.
Is there another way? On the device manager i find only the rift sensors, but not the headset to deactivate. any software solution would be very appreciated.

**Comment by POEDaley** [comment]
You can disable the service so the oculus software doesn't run.  Open CMD with elevated privileges and type - "net start ovrservice"

To restart the service, you can either reboot or type - "net start ovrservice" in the elevated cmd prompt

**Comment by Hanappi** [comment]
That works!
Thank you very much. 8D

BTW: net stop ovrservice to stop, but this was solveable by myself, lol

**Comment by POEDaley** [comment]
oops.. lol, Not sure why I messed that up, but yeah, seemed pretty easy to figure it out.

Glad it worked
