### ISSUE TITLE
Can't get through Steam VR 

### ISSUE THREAD

**Issue by POTATOChrisscar** [polygraphene/ALVR#384]
I've tried everything that other people have suggested here and nothing has worked. I really am on the verge of quitting, can't think of anymore possible solutions. 
![image](https://user-images.githubusercontent.com/34051027/58845884-d2394980-8631-11e9-99cd-d2b5f331e0dd.png) 
![image](https://user-images.githubusercontent.com/34051027/58845898-dcf3de80-8631-11e9-8432-ea2be92e712a.png)
![image](https://user-images.githubusercontent.com/34051027/58845920-f432cc00-8631-11e9-898a-bccdac7121a0.png)

**Comment by jwoodgate** [comment]
I was getting the same issue and then i tried the following:

1) Ran the .bat to deal with the firewall settings provided by the download
2) Added UDP 9934 and 9944 ports to my router
3) UPNP is enabled
4) Private network is enabled
5) Added the launcher to firewall
6) Re-installed it all.

Nothing works - the only thing that makes it work is when I disable the windows firewall. It connects and works instantly. I obviously don't want to do this when I play.

Try to disable the windows firewall and see if that connects, at least then you will know if that is your issue.

**Comment by POTATOChrisscar** [comment]
I already turned off my firewall. It doesn't seem to be the issue either.

**Comment by BorgiaMkUltra** [comment]
I have this exact same issue.

**Comment by zxsdklfhskyrvk** [comment]
Make sure you are only changing your PC's firewall.  Not your routers.  That would be dangerous.

Make sure you've installed the driver on the About tab, and the Android APK on your Quest(?). (you didn't indicate what device you are using)  So follow the install info on that topic.

A random thought on something that could cause software issues is non-ascii characters in your username/folder names.

**Comment by POTATOChrisscar** [comment]
I've gotten it working a few days ago. I can't really describe what I did other than it just randomly started working. Just recently though, it just stopped working? It was working like a charm just 2 days ago now its not even working like it used to.

**Comment by FlamingDuck04** [comment]
I have the same issue. Not sure how to fix.

**Comment by FlamingDuck04** [comment]
Disabling the firewall worked for me
