### ISSUE TITLE
ALVR as a background Service

### ISSUE THREAD

**Issue by jhaleit** [polygraphene/ALVR#385]
Just a suggestion..

It would be awesome to allow ALVR run on startup as a service running in the background. I have a gaming server setup that I use to Stream games and to connect directly without launching the app remotely every time would be a nice feature. :)

**Comment by babybasher** [comment]
I second this.  ATM i have added it to the windows 10 startup, so it's always ready to go.  A user friendly checkbox in the program to do this would be nice.

**Comment by bonsaiheldin** [comment]
This. And it would be also useful to have Autoconnect at startup, not only after connecting for the first time and then activating it.

**Comment by DocMAX** [comment]
Second that!
