### ISSUE TITLE
Distortion with Euro Truck Simulator on Oculus Quest

### ISSUE THREAD

**Issue by umbertomarotta** [polygraphene/ALVR#386]
This seems to be the same issue described here:

[https://forum.scssoft.com/viewtopic.php?t=270083](https://forum.scssoft.com/viewtopic.php?t=270083)

I've seen multiple instances of this issues by oculus rift owners, and they all solved by launching ETS2 with "-oculus" instead of "-openvr", which is needed by ALVR.

I could not get ETS2 to start correctly with "-oculus" and Revive.

So seeing that with Rifcat there is no such problem, I tried to recompile ALVR editing ALVR/ServerConfig.cs at line 117 with something like

`if (false && device != null && device.HasTouchController)`

To make the headset be not recognized as an Oculus Rift, thiking that was the problem, but It didn't work.

I also tried some edits on alvr_server/alvr_server.cpp, but only managed to fuck everything up.

Has anyone else had the same issue?

**Comment by ischicopter** [comment]
Same issue with DCS World which is a „native“ Steam VR game, no revive whatsoever.
No problems with Riftcat in DCS.

**Comment by Niceman35** [comment]
Same problem. ETS2 gives huge distorions.
