### ISSUE TITLE
Swapped and skewed hands on Oculus Quest

### ISSUE THREAD

**Issue by umbertomarotta** [polygraphene/ALVR#387]
I had this issue in [Trials on Tatooine](https://store.steampowered.com/app/381940/Trials_on_Tatooine/)

The controller's pitch is off by around 20°, and it uses the left one instead of right.

Again, no such problem with Rifcat.

Anyone able to replicate this issue?

**Comment by bonsaiheldin** [comment]
I can't exactly replicate the issue, but my controllers are off by a rough 90° which seems to be the same issue. It's like my hands are facing down all the time.
