### ISSUE TITLE
Packet loss only using ethernet on GearVR

### ISSUE THREAD

**Issue by tabletennis666** [polygraphene/ALVR#388]
Hello there

ALVR works great for me through wifi but my router is old and shitty and 2.4ghz so the image is choppy and laggy but it's consistent as hell with almost no packet loss.

I have the S8 though so I thought I'd try it through an ethernet cable after hearing all sorts of good things about it. I bought an adapter which seems to work perfectly, i got the same speed test numbers as I do on my desktop. Using it for ALVR though is impossible, I get huge packet loss and the image is OK when I'm not moving but once I load up a game or move my head a bit, I get crazy visual artifacts that I can barely see through. 

All my settings are at default except I'm on H.264 and for resolution whatever the option just under the recommended one is. I tried to play around with the settings but it didn't help

Any help would be hugely appreciated if anyone else has had the same problem

**Comment by polygraphene** [comment]
I have a similar issue. When I use USB ether adapter on my S8, I could see enormous packet "re-ordering", and which lead to many packet losses.
I don't know actual cause of the problem. Can the bad USB ether chip or the driver be the problem?
I wonder if there is anyone can use ether without problem on ALVR.

**Comment by tabletennis666** [comment]
> 
> 
> I have a similar issue. When I use USB ether adapter on my S8, I could see enormous packet "re-ordering", and which lead to many packet losses.
> I don't know actual cause of the problem. Can the bad USB ether chip or the driver be the problem?
> I wonder if there is anyone can use ether without problem on ALVR.

Thank you so much for the reply. I know very little about computers so I can't really contribute but I did read on reddit that people were having huge success using an ethernet adapter on the S8 with the GearVR which inspired me to try it

**Comment by zxsdklfhskyrvk** [comment]
You could try to find a higher quality cable.  They have categories on them  (CAT5,  CAT5E and CAT6)  You should have a CAT5E or 6 cable.  And if it is all twisted up,  then maybe replace it.
