### ISSUE TITLE
Question regarding Oculus Rift controllers

### ISSUE THREAD

**Issue by nk33** [polygraphene/ALVR#389]
This is all currently working for me using my Xbox gamepad and with games compatable with this.

If i purchase the Rift Cotrollers, will they work so i can play the motion controller supported games (obviously those that work with ALVR)?

Will it assume ALVR is a headset and allow the motion controllers to operate?

**Comment by evertec82** [comment]
No, you need a Rift to use Rift controllers

**Comment by nk33** [comment]
ok - what about if i get vive controllers?

**Comment by evertec82** [comment]
If you get lighthouses also, but at that point you may as well just buy a native headset and not go through ALVR. What headset are you currently using with ALVR?

**Comment by nk33** [comment]
i use a galaxy S8 in a basic headset , this gives me the vr, then i jsut play games which support gamepads at the moment...i really want to get some controllers and see how thatgoes..

what i understand is that alvr basically foools my pc into thinking that my S8 in a normal cardboard headset is actually a vive. if this is the case then why cant i just buy some controllers and the pc will surely think i have the whole kit?

**Comment by evertec82** [comment]
The problem is a galaxy s8 only has 3DOF tracking built in so you really need some way of tracking the headset and controllers. There is a system called Nolo VR that will add tracking and controllers to a gearvr headset like this, but it's still rather expensive ($150-200). I really would just recommend you getting a cheap WMR headset (~$150-200) if you're concerned about money, or the Samsung Odyssey+ ($300) or Oculus Rift S ($400) if you can afford it. You'll get a much better experience than you could ever get with the gearvr.

**Comment by nk33** [comment]
yes - i understand - i guess with all the hassle and money its worth just paying the money and getting the headset, sensors and controllers all in one and also benefiting from the full experience?

**Comment by nk33** [comment]
what package would you recommend as the best value for money per quality which gives me all of above?

**Comment by evertec82** [comment]
It really depends on the price point you're willing to pay. For the low end WMR headsets, you will get everything you need for around $150-200 but the next tier up, Samsung Odyssey+ has a much better picture, and then the Rift S has a nicer ecosystem and controllers. What GPU do you have on your PC? That will let me know if it's worth paying more or not.

**Comment by nk33** [comment]
GTX 980ti

I play all recent games pretty much on max - 2160p res

Can the Samsung Odyssey+ emulate a Vive headset using ALVR and also can i use the motion controllers with it?

**Comment by nk33** [comment]
wow - just checked the price of that odyssey lol...

**Comment by evertec82** [comment]
You don't need ALVR at all when using the Odyssey+. You can play all the vive games and oculus games using Revive. The 980ti is decent and will let you play everything, just not at maximum settings. If you can afford it, I'd recommend it or the Oculus. If you need something cheaper, this Dell will still do the job and only $160 (https://www.ebay.com/itm/Dell-VR118-Visor-VR-Headset-with-Controllers/323821515091?epid=21031290438&hash=item4b65443153%3Ag%3AKmgAAOSwYJVc8E4U&LH_BIN=1)

**Comment by evertec82** [comment]
The Odyssey+ is on sale right now for $299 on Amazon and other retailers though so it's really not a bad deal for the quality boost you get.

**Comment by nk33** [comment]
I'm in the UK - the Dell doesnt seem to be available over here and on Amazon the Oddyssey is like £700 - which is about $800....

**Comment by evertec82** [comment]
Oh wow, well, in that case I'd definitely recommend the Rift S. It's the best package overall in my opinion, and it's 399 pounds

**Comment by evertec82** [comment]
you might also consider the Oculus Quest if you think you'd like more portable VR, since it's also 399 pounds and you can use ALVR with it to play with the controllers without any additional hardware

**Comment by nk33** [comment]
ok - probably the rift s it is...

what do you think of this Acer one? apparantly the sensors for the motion controllers are built into the headset....is this how they are all done now?

https://www.amazon.co.uk/Acer-Reality-Headset-Wireless-Controllers/dp/B0763N26PW/ref=sr_1_1?crid=ZVV5EB6QK3MW&keywords=windows+mixed+reality+headset&qid=1559768994&s=gateway&sprefix=windows+mixed%2Caps%2C154&sr=8-1

**Comment by evertec82** [comment]
The Acer is in the same category as the Dell... on the low end of the WMR headsets. I definitely would only get it if you find it for much cheaper than the Rift S, as it is much worse. Yes, most of the headsets now have the sensors built into the headset.

**Comment by nk33** [comment]
the thing i liked about alvr was that there is no wire connected to the pc - my pc is in the living room - i use it as a media centre and gaming pc and general home server in one. So when i play games i play them on the couch - with xbox one controllers - so a usb cable going all the way from pc to couch is annoying...but i guess if it has to be done...

**Comment by nk33** [comment]
ok - sounds like the rift S it is - 

however is there a way to make this thing wireless? like with a dongle? are the controllers chargeable and how long do they last?

**Comment by nk33** [comment]
thanks so much for your time btw

**Comment by nk33** [comment]
is the rift s better than the oddyssey plus?

**Comment by evertec82** [comment]
Well, like I said you could consider the Oculus Quest as well. The quality will not be as good as the Rift S, and it won't be as smooth running PC games using ALVR, but if you really like the wireless aspect and think you'll like the portable aspect as well for running native games on it, then it's a very good system too. There is no wireless solution for Rift S yet. The controllers use AA batteries but they last a long time. I have both the Rift S and Odyssey+ right now and I would recommend Rift S over Odyssey+... it's a bit sharper, and the controllers and tracking are better. Plus, the Oculus store has some good exclusives and it's better to run those natively rather than going through Revive.

**Comment by nk33** [comment]
ok awesome - does the rift s support all the steam vive games as well or do you have to go through revive for those?

**Comment by evertec82** [comment]
No, it supports all the steam games as well without any third party plugin

**Comment by nk33** [comment]
thats great man! thanks again bud!

**Comment by nk33** [comment]
wow - so turns out this headset is almost impossible to buy right now in the UK.

Not sure whether its because it aint been released or they just sold out all their stock so quick

**Comment by evertec82** [comment]
Looks like you can order it on Amazon.co.uk, but has a ship date of June 17th

**Comment by nk33** [comment]
yep - seems to be its release date...day after fathers day over here lol

**Comment by nk33** [comment]
One more question before I part with my hard earned doe… .

Is the Quest not just a Rift S but.with the added benefit of also working without a pc as well as with a pc? Or does rhe Quest only work as srandalone? 

If the quest works with the PC does it work wirelessly?

**Comment by evertec82** [comment]
The quest is a standalone unit with oled screens instead of lcd and 72hz instead of 80. You can, however use it with alvr if you sideload it on and if you have a fast 5ghz wireless connection. It still won't look or play as well as the native rift s, but if you think you'll utilize the portable aspects of it, it's a good option, especially since it's the same price and you're getting basically a mini console built in as well as the hmd and controllers. I have it as well and still choose my rift s for pc gaming, but I do like being able to take it on trips and play in large outdoor spaces.

**Comment by nk33** [comment]
Thanks mate… great summary. I am gonna have to think about this. I suppose the main question will be "will i VR Game away from my pc… and if so will it be worth sacrificing the better quality when pc vr gaming ?"

**Comment by evertec82** [comment]
Yeah it's a hard choice...I'm not even sure which one I'd pick if I could only have one...I might lean toward the quest though if I had to choose one.

**Comment by nk33** [comment]
yeah - i was thinkin this too - if i get the best of both worlds....

i use 5ghz wifi all over the house. I even use tridef and moonlight to stream some games in 3d to my razer phone and that works pretty well...and combined with trinus i get the head tracking too...

i just need to know how much quality i would lose on PC gaming using alvr with quest instead of rift s - as pc gaming would be the main reason i am making the purchase

**Comment by evertec82** [comment]
With amazon's return policy you could always try it and if it doesn't work as well as you hoped, return and get the rift s

**Comment by nk33** [comment]
i actually found them both on Oculus website - delivery from tomorrow....i will look into their policy...

can you put a percentage on pc quality for each one? - putting the rift s at 100% - what would be the quality of the Quest using alvr on pc compared to it - assuming you had a faultless wireless connection. also assuming ALVR settings were optimised to perfection?

funny how we never look in the obvious places anymore - i went straight to amazon first...

**Comment by evertec82** [comment]
Hmm maybe like 85%?

**Comment by nk33** [comment]
cool

thanks

**Comment by nk33** [comment]
Is sideloading ALVR to the quest easy?

Does ALVR automatically detect the headset AND the controllers essentially fooling your pc into thinking you have a Rift S?

So basically what i am buying with the quest is a galaxy S8 (same processor) in a proper headset with motion tracking and 2 controllers?

I read that the Rift S has an extra sensor which makes the motion tracking on games much better also?

Oh man this is a difficult choice goddamit…

**Comment by evertec82** [comment]
Yes, once you sign up as a dev you just download an app called side quest which makes it drag and drop to install apps like alvr. The rift s does have an extra camera but I haven't found it to make a huge difference in practice.

**Comment by nk33** [comment]
Finding one of these Oculus Quests in the UK is actually turning into a Quest!!

**Comment by nk33** [comment]
Ok - ive pre-ordered the quest.....gonna have to wait a while..

While i am waiting can anyone help me with a simple guide to get ALVR working on the quest - with download links and what to do all in order start to finish?

**Comment by nk33** [comment]
I just wanted to say thanks to everyone for all theadvice given here. I have had the quest for a few days now and have managed to sideload ALVR very easily and use it to play PC games. I also managed to sideload APKs.

One question - when i use ALVR to play the PC version of Creed it thinks i have Vive controller, tells me to press the trackpad and move my arms up and down to walk forward - but this doesnt work....i have to move as far back as i can in the room, reset the screen, then i can walk forward to touch gloves...is there somewhere i can configure this?

**Comment by nk33** [comment]
> 
> 
> yeah - i was thinkin this too - if i get the best of both worlds....
> 
> i use 5ghz wifi all over the house. I even use tridef and moonlight to stream some games in 3d to my razer phone and that works pretty well...and combined with trinus i get the head tracking too...
> 
> i just need to know how much quality i would lose on PC gaming using alvr with quest instead of rift s - as pc gaming would be the main reason i am making the purchase

does anyone know how i can play games turned into SBS using tridef on my quest without getting split screen?

ATM if i use moonlight to stream tridef SBS games to the headset, it doesnt send one to one eye and the other to the other eye - it simply shows them SBS.

I understand why this is happening i was just wondering how i could change it?

**Comment by evertec82** [comment]
You can use virtual desktop or bigscreen to turn the sbs into a usable screen. Or, use vorpx without tridef at all

**Comment by nk33** [comment]
> 
> 
> You can use virtual desktop or bigscreen to turn the sbs into a usable screen. Or, use vorpx without tridef at all

ok - so when i install bigscreen on steam on my PC it tells me that i need to have a rift/vive headset - does this mean i can only use it from within ALVR?

you see the quest has its own "bigscreen" app - how would i use this app?

**Comment by evertec82** [comment]
I don't think bigscreen on the quest has added desktop streaming yet but last I heard it was a planned feature. So you'd either have to use virtual desktop native on the quest or bigscreen through alvr. I'd recommend getting virtual desktop anyway since it works better than alvr in a lot of games and streams the mic

**Comment by nk33** [comment]
thanks - though i found these instructions on google

    Launch Steam on your PC.
    Right-click Bigscreen Beta in your Steam library.
    Click Play Remote Desktop streaming client. ...
    Launch Bigscreen Beta on your Oculus Go.
    Select an environment in which you'd like to stream your desktop.
    Select Remote Desktop from the Tools section in the menu.
    Select Start.

it works - thanks so much

**Comment by nk33** [comment]
another thing - i noticed that whenever i connect a bluetooth controller to my Quest - ALVR always crashes as soon as i start it....is there a fix for this?
