### ISSUE TITLE
Sometimes I get stuck in a SteamVR overlay and I can't get out!

### ISSUE THREAD

**Issue by Thaurin** [polygraphene/ALVR#39]
It has happened a few times before: there is an interface overlay over my game and I can't control it. I have no idea how it got activated, but it is probably part of SteamVR. I can't exit it and I can't control it. It looks useful, though.

Making this issue to collect information on this issue and maybe find out what is causing it and find a solution.

**Comment by Kroktar** [comment]
Hi, i had this problem with riftcat a while ago.

Dashboard opens and gamepad does nothing.

The solution i found it was to add this parameter to SteamVR(In steam games)

-nodashboard

**Comment by Thaurin** [comment]
That sufficient of a solution for me. I don't know why the dashboard pops up, but I guess it needs controllers and therefore can't be compatible with ALVR. Closing this issue.

**Comment by polygraphene** [comment]
I think dashboard can be open/closed by "System" button.
I don't know why dashboard opens, but as an alternative way we may be able to close by assigning "System" to the trigger of controller and then click the trigger.

**Comment by Thaurin** [comment]
It would be awesome in general if we could control more of SteamVR Home. If we could launch games from VR, it would make everything even better! But I don't know if that'll be possible with a Go/GearVR controller.

Another thing that I don't understand is how some games say they support gamepad and yet my gamepad does nothing, while other games will work. In fact, SteamVR Home says to "press the (Y) button to begin" yet my gamepad does nothing.

Is that something that ALVR could work around? Not having a Vive or Rift, I have little knowledge about how they work.

**Comment by mikochu** [comment]
For sit-down experiences, I'd recommend disabling the dashboard in the
SteamVR settings (under Developer?).
