### ISSUE TITLE
The Oculus driver causes vive wireless not to work.

### ISSUE THREAD

**Issue by Volman13n0** [polygraphene/ALVR#390]
I want to use my gaming pc for ALVR on my oculus quest. For reference i have this up and running on my everyday pc. But on my gaming pc when i get it running then want to go back to using my og vive with wireless adapter it goes through process evrything seems fine then no pic in headset. I uninstall alvr including oculus driver then it works again.

**Comment by polygraphene** [comment]
I have written the code to avoid conflict with other drivers, but maybe it was not sufficient.
You can try "Uninstall driver" on About tab and then close ALVR to completely avoid conflict.

The log of vrserver will show some clues about the issue.
You can check it in `C:\Program Files (x86)\Steam\logs\vrserver.txt`

**Comment by slydog43** [comment]
I know its not exactly the same thing, but I stop the oculus service with Oculus Tray Tool  before each use of ALVR since I also use the PC with a Rift-S.  Polygraphene, do you mean I don't have to do this in order to run ALVR?
