### ISSUE TITLE
Microsoft Visual C++ library runtime error after connecting with GearVR

### ISSUE THREAD

**Issue by valde1992** [polygraphene/ALVR#391]
After clicking "Connect" in the ALVR Server (stable version) with my Samsung S10 in the ALVR client, Steam opens and so SteamVR. Then this "Microsoft Visual C++ library runtime error" shows up and says "program:            ". I have a Nvidia GTX 980.

Thanks in advance, regards.

**Comment by polygraphene** [comment]
Is the issue crash of steamvr?
Can you provide debug log of driver with this instruction?
https://github.com/polygraphene/ALVR/wiki/Debugging#how-to-enable-server-driver-log-output
