### ISSUE TITLE
Oculus Quest hands not working on steam

### ISSUE THREAD

**Issue by AlexLunaGarvin** [polygraphene/ALVR#392]
Well, I'm developing a videogame for the oculus quest, and I had 0 problems working on the engine, but once I try to play SuperHot on steam, it does not recognize my hands, and I can see them behind me not moving at all.

**Comment by polygraphene** [comment]
Can you play other games on steam?

**Comment by AlexLunaGarvin** [comment]
> Can you play other games on steam?

SuperHot is the only Steam VR game I own that has hands controllers, the others just use the head or the head + keyboard.

**Comment by firatsertgoz** [comment]
SUPERHOT has this issue with me too, the hands are on the floor, detached from the controllers  so I cannot interact with anything.

**Comment by buttercheetah** [comment]
same problem here, nothing i try fixes the problem

**Comment by Andrew1431** [comment]
Any luck you guys? My hands seem to spawn on the ground, I've not found any solution via google.
