### ISSUE TITLE
Resolution is always reset to 100%

### ISSUE THREAD

**Issue by xiisbk** [polygraphene/ALVR#394]
When I change the resolution on the server side to s.th. different from 100% ("Video" tab) , it is always reset to 100% when I restart ALVR or reboot the server. All other setting changes (e.g. encoding bandwith or encoder) are preserved when I reboot. Is this intended behavior or a bug?

**Comment by polygraphene** [comment]
It is a bug. I will fix it.

**Comment by xiisbk** [comment]
I think I have a fix for that, but cannot test it (I have no working VS 2015 environment). Shall I still send a pull request?

**Comment by polygraphene** [comment]
Thank you. But I could fix that.
The fix will be included in next release.

**Comment by DannyDan** [comment]
@polygraphene 
awsome!

**Comment by DannyDan** [comment]
any news about this fix?

**Comment by USER-TRASH** [comment]
> When I change the resolution on the server side to s.th. different from 100% ("Video" tab) , it is always reset to 100% when I restart ALVR or reboot the server. All other setting changes (e.g. encoding bandwith or encoder) are preserved when I reboot. Is this intended behavior or a bug?

hey man. iguess it was never fixed but thx anyways. Have anyone of you guys figured it out yet. Please leave a link (if any for solution) below. Thanks man.

**Comment by USER-TRASH** [comment]
> Thank you. But I could fix that.
> The fix will be included in next release.
we r missing u
