### ISSUE TITLE
DCS World w. Oculus Quest: ALVR does not work with Alpha 5, but OK with Alpha 4

### ISSUE THREAD

**Issue by ScubyFlying** [polygraphene/ALVR#395]
For DCS World simulator & Oculus Quest:

If ALVR Alpha5 is used, and when DCS.exe is started, it appears that SteamVR does not push any image to the VR headset. The result is that the PC monitor shows the default DCS menu and the headset "hangs" on the SteamVR loading window. 

If ALVR Alpha4 is used, everything seems to work OK.

**Comment by rgferreira** [comment]
You are right about DCS loading on Alpha 4 and not on Alpha 5 on my Quest.
My problem is, I uninstalled Alpha 5 and reinstalled Alpha 4 and now ALVR forces Steam VR to think I am using Vive controllers, overriding any settings of my own pointing out Oculus touch. Any help on this? Thanks

**Comment by ScubyFlying** [comment]
Yes. This happens because of a recent Oculus Quest firmware update. The fix is simple, only it is based on alpha5.apk, which means if you choose the fixed apk you'll get the correct controllers again but DCS will still not work. Alpha 4 is not an option either because the controllers remain screwed.

I have chosen the fixed alpha5.apk and accepted that DCS will not work with the Quest, for now.

Get your fixed .apk here: 
https://github.com/polygraphene/ALVR/issues/491

Or here:
https://github.com/polygraphene/ALVR/issues/479
