### ISSUE TITLE
DCS World w. Oculus Quest: VR image distortion / warping

### ISSUE THREAD

**Issue by ScubyFlying** [polygraphene/ALVR#396]
For DCS World simulator & Oculus Quest:

If Alpha 3 to 5 are used, it appears that all image (menu and cockpit/flight) in the VR headset is being distorted / warped. 

Earlier Alpha (<3) are not tested. 

Seems related to issue #386.

**Comment by ischicopter** [comment]
Same here. Doesnt happen with Riftcat, so must be related to ALVR
