### ISSUE TITLE
Extreme jitterness in alpha 5 and Quest

### ISSUE THREAD

**Issue by compubrain3000** [polygraphene/ALVR#397]
I am getting extreme jitterness in the headset movement and severe controller lag with Oculus Quest and alpha 5. Alpha 4 works very well except for the controllers being tilted downwards.

**Comment by zxsdklfhskyrvk** [comment]
I'm seeing "jitter" or "stuttering" in both a4 and a5 versions of a similar amount, when I play The Climb. For me, it almost seems to calm down after a bit but never disappears.

@compubrain3000 Are you using wifi for your PC connection?  Ideally the PC should be using cabled connection to reduce the wifi overhead.

**Comment by compubrain3000** [comment]
@zxsdklfhskyrvk I am actually using a cloud machine. Alpha 4 has no noticeable lag or jitterness, it's almost perfect if not for the tilted controllers. Alpha 5 has lots of jitterness in the headset movement as well as severe controller lag, it's basically unplayable.

**Comment by morgano86** [comment]
> @zxsdklfhskyrvk I am actually using a cloud machine. Alpha 4 has no noticeable lag or jitterness, it's almost perfect if not for the tilted controllers. Alpha 5 has lots of jitterness in the headset movement as well as severe controller lag, it's basically unplayable.

Cloud machine, hmmm, i hadn't even thought about doing something like that. Granted i don't have a Quest yet and the latency is going to be inside that's a great application of ALVR.

**Comment by donaldjosephsmith** [comment]
For what it's worth, I wasn't seeing any jitter in my Quest headset movement with alpha 5. Controller tracking was more inconsistent movement speed than jitter. (I plan to open an issue once I have a better characterization of it.) I do have the controller orientation tilted downward, but I assume that issue is elsewhere.

**Comment by ischicopter** [comment]
Feels more like the dev took out some kind of filter that used to smoothen the "natural jitteriness" of one´s hands. Like it is forwarding the raw input from the controllers. 
Best thing would be a slider in the controller-tab to adjust for personal preference.
 
Until that happens: Drink less coffee

**Comment by SecretHippo1** [comment]
@compubrain3000 May I ask how you went about your cloud machine setup? I've put my network on express VPN with a dedicated router up front, but I'm struggling to get my parsec machine on the same :/

**Comment by compubrain3000** [comment]
@SecretHippo1 Just use this guide.

https://github.com/polygraphene/ALVR/wiki/Setting-up-ALVR-for-VR-Cloud-Gaming-(no-Gaming-PC-required)
