### ISSUE TITLE
hardcoded steam vr paths on the drivers installer bat file

### ISSUE THREAD

**Issue by penkamaster** [polygraphene/ALVR#4]
The bat files that install and unistall the drivers (driver_install.bat and driver_uninstall) are pointing to C: \ Program Files (x86) \ Steam \ steamapps \ common \ SteamVR \ bin \ win32 \ vrpathreg.exe, so if steamvr is installed in another site, the driver will not be installed.

**Comment by polygraphene** [comment]
That's right.
We should get path of SteamVR from registry.
Latest release automatically installs the driver when pressing "Start Server".
(Refer: https://github.com/polygraphene/ALVR/blob/master/ALVR/DriverInstaller.cs)
And I'm planing to implement driver installation/uninstallation on GUI.
