### ISSUE TITLE
[1.9.2]Wrong Version

### ISSUE THREAD

**Issue by Kroktar** [polygraphene/ALVR#40]
Hi, First time here.

I tried 1.9.1 on the week and it worked without issues on my S9+
But i noticed there is a new version today but i cant seem to update it properly.

My APK signed it says:

"ALVR Client 1.9.2
Press connect button on ALVR Server.

But on my computer ALVR says i have wrong version
https://imgur.com/a/RSqdd1C

But in "ABOUT" it displays i have 1.9.2 server version.

https://imgur.com/a/OJlxTU1

Thanks.

**Comment by Tux0Topo** [comment]
Just a silly question... did you try to uninstal and reinstall a fresh copy of the client?
Also, before uninstall, go to the app manager and reset all data of the app...
Maybe some file get stuck there and thats the problem.

**Comment by Kroktar** [comment]
its not silly.

That was my first tought because i override 1.9.2 over 1.9.1...when i notice it failed i uninstalled 1.9.2 so i could reinstall it properly.

Ill try to reset all data

**Comment by Kroktar** [comment]
That didnt solved it but i managed to get another "solution"

I already had the "driver" installed from 1.9.1... i uninstalled it and installed it from a fresh 1.9.2 download.

But i have a new issue... Now my Gear VR is displayed as connected
https://imgur.com/a/1jC5kLX

But Gear VR still displays "Press connect on ALVR Server"
And SteamVR says the HMD is not visible to the motion cameras.

**Comment by Kroktar** [comment]
I managed to get it working after changing wifi.

Thanks.

**Comment by 77Mynameislol77** [comment]
i have the same phone and the same problem, changing wifi is not an option.
