### ISSUE TITLE
ALVR doesn't detect headset if PC has two wifi connections (bug?)

### ISSUE THREAD

**Issue by banchan86** [polygraphene/ALVR#400]
Im using GearVR with mobile hotspot on PC, but I ran into an issue that i had to workaround.

Config 1 - PC and GearVR to home WIFI - ALVR detects headset but slow connection
Config 2- PC to home WIFI, shares mobile hotspot to GearVR - ALVR doesn't detect headset
Config 3- PC to home WIFI, shares mobile hotspot to GearVR, **disconnects from home WIFI** - ALVR detects headset fast connection

Since its able to detect the headset in config 1 and 3, that leads me to think its not a problem with a firewall. Under config 2 I was able to surf the internet as well as ping the GearVR so I dont think its a problem with opening 2 wifi connections. Rather I think ALVR is having issues with detecting the headset if the PC has two wifi connections. Maybe its searching through the wrong wifi. Is this a possible bug that can be fixed?

Also a potential workaround could be to allow users to manually input the IP address. While the current workaround "works" it makes it impossible to use any internet enabled apps like Rec Room.

**Comment by polygraphene** [comment]
Maybe a bug, but I couldn't reproduce the issue.
Did you restart the SteamVR after enabling/disabling mobile hotspot?

**Comment by banchan86** [comment]
restarting the SteamVR did the trick! sorry for that!
