### ISSUE TITLE
Virtual Desktop

### ISSUE THREAD

**Issue by ghost** [polygraphene/ALVR#402]
Just a random crash occurrence when testing Virtual Desktop this afternoon.

https://youtu.be/pNdaGHau4kA?t=66

Just sayin'...

**Comment by machenmusik** [comment]
The VD developer notes that ALVR driver crashes if loaded and unloaded without being used (i.e. if ALVR is also installed, but VD is used instead)

**Comment by polygraphene** [comment]
I want to see crash log.

**Comment by iamliamiam** [comment]
Hi, it's happened three times did an 'Everything' search for alvr log and found three logs so will pop them on pastebin for you.  Suffice to say I wasn't running ALVR while testing VD these past few days.

https://pastebin.com/2hQ6dnLt
https://pastebin.com/eCQW260K
https://pastebin.com/10N18sTQ

It was my assumption that Virtual Desktop may have been borrowing parts of ALVR but I'd love to be proved wrong.  I am in contact with the developer on Discord so could just ask him there.

**Comment by iamliamiam** [comment]
Okay so ggodin says:

> There’s a bug in ALVR where it will crash if their driver gets loaded but doesn’t get used

In which case I am wrong to assume that VD has any ALVR code in it, apologies for any lines crossed there.  Is there a way to fix it polygraphene? as for now I will uninstall ALVR at least until an update.

**Comment by iamliamiam** [comment]
Virtual Desktop have had it's VR features stripped by Oculus!
Sign/comment here to protest:

https://oculus.uservoice.com/forums/921937-oculus-quest/suggestions/37885843-virtual-desktop-with-steam-vr-support

**Comment by polygraphene** [comment]
Thank you for crash log! I will try to fix.
Probably it is completely my fault. I feel sorry for devs of VD.

>Virtual Desktop have had it's VR features stripped by Oculus!
Sign/comment here to protest:

That's too bad. I was hoping that Oculus has changed their opinion since they reject my app on Go/GearVR. But it was disappointing.
