### ISSUE TITLE
floor level not right on alpha5 quest

### ISSUE THREAD

**Issue by falcoriss** [polygraphene/ALVR#404]
Context : oculus quest
Version : Alpha5

Heya

I can't seem to have the floor level set right in steamVR and its games. It's like i'm sitting while actually standing. I'm sure there's a way to set that somewhere but can't figure out where

Great job on the software, it works mostly great !

**Comment by POEDaley** [comment]
I would highly recommend using SteamVR Advanced Settings.  There is a floor fix option in there that works great with the quest.  I use it everytime.

**Comment by machenmusik** [comment]
I found that by doing standing Room Setup with correct height (don't put headset on ground and do 0 as that doesn't seem to stick?) it was still basically correct the next time, maybe that will help

**Comment by iamliamiam** [comment]
Use this and go to the floor fix settings, super easy and works (I've used it too).

https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/releases/tag/v3.1.0

**Comment by Yoshidk** [comment]
As my computer and "play room" is not on the same level, I find it hard to do the SteamVR setting as you need to follow the steps on the PC. Is there another way to do this?

**Comment by falcoriss** [comment]
Advanced settings floor fix nailed it

**Comment by Myhamof** [comment]
I don't remember the exact tab but on one of them there is an x y z thing that you can change, in my case i was on the floor level and not in the circle so i change the y from 0 to 1.8 (change it until you feel like you the right high) and the z to 1.5 (you may be in another place so just play with the xyz until you in the circle in the right high)

**Comment by Yoshidk** [comment]
> I don't remember the exact tab but on one of them there is an x y z thing that you can change, in my case i was on the floor level and not in the circle so i change the y from 0 to 1.8 (change it until you feel like you the right high) and the z to 1.5 (you may be in another place so just play with the xyz until you in the circle in the right high)

Yea, but I live in a contry where we use comma as decimater, so my PC does as well, so when I enter "1.8" in ALVR it changes automatically to "1,8", which only raise me "1 meter", when I then switch tab and return, it changes to "18", which sends me to the skies.

This is created as an issue a long time ago, but it was never fixed, making this function useless to me

**Comment by POEDaley** [comment]
@Yoshidk In Steam VR Advanced Settings you go to room adjustment (I'm pretty sure), then floor fix.  You don't enter in any number.  You place a controller on the floor, then click on floor fix.  It will set the floor to where your lowest controller is.  Just make sure before you click on fix floor that you take a good step back so when you click the button, the cameras on the quest can still see the controller on the floor.  You may have to do each session, but it takes only a second to do.

**Comment by Yoshidk** [comment]
> @Yoshidk In Steam VR Advanced Settings you go to room adjustment (I'm pretty sure), then floor fix. You don't enter in any number. You place a controller on the floor, then click on floor fix. It will set the floor to where your lowest controller is. Just make sure before you click on fix floor that you take a good step back so when you click the button, the cameras on the quest can still see the controller on the floor. You may have to do each session, but it takes only a second to do.

Ok, I will have to try this. Is this "fix floor" button available after starting the SteamVR through ALVR from within the headset? Or would I still have to click somewhere on the PC?

**Comment by POEDaley** [comment]
All done within the headset.  Open steamvr menu, then you should see advaned settings at the bottom.

**Comment by zxsdklfhskyrvk** [comment]
> 
> 
> Advanced settings floor fix nailed it

Close the issue here please,  if you are all set.
