### ISSUE TITLE
Steam VR and ALVR server crashing after starting server 

### ISSUE THREAD

**Issue by BlaxHazHax** [polygraphene/ALVR#406]
I have tried changing the video codec, going back to previous versions of ALVR, disabling steam sound uninstalling the driver and reinstalling. i am also using a 5ghz wifi connection.
![Capture](https://user-images.githubusercontent.com/51140038/59308750-cbcd5200-8c6f-11e9-9f67-13af0d354092.PNG)

**Comment by BlaxHazHax** [comment]
Intel(R) HD Graphics 620

**Comment by crazysword1** [comment]
Both your gpus don't meet the min specs to play a vr game. You need to get a better computer (gpu).
