### ISSUE TITLE
Model Clipping in Autodesk VRED

### ISSUE THREAD

**Issue by S005J** [polygraphene/ALVR#407]
So I'm using my Quest and ALVR to view my 3D models in Vred. It works really well btw. Good Job!!
My issue. I'm seeing some clipping of the model when I get close to it in the scene. I can also notice this happening to the scene in my periphery. Any ideas what causes this?
Also is there a way to change the button programming on the touch controllers? I'd like to access the VR menu in Vred but it is mapped to the Menu button on the Rift and Vive. Thanks

![clipping](https://user-images.githubusercontent.com/51731639/59322312-72bee780-8c8a-11e9-9b2a-f348f8d7d12a.jpg)

**Comment by polygraphene** [comment]
Perhaps it is caused by settings of the application. Can you find configuration like "near clipping distance"?

**Comment by S005J** [comment]
Hmm, I haven't seen a setting for that. I use the same file and setup with my Rift and have never noticed anything like this.. With my rift setup I'd have to put my head right through the Geometry to get a similar affect. I'll dig around and see if I can come up with anything.
On another note the same thing happened when I tried it with Virtual Desktop VR streaming function.. Thanks for your help..
