### ISSUE TITLE
I think ALVR has a memory leak

### ISSUE THREAD

**Issue by alansandbucket** [polygraphene/ALVR#409]
Hey,
i was playing ALVR for about an hour and a half (everything was fine) and my computer suddenly crashed due to running out of memory. sounds like a memory leak. If it happens again i'll give you more detailed information.
Thanks so much for the project, im gonna be using it alot :)
Alan

**Comment by polygraphene** [comment]
Thank you for reporting. Debugging is difficult only by the information.
Could you see memory usage of vrserver.exe or ALVR.exe is raised?

**Comment by alansandbucket** [comment]
yeah i'm planning on playing some minecraft tonight. i'll report the amount of memory used by it when done.

**Comment by alansandbucket** [comment]
just played minecraft for half an hour and ALVR looks fine. using like 13 mb. It may have been vivecraft that caused me to run out of memory. I had alotted up to 8 gigs for it so that could have been it. Again thanks for the project!
