### ISSUE TITLE
Offset for vive controllers

### ISSUE THREAD

**Issue by penkamaster** [polygraphene/ALVR#41]
Im using vive controllers with ALVR using "activateMultipleDrivers" on steamvr.vrsettings

I can see the controllers but they are displaced form my playing space but sending a "debug pos" of 0, -1.2, -1.6 in ALVR server's debug tab gets the offset to bring them to my game space.
I also compensate with "OpenVr advanced settings" the position of my playspace to compensate the  "debug pos" 

do you think that you can send these values as default?

**Comment by polygraphene** [comment]
Thank you for a comment.

I can implement to save "debug pos" on some config file for re-launch of ALVR.exe.
Is it sufficient for your situation?

**Comment by penkamaster** [comment]
Yes, I think that will be enough.

Thank you.

2018-06-11 14:07 GMT+02:00 polygraphene <notifications@github.com>:

**Comment by penkamaster** [comment]
I see this implemented on 2.0

Many thanks.
