### ISSUE TITLE
Oculus Quest Packet Loss?

### ISSUE THREAD

**Issue by hatterthethird** [polygraphene/ALVR#410]
I wanted to try running SteamVR for the first time on the Quest when I encountered an issue with SteamVR not detecting my headset. After a quick glance through the forums to no avail, I took another look at the ALVR application tab when I noticed what might be the issue

![image](https://user-images.githubusercontent.com/51773021/59404052-f98ec580-8d59-11e9-810b-03c80e463003.png)

how do I fix this?

edit: pardon me while I undoxx myself

**Comment by suTrust** [comment]
+1. I am having an identical issue.
Quest is on the same network as the desktop.
-Quest is wireless, Desktop is Ethernet.
Firewall permissions have been applied to desktop.
Router has no (apparent) rules blocking access between wireless and wired LAN.

Steam VR is hung up in setup. In the 'Establish Tracking' section, I have an error message reading 'Headset Not Visible'

I have a Charter/Spectrum 5Ghz Router.

**Comment by Myhamof** [comment]
Did you tried running ALVR on another internet, if you don't have any you can try using your phone hotspot, if this is working the problem is your internet connection, maybe your router can't handle streaming on lan.

**Comment by babybasher** [comment]
Try disable your firewall and antivirus completely to see if that makes any difference.
