### ISSUE TITLE
Tips to debug

### ISSUE THREAD

**Issue by GregGodin** [polygraphene/ALVR#415]
Hi,

I'm able to build. But I'm struggling to run the modified version of alvr_server in steamVr.
What is the process?

Thanks,
Greg.

**Comment by polygraphene** [comment]
Have you successfully built driver_alvr_server.dll? If so, then you copy it to driver\bin\win64, and run driver\driver_install.bat.
You can get help by driver.log and vrserver.txt log files.
See: https://github.com/polygraphene/ALVR/wiki/Debugging

**Comment by GregGodin** [comment]
Ok i figured out what i was missing.  I had the following error : "Cannot load library. ALVR works only on 64bits Windows with NVIDIA GPU.".

Using dependency walker, I found out it was due to a dependency to avutil-56.dll and swresample-3.dll
I add those to path and it worked.

Thanks !
