### ISSUE TITLE
What's the difference between HEVC and AVC?

### ISSUE THREAD

**Issue by GandalfTheGreen101** [polygraphene/ALVR#417]
Does one setting make the picture look better?
or is one less powerful than the other?
which one is recommended for better performance or different settings?

**Comment by GandalfTheGreen101** [comment]
I've also been having an issue where if I start the server with Steam sound on it crashes, therefore i can only play with it off.

**Comment by polygraphene** [comment]
H.265 HEVC has better quality than H.264 AVC.

Try to change sound settings to 48kHz/16bit/stereo.
