### ISSUE TITLE
HTC Vive support

### ISSUE THREAD

**Issue by KoolenDasheppi** [polygraphene/ALVR#418]
I know this is probably out of scope of this project, but would it be possible to add HTC Vive support? I need a way to use my Vive on my cloud PC I have (a Shadow PC). Unless someone has an alternative software?

**Comment by PaletteHD** [comment]
This would be useless because it simulates a HTC Vive

**Comment by kool601** [comment]
It's not useless because if you would've read the issue contents, I need a way to use my HTC Vive on a remote computer. This software has cloud gaming support in the wiki.

**Comment by polygraphene** [comment]
That's interesting. But as you said, it is out of scope. I've never heard of a software like it.

We can use ALVR server as-is. But for client, we should port current android client over to Windows openvr application.
That's large task.

I have no plan to do it. If anyone is interested in the porting, I can help.

**Comment by kool601** [comment]
If I had the knowledge I'd attempt it. I might be able to look into something that is a compatibility layer that lets you run Oculus Quest games on the Vive, that'd probably work. Maybe.

**Comment by SrzGitHub** [comment]
> 如果我知道我会尝试它。我可以查看一些兼容性层，让你在Vive上运行Oculus Quest游戏，这可能有用。也许。

请问您那边有适配VIVE FOCUS吗？
