### ISSUE TITLE
4 000 000+ latency

### ISSUE THREAD

**Issue by apkfr** [polygraphene/ALVR#419]
Hello !

I've went through the  installation of ALVR 2.4.0 alpha4 but when I connect to a server I got a very high latency.

My PC is connected to the router with an ethernet cable.
My Oculus Quest is connected to a 5Ghz wifi

My wifi may not be the best on earth but i don't think it would explain such a high latency.

Would have someone faced a same situation ? Any help would be appreciated

![image](https://user-images.githubusercontent.com/51848338/59548666-ded37100-8f52-11e9-9fe4-9f29068c9180.png)

Bests,

**Comment by polygraphene** [comment]
There are a lot of packet losses.
Please check signal quality and link speed on Wi-Fi settings.

**Comment by Myhamof** [comment]
Try to use your mobile phone hotspot to check if its your router or other problem

**Comment by apkfr** [comment]
Hello,

I've got a good signal, with a debit ranging from 130 mb/s to  340 mb/s. Is it too low ?

Ok i'll try with my phone good idea

**Comment by apkfr** [comment]
IT is still high latency using my phone (only 2.4 hgz). Excellent signal but slower debit 72mb/s

![image](https://user-images.githubusercontent.com/51848338/59549915-e1d75d00-8f64-11e9-860d-14e26def5749.png)

**Comment by apkfr** [comment]
Hey,

I turned my computer into a wifi hotpost ( I didn't even know I had this feature ) and it works !

Thank you ofr your support !

![image](https://user-images.githubusercontent.com/51848338/59550144-befa7800-8f67-11e9-805d-f21a9c37c935.png)

**Comment by polygraphene** [comment]
130 mb/s to 340 mb/s was not good. Maximum supported speed is 866Mbps on Quest.
Your Wi-Fi environment may be crowded with other routers. Changing channel may help you.

Anyway, I'm glad the problem was solved.
