### ISSUE TITLE
ALVR client crashes on startup

### ISSUE THREAD

**Issue by newuser1a** [polygraphene/ALVR#420]
Client just crashes on start up.  Tried 3 different version.  One being the latest alpha version.  Then tried the 2.30 AR Core and Normal version.  All the same.  Crashes on startup.

Also Avast anti virus said there were some security warnings when installing the alpha release.
Window defender gaved a warning on the ALVR version (both the latest alpha and the 2.31 version).

Does it matter what phone I am using?  I am using an LG phone.  It has sd845 so should be able to run it without problems.

**Comment by POEDaley** [comment]
What GPU/CPU does your computer have?
