### ISSUE TITLE
Blurry Image and packet loss in every moment (GEAR VR w/ S7)

### ISSUE THREAD

**Issue by fran49** [polygraphene/ALVR#422]
Sup everybody, I've been having this problem since yesterday. I used to use alvr with no problems. Yesterday I tried to play and I wasn't able. When I move my head, the image keeps static and after 2-3 secs it loads. I'm connected to a 5 ghz wifi, so I don't know what is happening.
Please help!
Thank you

**Comment by Myhamof** [comment]
Did you tried to restart your router/computer/phone? If it worked fine before i believe restart will help

**Comment by zxsdklfhskyrvk** [comment]
You need to remain pretty close to your router.  But I've seen issues like this in the past few days.  Not sure what else could cause it.  Maybe the "full restart" is the simplest fix.

**Comment by fran49** [comment]
Hey guys,
I tried restarting everything but the problem is still here.
In addition, i'm really close to the router, about 1-1.5 meters

**Comment by Myhamof** [comment]
Have you tried an older version, i don't really sure if it's work but it worth trying.

**Comment by fran49** [comment]
I tried with an older version but in those I can't start the server. It keeps in finding headset
