### ISSUE TITLE
alpha 5 stopped functioning on quest

### ISSUE THREAD

**Issue by pitu64** [polygraphene/ALVR#427]

**Comment by zxsdklfhskyrvk** [comment]
I used it in the last 5 hours.  So it is no ALVR's issue.  Maybe try reinstalling it, as well as the Windows software.

**Comment by pitu64** [comment]
Ok thanks for the reply I will try again
I will let you know

**Comment by pitu64** [comment]
ok reinstalled now working
i don't know what happened
thanks for you help
steve

TCB FAMILY TRUST AS TRUSTEESS FOR TCB GEELONG PTY LTD      ABN 51 875 172
601

**Comment by POEDaley** [comment]
If your issue is solved, please close the issue
