### ISSUE TITLE
Oculus Quest controller at wrong angle (pitch) + button mapping

### ISSUE THREAD

**Issue by Swirklich** [polygraphene/ALVR#432]
I've noticed that in all VR games on Steam the controllers seem to be at a really awkward bent angle. Is this fixable in the next release or am I simply missing something?

Also, Steam has the Oculus Legacy Layout selected, but for some reason most of the button layout seems to be off. Would I have to remap the controllers for every game?

**Comment by sen7inel** [comment]
I've noticed the same controller angle issue (maybe 20-25 degrees too low in games like COMPOUND), hopefully can be made adjustable at some point?

**Comment by BlaxHazHax** [comment]
Yeah its super annoying hopefully alpha 6 will fix this

**Comment by alansandbucket** [comment]
same problem

**Comment by eddybaronnet** [comment]
Same issue for me. Too bad because ALVR runs very well otherwise...

**Comment by CaptainStouf** [comment]
Same here. Too bad because ALVR runs really well otherwise...

**Comment by HolyCaonima** [comment]
Same here.
