### ISSUE TITLE
ALVR runs super bad on AMD Radeon (TM) R9 390 Series 

### ISSUE THREAD

**Issue by BlaxHazHax** [polygraphene/ALVR#434]
Alvr won't run at all unless I set the resolution below 100% and when it does run the resolution is super bad, tracking is 1 second late, controllers are set at a weird 45 degree angle there are alot of artifacts and it freezes up alot will this be fixed in Alpha 6?

**Comment by babybasher** [comment]
This was released recently, for AMD card.

I'm curious as to how well it works, please let us know! :P

https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR
