### ISSUE TITLE
Major Packet loss with latest version Alpha5 and Oculus Quest

### ISSUE THREAD

**Issue by dc1173** [polygraphene/ALVR#435]
I have been running Alpha 4 flawlessly on 5G wifi with the Oculus quest. I get about 300 packets lost over about 30 min with 5 million packets successful. When I upgraded to alpha 5 it was more like 50,000 packets lost and a lot of video problems rendering most things unplayable. All settings were default and I did uninstall and reinstall drivers.

**Comment by polygraphene** [comment]
It is difficult to debug real cause of packet loss.
I recommend to check your Wi-Fi environment by tools like [WiFi Analyzer](https://play.google.com/store/apps/details?id=com.farproc.wifi.analyzer&hl=en)
Or try to disconnect other Wi-Fi devices from your router.

**Comment by dc1173** [comment]
I downgraded to Alpha4 and everything was good again, it was night and day.
