### ISSUE TITLE
will it work?

### ISSUE THREAD

**Issue by chibisuke1219** [polygraphene/ALVR#436]
hi so I was wondering if there was any way to make it work on oneplus devices in other words I see that there is an apk for the quest and ik that androids apps are apks so what I was wondering is if it was either possible to:

- use the quest apk on the oneplus or android devices and use any headset 
or
- if its possible to make an apk for android devices including the oneplus so that u can just download that and use any headset
anyways thanks for reading and thanks for all responses

**Comment by polygraphene** [comment]
I'm working on daydream/cardboard support. It may take long time. Please be patient.
https://github.com/polygraphene/ALVRClient/issues/1
