### ISSUE TITLE
Multiple Oculus Go

### ISSUE THREAD

**Issue by Veria70** [polygraphene/ALVR#437]
Hello Dev,
I had questions about connecting multiple Oculus Go (two headset) to PC(Network) with ALVR,
is it possible to run multi server for each oculus go? need develop?
Could you show me a best way to do it and i will share my development.

**Comment by polygraphene** [comment]
Do you want to use single PC? What do you want to do actually?

If you can run multiple SteamVR on a PC, you should get to work by changing port number of ALVR server (need small development).
But I don't know how to launch multiple SteamVR at a time.

If you want to register multiple HMD on single ALVR driver, you need to develop (maybe large task).

**Comment by Veria70** [comment]
Do you want to use single PC? Yes Single PC
What do you want to do actually? I have a machine with two seat with same game
If you can run multiple SteamVR on a PC, you should get to work by changing port number of ALVR server (need small development). it's impossible but i develop game with unity & Unreal for PC VR headset and i can run multiple VR Headset at same time without bug or glitch and steamvr.
is it possible to streaming Video from a custom vr game (without steamvr)?
