### ISSUE TITLE
ALVR on Oculus Quest stuttering and low fps

### ISSUE THREAD

**Issue by TaylorGH** [polygraphene/ALVR#438]
so I sideloaded alvr on my oculus quest and im getting stuttering and low fps. is there a fix to this?

**Comment by Halowigeds** [comment]
I have the same issue. SteamVR only utilizes 50% of my GPU and CPU and my FPS are around 50

**Comment by TaylorGH** [comment]
> I have the same issue. SteamVR only utilizes 50% of my GPU and CPU and my FPS are around 50

dude we have the exact same problem

**Comment by Grocs-Blech** [comment]
Hey guys - check you are running a decent wireless channel on 5 Ghz. On your modem / router try changing the wireless channel to see if it improves things. If you have a choice on your 5 Ghz router, set to 80hz if you can.

**Comment by TaylorGH** [comment]
> Hey guys - check you are running a decent wireless channel on 5 Ghz. On your modem / router try changing the wireless channel to see if it improves things. If you have a choice on your 5 Ghz router, set to 80hz if you can.

I'm using an Ethernet cable plugged into my PC

**Comment by Grocs-Blech** [comment]
Hey Taylor, can I just confirm how you are streaming the image to your Oculus Quest? You are using wireless for that, yes?

I agree though - for internet and PC definitely hook up to the LAN. I do.

The other thing I would try is turning off your A/V if it is anything other than the default Microsoft Windows one. I had huge lag issues until I uninstalled my A/V, which was realtime scanning everything.

**Comment by TaylorGH** [comment]
> Hey Taylor, can I just confirm how you are streaming the image to your Oculus Quest? You are using wireless for that, yes?
> 
> I agree though - for internet and PC definitely hook up to the LAN. I do.
> 
> The other thing I would try is turning off your A/V if it is anything other than the default Microsoft Windows one. I had huge lag issues until I uninstalled my A/V, which was realtime scanning everything.

I am streaming the image with alvr, which is wireless. sorry im just confused by your question. im new to vr and computer stuff

**Comment by Grocs-Blech** [comment]
No problem at all. Tweaking VR can take some time, especially for the Quest. My earlier comment still stands then - I would try improving your wireless signal, and turn the 2.4 Ghz range off if you can so that it is definitely using the 5 Ghz. Keep in mind older network devices might rely on 2.4 Ghz though.

Can I confirm what sort of PC you are running this on too? I'm a pretty modest PC, but the Nvidia 1060 GTX is definitely the bare minimum for the video card (that is what I'm using).

**Comment by TaylorGH** [comment]
> No problem at all. Tweaking VR can take some time, especially for the Quest. My earlier comment still stands then - I would try improving your wireless signal, and turn the 2.4 Ghz range off if you can so that it is definitely using the 5 Ghz. Keep in mind older network devices might rely on 2.4 Ghz though.
> 
> Can I confirm what sort of PC you are running this on too? I'm a pretty modest PC, but the Nvidia 1060 GTX is definitely the bare minimum for the video card (that is what I'm using).

Sorry for late response. I'm using a 1050ti, which actually worked pretty well when I had my rift. and how do change my wireless signal to 5ghz?

**Comment by zxsdklfhskyrvk** [comment]
> 
> 
> > No problem at all. Tweaking VR can take some time, especially for the Quest. My earlier comment still stands then - I would try improving your wireless signal, and turn the 2.4 Ghz range off if you can so that it is definitely using the 5 Ghz. Keep in mind older network devices might rely on 2.4 Ghz though.
> > Can I confirm what sort of PC you are running this on too? I'm a pretty modest PC, but the Nvidia 1060 GTX is definitely the bare minimum for the video card (that is what I'm using).
> 
> Sorry for late response. I'm using a 1050ti, which actually worked pretty well when I had my rift. and how do change my wireless signal to 5ghz?

You setup a 5Ghz SSID/network on your router.  Then you select that wifi network on your Quest.

**Comment by Grocs-Blech** [comment]
Yes, the first thing would be to check 5Ghz is available. You have to be using a router that supports the AC standard at least, not the earlier standards of B,G or N.

**Comment by TaylorGH** [comment]
It’s on 5ghz. Pretty much the only games that lag are Spider-Man: Far From Home VR, and beat saber. Those are the only games I can notice any latency and FPS issues. Is it possible that there’s a fix for those games in particular?

**Comment by zxsdklfhskyrvk** [comment]
The issue is with streaming, and the demands of the game inside steamvr, not so much with ALVR.  Check your Super Sampling there and just set it to 100%, or less if you are willing.

Not sure what else could be done at steamvr side.

**Comment by Grocs-Blech** [comment]
Beat Saber is pretty notorious for not streaming as well as other games. I haven't tried Spider-Man: Far From Home VR. To see if it helps, you could try and set the per eye resolution to a lower amount for those two games only. Go into SteamVR settings and change the resolution on the application.

Alternatively you could try another streaming platform as ALVR is still in alpha. I use Virtual Desktop and I'm very happy with it.

**Comment by mbuckley2000** [comment]
Just fixed the same issue for me (stuck at ~50fps). Turned out to be the codec. Using h264 over HEVC brought me up to 72FPS.

I'm using 150% resolution in the ALVR server to match the resolution of the Quest, so the issue seems to be decoding high-resolution streams.
I think HEVC is more demanding to decode on the Quest, so it can't keep up with the server. The Quest client seems to tell the server to slow down the rendering if it can't keep up.

Also, check out your supersampling settings in SteamVR. If you run a game at 200% resolution, I think this may actually affect the resolution of the stream, rather than sampling it down to the Quest resolution on the server-side. This adds a large decoding overhead on the client.

I'm running ethernet from the PC and same-room 5GHz to the Quest.

**Comment by belugaking1** [comment]
I'm getting an issue myself, I've tried everything even changing the codec, and I'm getting lag just loading up steam vr. I'm running on a 1060 GTX and my internet is 5ghz

**Comment by sprlpy** [comment]
I play with hot spot to gear vr from pc   and enternet  cable to pc , when I connect to internet device suparately picture is broken , 5 or 2.5 not have big different for me
