### ISSUE TITLE
0 Packets

### ISSUE THREAD

**Issue by JiggyMcNelson** [polygraphene/ALVR#443]
This evening I installed the latest version of ALVR. However, once I launched the server, I was met with server stats that indicated a connection problem. There were no packets being shown, and the packet loss was somewhere in the millions. My Oculus Quest is connected to the router in the same room and my desktop computer it connected with an ethernet cable, so I'm just super confused what the problem could be. 
![Capture](https://user-images.githubusercontent.com/52222467/60139075-87b37480-977a-11e9-81bb-e9d79b14f266.PNG)

**Comment by sen7inel** [comment]
Turn off your windows firewall, restart both the desktop and quest apps and try again?

**Comment by JiggyMcNelson** [comment]
> 
> 
> Turn off your windows firewall, restart both the desktop and quest apps and try again?

So I've done everything you said, and I managed to get through the room setup. However, now the performance within Steam VR is awful. It's a laggy and distorted picture that's absolutely unplayable. These are the statistics when that happened. 
![Capture](https://user-images.githubusercontent.com/52222467/60142457-e6cbb600-9787-11e9-9325-cd6fdc2177e6.PNG)

**Comment by babybasher** [comment]
What type of router do you have, how is it connected to your PC?

What speeds do the PC and the Quest both connect to the router at, and how far away is it from both the Quest and PC?

1.  You definitely disabled the firewall? Double check.
2.  Try launching the ALVR program as administrator.
2.  Disable any anti virus programs.
3.  In the Network Profile, set it to Private if not already.
4.  In your router settings, make sure there's no router firewall active.
5.  Again in the router settings, look for a DMZ field.  Enable that setting your PC's IP as the target.

This is what I'd be trying anyway.

**Comment by Seether00** [comment]
I'm having the exact same problem. No data is being sent over even though steam's headset display works and if I move the head set the view moves. 

PC is Ethernet connected my cable-wifi router and the head set is in the same room on 5ghz. Tried turning off Windows firewall and still the same result. Just a black screen in the headset with the Guardian walls.
