### ISSUE TITLE
Quest: 72hz only, stuttering tracking

### ISSUE THREAD

**Issue by Bollean81** [polygraphene/ALVR#444]
Hi,

i use alpha 5, Oculus Quest and 5ghz wifi. There are 0 frames dropped, it looks simply flawless, but head and controller do stutter while moving. 
I know the Quest only makes 72hz and the encoding is in 60hz, same problem as with Oculus go. But there is the "force 60hz" button and i thought, it works with alpha 5. But it doesnt for me, there is no effect, it still runs at 72hz and stutters.
Is there any workaround?

Thx

**Comment by Myhamof** [comment]
I think that the oculus quest doesn't support yet 60 hz and they allow that in future update with the ability to use the headset as 3 degrees of freedom in dark places where the tracking system can't work
