### ISSUE TITLE
SteamVR Issues

### ISSUE THREAD

**Issue by cots-xd** [polygraphene/ALVR#445]
ALVR Drivers installed, connected and paired to my quest very easily.

but now I cannot get past room setup, steam cannot recognise or detects the quest.

any help with this?

**Comment by emporerodin** [comment]
Yeah, i'm having the same issue.

**Comment by cots-xd** [comment]
I have found a fix to this,

I allowed all VRSERVER.EXE I n windows firewall, it’s working fine now

**Comment by alekkenton** [comment]
I had the same issue, needed to temporarily disable my windows firewall completely, then having made sure the correct apps are allowed through I re enabled it and it all works fine now.

**Comment by Occyouloss** [comment]
I had the exact same issue after the Windows 10 May update installed and steamVR suddenly couldn't recognise the headset or controllers for the quest, with no indication why.  
Adding VRSERVER.EXE ( D:\SteamLibrary\steamapps\common\SteamVR\bin\win64\vrserver.exe for me ) to the firewall exception list  made it work straight away. There were already lots of other steamVR programs in the firewall allow list but that specific executable was it.

Thank you @cots-xd
