### ISSUE TITLE
ALVR SECOND  ALVRClient-GithubNormalOvr-release-v2.4.0-alpha5.apk ERROR

### ISSUE THREAD

**Issue by noahbam2** [polygraphene/ALVR#446]
I cant seem to beable to play alvr with my oculus quest, could anyone try to resolve this issue on Windows Powershell? This is the error msg that i got. 

PS C:\Users\Rubri\Downloads\platform-tools_r29.0.1-windows\platform-tools> .\adb devices
List of devices attached
1PASH9A2Q39203  device

PS C:\Users\Rubri\Downloads\platform-tools_r29.0.1-windows\platform-tools> .\adb install -g ALVRClient-GithubNormalOvr-release-v2.4.0-alpha5.apk
Performing Streamed Install
adb: failed to install ALVRClient-GithubNormalOvr-release-v2.4.0-alpha5.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install com.polygraphene.alvr without first uninstalling.]
PS C:\Users\Rubri\Downloads\platform-tools_r29.0.1-windows\platform-tools>

**Comment by alekkenton** [comment]
Hi, this just means you already have it installed (or partially installed of it didnt complete properly), you'll need to delete the existing installation from your headset, use the following command:
.\adb uninstall com.polygraphene.alvr

Once you've done this, you should be able to reinstall it.

**Comment by confused-person** [comment]
I Have the same problem, where should I paste the command?
.\adb uninstall com.polygraphene.alvr
