### ISSUE TITLE
Whenever i try to start the server i get a popup saying server crashed

### ISSUE THREAD

**Issue by FrostyNugget** [polygraphene/ALVR#448]
i click start server and then it pops up saying alvr server crashed sorry for the inconveniece with this beneath:
Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc NvEncoderD3D11 failed. Code=15 NvEncoder::LoadNvEncApi : Current Driver Version does not support this NvEncodeAPI version, please upgrade driver at c:\src\alvr\alvr_server\nvencoder.cpp:88

Can someone tell me how to fix it because it says i have the drivers installed btw im on oculus quest

**Comment by bobby3605** [comment]
What gpu do you have?

**Comment by FrostyNugget** [comment]
I have a gtx 1060
