### ISSUE TITLE
My ALVR testing

### ISSUE THREAD

**Issue by kgian** [polygraphene/ALVR#45]
Not an issue but I thought it would be nice to write about my experience with ALVR. 

I have an oculus Go. My PC is i5 3450, GTX 970.

My first try was with ALVR version 1.9.2
Tried to run the server and got .net framework error. After some searching I found out that I had to do a first run of steamVR for it to be setup correctly. 

After that I got a nvenc error. That was easy. I had to install the latest nvidia drivers.

Next I could not get the connect button even though the server was up and I could ping the headset. I had to follow this guide https://steamcommunity.com/app/250820/discussions/0/1290691937709136507/ and delete the "openvrpaths.vrpath" file. After that I could connect.

I tried both a 2.4 and a 5GHz wifi connection with the router directly next to me. 2.4 was unusable. 5GHz was great.

Today I upgraded to 2.0. I also did some performance testing. With the default 30MBps and 2048x1024 resolution I got around 48-55ms total latency with no packet loss. 
With 50MBps and 2880x1440 I got around 60-65ms latency, no packet loss but the graphics were greatly enhanced. 
I think about 60 or 70mbps I got severe increasing latency which quickly added up to multiple seconds. 

I tried Project cars 2, elite dangerous, doom VFR and Bigscreen beta.

Project cars 2 was running great. Totally playable. I tried it with gamepad. 
Elite dangerous was also running great. Also with gamepad. I may connect my hotas to try and play for extended period to test immersion. 
Doom VFR was stuttering. This game is stuttery though also on certain configurations even on high performance machines.
Bigscreen beta was working great also and with the higher resolution and bitrate very clear. 

Right now I am downloading The solus project and subnautica to test. I would like also to install revive to test my oculus games (I also have a rift).

In all my testings I had 72fps according to the nvidia geforce overlay FPS counter. Also on steamVR settings there is a bar on the bottom left which was green with "Framerate good".  Async reprojection and interleaved reprojection were off in steamVR, supersampling also set to 100%. 

My wishlist for ALVR is:

-  maybe a wired connection if it is possible and if it reduces latency with increased picture quality
- oculus go onboard sound and microphone support
- maybe some more analytics if it is possible like framerate or an in headset latency and fps overlay. Like the way it is with oculus tray tool. 

EDIT: I see that I had the go conencted to a N wireless router and the computer connected to a different AP with ethernet. According to the instructions you have to have both connected to the same router and prefferably on AC speeds. I will have to try to see if latency decreases. Any recommended budget AC router/AP?

**Comment by polygraphene** [comment]
Thank you for great report!

>48-55ms total latency

It's good. I have 60-70ms on same configuration with S8/11n Wi-Fi.

>maybe a wired connection if it is possible and if it reduces latency with increased picture quality

Does the "wired connection" mean connect Go on PC with USB cable (adb)?
If it is right, I will add it to the feature request list.

>sound and microphone

It need a hard work on implementation and takes a lot of time. Please be patient.

> more analytics

It's a good suggestion. I want this feature too.

I'm also using 11n Wi-Fi router and thinking about a new router.
I don't have deep knowledges about Wi-Fi, but I want to buy the router with 1000Base-T.

**Comment by kgian** [comment]
>Does the "wired connection" mean connect Go on PC with USB cable (adb)?
>If it is right, I will add it to the feature request list.

Yes, this is correct. Connect Go on PC with usb cable (adb). But we need this only if it reduces latency significantly, or it allows significantly larger bitrates. 

To be more precise, I would not mind tethering if it enhances the experience a lot.
