### ISSUE TITLE
Question: Use your PC as mobile hotspot.

### ISSUE THREAD

**Issue by Darktos** [polygraphene/ALVR#450]
Hi love ALVR ! 

https://support.microsoft.com/en-us/help/4027762/windows-use-your-pc-as-a-mobile-hotspot

could this be relevant for us ?

greetings Laurin

**Comment by Olsson32** [comment]
Hi,

I had this idea too, but when I connect me quest with the Wifi Hotspot of my PC, ALVR is not able to find the headset. For me it only works using a separate 5Hhz Wifi router.

**Comment by holymoo** [comment]
I was actually able to do this when I wasn't able to get it working with my wireless router. It worked out pretty well.

I did this with a 2018 Razer Blade 15
