### ISSUE TITLE
MJPEG codec support

### ISSUE THREAD

**Issue by SCheeseman** [polygraphene/ALVR#452]
There seems to be a pretty substantial latency hit from using MPEG4 on both ends that only gets worse with higher bitrates. Perhaps mjpeg is a solution? Encode and decode times are very fast (particularly using optimized encoders like libjpeg turbo) and there's plenty of bandwidth to spare. Greater control over the encode pipeline would allow for more VR targeted optimizations too, access to NVENC is hobbled by Nvidia without a license.

**Comment by zarik5** [comment]
I'm afraid it is not that simple. Excluding Nvidia that does not support MJPEG encoding, to be able to use a software encoder you have to transfer entire uncompressed frames from the GPU to the CPU. A while ago I did some tests and from what I remember a 720p frame takes at least 10ms to be transferred, so for the Oculus Quest it would take ~50ms at native resolution. Maybe it would still be useful to make MJPEG an option, expecially for those without a GPU powerful enough to handle the encoding.

**Comment by SCheeseman** [comment]
There's CUDA encoders for jpeg including one supplied by nvidia, though I'm unsure how fast the open source ones are. Reasonably fast CPU encoders exist too like libjpeg-turbo.

The Vive's Wireless kit that use the CPU to encode video to be transmitted wirelessly, which so it's unlikely copying the framebuffer to system RAM is a latency bottleneck.

**Comment by SCheeseman** [comment]
>>>>>  BGR (Top-down) <--> JPEG 4:2:0 Q90  <<<<<

Image size: 2880 x 1600
Compress      --> Frame rate:         83.037593 fps
                  Output image size:  298086 bytes
                  Compression ratio:  46.375878:1
                  Throughput:         382.637230 Megapixels/sec
                  Output bit stream:  198.018753 Megabits/sec
Decompress    --> Frame rate:         122.876567 fps
                  Throughput:         566.215219 Megapixels/sec

Image quality is reasonable in the image I used, which is a (mostly) raw quest framebuffer image I found on the internet somewhere so obviously the performance could vary. Still not fast but maybe technically usable?

**Comment by zarik5** [comment]
Good job! If you have more spare time you could try to integrate it into ALVR and submit a PR.
I'm currently working on adding fixed foveated rendering to reduce the framebuffer size.

**Comment by SCheeseman** [comment]
I'm a total coding novice and can barely get stuff to compile half the time, most of what I did was running benchmarks to see if the numbers make sense.

Still not sure if it's worth doing, but someone with a bit more skill could make this practical to implement. I suspect that the Vive Wireless kit is using a similar approach, maybe with a proprietary high-speed jpeg codec (there's quite a few of those, jpeg is used a lot in CV and security).

**Comment by jdagdelen** [comment]
@SCheeseman maybe we can work on this? I’m not an expert programmer by any means but I have parallelized scientific codes with CUDA.

**Comment by jdagdelen** [comment]
I don't think MJPEG decode is supported by the Snapdragon 385, only AVC, HVEC, and VP9. https://www.qualcomm.com/products/snapdragon-835-mobile-platform

**Comment by SCheeseman** [comment]
Yeah that's what I'm still most unsure about. libjpeg-turbo is multithreaded and has NEON optimisations but it might not be enough. At least the Quest isn't doing much else, maybe the GPU could be leveraged for parts of the decode pipeline?
