### ISSUE TITLE
ALVR Wont Open

### ISSUE THREAD

**Issue by SameemN** [polygraphene/ALVR#456]
![Capture](https://user-images.githubusercontent.com/36427194/60816359-6ecd9a80-a14e-11e9-89db-1c72054965f2.JPG)

It's said this every time I open it. It was working yesterday but now it does this?

**Comment by Ciunics** [comment]
Rest of the picture please?

**Comment by Neuromancer0525** [comment]
what version are you using cause i use alpha 4 version 5 has a lot of bugs in it 4 is more stable try uninstalling 5 if you have it and install 4 it may help.

**Comment by holymoo** [comment]
Could you please post the details that show up when you expand out "Details"?

**Comment by SameemN** [comment]
It was the audio. thanks for the help!
