### ISSUE TITLE
Cardboard/Daydream version?

### ISSUE THREAD

**Issue by Tux0Topo** [polygraphene/ALVR#46]
Maybe it´s something silly, but could be possible to make a version compatible with Cardboard/Daydream? For easy adoption...

**Comment by iamapie13** [comment]
if there was a version of ALVR for Cardboard/Daydream it wouldn't be much different from using Riftcat, ALVR get's i'ts smoothness from Asynchronous Time Warp (ATW) which is obtained from the Oculus SDK, the Google VR SDK doesn't have ATW as far as I know so a port to daydream/cardboard would remove this essential feature.
Although the Google VR SDK does have a similar feature called Asynchronous Reprojection but this would mean starting a new separate project from scratch

**Comment by Tux0Topo** [comment]
Ohhh!!! Didn´t knew... Thanks for answering and being so clear about it...

**Comment by iamapie13** [comment]
you're welcome, I too wondered why it was Gear VR only until I made some research about it

**Comment by penkamaster** [comment]
Daydream has his own asynchronous time warp called Asynchronous reprojection.
A daydream version is technically possible.

**Comment by polygraphene** [comment]
It is possible to port ALVR into Daydream.
Most important (and difficult) point of ALVR implementation is an accurate tracing of "FrameIndex" in the process of encode/transport/decode images.
It is not depend on Oculus Mobile SDK.

If Daydream's SDK have the similar API to Oculus Mobile SDK to implement Asynchronous Reprojection, we can port by simply switching SDK.

**Comment by sigmaxipi** [comment]
I have a basic prototype working for Daydream. I put some notes in https://github.com/polygraphene/ALVRClient/issues/1
