### ISSUE TITLE
ALVR Start Server Crash

### ISSUE THREAD

**Issue by MasterOfTartarus** [polygraphene/ALVR#460]
Whenever I try to start the server, this error code comes up:

Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc NvEncoderD3D11 failed. Code=1 NvEncoder::LoadNvEncApi : NVENC library file is not found. Please ensure NV driver is installed at c:\src\alvr\alvr_server\nvencoder.cpp:70

Help?

**Comment by zarik5** [comment]
Please read the [Troubleshooting](https://github.com/polygraphene/ALVR/wiki/Troubleshooting) page on the wiki.
