### ISSUE TITLE
[CLIENT] Performance degrading

### ISSUE THREAD

**Issue by canalaiz** [polygraphene/ALVR#461]
First of all, thank you for all your efforts. This software is beyond amazing.

I've noticed something weird happening (I'm currently using 2.4.0 alpha5) on an Oculus GO / Quest as the client.

I start streaming, everything runs super smooth.
Playing for, like, 30-40 mins and smoothness starts degrading. I don't know how to explain this better, it seems like the frame rate starts dropping. 

The more i keep the client running, the worse the degrading gets.

If i quit the client on the Oculus and start it again (so that it'll attach back to the running server) it will return on perfect performances. These will degrade with time, anyhow.

Could this be a memory leak on the client?
If you need any other info / test on this, just let me know!

**Comment by ShawnMayer** [comment]
Same here!

**Comment by simbake** [comment]
Same thing happens on Gear VR.

**Comment by canalaiz** [comment]
I've found out that performance degrading can be "counterd" checking "Force 60hz" and "Suppress Frame Drop" under the "Other" tab on ALVR server

**Comment by FingrMastr** [comment]
@canalaiz I have been trying to debug the degrading performance for a month. Actually, 60hz mode and suppress frame drop is not mitigating the degradation in my case. After around 20-30 minutes, the lag starts raising, and also movement jitterness. Also, I'm experiencing "freezes" sometimes after entering that strange behavior. The client on Quest shows the last freezed frame, and the Quest becomes totally unresponsive, I cannot even try to exit from alvr app. I need to restart the Quest in that case, keeping power button pressed. In my case, the freeze events are occurring more frequently on high buffer/bitrate combinations. Did you investigate the problem some more?

I tried every JackD83 version and also vanilla alpha5 version (with compatibility mode fix)...

Any detail would be helpful.
P.S. Sto a sbroccà pe sta cosa.
