### ISSUE TITLE
Head Nod not tracking in Defector

### ISSUE THREAD

**Issue by Shadowmask72** [polygraphene/ALVR#462]
Defector just released and whilst it boots up and allows you to play with the options and start mission 1 using Oculus Quest, once you get to the bathroom it asks you to nod your head. This action triggers the next sequence. However, using ALVR or Virtual Desktop, this action does not register and players cannot progress any further.

**Comment by DannyDan** [comment]
@Shadowmask72 how did you start the game? I'm using revive and it says "please plugin rift headset"?!?

**Comment by MadSpin** [comment]
I'm having the same issue on Quest. In my case Defector jitters on all quality settings on Quest but not on Index. I also tested head nod doesn't work on Quest in both ALVR and Virtual Desktop. Head nod works on Index. Using Revive 1.7.0.3 and latest SteamVR beta and ALVR.
