### ISSUE TITLE
ALVR Server has Crashed

### ISSUE THREAD

**Issue by kayiu-c** [polygraphene/ALVR#463]
Hello, I recently downloaded ALVR, but I got this error after I pressed Start Server. Any way to fix this? Thank you
Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc CreateEncoder failed. Code=15 NvEncoder::CreateEncoder : m_nvenc.nvEncInitializeEncoder(m_hEncoder, &m_initializeParams) returned error 15 at c:\src\alvr\alvr_server\nvencoder.cpp:271

**Comment by zarik5** [comment]
Please read the [Troubleshooting](https://github.com/polygraphene/ALVR/wiki/Troubleshooting) page on the wiki.
