### ISSUE TITLE
"Headset not found."

### ISSUE THREAD

**Issue by CommanderFrostbite** [polygraphene/ALVR#468]
I have my oculus on the same network and have alvr running on both my go and my computer but it still doesn't detect it. Please help i've looked at other threads and they weren't very helpful.

**Comment by CommanderFrostbite** [comment]
i also opened the port it says to open.

**Comment by PigOnSteroids** [comment]
Experienced the same issue, I noticed that SteamVR was in safe mode. Once I turned that off it connected right away.

**Comment by TomHVR** [comment]
ran the .bat scripts. turned off my firewall, PC is connected by Ethernet to the wireless router. Turned on client on the oculus go

checked with wireshark and no packets are received on ports 9944 or 9943
