### ISSUE TITLE
Direct connection to headset (via ip)

### ISSUE THREAD

**Issue by Groar90** [polygraphene/ALVR#470]
Hello,
Could you please add an option to manually connect the server with Oculus Quest headset by typing headset's IP in the server app?
I'm pretty sure it would solve a lot of people problems with headset not being found.
I have that problem with ALVR (my headset is not being found) and the same problem occurs with Riftcat but in riftcat windows app you can connect by typing the headset Ip adress and it connects without any problems.

**Comment by Strongfort** [comment]
Agreed. I've tried everything possible. Turning off all virus protection, firewalls, forwarding on router etc. I also had this same issue with Riftcat, but direct connection to IP worked.

I suspect it has something to do with my router - I'm on the Orbi Pro SRR60 router and satellites. It combines both 2.4 and 5ghz into one connection. I suspect that has something to do with it.

Please just add IP connection option.
