### ISSUE TITLE
Red screen

### ISSUE THREAD

**Issue by pdebaty** [polygraphene/ALVR#478]
I have installed ALVR v2.4.0-alpha5 on my Quest using Sidequest (not adb). I have the ALVR server running on a remote gaming PC (using Shadow). I followed the guide on the wiki to connect my cloud gaming PC to my OpenWRT router using Zerotier. After that, the ALVR server detects my headset and is able to connect to it and launch SteamVR. But when I launch ALVR client on my Quest, all I see is a red screen with some garbled artifacts on it. I waited a while to see if that would go away and it does not.
I'm able to play SteamVR games on my Quest using Virtual Desktop on this Cloud Gaming PC, but I heard ALVR has better visual performance so would love to get it to work.

**Comment by Lamethrower** [comment]
Also experiencing this issue. Tried uninstalling everything and reinstalling without luck. No difference between AVC and NVEC.

**Comment by Lamethrower** [comment]
Quick update, just tested on another completely separate PC but the same Quest device and got the same garbled red screen.
