### ISSUE TITLE
New Oculus Quest firmware update broke SteamVR controls completely

### ISSUE THREAD

**Issue by HanzoFactory** [polygraphene/ALVR#479]
You're probably aware of this, but I just want to make sure you do :>

**Comment by machenmusik** [comment]
https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/

**Comment by CallumSee** [comment]
> 
> 
> https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/

Didn't fix anything for me...

**Comment by BigDGW** [comment]
> > https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/
> 
> Didn't fix anything for me...

It did fix it for me

**Comment by CallumSee** [comment]
https://github.com/polygraphene/ALVR/issues/479#issuecomment-515265297

Oh awesome!

Did you use the batch file converter? Maybe that’s where I’m going wrong.

**Comment by Woohaaa** [comment]
> > > https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/
> > 
> > 
> > Didn't fix anything for me...
> 
> It did fix it for me

Could you share fixed alvr.apk?

**Comment by Zeldon567** [comment]
Can confirm ALVR unmodified is not working correctly.Will personally test suggested fix and verify if it works.

**Comment by BigDGW** [comment]
This is the APK, I added the line too and recompiled and resigned
https://drive.google.com/open?id=1XrzkkKgfGYVgD1eWeNRoa2UTy0uaU77w

> > > > https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/
> > > 
> > > 
> > > Didn't fix anything for me...
> > 
> > 
> > It did fix it for me
> 
> Could you share fixed alvr.apk?

This is the APK, I added the line too and recompiled and resigned
https://drive.google.com/open?id=1XrzkkKgfGYVgD1eWeNRoa2UTy0uaU77w

**Comment by ocquesttest** [comment]
> This is the APK, I added the line too and recompiled and resigned
> https://drive.google.com/open?id=1XrzkkKgfGYVgD1eWeNRoa2UTy0uaU77w


not working, i get this error:

INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl267024203.tmp/base.apk: Attempt to get length of null array

**Comment by Woohaaa** [comment]
> > > > > https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/
> > > > 
> > > > 
> > > > Didn't fix anything for me...
> > > 
> > > 
> > > It did fix it for me
> > 
> > 
> > Could you share fixed alvr.apk?
> 
> This is the APK, I added the line too and recompiled and resigned
> https://drive.google.com/open?id=1XrzkkKgfGYVgD1eWeNRoa2UTy0uaU77w

Can't sideload this fixed apk.
error:
adb: failed to install alvr24.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl970440867.tmp/base.apk: Attempt to get length of null array]

**Comment by BigDGW** [comment]
> > > > > > https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/
> > > > > 
> > > > > 
> > > > > Didn't fix anything for me...
> > > > 
> > > > 
> > > > It did fix it for me
> > > 
> > > 
> > > Could you share fixed alvr.apk?
> > 
> > 
> > This is the APK, I added the line too and recompiled and resigned
> > https://drive.google.com/open?id=1XrzkkKgfGYVgD1eWeNRoa2UTy0uaU77w
> 
> Can't sideload this fixed apk.
> error:
> adb: failed to install alvr24.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl970440867.tmp/base.apk: Attempt to get length of null array]

Oeps my bad this one wasnt signed this should work
https://drive.google.com/open?id=1-YHOu1w6CmhGj9UnoSAJahqIrGOvXSUx

**Comment by Woohaaa** [comment]
> > > > > > > https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/
> > > > > > 
> > > > > > 
> > > > > > Didn't fix anything for me...
> > > > > 
> > > > > 
> > > > > It did fix it for me
> > > > 
> > > > 
> > > > Could you share fixed alvr.apk?
> > > 
> > > 
> > > This is the APK, I added the line too and recompiled and resigned
> > > https://drive.google.com/open?id=1XrzkkKgfGYVgD1eWeNRoa2UTy0uaU77w
> > 
> > 
> > Can't sideload this fixed apk.
> > error:
> > adb: failed to install alvr24.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl970440867.tmp/base.apk: Attempt to get length of null array]
> 
> Oeps my bad this one wasnt signed this should work
> https://drive.google.com/open?id=1-YHOu1w6CmhGj9UnoSAJahqIrGOvXSUx

It works！Thx, bro.

**Comment by taladav** [comment]
cant sideload either:  failed to install ALVRClient-fixed.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.polygraphene.alvr signatures do not match the previously installed version; ignoring!]

**Comment by BigDGW** [comment]
> cant sideload either: failed to install ALVRClient-fixed.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.polygraphene.alvr signatures do not match the previously installed version; ignoring!]

You need to delete the old version before installing this one.

**Comment by taladav** [comment]
> > cant sideload either: failed to install ALVRClient-fixed.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.polygraphene.alvr signatures do not match the previously installed version; ignoring!]
> 
> You need to delete the old version before installing this one.

How do i do that? My knowledge on this topic is restricted to the informations given in that video: https://www.youtube.com/watch?v=Tk9Qx07I2Pg&t=463s

**Comment by taladav** [comment]
> > > cant sideload either: failed to install ALVRClient-fixed.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.polygraphene.alvr signatures do not match the previously installed version; ignoring!]
> > 
> > 
> > You need to delete the old version before installing this one.
> 
> How do i do that? My knowledge on this topic is restricted to the informations given in that video: https://www.youtube.com/watch?v=Tk9Qx07I2Pg&t=463s

OK, found it out..with another tutorial :D (https://www.youtube.com/watch?time_continue=96&v=n1tn_QeamAE)

**Comment by rudyharrelson** [comment]
I'm a bit unfamiliar with Android development, so I have a question about this issue:

The reddit post says this fix is applied by adding this line: 

`<uses-feature android:name="android.hardware.vr.headtracking" android:required="true" android:version="1"/>`

To the `AndroidManifest.xml` file after decompiling the apk file.

I figured I might submit a pull request for this repository, and just add the line to that file, since it seems pretty straightforward.

However, when I search this git repository, I do not see any file named "AndroidManifest.xml". Can anyone explain why that is?

**Comment by krzys-h** [comment]
@rudyharrelson I literally just did it and noticed your comment while making a list of issues it closes. The client code is in a separate repository here: https://github.com/polygraphene/ALVRClient

**Comment by rudyharrelson** [comment]
> 
> 
> @rudyharrelson I literally just did it and noticed your comment while making a list of issues it closes. The client code is in a separate repository here: https://github.com/polygraphene/ALVRClient

Ahh, that makes sense. Thanks a bunch!

**Comment by br0der** [comment]
Hey I downloaded and loaded the ALVRClient-fixed and the controllers worked, but the left eye and the right eye are switched, or something along those lines. Any solutions?
