### ISSUE TITLE
Need test for Oculus Key distribution.

### ISSUE THREAD

**Issue by polygraphene** [polygraphene/ALVR#48]
Now we can download ALVR Client from Oculus Store using Oculus Key.
I created [a key distribution page](https://alvr-dist.appspot.com/).

Open this page on your smartphone, and put key on the Oculus app.

It should work on both Gear VR and Oculus Go.
If you can (or cannot) download, please report here.

**Comment by polygraphene** [comment]
We don't need to become a developer any more if it works.

**Comment by Tux0Topo** [comment]
Okay... You are my hero! Damn! YOU ARE AWESOME!

**Comment by polygraphene** [comment]
Great!
Thank you for testing!

**Comment by carlosfoces** [comment]
Works great app is now in my oculus go, and I can see in home oculus. Thanks for all, great job.

**Comment by davinux** [comment]
It worked perfectly to me!. Great work!

**Comment by polygraphene** [comment]
Thank you for reporting!
I added the instruction on README.

**Comment by chapeka** [comment]
perfect you are the best, your JOB is amazing

**Comment by Jbbrack03** [comment]
You might want to add to the Guide that you can also apply the key through the Oculus Web Store on a computer. And there is no option to redeem the key on iOS, so iOS users will need to use the Web Store as well.

**Comment by polygraphene** [comment]
Thank you!
I didn't know that. I have updated the explanation.
