### ISSUE TITLE
ALVR hags when bluetooth controller (pad) is paired with Oculus Quest

### ISSUE THREAD

**Issue by sitte** [polygraphene/ALVR#485]
To reproduce:
1. I pair bluetooth pad with Oculus Quest headset (I tested Ipega and Mocute pads)
2. I run alvr desktop
3. I start alvr on headset (I see light enviroment with "press triger to start" or something)
4. I press triger

Result:
For 1-2 seconds it seems to connect but then alvr on headset hangs - system shows popup to restart or close.

I tested on 2 pads, both the same result. 
When I disconnect pad then alvr works perfect.

**Comment by nk33** [comment]
I have the same issue - has anyone looked at this yet? it means i have to play in the same room as my PC is in if i am playing a game that requires a gamepad...

thanks
