### ISSUE TITLE
Malformed packets received from Gear VR phone

### ISSUE THREAD

**Issue by fvig2001** [polygraphene/ALVR#487]
Setup:
1. ALVR 2.4 alpha 5 
2. ALVR for Gear VR via Oculus Store
3. Dual band Wifi router and Wifi Dongle
4. Disabled firewall on Win 10

Issue:
1. Headset not found by PC app
2. Press connect message on Gear VR
3. On Wireshark:
0000   ff ff ff ff ff ff a0 c9 a0 8d 0c d9 08 00 45 00
0010   00 48 6b 9c 40 00 40 11 9f bf c0 a8 56 f9 c0 a8
0020   56 ff 26 d8 26 d8 00 34 87 13 01 00 00 00 12 00
0030   00 00 73 61 6d 73 75 6e 67 20 53 4d 2d 4e 39 33
0040   35 46 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0050   00 00 3c 00 00 00

"3404","226.603871","192.168.86.249","192.168.86.255","WireGuard","86","Handshake Initiation, sender=0x00000012[Malformed Packet]"

ÿÿÿÿÿÿ É ÙEHk@@¿À¨VùÀ¨Vÿ&Ø&Ø4samsung SM-N935F<

**Comment by Enziet** [comment]
I'm having this same exact problem. 

ALVR v2.4.0-alpha5 (this also happens with all current alpha releases and the latest release)
ALVR Client v2.3.1 on Samsung Galaxy S8 SM-G950F
PC using Ethernet, S8 using 5g wireless connecting to same router.
Firewall disabled, ports 9944, 9943 open and forwarded to PC's dedicated network IP.

"Server is alive!" message shown along with "Headset not found."
"Press connect button on ALVR server" shown on ALVR client.
Wireshark shows malformed packets coming from S8 AVLR client.

5774 ,496.833630, 192.168.0.188, 192.168.0.255, WireGuard, 86, Handshake Initiation, sender=0x00000012[Malformed Packet]

**Comment by CodeMonk** [comment]
Same

**Comment by krzys-h** [comment]
I was debugging the exact same issue some time ago. The store version of the client is v2.3.1 and doesn't seem to be compatible with the later v2.4.0-alpha server versions - either downgrade the server, or build the alpha client as explained in https://github.com/polygraphene/ALVR/blob/master/README.md#alvr-client (it's not possible to simply share the updated file because of some weird Oculus signing stuff)

**Comment by Enziet** [comment]
This is solved by doing exactly as @krzys-h said. 

I skipped downloading any already built ALVR server/client apps and just cloned both repos then built them with android studio using my own oculus sig file.
