### ISSUE TITLE
some games fali with jitter

### ISSUE THREAD

**Issue by chapeka** [polygraphene/ALVR#49]
Hello my friend.
I am trying all my games with ALVR an my Oculus GO, some hames like Edge of nowhere, Feral rites, Willsons heart and Fallout 4 vr have jitter problems when you moveyour head, perfect resolution an 0 lag baut is impossible to play with them, Wich problem with them?¿?¿?

**Comment by polygraphene** [comment]
Same issue?
https://github.com/LibreVR/Revive/issues/548
