### ISSUE TITLE
development

### ISSUE THREAD

**Issue by DannyDan** [polygraphene/ALVR#490]
@polygraphene will this be developed further?

**Comment by HanzoFactory** [comment]
Developer is on vacation from what I heard, and will probably resume to working on it when he comes back

**Comment by DannyDan** [comment]
@HanzoFactory ah, thanks for the info. good to know.

**Comment by ajellyfishgr8** [comment]
dev has been doing amazing work! Hope they enjoys vacation!

**Comment by jakefever191** [comment]
that good to know they on vacation i thought they had drop it
