### ISSUE TITLE
Oculus quest black screen issue

### ISSUE THREAD

**Issue by derpyboii** [polygraphene/ALVR#495]
I have installed ALVR Alpha5 on my quest aswell as pc but when i connect to quest the screen freezes and if you go back to oculus home and back it turns black or show three dots on the screen. Looking on the steam vr side it shows that it is working but it doesnt stream the view from pc to the quest.

**Comment by davidlgj** [comment]
I had a similar issue, changing resolution to 75% fixed it for me! I guess its an issue o what the graphics card can handle.
