### ISSUE TITLE
error opening steam vr

### ISSUE THREAD

**Issue by penkamaster** [polygraphene/ALVR#5]
Once the drivers are installed, changing the location in the driver's installation bat.
When I click on ALVR start server then steam vr open ups but with the error "A key component of Steam VR isnt working properly"

if I uninstall the driver steam vr opens correctly.

**Comment by kameka22** [comment]
Hello 
 can this be : 

1. Launch SteamVR
2. Go into the Settings
3. Select Developer on the left side
4. Scroll down and select Remove all SteamVR USB Devices
5. Exit out of Settings and SteamVR
6. Restart computer and Relaunch to check if it worked

source : https://steamcommunity.com/app/250820/discussions/0/133262487500007819/

**Comment by penkamaster** [comment]
thank you for your quick reply.
I'm at work, when I get back home I'll try it.
Thank you very much for the suport and for developing this interesting project.

**Comment by buppa-burst** [comment]
Hello

I also confirmed that SteamVR got an error in the same way.("A key component of Steam VR isnt working properly")
I have created driver.log according to the procedure. Since I upload the file, please look. 
[driver.log](https://github.com/polygraphene/ALVR/files/2045676/driver.log)
I am sorry if there was any mistake.

I support the development of ALVR.  I am looking forward to it！

**Comment by penkamaster** [comment]
Hi, this is the content of my log 

[18:40:53.442 726] driver_null: Serial Number: RG-001
[18:40:53.442 726] driver_null: Model Number: ALVR driver server
[18:40:53.442 726] driver_null: Render Target: 2048 1024
[18:40:53.442 726] driver_null: Seconds from Vsync to Photons: 0.005000
[18:40:53.442 726] driver_null: Display Frequency: 60.000000
[18:40:53.442 726] driver_null: IPD: 0.064000
[18:40:53.442 726] driver_null: EncoderOptions: -codec h264 -preset ll_hq -rc cbr_ll_hq -bitrate 30M -gop 120 -maxbitrate 40M -fps 60
[18:40:53.470 650] Using NVIDIA GeForce GTX 1070 as primary graphics adapter.
[18:40:53.470 650] UdpSocket::BindSocket successfully bound to 0.0.0.0:9944[18:40:53.470 650] Initializing CNvEncoder. Width=2048 Height=1024

[18:40:53.470 650] UdpSocket::BindQueueSocket bound queue port: 2.0.198.210:50898

[18:40:53.470 650] UdpSocket::Startup success
[18:40:53.476 634] NvEnc Encoder Parameters:
NV_ENC_INITIALIZE_PARAMS:
encodeGUID: h264
presetGUID: ll_hq
encodeWidth: 2048
encodeHeight: 1024
darWidth: 2048
darHeight: 1024
frameRateNum: 60
frameRateDen: 1
enableEncodeAsync: 1
reportSliceOffsets: 0
enableSubFrameWrite: 0
enableExternalMEHints: 0
enableMEOnlyMode: 0
enableWeightedPrediction: 0
maxEncodeWidth: 2048
maxEncodeHeight: 1024
maxMEHintCountsPerBlock: 00000090D29FCF18
NV_ENC_CONFIG:
profile: (default)
gopLength: 120
frameIntervalP: 1
monoChromeEncoding: 0
frameFieldMode: 0
mvPrecision: 0
NV_ENC_RC_PARAMS:
    rateControlMode: 0x8
    constQP: 28, 31, 25
    averageBitRate:  30000000
    maxBitRate:      40000000
    vbvBufferSize:   0
    vbvInitialDelay: 0
    enableMinQP: 0
    enableMaxQP: 0
    enableInitialRCQP: 0
    enableAQ: 0
    qpMapMode: disabled
    enableLookahead: 0
    disableIadapt: 0
    disableBadapt: 0
    enableTemporalAQ: 0
    zeroReorderDelay: 0
    enableNonRefP: 0
    strictGOPTarget: 0
    aqStrength: 0
    minQP: 0, 0, 0
    maxQP: 0, 0, 0
    initialRCQP: 0, 0, 0
    temporallayerIdxMask: 0
    temporalLayerQP: 0, 0, 0, 0, 0, 0, 0, 0
    targetQuality: 0
    lookaheadDepth: 0
NV_ENC_CODEC_CONFIG (H264):
    enableTemporalSVC: 0
    enableStereoMVC: 0
    hierarchicalPFrames: 0
    hierarchicalBFrames: 0
    outputBufferingPeriodSEI: 0
    outputPictureTimingSEI: 0
    outputAUD: 0
    disableSPSPPS: 0
    outputFramePackingSEI: 0
    outputRecoveryPointSEI: 0
    enableIntraRefresh: 0
    enableConstrainedEncoding: 0
    repeatSPSPPS: 1
    enableVFR: 0
    enableLTR: 0
    qpPrimeYZeroTransformBypassFlag: 0
    useConstrainedIntraPred: 0
    level: 0
    idrPeriod: 120
    separateColourPlaneFlag: 0
    disableDeblockingFilterIDC: 0
    numTemporalLayers: 0
    enableTemporalSVC: 0
    spsId: 0
    ppsId: 0
    adaptiveTransformMode: 0
    fmoMode: 0
    bdirectMode: 0
    entropyCodingMode: 0
    stereoMode: 0
    intraRefreshPeriod: 0
    intraRefreshCnt: 0
    maxNumRefFrames: 0
    sliceMode: 0
    sliceModeData: 0
    NV_ENC_CONFIG_H264_VUI_PARAMETERS:
        overscanInfoPresentFlag: 0
        overscanInfo: 0
        videoSignalTypePresentFlag: 0
        videoFormat: 0
        videoFullRangeFlag: 0
        colourDescriptionPresentFlag: 0
        colourPrimaries: 0
        transferCharacteristics: 0
        colourMatrix: 0
        chromaSampleLocationFlag: 0
        chromaSampleLocationTop: 0
        chromaSampleLocationBot: 0
        bitstreamRestrictionFlag: 0
    ltrNumFrames: 0
    ltrTrustMode: 0
    chromaFormatIDC: 0
    maxTemporalLayers: 0

[18:40:53.828 694] Closing old control client

**Comment by penkamaster** [comment]
i updated my c++ redistributable with 2017 becuase my Vive stop working.
Unistalled 2017 and reinstalled the 2015 one.

now my log is more similar to the one from buppa-burst

[23:36:49.345 986] driver_null: Serial Number: RG-001
[23:36:49.345 986] driver_null: Model Number: ALVR driver server
[23:36:49.345 986] driver_null: Render Target: 2048 1024
[23:36:49.345 986] driver_null: Seconds from Vsync to Photons: 0.005000
[23:36:49.345 986] driver_null: Display Frequency: 60.000000
[23:36:49.345 986] driver_null: IPD: 0.064000
[23:36:49.345 986] driver_null: EncoderOptions: -codec h264 -preset ll_hq -rc cbr_ll_hq -bitrate 30M -gop 120 -maxbitrate 40M -fps 60
[23:36:49.386 294] Using NVIDIA GeForce GTX 1070 as primary graphics adapter.
[23:36:49.386 294] UdpSocket::BindSocket successfully bound to 0.0.0.0:9944
[23:36:49.386 294] Initializing CNvEncoder. Width=2048 Height=1024
[23:36:49.386 294] UdpSocket::BindQueueSocket bound queue port: 2.0.195.233:50153

[23:36:49.386 294] UdpSocket::Startup success
[23:36:49.394 290] NvEnc Encoder Parameters:
NV_ENC_INITIALIZE_PARAMS:
encodeGUID: h264
presetGUID: ll_hq
encodeWidth: 2048
encodeHeight: 1024
darWidth: 2048
darHeight: 1024
frameRateNum: 60
frameRateDen: 1
enableEncodeAsync: 1
reportSliceOffsets: 0
enableSubFrameWrite: 0
enableExternalMEHints: 0
enableMEOnlyMode: 0
enableWeightedPrediction: 0
maxEncodeWidth: 2048
maxEncodeHeight: 1024
maxMEHintCountsPerBlock: 000000B9AA9FCE58
NV_ENC_CONFIG:
profile: (default)
gopLength: 120
frameIntervalP: 1
monoChromeEncoding: 0
frameFieldMode: 0
mvPrecision: 0
NV_ENC_RC_PARAMS:
    rateControlMode: 0x8
    constQP: 28, 31, 25
    averageBitRate:  30000000
    maxBitRate:      40000000
    vbvBufferSize:   0
    vbvInitialDelay: 0
    enableMinQP: 0
    enableMaxQP: 0
    enableInitialRCQP: 0
    enableAQ: 0
    qpMapMode: disabled
    enableLookahead: 0
    disableIadapt: 0
    disableBadapt: 0
    enableTemporalAQ: 0
    zeroReorderDelay: 0
    enableNonRefP: 0
    strictGOPTarget: 0
    aqStrength: 0
    minQP: 0, 0, 0
    maxQP: 0, 0, 0
    initialRCQP: 0, 0, 0
    temporallayerIdxMask: 0
    temporalLayerQP: 0, 0, 0, 0, 0, 0, 0, 0
    targetQuality: 0
    lookaheadDepth: 0
NV_ENC_CODEC_CONFIG (H264):
    enableTemporalSVC: 0
    enableStereoMVC: 0
    hierarchicalPFrames: 0
    hierarchicalBFrames: 0
    outputBufferingPeriodSEI: 0
    outputPictureTimingSEI: 0
    outputAUD: 0
    disableSPSPPS: 0
    outputFramePackingSEI: 0
    outputRecoveryPointSEI: 0
    enableIntraRefresh: 0
    enableConstrainedEncoding: 0
    repeatSPSPPS: 1
    enableVFR: 0
    enableLTR: 0
    qpPrimeYZeroTransformBypassFlag: 0
    useConstrainedIntraPred: 0
    level: 0
    idrPeriod: 120
    separateColourPlaneFlag: 0
    disableDeblockingFilterIDC: 0
    numTemporalLayers: 0
    enableTemporalSVC: 0
    spsId: 0
    ppsId: 0
    adaptiveTransformMode: 0
    fmoMode: 0
    bdirectMode: 0
    entropyCodingMode: 0
    stereoMode: 0
    intraRefreshPeriod: 0
    intraRefreshCnt: 0
    maxNumRefFrames: 0
    sliceMode: 0
    sliceModeData: 0
    NV_ENC_CONFIG_H264_VUI_PARAMETERS:
        overscanInfoPresentFlag: 0
        overscanInfo: 0
        videoSignalTypePresentFlag: 0
        videoFormat: 0
        videoFullRangeFlag: 0
        colourDescriptionPresentFlag: 0
        colourPrimaries: 0
        transferCharacteristics: 0
        colourMatrix: 0
        chromaSampleLocationFlag: 0
        chromaSampleLocationTop: 0
        chromaSampleLocationBot: 0
        bitstreamRestrictionFlag: 0
    ltrNumFrames: 0
    ltrTrustMode: 0
    chromaFormatIDC: 0
    maxTemporalLayers: 0

[23:36:49.456 216] Control buf: GetConfig

[23:36:49.456 216] Control Command: GetConfig 
[23:36:49.460 231] Control buf: GetRequests

[23:36:49.460 231] Control Command: GetRequests 
[23:36:50.143 909] Control buf: GetConfig

[23:36:50.143 909] Control Command: GetConfig 
[23:36:50.144 866] Control buf: GetRequests

[23:36:50.144 866] Control Command: GetRequests

**Comment by penkamaster** [comment]
I've updated to the latest Nvidia graphics driver and now it works!!!
Thank you!!!

**Comment by polygraphene** [comment]
Great!
Perhaps, it was caused by failure of NVENC.
Thank you for debugging!
