### ISSUE TITLE
Do you think that with this router ALVR will work?

### ISSUE THREAD

**Issue by NOScancel** [polygraphene/ALVR#502]
zyxel 8825 b50b:
Multy Pro AC2400 VDSL2 Combo WAN Gigabit IAD
- 802.11 a/n/ac 5 GHz
- MU-MIMO support
My pc is thetered 1 meter from the router and the Quest will be 1.5 meters away from the router

**Comment by T3ER** [comment]
I got d-link ac750 (433mbps on 5ghz) on sale for half price and even it works perfectly fine on default alvr settings after I changed the router settings to use only 802.11n. Quest is barely over a meter away from router and pc is with 1m cable.
