### ISSUE TITLE
SteamVR Frozen

### ISSUE THREAD

**Issue by fullmetul** [polygraphene/ALVR#505]
I'm seeing a weird issue where ALVR is freezing upon loading into the steamVR room. 
I'm running this on bootcamp on a 2019 MBP with Radeon Pro 555X with 4GB dedicated VRAM, 16GB DDR4 main memory, and 2.2 GHz Intel Core i7.

The issue is when the ALVR app loads on the Quest I see the Steam VR room for just a hot second before the video completely freezes. If I display the steamVR view on the monitor display I see the headset is still sending the head-tracking and controller tracking data... it's just the display on the Oculus that's frozen.

What's even weirder is that this only seems to happen within the SteamVR room... the room setup screen, the welcome to VR tutorial, and even steam games work perfectly with ALVR on the multiple 5GHz routers.

If I load up Spider Man or Beat Saber using the trackpad, the headset leaves the SteamVR room and starts to load into the gaming apps just fine.

I've tried disabling the virus protection and the firewall on the machine and adjusting the resolution, codecs, bitrate, and buffer to every value imaginable. 

Steam VR seems to work fine when using a tethered headset on this machine, it's just the streaming to the Quest that seems to be broken.

Anyone else seeing any behavior like this?

**Comment by therealkeeg1** [comment]
I am having the same problem as you although i cant get anything to load. Did you find a solution?
