### ISSUE TITLE
Failed to initialize CEncoder

### ISSUE THREAD

**Issue by daizhuo** [polygraphene/ALVR#506]
Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc CreateEncoder failed. Code=22 NvEncoder::RegisterResources : m_nvenc.nvEncRegisterResource(m_hEncoder, &registerResource) returned error 22 at c:\src\alvr\alvr_server\nvencoder.cpp:542

I don't know why. It display these.
I use GTX 1060 and 5G router connect to Quest.
Thank you!

**Comment by JackD83** [comment]
Update to the latest nvidia driver. If you have a laptop with a nvidia and an intel gpu, you need to disable the intel gpu...

**Comment by steve-ddigital** [comment]
I had been using ALVR successfully for a couple of weeks after seeing this and updating to the latest NVIDIA drivers (at this time 436.30 running on a GTX 1080).  After using ALVR all day yesterday, I open it up today and it starts throwing the following error when launching SteamVR.

`Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc NvEncoderD3D11 failed. Code=10 NvEncoder::NvEncoder : m_nvenc.nvEncOpenEncodeSessionEx(&encodeSessionExParams, &hEncoder) returned error 10 at c:\src\alvr\alvr_server\nvencoder.cpp:51
`

I don't know of anything that changed overnight while the laptop was sleeping.

**Comment by steve-ddigital** [comment]
After a PC restart, uninstalling/installing SteamVR, getting the issue with SteamVR constantly starting in Safe Mode (without ALVR running), and trying to "Create a System Report" from SteamVR, SteamVR started working outside of Safe Mode again.

I hate computers.

**Comment by AndreyLebedenko** [comment]
If you are using a mobile chip (like i do), say 960M, then make sure you are using drivers of version 417.71 (or perhaps higher, but this version is 100% ok). You don't have to disable integrated Intel graphics.

**Comment by AndreyLebedenko** [comment]
One more note: as you know, GTX 960M does not support H.265 (HEVC), therefore, an attempt to start ALVR with this option selected in the "Video" tab will cause the application to stop with an error. Make sure you've selected H.264 and restarted the application before starting SteamVR.

**Comment by ItsHesus** [comment]
yo im a brainlet when it comes to computers and stuff, just like... what do I DO to fix this issue lol
