### ISSUE TITLE
Can't uninstall ALVR, no progress is made

### ISSUE THREAD

**Issue by aaronfranke** [polygraphene/ALVR#507]
![Untitled](https://user-images.githubusercontent.com/1646875/63451759-e9a6f800-c412-11e9-8e55-2dd45132a6c3.png)

I also noticed there was a "driver_uninstall.bat" in the "driver" folder, so I tried manually running that, and then running the uninstaller again, and it still doesn't uninstall.

**Comment by lcervo** [comment]
I have the same problem. after almost 1 year and no comments or solution yet.... wow
