### ISSUE TITLE
Question: Can I use vorpx with alvr and gear vr?

### ISSUE THREAD

**Issue by vrokolos** [polygraphene/ALVR#51]
Sorry but not really an issue. Had to ask though. Does it work ok? Thinking of buying vorpx.

**Comment by chapeka** [comment]
yes of course, i am playing this way RE7 and bioshok, it works perfect

**Comment by vrokolos** [comment]
Thanks

**Comment by vrokolos** [comment]
@chapeka  ok I bought it but there is a lot of stutter / lag on headtracking when on VR mode. In cinema mode it either works smoother or it's not that obvious since it's a bit far away. Have you solved this?
