### ISSUE TITLE
Using a school network to use ALVR - Not finding headset

### ISSUE THREAD

**Issue by TriCobalt** [polygraphene/ALVR#510]
Looked through a bunch of threads to try to find an answer for this one, but I couldn't get it to work.  I manually opened the ports needed and I couldn't get my computer to locate the headset, is it possible that my school network makes it impossible?  If so, what specifically might be causing it?

**Comment by JackD83** [comment]
You need a direct connection between your pc and the 5ghz access point. Your school network probably  has a firewall and switchs between them. Even if you could find the headset, it would not work very good
