### ISSUE TITLE
Oculus Quest Controllers not worked after last system update

### ISSUE THREAD

**Issue by graphicer** [polygraphene/ALVR#512]
Hello,
The oculus touch controllers do not work in the ALVR app after the last Oculus Quest update.
I had the same problem in my project.

You should add the following line to the AndroidManifest.xml file:
<uses-feature android:name="android.hardware.vr.headtracking" android:version="1" android:required="true" />

I have changed your ALVR client (APK file).

[ALVRClient-v2.4.0-alpha5-modified.zip](https://github.com/polygraphene/ALVR/files/3546780/ALVRClient-v2.4.0-alpha5-modified.zip)

Thank you for your Application. 
It was very useful to me.

(I'm sorry for my bad english)

**Comment by cain0z** [comment]
Thank you that fixed my issues

**Comment by DavisNT** [comment]
For Oculus Quest you can try [JackD83's fork](https://github.com/JackD83/ALVR). 
It works only with Quest, and it has several Quest specific improvements.
