### ISSUE TITLE
Only One Touch Controller is Being Read At A Time

### ISSUE THREAD

**Issue by WoodEMeister** [polygraphene/ALVR#514]
AVLR runs very smooth on my Quest. I was able to play FNaF Help Wanted with a very good connection. The only issue is that it's only letting me use one touch controller at a time. I'm able to switch hands if i press a button on the other controller, but is there a way to have both controllers read at the same time, so i can use both hands. Thanks!

**Comment by bosssu** [comment]
same

**Comment by zarik5** [comment]
Development on ALVR has moved here: https://github.com/JackD83/ALVR
