### ISSUE TITLE
My alvr app won't open

### ISSUE THREAD

**Issue by tecmine** [polygraphene/ALVR#515]
Whenever I open the alvr desktop app it doesn't do anything

**Comment by wonson** [comment]
are you using stable version?

**Comment by tecmine** [comment]
no

**Comment by pherplayde** [comment]
Same for me. It worked perfectly for about a week for me eventhough I had to take a hotfixed v5 apk. 
ALVR.exe also lost its icon and went to windows default. If I fastly open ALVR.exe like 5 times a msgbox says something like "ALVR is already running"
