### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by cpgb85** [polygraphene/ALVR#518]
This project dead?

**Comment by DannyDan** [comment]
yeah. it seems so. I asked this question some weeks ago and someone replied, that the dev is only on vacation. thats some loooong vacation. ;)

**Comment by cpgb85** [comment]
It's a shame.  This is so good compared to riftcat. I would be willing to pay a fee if it were paid software

**Comment by SnyderTheOne** [comment]
There seem to be a couple of active forks however. For example: https://github.com/JackD83/ALVR

**Comment by highvrahos** [comment]
> There seem to be a couple of active forks however. For example: https://github.com/JackD83/ALVR

I can confirm @JackD83's fork on the Quest works perfectly with a proper setup (wired 5GHz router).

**Comment by FingrMastr** [comment]
Please note that @JackD83’s is a “quest only” version. But since the last stable version of @polygraphene’s is perfectly working on gearVR and OculusGO, all devices all covered...
