### ISSUE TITLE
ALVR over internet?

### ISSUE THREAD

**Issue by Lightsteed** [polygraphene/ALVR#52]
Would it be possible to run ALVR over internet like you can with moonlight or streamtheater? I imagine the lag would be nauseating but would be an interesting experiment.

**Comment by Jbbrack03** [comment]
It is possible! Take a look at the guide that I posted in the Wiki for ideas. It's based on using a Cloud Gaming server, but you could technically use the same methods if you're hosting yourself. The key would be having enough internet upload speed to make it a good experience. Keep in mind that ALVR recommends a 30 Mbps connection. So your internet should have at least that much upload to handle it smoothly.

https://github.com/polygraphene/ALVR/wiki/Setting-up-ALVR-for-VR-Cloud-Gaming-(no-Gaming-PC-required)

**Comment by Lightsteed** [comment]
I have 80Mbps upload and download.. ill see if i can get it working

**Comment by polygraphene** [comment]
It's a interesting idea.
It would be nice if ALVR works good over the Internet.

But, we need a lot of work for solve some problems (e.g. securiy, performance) if using over the Internet.

Currently, I recommend to use VPN if you want using the Internet like the above article.

**Comment by Lightsteed** [comment]
Yeh for sure. Ill give it a go on vpn and see how it fairs

**Comment by Lightsteed** [comment]
I tried this method using the inbuilt windows 10 vpn, connected successfully with my phone and made a hotspot then connected the GO. It was working and pulling 30Mbps up and down on the go, however alvr did not find the client. Ill try it qith zero tier next and see if it can work.

**Comment by vrokolos** [comment]
vpn is probably fine for doing this but it would be a lot easier just having a "allow this device to connect over the internet" checkbox next to "auto-connect". Also a setting for host ip address somewhere on the server settings so we can enter "something.dyndns.org" and this gets sent to client next time it connects to the server on the local network.

**Comment by Lightsteed** [comment]
I couldnt get it working thru my mobile phone with zerotier and wifi hotspot. But i wasnt able to do some of the steps without using a router and wrt so not surprising i suppose. I dont rly know how zero tier works tho, its all very complicated. Mabe you want to test that setup and let me know if u can work it. The vpn did connect, just didnt find alvr again.

**Comment by polygraphene** [comment]
ALVR uses broadcast packet to detect clients. So you must put ALVR server and client on the same subnet.
For example, if ALVR server is on 192.168.1.2, the client must have address 192.168.1.*.

Therefore we need layer-2 VPN which can transport broadcast packets.
I think you are using layer-3 VPN. Please check IP Address on both server and client.

**Comment by Jbbrack03** [comment]
Right, the key with my guide is that the VPN Router is acting as a wireless bridge to the VPN network. It’s making sure that your headset ends up on the same ZeroTier subnet as your server. So it won’t work over a hotspot unless someone comes up with a ZerTier client for the Go. Which is possible, but beyond my skills. I’m a network guy, not a programmer.

**Comment by Lightsteed** [comment]
I see. Well i do have an asus router that can take internet (wan) from my mobile via usb, so i guess ill try that avenue next to test it.

**Comment by Lightsteed** [comment]
Btw- the zerotier client works on the go, you can configure it using Vysor.. but its still not working. any ideas?

**Comment by Jbbrack03** [comment]
Did you setup the ZeroTier network to use the IP’s and ranges from the guide? Did you uncheck the IPv6 box on the ZeroTier page? Did you assign the proper IP’s and enable both the Cloud Server and the Go on the ZeroTier page?

**Comment by Lightsteed** [comment]
Yep i did all those things except instead of using the ips u gave i used similar ones in the same range as my home network (10.1.1.1) would that mess it up?

**Comment by Lightsteed** [comment]
okay i changed the settings to exactly in your guide and still no go. the VPN is definately working though as the go is showing the same web ip address as my pc, and doing a speed test shows that the internet connection is through my home ISP, even tho the go is connected to the web via my mobile LTE

**Comment by Jbbrack03** [comment]
On the headset side of things, the setup will be the same as the Gaming PC at home. So we aren’t checking the bridging box on the ZeroTier Page. Did you manually assign the headset an IP in the 10.99.5.x range? Are both the headset and Gaming PC showing that they’re online on the ZeroTier network page? In the ZeroTier App on the Go, does it show that it’s connected and that the Status is Ok?

**Comment by Lightsteed** [comment]
Ahh ok ill try unclicking the bridging then. And yes i manually assigned ip addresses for both but only on the zerotier page as there is no way to assign an ip on the go itself for the phone hotspot connection

**Comment by Lightsteed** [comment]
And yes both are online with good status

**Comment by Jbbrack03** [comment]
The only other detail that makes my setup different from yours is that my local network is setup for a 192.168.1.xxx subnet. Not sure if that will make a difference, but you're using a similar IP range to what's setup on the ZeroTier network. Might make a difference to switch your router to 192.168.1.xxx and see if it changes anything.

**Comment by swmarc** [comment]
I got it to work with SoftEther.
I use a thin client (but any PC will do it) with Windows here for Shadow that also acts as the SoftEther VPN daemon. I also connected my Oculus by USB-ethernet, but a WiFi dongle connected to the thin client would do it also.
It's way easier to set up and less costly. For USB-Ethernet beware that not all dongles are compatible with the Oculus.

Just before, don't use the SoftEther VPN protocol. As far as I remember it is Ethernet over HTTPS and results in heavy packet loss when streaming (350000 loss were just 150000 were successfully sent).

For the SoftEther daemon you'll need L2TP over IPSec and EtherIP/L2TPv3 over IPSec enabled.
SoftEther is already listining on TCP port 443, but you may also need to open the port in your firewall settings. On the routers side, forward port 443 on TCP.
That's it on the Shadow client side.

On the Shadow PC install the SoftEther client and just create a new connection with the host/IP to your home. The default port 443 is already the correct one. On the right hand side enter your credentials you previously defined in the SoftEther daemon. Connect and ALVR will find your Oculus device.

Unfortunately, there's a caveat. Here I have some small random distortions in the video stream. I'm not 100% sure, but as ALVR still shows me some package loss and that's might the reason for that, if the displayed information is correct.

**Comment by swmarc** [comment]
After playing around a while with settings, reducing the packet loss, I fiddled out a setup that is far from perfect, but quite usable.

In the SoftEther client, so on the remote (Shadow) PC, right click on the connection and select "Properties". In the lower right click "Advanced Settings" and on the right hand side check "Disable UDP Acceleration". Save and reconnect.
Depending on the video bitrate and video content the packet loss rate is something between 0 and 40 now. Before with just a 5 Mbps video bitrate, I had a packet loss of ~1500 per second. Sometimes even higher.

In the ALVR video configuration set HEVC/6 Mbps/3072x1536 resolution & keep the buffer size at 200kB. The ALVR buffer size didn't really make a difference for me. Just too high values was even worse.
You could play around with the bitrate, but my reasonably acceptable limit were around 8 Mbps. With each MBit higher the packet loss significantly increases.

**Comment by da3dsoul** [comment]
My main thing is that we just got access to an Oculus Quest. Due to the portable nature of it, I figured it'd be cool to leave the processing to the beast under the desk at home rather than trying to make a sad laptop try to keep up. Thanks for all of the tips. I'll see what I can get working.

**Comment by jaroslaw-weber** [comment]
It would be great to make it work without second router and additional software...
