### ISSUE TITLE
Quest SteamVR not finding tracking data

### ISSUE THREAD

**Issue by kilrah** [polygraphene/ALVR#523]
Quest up to date on 8.0.0.135.626
SteamVR 1.6.10
ALVR server+client 2.4.0-alpha5

Server finds client no problem, launches SteamVR, SteamVR sees a device but "cannot detect position information for this headset".
Quest is in a guardian zone and tracking.

**Comment by DavisNT** [comment]
For Oculus Quest you can try [JackD83's fork](https://github.com/JackD83/ALVR). 
It works only with Quest, and it has several Quest specific improvements.
