### ISSUE TITLE
Keys Sold Out

### ISSUE THREAD

**Issue by DeadSpace72** [polygraphene/ALVR#525]
When I try to get my oculus distribution key to put in my phone it says "sold out"

**Comment by iracoon** [comment]
I'm getting the same issue

**Comment by ScottVards** [comment]
Same here

**Comment by iracoon** [comment]
would sideloading the app get around this issue?

**Comment by polygraphene** [comment]
> would sideloading the app get around this issue?

Yes.

**Comment by polygraphene** [comment]
I added new keys! Thank you for reporting.

**Comment by polygraphene** [comment]
I added new keys. Please try it.
