### ISSUE TITLE
Oculus Quest freezes when steamvr is open

### ISSUE THREAD

**Issue by therealkeeg1** [polygraphene/ALVR#529]
I am running 2.4.0-alpha5, i can connect my headset with my pc no problem but as soon as i launch steamVr the headset freezes on a whitescreen and nothing happens. If i go to steamvr on my computer and view the VR Viewer i can see from the headsets perspective. Its tracking completly fine, i can even see the controllers too but it just wont display on the headset.

**Comment by DavisNT** [comment]
For Oculus Quest you can try [JackD83's fork](https://github.com/JackD83/ALVR). 
It works only with Quest, and it has several Quest specific improvements.
