### ISSUE TITLE
Latest version has really bad packet loss issues.

### ISSUE THREAD

**Issue by vrokolos** [polygraphene/ALVR#53]
1.9.2 works almost fine with 100mbit on my wifi

This 2.0.2 latest version is a disaster here. I can only do 20mbits or lower without having packet loss and everything seems way worse than it was.

Did you change something? I tried both the versions multiple times and the results are consistent.
Was trying with skyrim VR

**Comment by TyrannicalBlade** [comment]
Not as drastic results here but, I also had to lower my mbit bandwith to not get much packet loss, back in 1.9.2 i was able to do 30mb fine, and now its about 20 and still experience some

**Comment by polygraphene** [comment]
Can you send me a logcat?
ALVR Client outputs a lot of log about performance.

**Comment by vrokolos** [comment]
Where can I find those? Do I have to enable "debug log"?

**Comment by polygraphene** [comment]
I mean `adb logcat` on Command Prompt.

**Comment by vrokolos** [comment]
I will try to do that later tonight when I get home

**Comment by vrokolos** [comment]
It works ok today. Weird. I'll let you know if it happens again.

**Comment by vrokolos** [comment]
I'm thinking the packet loss was the result of me messing with process priority of files on task manager. Generally I think I see packet loss happening when frame drops / hdd reads occur. Do you perhaps know of any setting of process priorities I should use in order to make streaming better? Out of all those VR processes which ones should I raise priority?

**Comment by TyrannicalBlade** [comment]
[logcat1.txt](https://github.com/polygraphene/ALVR/files/2104329/logcat1.txt)
The packet loss been insane today, and i am unsure whatever is something i did, i feel like, it might be something to do with my router, but i haven't figure out, This is from last version, i'll try using 1.9.2 to see if its any different and send you a logcat of that as well

**Comment by TyrannicalBlade** [comment]
Yeah i confirmed was my router settings that were messed up, fixed and its working fine again on last version

**Comment by polygraphene** [comment]
@vrokolos ALVR server driver (driver_alvr_server.dll) is responsible for video encoding and packet transfer and which run in vrserver.exe.
I have not tried yet, but setting high priority on vrserver.exe may produce a good result.

@TyrannicalBlade Good! I'm glad the problem was solved.

**Comment by vrokolos** [comment]
Retried high priority all vr processes and it works ok. my packet loss vanished completely.
