### ISSUE TITLE
ALVR kills 5g

### ISSUE THREAD

**Issue by ProletarianSean** [polygraphene/ALVR#531]
I can't quite find this problem elsewhere, despite seeing vaguely similar things--clicking "Start Server" on ALVR completely kills my router's 5g (Netgear Nighthawk r7000) within about 20 seconds. I can actually run ALVR and Steam VR on the 2.4g just fine, except that (of course) it's nothing but a nightmare of screen tears and vomit comets, while if I rush, I can usually see about three seconds of the very nice SteamVR tutorial room before all connected devices lose their connection to the wifi (phones, tvs, anything else--it just drops dead for a good while). If I click "Start Server," it is inevitable that my wifi will drop dead, regardless as to what I do. I can almost immediately see the default steam space on my headset, but will quickly end up again in the AVLR "Connect" room because my connection will die. I can confirm this is ONLY after starting the server; ALVR can connect to my headset (Quest) and stay apparently connected indefinitely.

There's nothing I can see in my router settings that would relate to this, so far as I know. Firewall settings appear correct. I've tried a few other things I've seen in other threads as well (one was to lower Steam's ping rate from 5k to 150 / 250) but none of them have changed this; the internet instantly dies. I have gone backwards through several iterations of firmware for my router to make sure that isn't the problem.

My system specs are ludicrous, just got a new computer with a 2080. Looks beautiful for the three seconds I can see.

**Comment by DavisNT** [comment]
This looks like wifi issue (as traffic should not crash routers - especially around 30 Mbps traffic). 

For Oculus Quest you can try [JackD83's fork](https://github.com/JackD83/ALVR). It might recover better on packet loss and have additional improvements.
