### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by itsharvyt** [polygraphene/ALVR#532]
Nothing happens when i connect
![Capture](https://user-images.githubusercontent.com/54998097/65984627-19b4d280-e478-11e9-8a43-99bfe347fa26.PNG)

**Comment by Marus** [comment]
Yeah - I'm getting the same type of thing when I try - but head set still tells me to press the connect button.

**Comment by DavisNT** [comment]
For Oculus Quest you can try [JackD83's fork](https://github.com/JackD83/ALVR). 
It works only with Quest, and it has several Quest specific improvements.
