### ISSUE TITLE
High latency no matter what

### ISSUE THREAD

**Issue by Raging-Beard** [polygraphene/ALVR#539]
Running v7 and using 5Ghz router.
Foveated Rendering on Slices at 2.0, everything else default and if I set Bitrate to 1 I still get Total Latency of about 51-65.
At a Bitrate of 70 latency is 65-72.
Is this normal?

**Comment by HolyCaonima** [comment]
That`s correct. The latency comes from 3 part. The encoding latency, transporting latency and the decoding latency. Reduce Bitrate only help to reduce the encoding latency and decoding latency and slightly transporting latency. The video decoding in quest device side cause a big deal.
