### ISSUE TITLE
controllers not working

### ISSUE THREAD

**Issue by 1Mist1** [polygraphene/ALVR#540]
for some reason the controllers wont work for me it only shows on but as a htc vive controller and all the buttons dont work. 
![Screenshot (7)](https://user-images.githubusercontent.com/56738767/67119616-84267c00-f1b5-11e9-8165-0595244a372f.png)

**Comment by Nicolleta** [comment]
Same problem I am having.

**Comment by kikoano** [comment]
My oculus go controller is also not working in the newest experimental verison, Will be nice if someone fix that.

**Comment by zatdevil** [comment]
Same problem but is there a way to repair it ? someone find something ??

thanks !

**Comment by LibreGit** [comment]
Use the https://github.com/JackD83/ALVR fork. It solves the controllers issues and has a lot of improvements as well. This is the most up to date version of ALVR.

**Comment by sammiestarshine** [comment]
the only thing missing from this newest update is the ability to add fake base stations that some games require
