### ISSUE TITLE
ALVR Error

### ISSUE THREAD

**Issue by strawbberrys** [polygraphene/ALVR#541]
I keep getting this error with ALVR. I have a NVIDIA GPU and stuff like that. My hard drive just got replaced but before it got replaced I used ALVR for my quest just fine. I don't know why this error is happening. Help?

Cannot load library. ALVR works only on 64bits Windows with NVIDIA GPU. C:\Program Files\driver\bin\win64\driver_alvr_server.dll Code:0

**Comment by xxValiumxx** [comment]
Sounds like you might have gotten the 32 Bit version of Windows accidentally.

**Comment by helpforsupport** [comment]
> Sounds like you might have gotten the 32 Bit version of Windows accidentally.

Thats impossible because it says I have windows 10 64 bit. 
![image](https://user-images.githubusercontent.com/56797207/67527679-9016b000-f685-11e9-9010-8b7542d12c8e.png)

**Comment by gunnarweibrink** [comment]
> Cannot load library. ALVR works only on 64bits Windows with NVIDIA GPU. C:\Program Files\driver\bin\win64\driver_alvr_server.dll Code:0

Really?
Missing something like "C:\Program Files\**ALVR\**driver\bin\win64\driver_alvr_server.dll".
Copy the whole thing to C: eg. "C:\ALVR\... and try again.

**Comment by helpforsupport** [comment]
I copied the ALVR Folder into my C: Drive. This fixed the issue.

**Comment by TashaSkyUp** [comment]
I'm having this problem. I however am not building from source. C++ is not something i'm familiar with. might this be because my steam install is not on C: Drive?

**Comment by codewing** [comment]
I've resolved the problem by adding the ``avutil-56.dll`` and ``swresample-3.dll`` next to the ``driver_alvr_server.dll`` in the folder ``driver\bin\win64`` which needed to be added as a subfolder where the ALVR.exe resides in.

I've got these dlls from the binary build but from what I saw you probably can build them yourself by building the code in ``ALVR\libswresample``.

**Comment by UnderCraft42** [comment]
I'm having a problem where whenever I start server it says server down then a pop up appears I agree to it then it disappears. after that another pop up appears and says Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc NvEncoderD3D11 failed. Code=1 NvEncoder::LoadNvEncApi : NVENC library file is not found. Please ensure NV driver is installed at C:\Dev\repos\ALVR\alvr_server\NvEncoder.cpp:70

Please help
