### ISSUE TITLE
HOW DO I UPDATE THE OCULUS  QUEST CLIENT 

### ISSUE THREAD

**Issue by gib1232** [polygraphene/ALVR#544]
So i have some issues with the oculus quest and alvr . i have the newest version on pc but on quest i have the experimental v7 how is that possible and how to fix. Please help

**Comment by codewing** [comment]
Generally if you need help with anything describe in detail what you did and at which step you've failed. Additionally you can add what you've already tried to solve the problem. 

Questions like "i have some issues" without any context don't provide enough background to be able to help you.
