### ISSUE TITLE
ALVR Controller mapping request

### ISSUE THREAD

**Issue by Ekristoffe** [polygraphene/ALVR#546]
Hello, depending of the game we need this or that configuration to go in the menu.
Is it possible to add some kind of preset depending of the game we are playing ?
Also a return to default button should be nice to have (I have lost my default configuration).
Anyone has a screenshot of the controller settings view by default ? thanks.

**Comment by dennisjerdz** [comment]
I'm having the same problem. I hope someone could help.

**Comment by Jimmy5k** [comment]
I had to fiddle about with settings. the mapping still isnt great, but the triggers work now.
I dont know if its to do with steamVR but the controllers are still set to look like Vive.
It's as though the controller buttons arent replicating into a customisable format (doesnt recognise certain button presses). I guess this guy is getting smashed with reports.
Also it took dropping the VR and reconnecting from SteamVR to help fix a few problems. 
Do you guys have both controllers active at the same time?

**Comment by Ekristoffe** [comment]
I can't say, I am using a Oculus Go which only have one controller. I gess you have the Quest with 2 controller.

**Comment by Jimmy5k** [comment]
> 
> 
> I can't say, I am using a Oculus Go which only have one controller. I gess you have the Quest with 2 controller.

Thats right. i assumed you were in the same boat.
Did this work ok in alpha v4? from what i'm reading in posts, when they've tried to integrate the second controller (Alpha 5-quest), things got wierd.
also i think i had to change the buttons in ALVR Server - controller tab

in addition, you can change the controller type in SteamVR to an oculus touch. unsure if that's a rift-S thing or if thats a generic term for oculus controls. from there you can 'test' controls.

But like i said, initially i had to push both X and Y and the menu came up. all i can say is trial and error and something might happen.

This is an Alpha thing so there's bound to be a bunch of ... unusual things happen.
