### ISSUE TITLE
Oculus Go - Headset not found (same network)

### ISSUE THREAD

**Issue by ghost** [polygraphene/ALVR#549]
I cannot get the ALVR app to find the headset, I've tried turning off the firewall and got nothing.

I can ping the headset from the PC but I tried to ping the PC from the headset using ADB and got no response so it seems as if it can't connect to the PC. Which is weird because I am able to use other local apps such as Plex's DLNA server and SkyboxVR's airscreen feature and also Virtual Desktop which correctly shows the PC's local IP address.

Not really sure what's going on here. Also I'm a bit of a newbie when it comes to network stuff so I'm just a bit lost here.

**Comment by cod0rama71** [comment]
I got it working by using this build:

https://github.com/JackD83/ALVR/releases

I also installed the APK in that latest release using ADB to my Go. Working flawlessly now.

**Comment by buddyboi7145** [comment]
I don't really get whats ADB can u help me cuz I'm new to  oculos go

**Comment by Ekristoffe** [comment]
@cod0rama71 I would really appreciate if you or someone else made a "how to" about installing ALVR by using ADB. lot's of non techies have trouble with ADB and I think this should be somewhere on the ALVR wiki ...

**Comment by kikoano** [comment]
> I got it working by using this build:
> 
> https://github.com/JackD83/ALVR/releases
> 
> I also installed the APK in that latest release using ADB to my Go. Working flawlessly now.
> 
> If anyone is having the same issue as me just do that, should be good.

How did you manage to get it working with the Go controller with that version? They deleted the Go controller support.

**Comment by velteyn** [comment]
could it be a IPV6 / IPV4 problem ??

**Comment by CodeMonk** [comment]
Pretty sure it's a port 9944 vs 9943 issue
