### ISSUE TITLE
Using ALVR with Revive for Rift Games

### ISSUE THREAD

**Issue by Jbbrack03** [polygraphene/ALVR#55]
I just downloaded the latest stable release of Revive and tested a few games with ALVR. As soon as you launch a game with Revive, the ALVR client on the headset disconnects. The server on the PC still thinks that it's connected, and SteamVR still thinks that it's connected. Happens in every game that I tested through Revive.

It would be great to be able to use ALVR with Revive since there are some good exclusive games that aren't available through Steam.

**Comment by kgian** [comment]
I tried quickly dreamdeck with alvr and revive and it worked fine!

**Comment by Jbbrack03** [comment]
We’re you using ALVR server 2.0.2 and ALVR 2.0.2 from the Oculus Store? Are you using a Go or a Gear headset?
