### ISSUE TITLE
Nvidia p106

### ISSUE THREAD

**Issue by etempm** [polygraphene/ALVR#550]
I have a nvidia p106 (gtx 1060 6gb) gpu. It has no output socket, no hdmi or any output. Can i use that gpu for Alvr rendering? I am also using rx550 for output. If possible it will be great for me.

**Comment by RAJ-Huff** [comment]
Yes, and you may not even need custom drivers/firmware.  If you can set ALVR to use Nvidia GPU in the Nvidia Control Panel, start the server and see if the compositor runs.  If it doesn't here's a related video that has some useful info to make it work.
https://www.youtube.com/watch?reload=9&v=TY4s35uULg4
