### ISSUE TITLE
Oculus Quest - Headset not found 

### ISSUE THREAD

**Issue by Schnoinsch** [polygraphene/ALVR#552]
Hey guys,

got the issue that my Quest is not found. Computer is on the same router via cable like the wifi of the quest. Installed newest APK and newest software for PC.
On my laptop it sometimes finds the Quest, but since it´s a crappy (only tried it for the sake of trying all options) one, it crashes when starting the server. 

I just can´t get my computer to "see" the Quest. Any suggestions?

Greetings, Schnoinsch

**Comment by Ekristoffe** [comment]
Hello, for the quest please look at this fork:
https://github.com/JackD83/ALVR
It is specially developed for the quest.
