### ISSUE TITLE
Unhandled Exception. ExceptionCode=C0000005 Address=00007FF9BAE150D4 (00007FF9C8A10000 + FFFFFFFFF24050D4)

### ISSUE THREAD

**Issue by Schnoinsch** [polygraphene/ALVR#553]
Getting error code above. Finds headset without any issue but when starting the server, it crashes. Also, SteamVr says when starting it, it´s unable to update because it´s runnig.

**Comment by Jimmy5k** [comment]
I used to have an exception code every time.
What're you running? 
changing my vid card worked (can your card support VR? needs to be pretty beefy)

My rig now has a 1660TI, changed from a Radeon 550.
That's the only thing I changed. as the ram, and CPU were plenty alright for use for VR.
