### ISSUE TITLE
Quest controller Problems

### ISSUE THREAD

**Issue by AsusAlex** [polygraphene/ALVR#556]
It only registers 1 controller at a time When pressing a button on the right controller it shows the left controller as "dead" and same with the left one

**Comment by spiegela** [comment]
I'm having the same issue with ALVR.  Its only recognizing a single controller at a time.

**Comment by Jimmy5k** [comment]
me too. there were a bunch of issues with my controller mapping. 
i'm getting through them slowly, but can't think around the one-at-a-time controller issue.

**Comment by marcelbrode** [comment]
same here

**Comment by solspire** [comment]
You need a custom alvr for oculus (patch controler). I don't find a link of that sorry

**Comment by Jimmy5k** [comment]
I picked up the experimental version that one of polygraphene's mates seems to be working on.
(uninstalled ALVR version from headset and uninstalled alvr server. installed experimental version on headset and extracted the standalone application and ran it on the PC).

worked perfect

**Comment by spiegela** [comment]
@Jimmy5k Is [this the fork](https://github.com/JackD83/ALVR) you installed from?  There are a couple of pretty active forks that look like prime candidates?  Did you need to build these from source, or are the binaries for the experimental branch posted somewhere?

Thanks in advance!

**Comment by Jimmy5k** [comment]
Yep, thats the fellah.
Traversing the Github is a bit ... ungainly. well, for me anyway. I'm not that smart.
There are install files if you go to his alvr page and look for 'releases'.
To be honest, I cant recall which 'Experimental' version I acquired.
As indicated, you'll have to uninstall the old ALVR from both headset and PC.
