### ISSUE TITLE
SteamVR Not Found

### ISSUE THREAD

**Issue by ghost** [polygraphene/ALVR#559]
so i am trying out ALVR for the first time and im watching videos on how to do it, but i can never get past the "install SteamVR" part. i do have it installed (i dont have a steam vr headset but i have it installed) and when i try to run steam vr it says running for 3 secounds then stops. nothing opens. and when i try to open ALVR on my computer, it says "No SteamVR installation found." but i know i have it. Please help, Thanks!
![2019-12-10](https://user-images.githubusercontent.com/58752579/70573777-a6fb5e00-1b70-11ea-8054-37200b65aa23.png)
![2019-12-10 (1)](https://user-images.githubusercontent.com/58752579/70573872-ceeac180-1b70-11ea-85db-7150d423f79d.png)

**Comment by mrpeoplzzz** [comment]
also i am reinstalling it to see if that is the problem

**Comment by lancodec** [comment]
need install SteamVR in STEAM

**Comment by mrpeoplzzz** [comment]
I did (as shown in the second picture) and it still doesn’t work

**Comment by mrpeoplzzz** [comment]
You can’t really see it very well but that is the steam be page on steam and it’s installed and ready to be played

**Comment by krunkster** [comment]
I believe the cause of this is that new installations of SteamVR are not into a directory named OpenVR
I was able to workaround this issue by creating a symbolic directory link.  From the target directory you can run this command "mklink /D SteamVR OpenVR" (you will need to run the command prompt as administrator as well)

**Comment by victorkc** [comment]
Hi,
 
Maybe this won't work for all but I had the problem and I solved this just starting SteamVR first and then initiate ALVR, for me works.

Regards.
