### ISSUE TITLE
Microphone streaming in the future

### ISSUE THREAD

**Issue by vrokolos** [polygraphene/ALVR#56]
A lot of VR games use the microphone.
I know you have sound streaming and h265 on your future features but I'd also love using the microphone from the device / headphones.

**Comment by Lightsteed** [comment]
Just get a bluetooth mic/headphone dongle in the meantime. Cheap as chips and probs better to not take bandwidth away from the video anyways

**Comment by vrokolos** [comment]
I do have one but the sound quality when connected to my windows 10 pc is awful. On my phone it's fine however. Bluetooth on windows sucks

**Comment by polygraphene** [comment]
Thank you for comments!
It would be nice if we can play games like VRChat with completely wireless.
I will add this to feature request list.

**Comment by madjin** [comment]
This would be a most excellent feature! Microphone streaming would be the last layer of friction needed to be reduced for a seamless experience and would make demoing so much easier. I bought a $30 wireless bluetooth headset but it keeps running out of battery and its annoying to constantly put on/take off and reconnect when I want to jump into ALVR + social VR programs.
