### ISSUE TITLE
error uhhh what does this mean

### ISSUE THREAD

**Issue by huskyredfox** [polygraphene/ALVR#566]
Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc CreateEncoder failed. Code=15 NvEncoder::CreateEncoder : m_nvenc.nvEncInitializeEncoder(m_hEncoder, &m_initializeParams) returned error 15 at c:\src\alvr\alvr_server\nvencoder.cpp:271

**Comment by huskyredfox** [comment]
also i have a gtx 1060 with 16 gbs of ram

**Comment by RAJ-Huff** [comment]
Without further specifications provided, I'm going to assume this is a laptop or some system using Intel built-in graphics.  In the Nvidia Control Panel>Manage 3D Settings>Program Settings add ALVR and set it to use the Nvidia GPU.  You may want to configure PhysX the same way.
Video RAM is far more important to VR than system memory, the desktop GTX1060 comes in a sufficient 3GB and a plentiful 6GB variety.
Make sure SteamVR is not already running when you start the ALVR server.
