### ISSUE TITLE
Can't disable SteamVR Safe Mode without ALVR crashing

### ISSUE THREAD

**Issue by LemonHeist** [polygraphene/ALVR#567]
> Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc NvEncoderD3D11 failed. Code=1 NvEncoder::LoadNvEncApi : NVENC library file is not found. Please ensure NV driver is installed at c:\src\alvr\alvr_server\nvencoder.cpp:70

This is the error message I recieve every time I try to disable Safe Mode on SteamVR. ALVR was loaded without much issue onto my Oculus Quest, and I've connected ALVR to my Oculus, and have installed SteamVR. However, every time I load up SteamVR, it loads in Safe Mode, and I can't disable it without ALVR crashing.

This feeds into a larger problem of mine where SteamVR is unable to detect the Oculus Quest, but I'd like to take things one step at a time.

**Comment by RAJ-Huff** [comment]
One step at a time would require you to provide hardware information.  Based on very little detail, it appears that you may be using a computer with incompatible graphics.

**Comment by lemmy04** [comment]
I am having the same problem: #575 

My hardware: Acer E5-571, Intel i5, Intel graphics + nvidia optimus, the nvidia card's a Geforce 840M.

Switching to "use nvidia" as the default adapter does not help.

**Comment by RAJ-Huff** [comment]
> I am having the same problem: #575
> 
> My hardware: Acer E5-571, Intel i5, Intel graphics + nvidia optimus, the nvidia card's a Geforce 840M.
> 
> Switching to "use nvidia" as the default adapter does not help.

Hi lemmy04,
I've replied to your other thread.  https://github.com/polygraphene/ALVR/issues/575
