### ISSUE TITLE
it says no headset found on steamVR wean it lanchs

### ISSUE THREAD

**Issue by pewpewgamer** [polygraphene/ALVR#570]

**Comment by RAJ-Huff** [comment]
You need to open ALVR and 'start server' there, opening SteamVR any other way will result in failure.

**Comment by Pizzaaboi** [comment]
> You need to open ALVR and 'start server' there, opening SteamVR any other way will result in failure.

Does that button appear without ALVR seeing the headset? it's not detecting the headset for me and I cant see a "start server" button.
