### ISSUE TITLE
server not starting

### ISSUE THREAD

**Issue by snake243X** [polygraphene/ALVR#571]
i installed ALVR to play vr games on my olocus go it is installed on my go and is waiting to connect to server. on the ALVR pc app the server is still "finding headset" please help.

![Screenshot (11)](https://user-images.githubusercontent.com/50460151/71497590-ea1f2780-2826-11ea-8c5f-5227fdde07ac.png)

**Comment by RAJ-Huff** [comment]
Make sure that the oculus is on the same wi-fi network and that you have added a firewall rule to allow ALVR.
