### ISSUE TITLE
ALVR Games loading on Monitor not Headest (QUEST)

### ISSUE THREAD

**Issue by Frase32** [polygraphene/ALVR#572]
Hi Guys I have got alvr alpha 5 working on both headsets but when I launch DCS in steam the game loads onto the monitor and not the headset? I have seen similar issues with the rift but not much mention with the quest? 

Does anyone have any solutions?

**Comment by RAJ-Huff** [comment]
Are you launching the VR version, or the desktop version via steam?

**Comment by lemmy04** [comment]
I'm having the same issue with Elite: Dangerous and a GearVR
I'm not playing E:D through steam. The HMD can be activated in E:D, which changes the window to the typical preview thing, but on my HMD all I see is "stream will start soon".
