### ISSUE TITLE
do not reconize oculus controllers with the quest

### ISSUE THREAD

**Issue by shadkp** [polygraphene/ALVR#574]
Hello ! I want to start with I love your work I think it is a great idea to use wi-fi for connecting the quest and go to the pc (that keep the wireless feature of those devices).
I hope you'll be able to connect it right through the oculus home in the future.

For now the issue I have to report is that the controllers change to valves controllers once in steamVR and the mapping isn't good I can't even change it or do anything.

**Comment by JashanChittesh** [comment]
There's a fork that is optimized for Quest that you might want to try: https://github.com/JackD83/ALVR

Experimental v8 worked quite well for me. The only issue I'm having is that audio doesn't work at all, with neither of the two builds.
