### ISSUE TITLE
Server does not start

### ISSUE THREAD

**Issue by lemmy04** [polygraphene/ALVR#575]
When I try to start a session, the server crashes with this error:

Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc NvEncoderD3D11 failed. Code=2 NvEncoder::NvEncoder : m_nvenc.nvEncOpenEncodeSessionEx(&encodeSessionExParams, &hEncoder) returned error 2 at c:\src\alvr\alvr_server\nvencoder.cpp:51

Could this be because I'm trying on a laptop with nvidia optimus?

**Comment by lemmy04** [comment]
changing the default in nvidia settings to "use nvidia card" does not help.

**Comment by RAJ-Huff** [comment]
Hi lemmy04,
The 840M is not capable of using NVENC to encode H.265 for the wireless stream, so playback would be limited to H.264 which uses more bandwidth and results in lower quality.  The 840M is also a low tier chip which would not offer very good VR performance even if it could handle NVENC.

**Comment by lemmy04** [comment]
figured as much, uninstalled on laptop :)
