### ISSUE TITLE
uninstaller hangs

### ISSUE THREAD

**Issue by lemmy04** [polygraphene/ALVR#576]
So it seems my laptop's not compatible with this, and I'm trying to uninstall ALVR, but the uninstall is not doing anything - progress bar is not moving.

How do I manually uninstall?

**Comment by RAJ-Huff** [comment]
C:\Program Files\ALVR 
    Uninstall, or delete the folder.
C:\Program Files (x86)\Steam\config\alvr_server
    Delete the folder
C:\Program Files (x86)\Steam\config > steamvr.vrsettings
    Delete the file to start fresh, or remove undesired lines.
AppData\Local\ALVR
    Delete the folder

**Comment by lemmy04** [comment]
this worked for me: install the latest beta over the release, then the uninstaller did its job.
