### ISSUE TITLE
Play audio through oculus quest

### ISSUE THREAD

**Issue by Jakeyjuju** [polygraphene/ALVR#577]
Hi, I’ve set up alvr for my quest and everything (controllers, display) works except for the audio, which only works through my computers wired headphones. Is there a way to send the audio to play directly through the quest?

**Comment by JashanChittesh** [comment]
I'm having the same issue, both with the last build from here as well as using the [Quest-optimized fork](https://github.com/JackD83/ALVR). I also [filed the issue there](https://github.com/JackD83/ALVR/issues/103).

**Comment by Ruchuchmur** [comment]
We need to find a real solution for this issue
