### ISSUE TITLE
I downloaded ALVR and when I run the program it doesn't work

### ISSUE THREAD

**Issue by jaanananacfgvh** [polygraphene/ALVR#578]
I downloaded ALVR and when I run ALVR.exe, a popup appears saying "Unhandled exception has occurred in your application....." When I click continue it opens up but nothing happens when I click install driver.
![download](https://user-images.githubusercontent.com/59804277/72224091-69f60300-3544-11ea-8db2-87a6b3d7e468.png)

**Comment by Pizzaaboi** [comment]
I am not an expert on this but try to reinstall it. Seems like something went wrong with the installation. If that doesn't help click on details en search it up on the internet.
