### ISSUE TITLE
Headset not detected after recent steam VR update

### ISSUE THREAD

**Issue by atrewitz** [polygraphene/ALVR#579]
It was working fine prior to the January 16 update for Steam VR. It may also be from a GeForce Driver update on the 6th but I think it was working even after that. It now shows that the headset is not available.

**Comment by shadkp** [comment]
just happened to me right now, I was using it fine a few hours ago. the version 2.4.0 experimental v8

well, maybe I'm gonna use virtual desktop... does anyone knows if it works ?

**Comment by AlexBasto2017** [comment]
volte para versão 2.3.1 do ALVR, o meu funcionou depois de voltar a versão, utilizo esta mesma versão no gear vr, pois só baixa essa e nao acha a versão mais nova para Android, se é que existe
