### ISSUE TITLE
Server is not running

### ISSUE THREAD

**Issue by beatet** [polygraphene/ALVR#58]
Hi,
I´m trying to connect but when I click on start server, appears steamvr and says "headset isn´t detected" error 108.
I´ve updated nvidia drivers but I don´t know what else I can do.
Any help?

**Comment by polygraphene** [comment]
Please tell me the followings.
1. GPU
2. OS version
3. 32bits/64bits

And please send me driver.log file with following instructions.
1. Check `DebugLog` on Debug tab
2. Terminate vrserver.exe, vrmonitor.exe, vrdashboard.exe and vrcompositor.exe on task manager if exist.
3. Click `Start Server`
4. driver.log may be produced on driver folder.
If driver.log does not exist, please tell me.

**Comment by polygraphene** [comment]
Are you using Windows 10?
Currently windows 7 is not supported.
If you using 10, please check the followings.

1. Click "List drivers" on About tab and then tell me the result.
2. Click "Start Server" and then open Command Prompt as Administrator and put `netstat -abn -p TCP`. Then check the output contains lines like:
```
 [vrserver.exe]
  TCP         127.0.0.1:9944         0.0.0.0:0              LISTENING
 [vrserver.exe]
  TCP         127.0.0.1:9944         127.0.0.1:54095        TIME_WAIT
```

**Comment by beatet** [comment]
Yes, windows 10
C:\users/..../desktop/alvr-v1.7\alvr\driver\
C:\users/..../desktop/alvr-v2.0.4\alvr\driver\
C:\users/..../desktop/alvr-v2.0.2\alvr\driver\


 [vrserver.exe]
  TCP    127.0.0.1:56552        127.0.0.1:56553        ESTABLISHED

I have only one [vserver.exe]

**Comment by polygraphene** [comment]
Oh. If you install driver on multiple locations, which cause some issues.
Make sure only one entry is shown on "List drivers".
Please uninstall other installation by launch `driver_uninstall.bat` on driver directory on each ALVR installation.

**Comment by beatet** [comment]
I have desinstalled all of them and now I have only the 2.0.2 version.
Nothing happens, "server is not running.Press start server" and steamvr opens ans says headset not detected

**Comment by polygraphene** [comment]
Sorry to keep you waiting. I have no idea about it...
I think vrserver cannot load driver correctly. But I have not see that issue.

Please send a log file on `C:\Program Files (x86)\Steam\logs\vrserver.txt` and `C:\Program Files (x86)\Steam\logs\vrserver.txt`.
We may find something on those logs.

**Comment by beatet** [comment]
Thanks for your patience!!
[vrmonitor.txt](https://github.com/polygraphene/ALVR/files/2125307/vrmonitor.txt)
I don´t have vrserver.txt

**Comment by polygraphene** [comment]
Oh! It was SteamVR error.
>Sat Jun 16 2018 21:32:48.531 - vrmonitor starting up with config=c:\program files (x86)\steam\config
Sat Jun 16 2018 21:32:48.531 - Runtime: 
...
[Status Alert] VRInitError_Init_InstallationNotFound_Header (100)

I have not seen this error, but reinstalling steamvr may help you.
And if you installed steamvr on another drive, please try to install on C: drive.

**Comment by beatet** [comment]
Hi, I´ve reinstalled steam vr and it is on C: drive and nothing.
I,ve tried with my oculus rift plugged (for the 108 error) and it doesn´t work too.
I really want to try  your app but I don´t know what to do :(
