### ISSUE TITLE
Quest Latest Update - HTC Vive Controllers

### ISSUE THREAD

**Issue by AstroCoding** [polygraphene/ALVR#586]
Ever since I got the latest quest update, ALVR has stopped registering the Quest controllers as Oculus and went back to Vive. Can't play anything anymore.

**Comment by yaonur** [comment]
theres a experimental version of alvr it solved the issue for me

**Comment by CaptainChemist** [comment]
@yaonur ooh I was having this issue too- where can you get that experimental version? I'm on 2.4.0-alpha 5 now

**Comment by yaonur** [comment]
https://github.com/JackD83/ALVR/releases

**Comment by ZeeCoder** [comment]
That works for me too, but for some reason when I play Half Life Alyx the grab button doesn't close my hand in the air, only when there's actually something to grab.

So essentially I'm walking with my hands open to their full extent all the time.
