### ISSUE TITLE
Unable to compile ALVR Project

### ISSUE THREAD

**Issue by ronakjain89** [polygraphene/ALVR#589]
I am trying to compile the ALVR project on the PC side but somehow I am getting errors like **"LINK104: cannot open file CUDA.lib"** and also, the system I am using is windows7-64bit with visual studio 2017.
Please let me know what I am missing?

Thanks,
Ronak

**Comment by fridgy** [comment]
Make sure you've installed Cuda and done this: https://devtalk.nvidia.com/default/topic/1023301/cuda-setup-and-installation/no-supported-version-of-visual-studio-was-found-some-components-of-cuda-toolkit-will-not-work-properly-please-install-visual-studio-first-to-get-the-full-functionality/

I had a similar issue on JackD83's version and this resolved my issue.

**Comment by ronakjain89** [comment]
Hi @fridgy ,

Still, I am having the same issue. Unable to compile ALVR server project and also the error message is same **"LINK104: cannot open file CUDA.lib"**.

I am using the following system:
> **Windows 10 (64bit) with i7 processor and 8GB RAM**
> **GPU GTX GEFORCE 1650** 
> **Visual Studio 2017**
> **Windows SDK Version 10.0.17763.0**
> **cuda_9.2.148_win10** development kit

Is there any further dependencies to build the ALVR server project? or correct me if I am missing anything.

Any help will be highly appreciated...!!!

Thanks,
Ronak

**Comment by fridgy** [comment]
Unfortunately, I'm not sure how to resolve this if the link I sent didn't help. I used the information in the link to resolve the issue (or a similar one). Have you tried reinstalling Cuda?

**Comment by inspire22** [comment]
Does anyone else have a precompiled release (or forked git) for windows 10 that might be newer than the alpha from May 2019?

**Comment by ronakjain89** [comment]
> Unfortunately, I'm not sure how to resolve this if the link I sent didn't help. I used the information in the link to resolve the issue (or a similar one). Have you tried reinstalling Cuda?

Hi fridgy,

I have also tried the same reinstalling the CUDA 9.2 version but the situation is the same. Still, the issue is not resolved.

Can you please confirm that, is the CUDA 9.2 version is compatible with Visual Studio 2017???

Please give some input on it.

Thanks,
Ronak

**Comment by ronakjain89** [comment]
Hi fridgy,

I have tried to build the same with **cuda_10.2.89_441.22_win10** and getting these errors:
**LNK1104	cannot open file 'C:\Users\ronakj\Downloads\ALVR-master\x64\Debug\CUDA.lib'	alvr_server	C:\Users\Softnautics\Downloads\ALVR-master\alvr_server\LINK	1**	

**The CUDA Toolkit v9.2 directory '' does not exist.  Please verify the CUDA Toolkit is installed properly or define the CudaToolkitDir property to resolve this error.	CUDA	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 9.2.targets**	

I don't understand when I install CUDA 10.x version then why it is looking for CUDA 9.2 version and also when I install the CUDA 9.2 then also it shows the same error **CUDA.lib cannot open.**

I don't understand which CUDA version should I look for. Is there any missing component?

Also, I have attached the error logs for the references. Please have a look at it and get me out.

![cuda_9 2_version_error](https://user-images.githubusercontent.com/55231966/74806862-1037e400-530d-11ea-897a-23f4720aef90.jpg)

Thanks
Ronak
