### ISSUE TITLE
Can't start server by pushing [Start Server] Button

### ISSUE THREAD

**Issue by blu3mo** [polygraphene/ALVR#59]
I'm trying to use Steam VR with Oculus Go and Windows 10.
When I click the [Start Server] button, Steam VR starts, but the button isn't changing to green and the server isn't started.
I tried the first one of troubleshooting, and for the second one, I couldn't find the vrserver.exe in Task Manager.
Is there any other solution?

**Comment by polygraphene** [comment]
Please send me `driver.log` file with following instructions.

1. Check `DebugLog` on Debug tab
2. Terminate `vrserver.exe`, `vrmonitor.exe`, `vrdashboard.exe` and `vrcompositor.exe` on task manager if exist.
3. Click Start Server and then the `driver.log` may be produced on driver folder.

If driver.log does not exist, please tell me.

**Comment by Heyy1235** [comment]
I am having the same problem but alvr changed a lot since 2018, so i'm not sure this fix still works.
Can you please make a updated version of this fix or explain it in more detail? That would help me a lot. also driver.log dose not exist in my alvr folder.
