### ISSUE TITLE
Is it possible to use Vive controllers (with base stations) with Quest HMD?

### ISSUE THREAD

**Issue by hvent90** [polygraphene/ALVR#591]
I'd prefer to use my Vive wands with my base stations because of the better tracking than the quest controllers. Is it possible to do this with the Quest?

**Comment by hvent90** [comment]
Looks like it gets detected when I turn on a vive wand, however the HMD offset immediately becomes incorrect. The offset is too difficult to manually correct. Does anyone know how to resolve this?

**Comment by RaymondSmit** [comment]
Maybe you can use OpenVR-SpaceCalibrator.

**Comment by hvent90** [comment]
That was the solution, thank you!
