### ISSUE TITLE
Quest controllers not working

### ISSUE THREAD

**Issue by ragingclownz** [polygraphene/ALVR#595]
When i launch steam vr only one controller works but only 1 button registers. It shows the htc vive controllers as well not the quest controllers. On the latest alpha build. What should I do to fix?

**Comment by Yuuki795** [comment]
i have the same issue

**Comment by DirkSiegmund** [comment]
I also have this problem with 2.40 alpha5. Only vive controllers appear and I can only switch light on and off.

**Comment by Yuuki795** [comment]
Here's the fix https://github.com/zarik5/ALVR
