### ISSUE TITLE
cant start server

### ISSUE THREAD

**Issue by bruhmoment125** [polygraphene/ALVR#598]
whenever I try starting a server it does nothing

**Comment by AlexBasto2017** [comment]
o meu acontecia isso na versão mais nova, dai instalei a versão 2.3.1 que é a mesma versão baixada no gear vr, ai funcionou normalmente. na versão nova nao vai de jeito nenhum

**Comment by AlexBasto2017** [comment]
> o meu acontecimento está na versão mais nova, da versão 2.3.1 que é a mesma versão baixada no gear vr, e funciona normalmente. na versão nova não vai de jeito nenhum

SteamVR esta instalado certo? se estiver, é bem provável ser a versão
