### ISSUE TITLE
Jerky framerate

### ISSUE THREAD

**Issue by RavengerOne** [polygraphene/ALVR#60]
First of all, many thanks for ALVR! It's a miracle I can stream Steam VR games to the Go. Absolutely awesome!

I have had some issues with getting this working, but it's mostly working now, except the framerate is very jittery. The tracking with the headset is perfectly smooth, but gameplay is jerky.

Any ideas why this could be?

I have an i7-4790k, with a 1080ti. The games run fine on my Oculus Rift (I'm trying ALVR to see if it's better for sims, due to the Oculus Go's higher resolution and subpixel arrangement).

Potentially the issue may be with my router, which is a Virgin Media Superhub - they don't have a particularly brilliant wi-fi signal, but I'm using the headset right next to the router. Both PC and Headset are connected to the same router the PC being on a direct ethernet connection.

Thanks!

**Comment by Tux0Topo** [comment]
Just checking, but your wifi router signal is 2.4Ghz or 5Ghz?

**Comment by RavengerOne** [comment]
5Ghz

**Comment by polygraphene** [comment]
Can you send me output of `adb logcat`?

**Comment by Jbbrack03** [comment]
You might also check and see if the router has a QoS setting. If it does, try turning it off. QoS is known to sometimes cause issues with streaming. You might also try another channel on 5 Ghz to see if that helps.

**Comment by vrokolos** [comment]
Maybe this is what you're seeing: https://github.com/polygraphene/ALVR/issues/42#issuecomment-399364452
