### ISSUE TITLE
How does cs server communicate with the alver-server library?

### ISSUE THREAD

**Issue by joeyskeys** [polygraphene/ALVR#600]
hi everyone, I've been reading the code for a while and was quite confused about the communication machnism between the CS part and cpp part, only see LoadLibrary call in SoundDevice.cs and seems is not relating to the communication.
I guess the server might do it through a local web socket but I cannot find any related code, can anybody help explain?
This is not a feature request nor a bug report, didn't find any good place to post the problem, sorry if it is not the place to put the question.

Thanks.

**Comment by mmSir** [comment]
I had the same question three months ago~XD
Ur guess is probably right! C# GUI communicates with C++ library by using the ControlSocket. The ControlSocket connect 127.0.0.1 (local address). When u push a button on GUI, the ControlSocket(C#) send a command to the opposite ControlSocket(C++).Then C++ library knows what to do.
See details in ControlSocket.cs/ControlSocket.cpp.
By the way,what i said above is base on release version 2.3.0. I don't know if there are any changes in the recent updated version.

I hope it helps.

**Comment by joeyskeys** [comment]
Just found something interesting, the alvr_server.dll is actually used by streamvr.
The naming is confusing, it's actually a streamvr driver and is loaded and used by steamvr. Then the driver sends out the encoded video and audio stream to the connected client.
