### ISSUE TITLE
Cannot load library?

### ISSUE THREAD

**Issue by JalenTheDumb** [polygraphene/ALVR#603]
Every time I attempt to boot ALVR I get an error saying: 
"Cannot load library. ALVR works only on 64bits Windows and requires
latest Visual C++ 2015 Redistributable (vcredist) .
C:\Users\merke\Desktop\\ALVR\driver\bin\win64\driver_alvr_server.dll
Code:126"
My CPU is 64 bit, and I've uninstalled and reinstalled C++ several times now, I have no idea what it causing this error.

**Comment by thebender7** [comment]
Maybe this helps:
https://github.com/JackD83/ALVR/issues/133
