### ISSUE TITLE
Is there any plan that about fix vibration for Oculus Quest?

### ISSUE THREAD

**Issue by BearMett** [polygraphene/ALVR#605]
When I play games with Oculus Quest and ALVR, I cannot feel Controller's Vibration .

so I searched about issues but there's no mention of this problem.

Is there any plan to fix this issue? or any way to solve this?

**Comment by thebender7** [comment]
You may want to have a look at this:
https://github.com/JackD83
It is an active fork focussing on the Quest

**Comment by BearMett** [comment]
> You may want to have a look at this:
> https://github.com/JackD83
> It is an active fork focussing on the Quest

Thank you for comment, I'll find out the issue in there
