### ISSUE TITLE
Support for Lenovo Mirage Solo

### ISSUE THREAD

**Issue by tristan-k** [polygraphene/ALVR#606]
Since the Lenovo Morage Solo is deprecated it's one of the more affordable VR headsets. I know that [Trinus VR](https://www.trinusvirtualreality.com/) do support the device, but I do wonder why ALVR won't support it.

**Comment by FrankyMc** [comment]
Agreed, we need support for this. Specwise the Lenovo Mirage Solo is almost identical to the quest, only the room scale tracking works a bit different and it doesn't have it's own 6DoF controllers. Saw it on sale for 99€ today.

**Comment by jshamg** [comment]
I'm really interested in this, too. The mirage is much better than the Oculus go for around 100€. If the support is there I consider buying one.
Can someone give some feedback wether or not there will be support added?
Greetings!
