### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by Changeabledead** [polygraphene/ALVR#609]
![ALVR](https://user-images.githubusercontent.com/38870015/76717766-a12e8f00-6702-11ea-83bd-0e68ef695569.PNG)
Whenever I click on the start server button, steamVR opens but it still says the server is down. Also, steamVR says "Headset Not Detected" and "Some Add-ons Blocked."

**Comment by lambegraham** [comment]
Fix for this issue:

1. Connect Quest to PC via Oculus Link
2. Launch and go to SteamVR application
3. You will see "Some Add-ons Blocked" window, click "Manage Add-ons"
4. Enable ALVR sever add-on and restart SteamVR
5. Enjoy!
