### ISSUE TITLE
Disable steamvr's safe mode???

### ISSUE THREAD

**Issue by SweTrece** [polygraphene/ALVR#612]
For 2 days when opening the Steamvr I get a sign that indicates that Steamvr is working in "safe mode" and gives me the options to "discard" or "disable safe mode". Until 2 days ago I chose the latter, "deactivate safe mode" and everything started to work correctly, but now, when I give it, I get a new "Steamvr settings" window in which it only tells me to connect the vr viewer and therefore does not let me disable safe mode, nor touch any settings. I use "Alvr" to connect my Oculus Go to the pc, and the problem is that in order for Steamvr to recognize the Oculus Go I need to deactivate the safe mode, but to deactivate the safe mode I need to have the Oculus Go connected ...... ..... any ideas or solutions ???
Or maybe I have no idea what's wrong :)
Thanks for any help.

**Comment by Awsomeworld304** [comment]
Turn on advanced settings then go to the Startup / Shutdown tab and choose manage add-ons and disable or enable "alvr_server".
Then try to disable everything but the alvr_server then try it after a restart.
