### ISSUE TITLE
Server is down Error 108

### ISSUE THREAD

**Issue by jordocart** [polygraphene/ALVR#613]
I have been playing using ALVR on my quest for almost a week, i was playing the forest vr and then after when i went to play another game, my ALVR now says "server is down" and on my steam vr, i only get error 108.

I have tried everything i thought of:
- updating drivers
- uninstalling and reinstalling ALVR
- uninstalling and reinstalling SteamVR
- trying older versions of ALVR
- etc

I have lingered on this problem for almost 7 hours now and haven't anything on Reddit, or GitHub. If there happens to be a solution on GitHub, please link. Thank you.
![ALVR](https://user-images.githubusercontent.com/62377685/77051316-d135a500-6a16-11ea-93a9-87142aac8b30.PNG)

**Comment by lambegraham** [comment]
Fix for this issue:

1. Connect Quest to PC via Oculus Link
2. Launch and go to SteamVR application
3. You will see "Some Add-ons Blocked" window, click "Manage Add-ons"
4. Enable ALVR sever add-on and restart SteamVR
5. Enjoy!

**Comment by jordocart** [comment]
I don't happen to have a high end cable that works with oculus link, could there possibly be another way?

**Comment by lambegraham** [comment]
I couldn’t seem to find one. Maybe there’s a way to reset steam vr config
by deleting files.

**Comment by jordocart** [comment]
it's all good now, i downloaded experimental v3 and it managed to trick steam into thinking that i have a headset plugged in and it allowed me to unblock ALVR.
