### ISSUE TITLE
VIVE Controller bug in v2.4.0-alpha5

### ISSUE THREAD

**Issue by Joel-Schmidt00** [polygraphene/ALVR#619]
so I have a big problem. Whenever I start ALVR on my oculus quest and connect it to my pc it only shows me the VIVE controllers despite the latest ALVR version v2.4.0-alpha5. In addition to that only the right one works and the left one is centered in the middle, cannot be moved and steam shows that it has only 1% battery left although it is 100% charged.

**Comment by bosezath-2** [comment]
Yes, I'm having that problem also.

**Comment by Ekristoffe** [comment]
for the quest please try this fork:
https://github.com/JackD83/ALVR
