### ISSUE TITLE
not connecting

### ISSUE THREAD

**Issue by gb2111** [polygraphene/ALVR#62]
Hi,
I can't get oculus go and server connected. Any suggestions were to search for problems?
Greg

**Comment by Haylefal** [comment]
I was using 2.03 and upgraded to 2.04. It then wouldn't connect so uninstalled and went back to 2.03. works now.

**Comment by polygraphene** [comment]
@gb2111 Please tell me more detail of your situation. What is displayed in ALVR server? And SteamVR is correctly started?

@Haylefal Please confirm that only one driver installation is shown by clicking "List drivers".

**Comment by gb2111** [comment]
hi.
on the server I see info that headset not found. I tried 2.0.2, 2.0.3 and 2.0.4.
on client 2.0.2 I see standard info prompting to connect to server
i tried ping and good result which is good I think.
let me know if I can provide you more info.


C:\Minimal ADB and Fastboot>adb shell ping -c 5 192.168.8.106
PING 192.168.8.106 (192.168.8.106) 56(84) bytes of data.
64 bytes from 192.168.8.106: icmp_seq=1 ttl=128 time=7.72 ms
64 bytes from 192.168.8.106: icmp_seq=2 ttl=128 time=6.74 ms
64 bytes from 192.168.8.106: icmp_seq=3 ttl=128 time=8.83 ms
64 bytes from 192.168.8.106: icmp_seq=4 ttl=128 time=7.18 ms
64 bytes from 192.168.8.106: icmp_seq=5 ttl=128 time=9.85 ms

--- 192.168.8.106 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 6.743/8.067/9.855/1.137 ms

**Comment by polygraphene** [comment]
Thank you for replay!

The SteamVR is started? If so, please tell me what is display in the SteamVR window.
And I want to see the `driver.log` file. Please check `DebugLog` on Debug tab and click `Start Server` then `driver.log` may be produced in `driver` folder.
If `driver.log` file is found, please upload this file.

**Comment by gb2111** [comment]
widnow sayd: headset not traking and steamvr shows as 'not ready' there is headset icon blinking with letter S.
Attached log.
[driver.log](https://github.com/polygraphene/ALVR/files/2114504/driver.log)

**Comment by polygraphene** [comment]
Thank you for the log!
I couldn't find the packet log from client in the log.
Did you try the firewall config on PC?

http://www.tikilive.com/manual/dashboard/user-faq/manually-open-ports-in-windows-firewall/
In this instruction, select UDP and set 9944 on "Specified local port" in step 7.

**Comment by polygraphene** [comment]
I think USB tethering does not work.

We need to debug network issue.
If you can use Wireshark, check the packet is arrived like following image.
Put `udp.dstport == 9944` in the filter.
![wireshark](https://user-images.githubusercontent.com/2751376/41591277-382d6b1e-73f4-11e8-85e6-7a7e890d3e98.png)

**Comment by gb2111** [comment]
it is there :)
![obraz](https://user-images.githubusercontent.com/22025896/41641245-fe301c6a-7464-11e8-9757-488287fecaf2.png)

**Comment by polygraphene** [comment]
Hmm... Looks OK.
I think the server is not listening the port 9944 or firewall issue.

Please open command prompt as administator, and put `netstat -abn -p UDP`.
If server is listening correctly, you can see following lines.

```
   UDP         0.0.0.0:9944           *:*
 [vrserver.exe]
```

**Comment by gb2111** [comment]
svhost.exe is using it.
i have 20 svhosts running :(

**Comment by polygraphene** [comment]
It seems that the server is correctly working. I think you can see vrserver.exe "after" that line.
Please re-check the firewall settings.
You need to open UDP 9944 port. And please check the rule is applied on "all" profile.

**Comment by gb2111** [comment]
hi. i changed access here and now it found. but it seems i have version clash and last update via oculus go is crashing my go.

anyway this problem closed. thanks :)
![obraz](https://user-images.githubusercontent.com/22025896/41676713-a4f2ad4a-74c6-11e8-8857-074c19c6007c.png)
