### ISSUE TITLE
[Oculus Quest] Headset not found V9

### ISSUE THREAD

**Issue by DewenX7** [polygraphene/ALVR#625]
So from yestarday until now i can't manage to make ALVR find my quest, i tried a bunch o things that are write here but nothing works for me, or maybe i was doing them wrong, so i need a little help please.

**Comment by Ekristoffe** [comment]
for the quest please try this fork:
https://github.com/JackD83/ALVR

**Comment by DewenX7** [comment]
> for the quest please try this fork:
> https://github.com/JackD83/ALVR

I was trying already but are the same things.
