### ISSUE TITLE
ALVR .net error

### ISSUE THREAD

**Issue by jibberish12212** [polygraphene/ALVR#627]
i keep getting this error when i start up ALVR,try to run a server,or install the drivers 

![Annotation 2020-03-21 155228](https://user-images.githubusercontent.com/63061758/78268067-51efa900-74cd-11ea-8e34-03fae4422104.jpg)

can anyone help me

**Comment by foreversos** [comment]
ME TOO.SO BAD

**Comment by DemonsDeath0976** [comment]
use the 2.3.1 if you have the 2.1.5 change
