### ISSUE TITLE
Connected through server, but the "connect

### ISSUE THREAD

**Issue by Casyi** [polygraphene/ALVR#63]
The ALVR server is alive. In the Oculus client app I can see a black screen where it says that I have to press connect. But if I press connect on the server, the app doesn't change at all and is stuck at that screen. 

See below's screenshot for the ALVR status + SteamVR status:

![image](https://user-images.githubusercontent.com/20356242/41615066-8fa7c992-73fa-11e8-99d1-435483e9a3b4.png)

Here's also my driver log:
[driver.log](https://github.com/polygraphene/ALVR/files/2116329/driver.log)

Any idea what I can do about this?

**Comment by polygraphene** [comment]
Please connect USB cable and put `adb shell ping -c 5 (IPAddress of PC)` on Command Prompt.
It may be a temporary network error and may be solved by this command.
refer: https://github.com/polygraphene/ALVR/issues/20#issuecomment-394164829

**Comment by Casyi** [comment]
Works. Thank you (also updated client + server). Solved!
