### ISSUE TITLE
Blue horizontal line through the middle of Oculus Go

### ISSUE THREAD

**Issue by kenkwok83** [polygraphene/ALVR#64]
Hi,
I managed to get ALVR to work on my oculus Go and started streaming some steamvr apps.  There's this really annoying blue (or green) horizontal line through the middle of the Oculus Go.  It kind of looks like the safety barrier when you play games on vive and go too near the end of the playable area, but it's just one horizontal line and I can't get rid of it.  Any ideas?

**Comment by polygraphene** [comment]
Did you try it? I could remove the line by this.
https://www.reddit.com/r/Vive/comments/4ehsnn/turning_off_chaperone_for_seated_vr/

>Solution found:
Go to \Steam\config
Open steamvr.vrsettings with Notepad
Change this line to: "CollisionBoundsColorGammaA" : 0,
Save
GammA is the alpha transparency channel so you're setting it to 100% transparent, aka invisible :)

**Comment by okuda** [comment]
Can you try this?
ALVR server>other>apply offset(xyz)>0,1,0

**Comment by vrokolos** [comment]
You need to do room setup on steam and enter your height using your keyboard. If you don't do that steam will place you right on the floor.
