### ISSUE TITLE
strange ALVR and steamVR errors PLEASE HELP!!!!

### ISSUE THREAD

**Issue by falafell** [polygraphene/ALVR#643]
when enter ALVR, I started the server, launched steamVR, and connected my oculus go. But when I connected it, I received a "critical error" from steamVR and a error code from ALVR reading:
 Unhandled Exception.
ExceptionCode=C0000005
Address=00007FFC728FA036 (00007FFC728E0000 + 000000000001A036)

If the github team ALVR developers, support assistants, or anyone else can help me with this issue, please help me out!      (note, I am using ALVR version 2.3.1)

**Comment by DemonsDeath0976** [comment]
same thing happens to me
