### ISSUE TITLE
ALVR Crashing For Oculus Quest

### ISSUE THREAD

**Issue by Zespuh** [polygraphene/ALVR#647]
Hi I Am Trying To Run ALVR for my oculus quest and i keep getting the same crash issue any or discussion about this would be helpful i have friends having the same issues.

Code Below

Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc CreateEncoder failed. Code=15 NvEncoder::CreateEncoder : m_nvenc.nvEncInitializeEncoder(m_hEncoder, &m_initializeParams) returned error 15 at c:\src\alvr\alvr_server\nvencoder.cpp:271

**Comment by Heilemann** [comment]
I’m seeing the exact same thing. Running 2.0.4a5. Connects fine, but once Steam VR starts it crashes.

**Comment by Ekristoffe** [comment]
hello could you please try this one:
https://github.com/JackD83/ALVR
He made it especially for the quest.
