### ISSUE TITLE
Version mismatch between server, android APK and client inside GearVR Library

### ISSUE THREAD

**Issue by johnverv** [polygraphene/ALVR#650]
Hi guys, I am unable to get the client inside the GearVR Library past v2.3.1
I have server v2.4a5, and the APK installed on the GalaxyS7 is also apk v2.4a5.
However when I load up GearVR and go to Library > ALVR, I get shown v2.3.1 again, and it refuses to be detected by the server.
If I revert to server 2.3.1, it is detected...
How can I update the Samsung Library ALVR version, there is nothing else in the store and that is the last update it installs
Cheers!

**Comment by Boryz** [comment]
Doesn't it mean that you have two versions installed on your mobile device? 

One provided by Oculus Store, and the newer version from apk install. 

If I remember correctly, Oculus in gear VR works similarly to a virtual machine. It will only run apps installed from Oculus store.

To use the new version apk, you will have to prevent Oculus from executing when you insert the phone into headset.

**Comment by dpluigi** [comment]
I have the same issue. When I start the client v2.4a5 on my S10, GearVR Greeting room appears, even though the phone is connected to the server on my PC and SteamVR is launched. Room Setup is initiated but even with fake tracker stations enable I can't successfully complete the room setup standing up option.
I can even start an app on my PC injecting it in Revive but it won't stream to the VRGear/S10.

How can I stream successfully as I used to be able up until 2.3.1, where the client could be launched from Oculus store as described above.

Thanks for the input and pointers.
