### ISSUE TITLE
Headset not found - Oculus quest V16.0 - ALVR v10

### ISSUE THREAD

**Issue by peruna77** [polygraphene/ALVR#651]
When I boot alvr.exe on my pc it cannot find the headset (yes the client was running on the quest at the same time). I have tried disabling the firewall completely, running the firewall settings.bat, portforwarding my router and I just can't get it to find the headset. I have no clue what to try next

**Comment by Ekristoffe** [comment]
v10 doesn't exist here.
I think you want to open an issue here:
https://github.com/JackD83/ALVR
