### ISSUE TITLE
Is there maybe a beta for x265 hevc encoding I can test?

### ISSUE THREAD

**Issue by vrokolos** [polygraphene/ALVR#66]
Really looking forward to it since video artifacts are annoying on 3D and they are very obvious on Skyrim VR with the foggy - misty environment.

**Comment by polygraphene** [comment]
I have heard H.265 is way better than H.264. And I also want to test H.265.
But current ALVR code largely relies on H.264. We need a lot of implementation power and knowledge of H.265.
It may take a long time and it depends on my motivation.
