### ISSUE TITLE
Controller/Guns Tilted

### ISSUE THREAD

**Issue by MatthewFBullock** [polygraphene/ALVR#663]
Hey everyone,

I'm running v2.4.0-alpha5 on my Oculus Quest. I also installed the controller patch as referenced in #491 which got both my Oculus Quest controllers working (although in SteamVR they model after the gen1 Rift touch controllers vs the new Quest/Rift S touch controllers. Interestingly enough, when in-game in Half Life Alyx they seem to update to the new touch controllers).

I'm still having the same problem as brought up in #356 and was wondering if there's been a fix since the issue was originally posted over a year ago. I've done a bunch of googling and am at a loss.

Thanks!

**Comment by Ekristoffe** [comment]
Please check this fork made for the quest:
https://github.com/JackD83/ALVR
