### ISSUE TITLE
Keys sold out for oculus go

### ISSUE THREAD

**Issue by webarro70** [polygraphene/ALVR#666]
Can you send me a key for oculus go alvr client? It says its sold out...

Thanks

**Comment by Ekristoffe** [comment]
Please follow:
https://github.com/polygraphene/ALVR/wiki/Installation#for-oculus-quest-install-from-apk
And use the manual installation mode.

**Comment by webarro70** [comment]
Thanks but I don't understand how to install an apk and where (phone, pc, headset)..., Sorry for beibg a rookie on this..

**Comment by webarro70** [comment]
> Please follow:
> https://github.com/polygraphene/ALVR/wiki/Installation#for-oculus-quest-install-from-apk
> And use the manual installation mode.

Sorry sir but I am a rookie on this matters, how do I install and apk, and where ( Go headset, pc or phone app)?, I installed the inf adb as instructed but then what, how do I run the adb to install the alvr?... Help!..

**Comment by Ekristoffe** [comment]
In the detailed instruction (cf: https://uploadvr.com/how-to-sideload-apps-oculus-go/)
everything is described.

**Comment by polygraphene** [comment]
New keys are added!
Thank you for reporting.

Please make sure those keys are dedicated for Go and GearVR.
For Quest, you need to manually install apk.

**Comment by webarro70** [comment]
> New keys are added!
> Thank you for reporting.
> 
> Please make sure those keys are dedicated for Go and GearVR.
> For Quest, you need to manually install apk.

Thanks a lot its working!  The key says is for Oculus but don't specify which one. I have Go and when in steam vr, the controller displayed its a Quest controller. Maybe is just Google Earth VR that doesn't have it. Thanks anyway!
