### ISSUE TITLE
ALVR is dead?

### ISSUE THREAD

**Issue by ericksantos12** [polygraphene/ALVR#668]
No one fix the .net bug, no devs answer

**Comment by Ekristoffe** [comment]
ALVR is in a strange phase.
This repo is in a coma. One of the fork is heavily developed:
https://github.com/JackD83/ALVR
But only for the Quest.
There is a new ALVR which will be rebuild from scratch :
https://github.com/JackD83/ALVR/issues/183
But it will take time.
Depending on the device you have use one of the fork, or wait.
