### ISSUE TITLE
alvr update on oculus black screen

### ISSUE THREAD

**Issue by gb2111** [polygraphene/ALVR#67]
i just updated ALVR client on oculus.
once I launch it screen goes black (very gray).
i cannot even go back to library or press calibrate button.
only restart or shutdown works upon longer press of power button on headset.

**Comment by asiercamara** [comment]
Same bug here on my oculus go.

**Comment by polygraphene** [comment]
Can you send the output of `adb logcat`?

**Comment by asiercamara** [comment]
there is the adb logcat -d

[https://pastebin.com/9rWsfaNk](url)

**Comment by vincerex71** [comment]
unfortunately after downloading the new version does not work even on my gear vr only black screen no connection even if the phone is connected to the sever.

**Comment by polygraphene** [comment]
@vincerex71 If you using Exynos device, please check test this version. https://github.com/polygraphene/ALVRClient/releases/tag/v2.1.1
https://github.com/polygraphene/ALVR/issues/35#issuecomment-398835011

**Comment by polygraphene** [comment]
@asiercamara Thank you! Please try this version. I don't know if the issue is fixed...
https://github.com/polygraphene/ALVRClient/releases/tag/v2.1.2
If it produce same result, please send a logcat again.

**Comment by vincerex71** [comment]
I downloaded the update from the oculus store and installed on my s6 so I have to uninstall the version of the store?

**Comment by polygraphene** [comment]
@vincerex71 I have uploaded on Store! Please check.

**Comment by vincerex71** [comment]
thanks OK working!!!

**Comment by asiercamara** [comment]
good news!. The new version it's working. I try to restart few times and no problem. Sound working too, awesome work @polygraphene !

**Comment by Haylefal** [comment]
working. Is the arcore version updated too? Dying to give it a go.

**Comment by polygraphene** [comment]
@vincerex71 @asiercamara @Haylefal Great! I'm so glad.🤣

@Haylefal 
ARCore on Oculus Go needs more work (https://github.com/polygraphene/ALVR/issues/8#issuecomment-396062936). But I didn't try it. Please be patient.
