### ISSUE TITLE
Failed to start audio capture

### ISSUE THREAD

**Issue by pumpkinss** [polygraphene/ALVR#673]
Every time I try starting ALVR I get this audio error, I've tried changing the audio quality, reinstalling/updating drivers, and turning off Stream game audio and I still get this error: message=IAudioClient::Initialize failed: hr = 0x88890008

**Comment by ParrotVR** [comment]
i dont know why it keeps happening to me too

**Comment by ParrotVR** [comment]
you found out why yet
