### ISSUE TITLE
ALVR will not Install.

### ISSUE THREAD

**Issue by marksublettejr** [polygraphene/ALVR#679]
I had not used it for awhile and this message came up:
![alvr problem 2](https://user-images.githubusercontent.com/30219466/94209676-1cc78080-fe8a-11ea-9db7-d2b32cb5403c.PNG)
So I tried to update and now I get this problem:
![alvr problem](https://user-images.githubusercontent.com/30219466/94209717-2fda5080-fe8a-11ea-92d0-b4faae94bf91.PNG)
The new version will not install. Any ideas? Nvidia 1080  graphics card, running windows 10. I was able to install it yesterday, however the new version was gone today.

**Comment by Kio-td** [comment]
You're using JackD83's ALVR, correct?

Close SteamVR. Open Task manager, and look for alvr.exe, or alvr_web_server.exe. Close these.

If you're upgrading from polygraphene's version to JackD83, then use a clean directory.
