### ISSUE TITLE
Bug when starting server

### ISSUE THREAD

**Issue by goldencreedyt** [polygraphene/ALVR#680]
Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 10. g_AMFFactory.GetFactory()->CreateComponent(amfContext, pCodec, &m_amfEncoder), NVENC: NvEnc NvEncoderD3D11 failed. Code=1 NvEncoder::LoadNvEncApi : NVENC library file is not found. Please ensure NV driver is installed at c:\src\alvr\alvr_server\nvencoder.cpp:70

i get this when starting server using an oculus go

**Comment by bxigxy** [comment]
I have the same problem but im using a oculus quest 2
