### ISSUE TITLE
Client FPS 0, Server FPS 72. Unusable

### ISSUE THREAD

**Issue by crookedbag** [polygraphene/ALVR#681]
I recently discovered ALVR and thought I'd try it out since I've got the oculus quest and my brother has Half-Life Alyx on steam so I decided to try and set it up on my new laptop. After ALVR loads steamvr, I get about 48-52 fps for maybe 4 seconds and then the image freezes on my quest and the streaming statistics tell me there is 0 fps on client side?? This is confusing because server fps is 72. I'm new to this and unsure where to begin and there doesn't seem to be anything on here dealing with this kind of issue so I figured I'd ask.

I'm using a 5 Ghz router with standard of 802.11ax which should be the best right? I've also tried the mobile hotspot feature on my laptop at 5 Ghz band and still the same problem. I can't bring the router into my room so I was hoping this wasn't the issue. My GPU is GTX 1650 Ti and when steamvr is running, it goes upwards of 93% utilization (you can check out my task manager). If the GPU is the issue, I have an integrated radeon graphics card with my Ryzen 5 4600H chip so should I reinstall ALVR using that GPU? I've used the steamvr performance test on the 1650 ti GPU and says that its very capable and the games do run well without any problems on the PC's side through steamvr. 

Here are images of what I'm seeing. Thanks for any help you can give, I really want to play Alyx!

![Screenshot 2020-10-13 025036](https://user-images.githubusercontent.com/72785347/95825727-4fcd9900-0cff-11eb-92b3-9ea579497099.png)
![task manager](https://user-images.githubusercontent.com/72785347/95825735-52c88980-0cff-11eb-8184-78d71a8524e4.png)

Also doing the steamvr performance test seems to be testing my integrated radeon graphics, but I have the 1650 Ti GPU selected as the default. Why is this?
![Steamvr](https://user-images.githubusercontent.com/72785347/95828528-19921880-0d03-11eb-9f2f-2de474ee6927.png)

**Comment by Redageddon** [comment]
change video code to HVEC(h265)

**Comment by Ekristoffe** [comment]
this ALVR version seems to be the fork for the quest.
Please put the issue on the right Github page.
