### ISSUE TITLE
need help fixing "headset not detected"

### ISSUE THREAD

**Issue by colrobloxkid69420** [polygraphene/ALVR#686]
Here is a screenshot I took (as you can see there is no alvr add on in steamvr which from what I've seen is supposed to be there)
![Capture](https://user-images.githubusercontent.com/73903938/98019701-bfb8d600-1e0a-11eb-830e-10153359a7bf.PNG)
And in debug.log it wrote: [1103/135130.737:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
I'm not so sure if you can help me with only this data so if you need to ask a question pls do

**Comment by eclipsek20** [comment]
Try Pressing restart SteamVr Button
