### ISSUE TITLE
The screen flashes occasionally on Quest

### ISSUE THREAD

**Issue by jichang9527** [polygraphene/ALVR#688]

**Comment by Ekristoffe** [comment]
Hello,
Maybe some information about your machine and the version of ALVR would be nice to have.
Ps polygraphene ALVR is no more maintained.
Could you try with this fork especially made for the quest:

https://github.com/JackD83/ALVR

And if you have any trouble open a new ticket on JackD83 fork of ALVR.

Thanks.

Sent from my iPhone

On Nov 17, 2020, at 20:23, jichang9527 <notifications@github.com> wrote:

﻿
