### ISSUE TITLE
connect with usb cable.

### ISSUE THREAD

**Issue by burhancam** [polygraphene/ALVR#69]
Can we connect with usb cable only?

**Comment by polygraphene** [comment]
What do you mean?
We can use USB tethering to stream video since v2.1.0.
And if you use USB tethering, you don't need to use Wi-Fi.

**Comment by burhancam** [comment]
oculus go with my own usb cable. but the oculus does not seem to go.
How can I connect with cable?

**Comment by burhancam** [comment]
I can connect with wifi headset sees. but I do not recognize it by cable. what should I do.

**Comment by polygraphene** [comment]
I don't know if we can enable USB tethering on Oculus Go.
https://www.reddit.com/r/OculusGo/comments/8hz51k/oculus_go_usb_tethering_working_microusb_to/

So, USB tethering connection is currently only for Gear VR.
I think we need to use adb to connect Oculus Go with USB cable.
I will add adb connection on future release, please be patient.

**Comment by burhancam** [comment]
thank you.

**Comment by parkerlreed** [comment]
Any update on this? Would love to use this for my Go.

**Comment by dabde** [comment]
I found a more or less crazy workaround.

tools you need:
- openvpn
- adb
- alvr from JackD83 (support for static IP settings) https://github.com/JackD83/ALVR/releases/tag/ev6

## howto
1. setup you windows pc to a openvpn server
```server.ovpn
dev tun
ifconfig 192.168.2.1 192.168.2.2
cipher none
secret static.key
proto tcp-server
```

2. enable adb on your oculus go and install adb on you local windows pc
3. define a remote port forward over adb `.\adb.exe reverse tcp:1195 tcp:1194`
4. install and setup openvpn on you oculus go (maybe need to install oculus tv)
- cipher none
- static key (need to copy to oculus go)
- server: localhost:1195
- proto: tcp (adb can't forward udp ports, so you need use tcp)
5. start openvpn on server (windows) and client (oculus go), check if you can ping oculus go
6. install alvr from JackD83 on you windows pc and oculus go
7. define the server ip for alvr over adb `.\adb.exe shell am startservice -n "com.polygraphene.alvr/.ChangeSettings" --es "targetServers" "192.168.2.1"`
8. start alvr on oculus go and windows. alvr on windows should show HMD with IP "192.168.2.2:9944", press connect


Some Pictures:
![image](https://user-images.githubusercontent.com/34655672/82711228-0e234f80-9c85-11ea-9d0a-5402fd15fa5f.png)

You see the traffic over the TAP Interface, not Wifi.

![image](https://user-images.githubusercontent.com/34655672/82711237-12e80380-9c85-11ea-87cd-3f0116cc55fe.png)

Here you can see the remote IP Address.


5Ghz was not stable in my case (also direct a wifi ap on my desk and connected with ethernet adapter). But with this, the stream looks really stable at full res (2880x1440)
