### ISSUE TITLE
ALVR pins microsoft edge to taskbar, every time it starts

### ISSUE THREAD

**Issue by CUPZYY** [polygraphene/ALVR#690]
Every time i launch ALVR, it pins microsoft edge to my taskbar for some reason.
pls help me get rid of that

**Comment by zarik5** [comment]
As explained in the #faq channel on the Discord server, you need to install Chrome.

**Comment by Ekristoffe** [comment]
hello,
I don't remember poly ALVR using the web browser.
this problem is from Microsoft side and we can't do anything about it.
Also could you try the latest ALVR fork:
https://github.com/alvr-org/ALVR
