### ISSUE TITLE
ALVR not installing on Oculus Go

### ISSUE THREAD

**Issue by ghost** [polygraphene/ALVR#692]
Hello,

ALVR cant install on my Oculus Go.
Please help!

Thanks in advance!

**Comment by Kingofmtg** [comment]
I have the same issue, help would be appreciated

**Comment by Ekristoffe** [comment]
ok it seem the Oculus GO App store doesn't have the file anymore but the link is still valid ...
Please try with this :

Install from apk
- Need to enable developer option for Quest.
- Download apk from [Releases](https://github.com/polygraphene/ALVR/releases)
- Check [Installation](https://github.com/polygraphene/ALVR/wiki/Installation).

**Comment by Ekristoffe** [comment]
Thank you for reporting.
Currently we have another problem on installation.
Please check #695 (comment)

**Comment by danloman** [comment]
> ok it seem the Oculus GO App store doesn't have the file anymore but the link is still valid ...
> Please try with this :
> 
> Install from apk
> 
> * Need to enable developer option for Quest.
> * Download apk from [Releases](https://github.com/polygraphene/ALVR/releases)
> * Check [Installation](https://github.com/polygraphene/ALVR/wiki/Installation).

Uh, what do I do? I have the pc app, but how do/what do I install for the oculus go? Thanks a lot?

**Comment by Ekristoffe** [comment]
https://github.com/polygraphene/ALVR/wiki/Installation
Under "Install from apk"

You may be able to use sidequest to upload the file on the GO without too much trouble.
