### ISSUE TITLE
ALVR install abort during install on Oculus Go 32 with developper mode ok

### ISSUE THREAD

**Issue by thelastof** [polygraphene/ALVR#693]
Hello,

my oculus go is already in developper mode, already with some apk installed and working (steamlink for example)

trying to install ALVR on it.
ALVR code validated in oculus store
automatic install on Oculus failed, i tryied to install from oculus manually, 
the download seem ok but the install abort

Below is the log i can observe with adblogcat just after download :

Any idea ?
Thx,

12-20 00:48:23.777  1842  7988 I InstallerServiceVerificationHelper: Checksum verified for ApkUpdateInfo{id=88, identifier=com.polygraphene.alvr.oculus, update_type=STORE_FULL_APK, state_str=VERIFYING, dependencies=none, download_id=63}
12-20 00:48:23.833  1842  7988 I InstallerFileUtils: Attempted to remove file /data/user/0/com.oculus.ocms/files/apk_to_install/88.com.polygraphene.alvr.oculus.apk for reason "Clearing reserved spot for move operation", removed = true
12-20 00:48:23.851  1842  1842 I LibraryProvider: running queryApp(com.polygraphene.alvr.oculus) for com.oculus.ocms
12-20 00:48:23.865  1842  1842 I LibraryProvider: running queryApp(com.polygraphene.alvr.oculus) for com.oculus.ocms
12-20 00:48:23.873  1842  1842 I LibraryProvider: running queryApp(com.polygraphene.alvr.oculus) for com.oculus.ocms
12-20 00:48:23.884  1842  1842 I LibraryProvider: running queryApp(com.polygraphene.alvr.oculus) for com.oculus.ocms
12-20 00:48:23.948  1261  1261 D OculusNotificationListenerService: Notification posted: 0|com.oculus.ocms|20007|null|10042
12-20 00:48:23.955  1684  1684 I [OAN] VrNotificationListenerService: onNotificationPosted(): key = 0|com.oculus.ocms|20007|null|10042, type = invalid
12-20 00:48:23.955  1684  1684 I [OAN] VrNotificationListenerService: onNotificationPosted(): user|package|tag|id = UserHandle{0}|com.oculus.ocms|null|20007
12-20 00:48:23.964  1684  1684 E OsSdk   : Failed to connect to XrspBroker.
12-20 00:48:23.967  1684  1684 D VrNotificationAnalytics: logNotificationPosted(invalid)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils: NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at org.json.JSONTokener.nextValue(JSONTokener.java:94)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at org.json.JSONArray.<init>(JSONArray.java:92)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at org.json.JSONArray.<init>(JSONArray.java:108)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at com.oculus.appmanager.installer.service.InstallerServiceVerificationHelper.verifyEsigOrThrow(InstallerServiceVerificationHelper.java:309)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at com.oculus.appmanager.installer.service.InstallerServiceVerificationHelper.verifySandboxedFile(InstallerServiceVerificationHelper.java:294)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at com.oculus.appmanager.installer.service.InstallerServiceVerificationHelper.verifyDownload(InstallerServiceVerificationHelper.java:102)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at com.oculus.appmanager.installer.service.InstallerServiceManager.verify(InstallerServiceManager.java:696)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at com.oculus.appmanager.installer.service.InstallerServiceManager.onDownloadComplete(InstallerServiceManager.java:140)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at com.oculus.appmanager.installer.service.InstallerService.handleAction(InstallerService.java:149)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at com.oculus.appmanager.installer.service.InstallerService.onHandleIntent(InstallerService.java:93)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at android.os.Handler.dispatchMessage(Handler.java:102)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at android.os.Looper.loop(Looper.java:154)
12-20 00:48:23.972  1842  7988 E com.oculus.appmanager.info.InfoUtils:  at android.os.HandlerThread.run(HandlerThread.java:61)
12-20 00:48:23.974  1684  1684 D [OAN] VrBroadcastReceiver: action: com.oculus.vrshell.intent.action.NOTIFICATION_WAKE
12-20 00:48:23.977  1684  1684 D [OAN] VrNotificationService: VrNotificationService onStartCommand() Intent { cmp=com.oculus.vrshell/.VrNotificationService }
12-20 00:48:23.990  1672  1672 D [SUI] NotificationBroadcastReceiver: action: com.oculus.intent.action.NOTIF_CHANGE
12-20 00:48:23.990  1672  1672 I NotificationManagerSourceHandler: Dataset has changed
12-20 00:48:24.004  1672  1672 V NotificationManagerSourceHandler: Notifications in manager set and current set are the same size
12-20 00:48:24.005  1672  1672 V NotificationManagerSourceHandler: Removing a download notification for update NativeNotification{id: 20007, title: T├®l├®chargement de ALVR..., text: 100%, category: DOWNLOAD_IN_PROGRESS}
12-20 00:48:24.005  1672  1672 V NotificationDatasetProxy: Removing notif NativeNotification{id: 20007, title: T├®l├®chargement de ALVR..., text: 100%, category: DOWNLOAD_IN_PROGRESS} from central list
12-20 00:48:24.006  1672  1672 V NotificationManagerSourceHandler: DOWNLOADS
12-20 00:48:24.009  1672  1672 V NotificationManagerSourceHandler: Adding an updated download notification NativeNotification{id: 20007, title: Installation, text: ALVR, category: DOWNLOADS}
12-20 00:48:24.009  1672  1672 V NotificationDatasetProxy: Adding new notif NativeNotification{id: 20007, title: Installation, text: ALVR, category: DOWNLOADS} to central list
12-20 00:48:24.009  1672  1672 D [SUI] AnytimeUINotifsBarView: onNotificationsChanged - skipped, detils bar not visible
12-20 00:48:24.020  1672  1672 E [SUI] AnytimeUINotifsBarView: Unexpected badge route, ignoring: systemux://notifications
12-20 00:48:24.032  1842  7988 I InstallerFileUtils: Attempted to remove file /storage/emulated/0/Download/oculus_downloaded_apks/88.com.polygraphene.alvr.oculus.apk_downloading for reason "clean up", removed = not found
12-20 00:48:24.033  1842  7988 I InstallerFileUtils: Attempted to remove file /storage/emulated/0/Download/oculus_downloaded_apks/88.com.polygraphene.alvr.oculus.apk for reason "clean up", removed = not found
12-20 00:48:24.035  1842  7988 I InstallerFileUtils: Attempted to remove file /storage/emulated/0/Download/oculus_downloaded_apks/88.com.polygraphene.alvr.oculus.apk for reason "clean up", removed = not found
12-20 00:48:24.044  1842  7988 I InstallerFileUtils: Attempted to remove file /data/user/0/com.oculus.ocms/files/apk_to_install/88.com.polygraphene.alvr.oculus.apk for reason "clean up", removed = true
12-20 00:48:24.051  1842  1842 I LibraryProvider: running queryApp(com.polygraphene.alvr.oculus) for com.oculus.ocms
12-20 00:48:24.061  1842  2599 I LibraryProvider: running queryApp(com.polygraphene.alvr.oculus) for com.oculus.ocms
12-20 00:48:24.074  1842  2599 I LibraryProvider: running update(com.polygraphene.alvr.oculus, values[5]) for com.oculus.ocms
12-20 00:48:24.074  1842  2599 I LibraryStorage: status changing for com.polygraphene.alvr.oculus from INSTALLING to ENTITLED
12-20 00:48:24.097  1842  2599 I LibraryStorage: Successfully saved 1 entitlements. Total entitlements: 106. Notifying: 1
12-20 00:48:24.097  1842  2599 I LibraryStorage: notifying: content://com.oculus.ocms.library/apps/com.polygraphene.alvr.oculus
12-20 00:48:24.241  1842  1842 I LibraryProvider: running queryApp(com.polygraphene.alvr.oculus) for com.oculus.ocms
12-20 00:48:24.251  1842  1842 I LibraryProvider: running queryApp(com.polygraphene.alvr.oculus) for com.oculus.ocms
12-20 00:48:24.257  1842  1842 I LibraryProvider: running queryApp(com.polygraphene.alvr.oculus) for com.oculus.ocms
12-20 00:48:24.272  1842  1842 I LibraryProvider: running queryApp(com.polygraphene.alvr.oculus) for com.oculus.ocms
12-20 00:48:24.302  1261  1261 D OculusNotificationListenerService: Notification posted: 0|com.oculus.ocms|20007|null|10042
12-20 00:48:24.308  1684  1684 I [OAN] VrNotificationListenerService: onNotificationPosted(): key = 0|com.oculus.ocms|20007|null|10042, type = invalid
12-20 00:48:24.308  1684  1684 I [OAN] VrNotificationListenerService: onNotificationPosted(): user|package|tag|id = UserHandle{0}|com.oculus.ocms|null|20007
12-20 00:48:24.321  1684  1684 E OsSdk   : Failed to connect to XrspBroker.
12-20 00:48:24.322  1684  1684 D VrNotificationAnalytics: logNotificationPosted(invalid)
12-20 00:48:24.324  1684  1684 D [OAN] VrBroadcastReceiver: action: com.oculus.vrshell.intent.action.NOTIFICATION_WAKE
12-20 00:48:24.333  1684  1684 D [OAN] VrNotificationService: VrNotificationService onStartCommand() Intent { cmp=com.oculus.vrshell/.VrNotificationService }
12-20 00:48:24.338  1672  1672 D [SUI] NotificationBroadcastReceiver: action: com.oculus.intent.action.NOTIF_CHANGE
12-20 00:48:24.338  1672  1672 I NotificationManagerSourceHandler: Dataset has changed
12-20 00:48:24.348  1672  1672 V NotificationManagerSourceHandler: Notifications in manager set and current set are the same size
12-20 00:48:24.350  1672  1672 V NotificationManagerSourceHandler: Removing a download notification for update NativeNotification{id: 20007, title: Installation, text: ALVR, category: DOWNLOADS}
12-20 00:48:24.351  1672  1672 V NotificationDatasetProxy: Removing notif NativeNotification{id: 20007, title: Installation, text: ALVR, category: DOWNLOADS} from central list
12-20 00:48:24.352  1672  1672 V NotificationManagerSourceHandler: DOWNLOADS
12-20 00:48:24.353  1672  1672 V NotificationManagerSourceHandler: Adding an updated download notification NativeNotification{id: 20007, title: ├ëchec de lÔÇÖinstallation, text: ALVR, category: DOWNLOADS}
12-20 00:48:24.355  1672  1672 V NotificationDatasetProxy: Adding new notif NativeNotification{id: 20007, title: ├ëchec de lÔÇÖinstallation, text: ALVR, category: DOWNLOADS} to central list
12-20 00:48:24.355  1672  1672 D [SUI] AnytimeUINotifsBarView: onNotificationsChanged - skipped, detils bar not visible
12-20 00:48:24.368  1672  1672 E [SUI] AnytimeUINotifsBarView: Unexpected badge route, ignoring: systemux://notifications

**Comment by Ekristoffe** [comment]
ok it seem the Oculus GO App store doesn't have the file anymore but the link is still valid ...
Please try with this :

Install from apk
- Need to enable developer option for Quest.
- Download apk from [Releases](https://github.com/polygraphene/ALVR/releases)
- Check [Installation](https://github.com/polygraphene/ALVR/wiki/Installation).
