### ISSUE TITLE
it was not possible to install ALVR in Gear Vr - Galaxy S6+

### ISSUE THREAD

**Issue by Alex-Basto** [polygraphene/ALVR#694]
I can't install ALVR on my galaxy s6 + anymore, even redeeming the application code, the installation error, plus anyone with the same problem?

**Comment by Ekristoffe** [comment]
ok it seem the Oculus GO App store doesn't have the file anymore but the link is still valid ...
Please try with this :

Install from apk
- Need to enable developer option for Quest.
- Download apk from [Releases](https://github.com/polygraphene/ALVR/releases)
- Check [Installation](https://github.com/polygraphene/ALVR/wiki/Installation).
