### ISSUE TITLE
Keys sold out

### ISSUE THREAD

**Issue by Ishmaelinhabits** [polygraphene/ALVR#696]
Went to get a key for ALVR, but they're sold out.

**Comment by coolautech** [comment]
I want a key too. :-)

**Comment by polygraphene** [comment]
Thank you for reporting.
Currently we have another problem on installation.
Please check https://github.com/polygraphene/ALVR/issues/695#issuecomment-757471079

**Comment by polygraphene** [comment]
Key distribution has been discontinued. Use apk method instead.
See https://github.com/polygraphene/ALVR/issues/695#issuecomment-769342707
