### ISSUE TITLE
No keys, it said to notify dev here

### ISSUE THREAD

**Issue by SomeRandomPokemon42** [polygraphene/ALVR#697]

**Comment by polygraphene** [comment]
Thank you for reporting.
Currently we have another problem on installation.
Please check https://github.com/polygraphene/ALVR/issues/695#issuecomment-757471079

**Comment by polygraphene** [comment]
Key distribution has been discontinued. Use apk method instead.
See https://github.com/polygraphene/ALVR/issues/695#issuecomment-769342707
