### ISSUE TITLE
Keys are missing.

### ISSUE THREAD

**Issue by NOtANamee** [polygraphene/ALVR#698]
Not to be a bother, but I am unable to get a key. I have seen previous messages about a separate issue and would just like an update on how things are going. Good luck mate.

**Comment by Ekristoffe** [comment]
Thank you for reporting.
Currently we have another problem on installation.
Please check #695 (comment)

**Comment by polygraphene** [comment]
Key distribution has been discontinued. Use apk method instead.
See https://github.com/polygraphene/ALVR/issues/695#issuecomment-769342707
