### ISSUE TITLE
issue#695

### ISSUE THREAD

**Issue by CloudzInnit** [polygraphene/ALVR#701]
I cannot seem to be able to get a key to redeem can someone help

**Comment by Ekristoffe** [comment]
Thank you for reporting.
Currently we have another problem on installation.
Please check https://github.com/polygraphene/ALVR/issues/695#issuecomment-757471079

_Originally posted by @polygraphene in https://github.com/polygraphene/ALVR/issues/697#issuecomment-757480106_

**Comment by polygraphene** [comment]
Key distribution has been discontinued. Use apk method instead.
See https://github.com/polygraphene/ALVR/issues/695#issuecomment-769342707
