### ISSUE TITLE
Oculus Quest 2 not working on Alvr?

### ISSUE THREAD

**Issue by SeanYo9229** [polygraphene/ALVR#702]
![thing](https://user-images.githubusercontent.com/78313965/106391325-b5cb5280-63ba-11eb-9fba-9e9f03b365de.PNG)
Every time I try to use ALVR v14.2.1 on my Oculus Quest 2, this message pops up and Steam VR just doesn't work. Can someone please help!!!

**Comment by SeanYo9229** [comment]
also here is my computer stuff
![System 1_31_2021 11_40_00 AM (2)](https://user-images.githubusercontent.com/78313965/106391446-4f92ff80-63bb-11eb-883d-d9ece2ccabd3.png)

**Comment by Ekristoffe** [comment]
Hello you are not on the right repository.
Please report the problem on https://github.com/alvr-org/ALVR/issues/

**Comment by SeanYo9229** [comment]
> Hello you are not on the right repository.
> Please report the problem on https://github.com/alvr-org/ALVR/issues/

Thanks!
