### ISSUE TITLE
Rainbow artifacts when increasing video resolution - Quest 2

### ISSUE THREAD

**Issue by xcloudx01** [polygraphene/ALVR#708]
I'm unable to increase the video resolution as when I pick something over 100%, I get the following video artifacts:
https://www.youtube.com/watch?v=uTwGrkk0Q-U

Weirdly enough it only occurs inside the headset, it doesn't appear if i record a video using the headset.

**Comment by Ekristoffe** [comment]
are you using polygraphene ALVR or the quest optimized fork:
https://github.com/alvr-org/ALVR

**Comment by xcloudx01** [comment]
I'm using the quest optimized fork that you linked

**Comment by Ekristoffe** [comment]
In that case please open a support request on the fork.

**Comment by xcloudx01** [comment]
Thanks, will do.
