### ISSUE TITLE
Guide for QOS + Gamestream. Made a difference here, maybe add it to troubleshooting page

### ISSUE THREAD

**Issue by vrokolos** [polygraphene/ALVR#71]
https://www.reddit.com/r/theNvidiaShield/comments/2rkzgr/shield_portable_gamestream_tips_that_helped_out_a/

**Comment by polygraphene** [comment]
Thank you!
I created troubleshooting page.
https://github.com/polygraphene/ALVR/wiki/Troubleshooting
You can freely edit this wiki.
