### ISSUE TITLE
[info needed] ALVR design / protocol

### ISSUE THREAD

**Issue by hrvach** [polygraphene/ALVR#712]
I'm trying to figure out how to stream (low latency) video to the Quest 2 and ALVR seems like an ideal choice.

Is there any documentation about the protocol or block diagram? From what I've figured, there is a control port 9944 where the client from the Quest connects and issues commands (like connect host:port), then receives video packets there with additional FEC information to allow for some packet loss. Apparently it leverages NVENC capability on Nvidia GPUs to encode (h.264?) video in realtime, with lowest latency possible and send to the headset.

Any pointers or docs about the simplest way to send some video data to the device without using the provided server? My use case is generating the stream in hardware.

Thanks for any help or advice and great work on the project!

**Comment by Ekristoffe** [comment]
Hello, for this i would recommend you to go to https://github.com/alvr-org/ALVR also if possible go to their Discord.
