### ISSUE TITLE
ALVR server has crashed. Sorry for the inconvenience

### ISSUE THREAD

**Issue by cots-xd** [polygraphene/ALVR#713]
Everytime i pull the trigger to launch steamvr the server crashes

Error on parsing json: syntax error at line 1 near: NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN],enableSound:true,soundDevice:{0.0.0.00000000}.{98775098-b7e4-4b0f-8c64-fb0684ed8cb3},debugOutputDir:C:\\Program

UdpSocket::BindSocket bind error : Address=:0 10049 The requested address is not valid in its context.

**Comment by eMech69** [comment]
I am getting this error also, I didn't do anything, it worked perfectly yesterday but now, now it's broken.
