### ISSUE TITLE
I can't Uninstal ALVR from my pc

### ISSUE THREAD

**Issue by NightWolf301** [polygraphene/ALVR#717]
Ok some how this have been 5 days and it wouldn't be able to get removed from my pc can you you help me please

**Comment by Ekristoffe** [comment]
hello, what installer have you used ?

**Comment by NightWolf301** [comment]
The one from here and I try everything to remove it and it still there

**Comment by Ekristoffe** [comment]
Do you have any error message ?
Since the soft is also usable without installer I don't think there is any register key change done by it.
You may be able just to open it, unregister the drivers and delete it manually from the pc

**Comment by NightWolf301** [comment]
How do I do that?

**Comment by asdraper0** [comment]
As per the "uninstallation" section:

1. Execute `driver_uninstall.bat` in the driver folder
2. Delete the install folder (ALVR does not use the registry)

If you already deleted the folder without executing driver_uninstall.bat:
1. Open `C:\Users\%USERNAME%\AppData\Local\openvr\openvrpaths.vrpath` and check install directory
2. Execute `"C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win32\vrpathreg.exe" removedriver (install folder)` in Command Prompt

**Comment by NightWolf301** [comment]
so I just delete driver_uninstall.bat or just run it

**Comment by asdraper0** [comment]
You'll want to run it before deleting the ALVR directory.

**Comment by NightWolf301** [comment]
ok then I uninstall the app

**Comment by NightWolf301** [comment]
it work thank you so much
