### ISSUE TITLE
Poor tracking

### ISSUE THREAD

**Issue by ImmenseViola248** [polygraphene/ALVR#720]
I connect to the pc fine, get a good image, barely any latency, everything is smooth. The tracking lags by quite a bit though. The controllers sort of smoothly follow my movements. Beat saber is unplayable. Here are my pc specs just in case:

Windows 10 Pro 64-bit
Intel Core i5 4670K @ 3.40GHz
8,00GB Dual-Channel DDR3 @ 666MHz
2047MB NVIDIA GeForce GTX 750 Ti

 I know the computer is on the lower end, but beat saber achieves a perfect 72fps for me.
Edit: setting the refresh rate higher significantly improved tracking.

**Comment by Ekristoffe** [comment]
hello what version of ALVR are you using ?
