### ISSUE TITLE
Steam-vr blocking add-ons

### ISSUE THREAD

**Issue by Pedzio231** [polygraphene/ALVR#721]
Steam-Vr is blocking add-ons and I cant play vr games I downloaded latest version of alvr v16.0.0 when I unblock them and restart they are still blocked pls help 
![image](https://user-images.githubusercontent.com/91563527/135143623-94087dbb-dd3c-425a-9b7f-2f78f5510244.png)

**Comment by Ekristoffe** [comment]
you are not in the right repository.
you are talking about 
https://github.com/alvr-org/ALVR
open a ticket there and close this one.
thanks
