### ISSUE TITLE
create installer for server app

### ISSUE THREAD

**Issue by gb2111** [polygraphene/ALVR#74]
hi.
i could write simple installer using inno setup so you can get server installed, icon, etc.
if you like idea and have not planned anything else i would be happy to do that. 

unforunately I cannot compile project as I don't have cuda. if you could provide me compilete build folder and tell where you would like installer file to be and where to make package I would be able to contribute at least a little :)

greg

**Comment by polygraphene** [comment]
Thank you for your help!
I will be glad if you create that! Do you need all build output like *.obj or *.pdb?
I think if you have CUDA.lib (static library), you can avoid CUDA compilation.

[CUDA.zip](https://github.com/polygraphene/ALVR/files/2124622/CUDA.zip)

I don't know how we should collaborate to create installer. I added you as collaborator for now. So perhaps you can put it on release page by your privilege.
Please check it.

**Comment by gb2111** [comment]
i already tried but Visual Studio could not open CUDA project at all as there was some .properties file missing and path for this file was reffering to folder with CUDA name.

So full build would be best I think.

I guess best if I will make my changes on fork and make pull request.

**Comment by polygraphene** [comment]
Okay.
I can't upload packages (include libraries ALVR depends on) directory, because the directory is too large to upload on GitHub.
This zip contains 7zip archive of Release build outputs.

[ALVR.zip](https://github.com/polygraphene/ALVR/files/2127068/ALVR.zip)

> I guess best if I will make my changes on fork and make pull request.

I got it.

**Comment by gb2111** [comment]
hi.
you can get installer from my fork
https://github.com/gb2111/ALVR

it is in installer folder. there are empty license file, you can update but we can also remove.
you need install InnoSetup to make it working.

I assumed some names for program, group and not sure if they are ok.
if you open file you can change all easily. when you are ok I can make pull request to your branch.

let me know if you have any comments.

**Comment by sols000** [comment]
hi. @gb2111 
did you compile the ALVR with CUDA?  I can't Load CUDA, and I can't find <cuda.h> in NuEncoderCuda.h.

**Comment by gb2111** [comment]
i did not compile but used ready build that is attached to prev thread.
i asked for this just for purpose of making installer.

**Comment by polygraphene** [comment]
It works! Great!
Can you create PR? or can I pick your commit?

I don't know how to create license file. I want to put MIT license text. But, is it normal on an open source project?

We should add some files for newer version (it introduce new dlls).
I will try it myself after you send PR.

**Comment by gb2111** [comment]
hi,
here is [pr](https://github.com/polygraphene/ALVR/pull/98)

yes. this is quite easy. it would be good to check names as I don't think that mine are best ones :)
Also would be good to run something on uninstall to unregister driver. If you have any questions please let me know.

**Comment by polygraphene** [comment]
Thank you!
Yea. ALVR Client maybe a confusing name.
I will fix name and add code to run driver_uninstall.bat on uninstall.

**Comment by gb2111** [comment]
OMG!
i forgot the file is there.

just add something like this:

[UninstallRun]
Filename: {app}\driver_uninstall.bat;

**Comment by polygraphene** [comment]
@gb2111 Oh! Thank you!

@sols000 Install CUDA 9.2 and check CUDA_PATH point to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
Or you can remove CUDA related code. CUDA is only used for Windows 7.
