### ISSUE TITLE
Change left / right of controller, and assign buttons and touch pad to keyboard or xbox controller

### ISSUE THREAD

**Issue by okuda** [polygraphene/ALVR#76]
The pleasure of Oculus go has increased very much with AlVR you made. Thank you.
By the way, I like to enjoy Google earth VR with ALVR, I am manipulating ALVR controller settings every time. However, since it is very hard, I am exploring whether it is possible to assign the left / right change of the controller and the operation of buttons and touch pad to the keyboard and xbox controller.
Perhaps these functions are beneficial to other VR applications as well.
I expect information such as implementation of their function in ALVR and its remodeling method, integration with controller emulation application such as Freepie etc.

**Comment by polygraphene** [comment]
I noticed that various requests around the controller exist. But if we implement all of those request, ALVR will become fat codebase.
So I want to add integration for FreePIE on ALVR. I'm searching on FreePIE now.
Please wait.

**Comment by okuda** [comment]
That's a very nice news! I am looking forward to its development. Although it is a small amount, I donated it.

**Comment by okuda** [comment]
Thanks! perfect job!

this movie is alvr 2.2.2!
https://youtu.be/EWyuX3u9oTg
https://youtu.be/vtm-rAgBWFc
https://youtu.be/Egnuypry0Ns
