### ISSUE TITLE
Can't run Steam Room Setup

### ISSUE THREAD

**Issue by ekode** [polygraphene/ALVR#77]
I am stuck. Installed ALVR Client and Server.
I run server and click "Start Server". It finds my headset and then I click connect.
Steam VR starts and tells me that Room is not set up.

I run Room setup (standing only) and get to the point where it tells me to put headset to location where it will be visible from base stations. Here I see a message that headset is not visible and next button is grayed out. I can't proceed further.

What is it that I am missing?

UPDATE:
I see no mention on height anywhere in Steam VR settings. I googled this problem to death. Everybody says that setting height is part of room setup process and cannot be avoided.
I even installed tool "OpenVR Advanced Settings" that allows changing height, but I can't access it because I can't really access steam cause I didn't finish room setup.

I found option Quick Calibrate. Settings > Developer > Room and Tracking > Quick Calibrate
It seems that this is what I am supposed to use, but it doesn't work.
Really bummed about this. Debugger is not showing any errors. Client on device is displaying "press connect on the server..." and that message never goes away

The only thing what I did that is different from installation instructions is that I didn't install vc_redist.x64.exe because I already had newer version on my Windows 10 machine.

**Comment by vrokolos** [comment]
You don't need to run room setup. I remember somewhere on the settings I manually set my height using keyboard and mouse. Look for that

**Comment by Thaurin** [comment]
Yes, this. I entered this information manually with the keyboard as well.

**Comment by ekode** [comment]
There is nothing in Steam VR settings that reassemble height. I googled this problem to death. Everybody says that setting height is part of room setup process. 
I even installed tool "OpenVR Advanced Settings" that allows changing height, but I can't access it because I can't really access steam cause I didn't finish room setup.

**Comment by ekode** [comment]
Settings > Developer > Room and Tracking > Quick Calibrate
It seems that this is what I am supposed to use, but it doesn't work.
Really bummed about this. Debugger is not showing any errors. Client on device is displaying "press connect on the server..." and that message never goes away

**Comment by vrokolos** [comment]
Do room setup with your mouse and keyboard. I tuink there it is after some screens

**Comment by ekode** [comment]
Can you please take time to explain how to do that?
I am using mouse and keyboard. Whole Steam Room Setup is always done with mouse and keyboard. My problem is that eventually I get to the point (second screen I think) where I can't proceed as NEXT button is disabled. I can't click on the NEXT button.

**Comment by vrokolos** [comment]
Second screen it tries to find the headset. Is ALVR on? And is Steam VR showing you that a headset (green icon) is connected and tracking? Did you try to wear the headset? Is it connected?

**Comment by jamskahler** [comment]
So has anyone found a solution to this yet? How are you supposed to get past a room setup screen that requires the headset to be detected by the base sensors? 

Just curious

**Comment by polygraphene** [comment]
Did you connect your headset with ALVR server?
If you could get connected, you will get the display like following.
![](https://raw.githubusercontent.com/wiki/polygraphene/ALVR/installation/room-setup-4.png)

**Comment by jamskahler** [comment]
I'll check out the tabs on ALVR to see if that's what's going on, but the issue is that the next button is greyed out, and several others are reporting this issue.

I want to say that my computer did in fact recognize that there was a VR headset attached, but I'm not sure if ALVR was seeing it.

Will give it a shot tonight to see what's going on. Prediction is that issue will be unresolved, if I do get it resolved I will absolutely post solution.

**Comment by jamskahler** [comment]
Ok, so ALVR is not recognizing the headset, but I am getting Steam VR recognizing the headset:
![capture](https://user-images.githubusercontent.com/19949947/44452143-97868900-a5aa-11e8-8789-09ac0e323a83.PNG)

**Comment by polygraphene** [comment]
You should solve a network issue before proceeding to room setup.
Please open 9944/UDP on firewall settings.
And also check this page.
https://github.com/polygraphene/ALVR/wiki/Troubleshooting#ip-address-is-not-displayed-on-alvrexe

**Comment by jamskahler** [comment]
Cool cool, thanks - will update

**Comment by jamskahler** [comment]
Ok, so I've been working on this for a while tonight and still haven't gotten any further.

I am using a mobile hotspot (Sprint R850) for a LAN connection and am wondering if this is part of the issue, as it seems to work seamlessly for other folks w/ regular routers.

Not sure where to go from here, but would really like to be able to do this. Is there any way to tether the Oculus Go via USB to get around this issue?

**Comment by polygraphene** [comment]
@jamskahler Did you connect PC and Go on the same router? If so, you can get it working.
Can you try `ping (IP Address of Go)` on command prompt?

Currently Oculus Go can't be used with USB connection. I have a plant to support USB connection, but I don't know when it is done.

**Comment by jamskahler** [comment]
I got it!!!! YAY!!

I had to turn off "Privacy Separator" on my router settings to allow other devices to see each other.

Have successfully connected headset to computer via ALVR and gotten past room setup.

**Comment by jamskahler** [comment]
Now to find a cheap 5 Ghz router lol... (mine only has 2.4 Ghz)

**Comment by Eltomato22** [comment]
Cheaper option: usbc to ethernet adapter and ethernetcable. (Enable ethernet in phones developer options). I have 5ghz wifi and still use cable
