### ISSUE TITLE
Alvr Download for GearVr

### ISSUE THREAD

**Issue by ICURSEDANGEL** [polygraphene/ALVR#81]
Hey! i have been searching on how to get a download key for the Gearvr but im unable to find may i know from where to get a code please?

**Comment by polygraphene** [comment]
You can get key from here.
https://alvr-dist.appspot.com/

**Comment by ICURSEDANGEL** [comment]
the link isnt working for me not sure why says page not found is there any other way i could get or if you could support me with a key please?

**Comment by ICURSEDANGEL** [comment]
IT WORKS!!! thank you so much and may i ask if theres a discord server related to the app?

**Comment by ICURSEDANGEL** [comment]
why does the app only shows black screen?

**Comment by polygraphene** [comment]
I did not heard discord about ALVR. I sometimes find the reddit thread about ALVR on https://www.reddit.com/r/OculusGo/
I don't know except for this.

**Comment by polygraphene** [comment]
What did you do on service side?
Can you see "press button" message on client?

**Comment by thoughtfix** [comment]
Since the install key issue is resolved. please mark this as closed in the issue tracker and continue debugging the black screen issue on the other open issue #82 

Just trying to keep things clean for other users :)
