### ISSUE TITLE
Alvr V2.1.5 black screen gearv vr+s7 edge

### ISSUE THREAD

**Issue by ICURSEDANGEL** [polygraphene/ALVR#82]
when i launch the Alvr app for the gearvr it just shows a black screen nothing else. any fix?

**Comment by polygraphene** [comment]
Can you see "press CONNECT button" message?
If you don't see that, please send a output of `adb logcat` by connecting your phone with USB.

**Comment by ICURSEDANGEL** [comment]
i see nothing.

is there a tutorial video on how to setup?

**Comment by polygraphene** [comment]
tutorial of adb setup?
I think you can use "minimal adb" and following video.
https://www.youtube.com/watch?v=DPWEG3kkvXU

**Comment by ICURSEDANGEL** [comment]
do i turn on developer mode on my device or theres no need?
