### ISSUE TITLE
It keeps saying that steamvr isn't installed.

### ISSUE THREAD

**Issue by CommanderFrostbite** [polygraphene/ALVR#83]
i installed it but it says it isn't installed help.

**Comment by crimson-woof** [comment]
SteamVR installed on C drive default path?  If not, try that first.

**Comment by thoughtfix** [comment]
In Steam your Steam library under VR, right click on the SteamVR application and go to Properties. From there, click on the Local Files tab. It should say something like "Disk Usage: xxxx MB on drive C:" 

If it says anything other than Drive C, ALVR might not detect it. You can use the "move install folder" button on that tab to move it to the default C: library.  Where are you getting the error that "it keeps saying steamvr isn't installed?"  What are you doing when that error pops up?

If this solves your issue, please make sure to mark the issue as "resolved" in this tracker.

**Comment by CommanderFrostbite** [comment]
okay so it is installed on drive c. after i boot it up. When i start ALVR up on pc it says "cannnot load library. ALVR works only on 64bits Windows" along with C:\Users\user\Downloads\ALVR-v2.1.5-portable\ALVR\driver\bin\win64\driver_alvr_server.dll

after it says that, i just go on with the application and then it says "SteamVR is not installed. Registry (HKEY_CLASSES_ROOT\vrmonitor\shell\open\command was not fouund.) Please install and try again" when i try to start the server or install the drivers through the app, even though i installed steamvr

**Comment by vrokolos** [comment]
What GPU do you have?

**Comment by kuhiobay** [comment]
Hi! I'm totally new here. I had that same issue when trying to innitiate ALVR, but all I had to do to solve it was to run at least one time SteamVR. After that one time, ALVR ran perfect. Perhaps this might help you. Sorry, english is not my native language.

**Comment by CommanderFrostbite** [comment]
okay that partially worked but i have another problem. when i start ALVR up on pc it says "cannnot load library. ALVR works only on 64bits Windows" along with C:\Users\user\Downloads\ALVR-v2.1.5-portable\ALVR\driver\bin\win64\driver_alvr_server.dll and running steamvr only fixed the second part of my dilemma. even then you still helped me solve my problem a lil bit so thanks.

**Comment by kuhiobay** [comment]
I've been there DUPERMUSHROOM... it means that you have to run the Steam VR software on Steam, double click and open it. Just that. Then you close it, and from now on, when you run the VR game you want to play, Steam VR opens automatically. But the first time, before playing any VR game, you have to open Steam VR one time.

**Comment by zaki123x** [comment]
Any help guys on this ?

**Comment by zaki123x** [comment]
I am getting exact same messages as above ?

**Comment by BogdanBerg** [comment]
I had the same problem. I have Steam installed in a custom location, no the default on system drive under Program Files (x86).

Solution - create a symbolic link. Open administrative command prompt and run (update the second path to point to your Steam location):
mklink /D "C:\Program Files (x86)\Steam" "D:\Steam"

Then launch SteamVR at least once, as mentioned above (right click on Steam in tray -> SteamVR). It won't detect headset, but that's ok. Now try launching ALVR again - it should now work!

**Comment by kingkw1** [comment]
Worked for me. Thanks BogdanBerg!

**Comment by TheTypographer** [comment]
> I had the same problem. I have Steam installed in a custom location, no the default on system drive under Program Files (x86).
> Solution - create a symbolic link. Open administrative command prompt and run (update the second path to point to your Steam location):
> mklink /D "C:\Program Files (x86)\Steam" "D:\Steam"
> Then launch SteamVR at least once, as mentioned above (right click on Steam in tray -> SteamVR). It won't detect headset, but that's ok. Now try launching ALVR again - it should now work!

I'm getting the same issue. I tried using the command you mentioned, but it said: "Cannot create a file when that file already exists."
BTW, I have Steam installed on Drive C, but I have SteamVR installed on a separate hard drive, could that be the issue?

**Comment by BogdanBerg** [comment]
I think this might indeed be the problem (the fact that you have steam
installed on C and Steam VR on D) . I suspect if you check the contents of
D:\Steam, you'll find some files and folders there. As such, running the
above command for each of those files and folders would probably fix it (as
that way we'd create links for the SteamVR contents). Be sure to modify the
command accordingly.

For example, if under D:\Steam you find "folder1" and "file1" you'd run:

mklink /D "C:\Program Files (x86)\Steam\folder1" "D:\Steam\folder1"
mklink "C:\Program Files (x86)\Steam\file1" "D:\Steam\file1"

One thing that will be problematic is if there are some folders with same
names in those locations - it will give you same error, in which case we'd
have to navigate into those folders and create links recursively.

I suspect, if possible, reinstalling SteamVR into the root location of
Steam is a safer and less hacky solutions... 😊

Hope that helps!

Thanks,
Bogdan

**Comment by victorkc** [comment]
Hi,
 
Maybe this won't work for all but I had the problem and I solved this just starting SteamVR first and then initiate ALVR, for me works.

Regards.
