### ISSUE TITLE
Gear VR S7 AR CORE

### ISSUE THREAD

**Issue by ManuelGDA** [polygraphene/ALVR#84]
What is the process to enable 6dof with arcore? I have a Gear VR with an S7, installed the last servers and clients, I m going to check wich server client versions are installed. I installed AR core through google play, and checked some aplications to see if it worked, (e.g. IKEA app, etc) they do work but I am missing something maybe, could someone describe the process to make arcore 6dof work? Thank you all and specially thanks to the creator of the program :D!

**Comment by ManuelGDA** [comment]
Ok instaled the arcore from google play again, the apk 2.1.5 portable client for arcore and the 2.1.5 server. I loaded the app and found that on the connect screen it only rendered the right eye. But when I connected the 6dof worked! it was a little buggy but it is a very nice achievement! I used my phone in flight mode to prevent other apps to lag the system, but I dont know if in this case its better to put on the airplane mode or not... Maybe the Real life room setup was not apropiated, the phone was not fully charged and already hot. I will test it with full batery, without  other processes running in the background. I plan to test it with a fast charge external batery and a CUVR cooling fan. Any tip to make the 6dof work better would be super ;) , and I am eager to try a more stable version of the arcore version. This is so great!!!

**Comment by polygraphene** [comment]
I think flight mode is almost no effect about it.
What the exact problem do you experience?

If you get "warp to another position", ARCore may lose the tracking, I think.
We may need a flat floor with enough "interesting point" for ARCore to correctly work.

https://developers.google.com/ar/discover/
>ARCore's motion tracking technology uses the phone's camera to identify interesting points, called features, and tracks how those points move over time. With a combination of the movement of these points and readings from the phone's inertial sensors, ARCore determines both the position and orientation of the phone as it moves through space.

https://github.com/ChristophGeske/ARCoreInsideOutTrackingGearVr
> Fast movements, featureless white areas and poorly lit areas can affect the quality of tracking
  severely ...

**Comment by co5mo** [comment]
@ManuelGDA try enabling game mode in s7 arcore worked perfectly for me S7E Exynos Nougat
