### ISSUE TITLE
Grey screen in Steam, frame rate immeasurably slow

### ISSUE THREAD

**Issue by thoughtfix** [polygraphene/ALVR#85]
Hi ALVR! I just installed today's version of everything, updated my GPU drivers, and gave it a shot. 

SteamVR detects the headset and the mirror window shows head movement and controller movement, but the image on the Oculus Go is just one big grey screen with compression artifacts. I logged into my router to watch traffic and it was transferring data at 3.8 MBPS (so almost 30 megabit on the nose) so it must be a decompression issue on the Oculus Go? Head movement within the VR environment inside the headset works in that it moves the compression artifacts pretty close to 1:1 movement in the grey screen. 

Any thoughts?

**Comment by thoughtfix** [comment]
Source system: 6700K @ 4.7GHz, 2x980 Ti (tried with SLI enabled and disabled.) 

Render speed in the Steam preview window is plenty fast. Latest nvidia drivers as of today.

**Comment by polygraphene** [comment]
Do you get same issue whenever restart client?
Please try adjust video bitrate or buffer size. And try to press "Cause packet loss" button on Debug tab.

**Comment by thoughtfix** [comment]
I have yes, but given another user's report of issues with dual GPUs even with SLI disabled, I am going to attempt to install the driver on another system to see if a single-card system will handle it better.

**Comment by thoughtfix** [comment]
Okay further testing: 

Totally separate PC on the same wired network (7700k@4.9GHz, 1080 Ti) and same wifi. Same Oculus Go. Same result.  Tried about 10 different settings between 1mbit and 100mbit (restarting the server each time) and no appreciable change. It looks like it is simply having difficulty decoding the stream. Communication from headset to server seems fine: the movement of my head is reflected instantly in the VR mirror window.

Ran a couple internet speed tests in the Go's browser. Even the lowest of the results was above 30mbit so that should rule out a bandwidth issue. Router is an AC68U that's older, but still stable most of the time (though showing some drops and errors to my nvidia TV hield from time to time - maybe showing signs of age) and within 8 feet line-of-sight to the Oculus Go.

Logged into the router: When set to 30mbit, the stream of the grey SteamVR home (which is, I assume, the source of my artifact-filled not-moving grey screen) pushes about 21 mbit and that's reflected in the traffic monitor to the 5GHz link reporting 2,671 KB/s.

Checking CPU power on the Oculus - without rebooting played Dead and Buried and Tomb Raider VR games without a hitch, plus some some low-quality streaming from Within and some high-quality streaming locally on my network using SkyboxVR. I even stuck a heatsink to the front of the headset and plugged it into the wall to make sure it wasn't a power/heat issue.

I was thinking of replacing that router anyway, but am open to further suggestions.

**Comment by vrokolos** [comment]
while streaming does alvr server show any packet loss?

**Comment by thoughtfix** [comment]
Good question: 
I checked the Go's Wifi and it's reporting a 5GHz link, "excellent" quality, and 866mbit negotiated speed

OH YES does it show packet loss! Wow it spikes up HIGH. It's saying it's losing orders of magnitude more packets than it is sending:  https://i.imgur.com/ycKSXFU.png

__

**Comment by vrokolos** [comment]
hell... your network is messy. try changing qos settings. check main page for guide

**Comment by vrokolos** [comment]
https://www.reddit.com/r/theNvidiaShield/comments/2rkzgr/shield_portable_gamestream_tips_that_helped_out_a/

also raise the buffer to 1mb

**Comment by thoughtfix** [comment]
This was fun to record:
https://youtu.be/uR3rIOz9LHM

QOS was disabled on my router. The only QOS options are for internet shaping and not for LAN/wireless traffic shaping.

**Comment by vrokolos** [comment]
Well can't help you there :P

You need to try different wifi channels / settings, move router etc I guess

**Comment by thoughtfix** [comment]
I just tried iperf to look at the UDP on my wifi and it's just awful. No
router settings have helped thus far. I guess #closed

Connecting to host 192.168.1.200, port 5201
[  4] local 192.168.1.193 port 57415 connected to 192.168.1.200 port 5201
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.00   sec   152 KBytes  1.24 Mbits/sec  19
[  4]   1.00-2.00   sec   120 KBytes   985 Kbits/sec  15
[  4]   2.00-3.00   sec   136 KBytes  1.11 Mbits/sec  17
[  4]   3.00-4.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   4.00-5.00   sec   112 KBytes   918 Kbits/sec  14
[  4]   5.00-6.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   6.00-7.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   7.00-8.00   sec   136 KBytes  1.12 Mbits/sec  17
[  4]   8.00-9.00   sec   144 KBytes  1.18 Mbits/sec  18
[  4]   9.00-10.00  sec   136 KBytes  1.12 Mbits/sec  17
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total
Datagrams
[  4]   0.00-10.00  sec  1.29 MBytes  1.08 Mbits/sec  0.146 ms  0/164 (0%)
[  4] Sent 164 datagrams

iperf Done.

**Comment by polygraphene** [comment]
Thank you for executing various checks!

The broken "packet loss" counter is caused by out-of-order packet. ALVR client reports negative value as lost packet on bad ordered packet. And the GUI shows broken values.
I will fix the broken counter on future release. And I want to add packet re-ordering function to recover by this types of network error.
Current ALVR implementation is very weak for continuous out-of-order packet.

**Comment by thoughtfix** [comment]
Chalking this one up to a router not properly handling UDP traffic.  Closing. Thanks for all the help!

**Comment by thoughtfix** [comment]
Replaced flaky AC-68U with new AC-86U. Buttery smooth movement now. Thanks!
