### ISSUE TITLE
New user, need help setting up ALVR

### ISSUE THREAD

**Issue by jceetnm** [polygraphene/ALVR#86]
I read about ALVR on reddit/OculusGo and figured I'd give it a shot. But I am running into some problems. 

- I did not install vc_redist.x64 because I already have the 2017 version and it does not allow me to install this on top. Do I need this version or is the 2017 ok?
- When I run SteamVR by itself, it runs fine. But when I start ALVR and it launches SteamVR, it is saying it is missing a key component (Error 301). I tried deleting openvrpaths and relaunching SteamVR, this didn't fix it. 
- When I start ALVR and click on Start Server, it will go to Server running for a second and then go offline. This is when SteamVR will say it is missing a key component.
- I do not see vrserver.exe, vrmonitor.exe, vrdashboard.exe and vrcompositor.exe in the task manager when ALVR is running
- List drivers only shows one location
- SteamVR is not installed on the C drive, but on my secondary. This is properly reflected in the openvrpaths file

Additional information:
GPU: GTX 1070
OS: Win10 64bit

Any help is appreciated.

**Comment by crimson-woof** [comment]
Did you install the driver?  The bat file has hardcoded path to C drive default steam directory.  Before start server, go to About page and see if driver is installed.  You do not need to install vc_redist if it says you have the later version.

**Comment by jceetnm** [comment]
I just reinstalled my Steam and SteamVR to the C drive. I am still running into the problem where when I click on Start Server, it will temporary say Server is Running and then return to original status. Then SteamVR will say it is missing key component. Running SteamVR by itself does not yield such error.

- Deleted the openvrpaths file
- Ran SteamVR
- Checked openvrpaths, it is pointing to steam on C drive now
- Uninstalled and reinstalled drivers on ALVR
- Tried putting ALVR on C drive and running it from there, still the same problem

**Comment by sergiu-paraschiv** [comment]
Same here. Funny thing is it worked at first but now SteamVR (vrserver.exe) refuses to start.

**Comment by jceetnm** [comment]
Actually yes, I do recall it working when I first ran it last night. It saw my headset, but when I tried to connect to it, it didn't work. And it just never worked after.

**Comment by jceetnm** [comment]
Unfortunately I already have 2.1.4

**Comment by jceetnm** [comment]
Ran SteamVR with my Rift just to make sure it works properly and it worked fine. 
It's just when ALVR launches SteamVR when it has problems.

**Comment by jceetnm** [comment]
- Checked graphics driver update, it is the latest release 398.11 released on June 5, 2018
- Do I have to configure some settings to enable NVENC?
- Updated ALVR to 2.1.5

**Comment by jceetnm** [comment]
Ok finally got it to run by disabling Steam sound under the Sound tab.

**Comment by crimson-woof** [comment]
Sound must be using 48000 hz sample rate, if using any other, ALVR won't work and needs Stream sound disabled.

**Comment by jceetnm** [comment]
I just checked and the default settings are 2 channel, 16 bit, 48000 Hz (DVD Quality).

**Comment by crimson-woof** [comment]
Hmm, couldn't find anything else about the Stream sound option other than https://github.com/polygraphene/ALVR/issues/75 (Closed).  Maybe something else isn't working.  Did you try debug log to see anything else wrong?  Developer might like that info.

**Comment by jceetnm** [comment]
I tried to run the debug log, but it does not generate any log files. It might have terminated before it even hit that point?

**Comment by crimson-woof** [comment]
debug log is for the driver, so it will create a log file in the driver directory when you click start server and the StreamVR loads up.  You have to close StreamVR to delete the debug file.

**Comment by vrokolos** [comment]
Try running it with no sound
