### ISSUE TITLE
Alvr 2.1.3(Arcore) says apk not signed when launching GearVr + S7 Edge

### ISSUE THREAD

**Issue by ICURSEDANGEL** [polygraphene/ALVR#87]
First of all i dowloaded the apk file 2.1.3 because the latest one 2.1.5 shows black screen and the 2.1.3 opened but says that apk not signed what should i do to fix it please help.

**Comment by wonjb0303** [comment]
also alvr (arcore) 2.1.5 SM-G965N 

Thread Priority Security Exception.
Make sure the APK is signed

please help

**Comment by ICURSEDANGEL** [comment]
@polygraphene could you please help us both sir

**Comment by vrokolos** [comment]
You need to insert the sig file using apk editor or get a key for the app store. The directions are on the main page. First do those

**Comment by polygraphene** [comment]
That error is caused by missed osig file as vrokolos said.
Please check this instruction.
https://github.com/polygraphene/ALVR/wiki/Installation#download-from-github-for-gear-vr-optional
