### ISSUE TITLE
YouTube VR, War Thunder, Elite Dangerous - head movement is jerky

### ISSUE THREAD

**Issue by Muhlawor** [polygraphene/ALVR#88]
When looking around image is laggy, same thing in War Thunder, Elite Dangerous. Framerate is 72fps constantly. VRChat and Bigscreen don't have this issue.

**Comment by Muhlawor** [comment]
Fixed Elite Dangerous by disabling SLI, but YouTube VR still lags.

**Comment by Muhlawor** [comment]
On mirrored image everything is smooth and 72 fps constantly, I have Intel I5-8400 and 1070TI in SLI

**Comment by polygraphene** [comment]
I have same issue on YouTube VR.
YouTube VR reports a wrong tracking data for rendered frame.
I will add an option to adjust this issue.

It is difficult to debug the problem on other games, because I have no SLI environment.

**Comment by Muhlawor** [comment]
Oh ok thanks, SLI is troublesome like that. On many games it either not working at all or just making problems.

**Comment by polygraphene** [comment]
I added the fix for YoutubeVR.
Try to put "-1" on TrackingFrameOffset on Other tab.
This feature is only added on alpha release.
If you want to use Oculus Store, please wait next stable release.
