### ISSUE TITLE
Pair the controller to the headset

### ISSUE THREAD

**Issue by penkamaster** [polygraphene/ALVR#9]
I take this bug / request to congratulate you on your project.
Works really great!!!
It's a pleasure to enjoy  VR dolphin or skyrim VR unthetered and with the visula quality of the go!!!

Just I just need to pair the gamepad to the headset to being able of enjoying it everywhere.

Thank you!!!!!!

**Comment by polygraphene** [comment]
Thank you for comment.
Does "pair the controller" mean "connecting a gamepad on Oculus Go with bluetooth"?
I recommend that you connect a gamepad on PC.
If you connect a gamepad on oculus go, it introduce an additional input latency.

**Comment by vrokolos** [comment]
How do I play with a gamepad on the PC? I've got a steam controller connected but it doesn't work when in VR :(

**Comment by vrokolos** [comment]
Well after testing a lot: It works fine with xbox 360 controller but not with steam controller. wtf
