### ISSUE TITLE
Oculus Go and SteamVR Error Component not working

### ISSUE THREAD

**Issue by Polarborn** [polygraphene/ALVR#95]
I cannot get ALVR to start server.  When first launch, box flashes stating cannot find headset, disappears then server appears to start then stops.  At same time, Steam VR launches then has error where key component missing.  Items tried:
1) Reinstall VRsteam - done and works with Riftcat 
2) Checked and changed install path for driver - now points to Steam on correct drive and folder
3) Disabled Steam sound in ALVR, disabled other options - same error
4) Tried on different  compute with Geforce 900 series card - same error
5) Running Windows 10, Nvidia, 570 Geforce with latest driver (realize this is older card but works with Riftcat)

Any other suggestions?

Polar

**Comment by vrokolos** [comment]
"key component missing" for me was happening when I tried to install PSMOVESERVICE and I didn't install the driver correctly.

Try listing and uninstalling all drivers from ALVR and then installing a single one.

Also try restarting

**Comment by vrokolos** [comment]
Ah nevermind GeForce GTX 570 doesn't support nvenc / shadowplay I think. Go check it out

**Comment by ciddester** [comment]
I am having the same error: Component of steam VR isn't working properly . The graphic is up-to date. I have installed ALVR several times. I also try to add the ALVR drivers into the driver on steamvr. I have looked online how to resolve this issue but nothing. Let me know if anyone of you found the solution.
Thanks you.

**Comment by vrokolos** [comment]
You need at least Geforce 630+ and still some of them don't have NVENC support. Riftcat doesn't depend on it but ALVR absolutely needs it and will not run without it. That "Component" error comes up when the driver is not properly installed or you don't have a supported graphics card. Please check your GPU support before even trying to run ALVR. The older GPUS you can see pressing the button bellow the first table. If your GPU is not listed as NVENC compatible ALVR will not work.

Here are the card support: https://developer.nvidia.com/video-encode-decode-gpu-support-matrix

**Comment by limno97** [comment]
Hm im getting the same error of server is not running and a key component of steamvr is not working. do seem to have a GeForce GTX 1060 which looks like it should work but idk..

**Comment by vrokolos** [comment]
Make sure all drivers are uninstalled from the drivers tab and then install a single one and try again

**Comment by limno97** [comment]
Sorry, im bad at this kind of thing. how do i do that?

**Comment by vrokolos** [comment]
Open the about tab on ALVR and click list drivers. Show me what you see

**Comment by limno97** [comment]
ah hm.
![driver](https://user-images.githubusercontent.com/40625041/41960244-63f8704a-7a43-11e8-9e17-5b47bd52ecd7.PNG)

**Comment by vrokolos** [comment]
Try uninstall driver and then reinstall

Also what is that MixedRealityVRDriver? Do you have another headset?

**Comment by limno97** [comment]
im not sure about mixedreality. only have the gear vr. 

for the desktop location, do seem to have the driver_uninstall batch but dont for the mixedrealityvrdriver, maybe i should deleted the whole folder if i cant uninstall? dont even know what it is lol
![mixed](https://user-images.githubusercontent.com/40625041/41961069-89b799d0-7a45-11e8-94fb-6d7a933b05ad.PNG)

**Comment by limno97** [comment]
did try uninstall the one in desktop, and checking the list again. theres only one driver (which is in the mixedreality). then i tried start server again, but same thing where i get server is down, again.

also tried uninstall driver which is above the list and only the mixedreality one is there, duno if it can be uninstalled

**Comment by VRtinker** [comment]
@limno97 
try to start the server without having the option "Stream sound" selected under the "Sound" tab. You can get the "missing component" error ALSO if your Windows sounds settings are set below 48000hz.

**Comment by limno97** [comment]
oh doing a google search the mixedreality thing seemed to have been this https://store.steampowered.com/app/719950/Windows_Mixed_Reality_for_SteamVR/

did just uninstall it and now the driver and stuff is gone for it

**Comment by limno97** [comment]
So now only have one driver in D:Desktop\ALVR\ALVR\driver\. tried starting server and still have the same error

@VRtinker. just tried no steam sound option and no luck either

**Comment by vrokolos** [comment]
Is your gpu driver updated to latest release?

**Comment by limno97** [comment]
yea i actually checked that while looking some info a bit ago. seems to be updated
![updated](https://user-images.githubusercontent.com/40625041/41961787-79fd87a0-7a47-11e8-8b9e-c0e3af3392b4.PNG)

**Comment by vrokolos** [comment]
Use GeForce experience to check for new drivers or go to nvidia web site

**Comment by VRtinker** [comment]
>  just tried no steam sound option and no luck either.
not sure how check the windows sounds setting tho

> 

Right click on the sound icon on the taskbar and click on "open sound settings". Then click on "device properties" on the window that opens. From there go to the "Advanced" tab and make sure you've got something that's not "CD Quality".

Updating video drivers will likely be useless. Instead, make sure that SteamVR runs without error 301 if executed outside of of ALVR. You should get error 108 instead (headset missing). If you are REALLY missing a component, you would instead still get the same error 301, at which point I would suggest you uninstall/reinstall steam/steamVR instead. Steam would not complain about missing components referring to drivers of a particular video card. It wouldn't know about it, nor care. GeForce Experience is mostly bloatware, especially when dealing with VR games.

**Comment by limno97** [comment]
for the driver, did just install that one there and still get the error. have also tried install/uninstall steamvr a few times.

and for the sound i have this
![sound](https://user-images.githubusercontent.com/40625041/41963039-b6a591e0-7a4a-11e8-976b-fbed8e019958.PNG)

im not sure, it does say missing specifically. it says a key component of steamvr isnt working properly

**Comment by VRtinker** [comment]
Sorry, I meant "device properties" of your "output device" not "input" (the window that opens will be called "Speakers Properties" not "Microphone Properties".

You are right, when the issue is related to the audio sample rate missmatch, the error you get in SteamVR is "A key component of SteamVR isn't working properly (301)". But when you run SteamVR without opening ALVR, you should only get the "headset not detected" instead (this will indicate that the issue is related to ALVR and not SteamVR iteself. If you get anything else, like I said, reinstall Steam/SteamVR (or you could try to have Steam verify the integrity of SteamVR)

**Comment by crimson-woof** [comment]
It looks like you don't have SteamVR installed in the default C: drive.  Could you try reinstalling SteamVR on your C: drive?

**Comment by limno97** [comment]
ah i see. so checked the output and its at 24 bit, 48000 hz (studio quality) atm
yea do get 'headset not detected' when running without ALVR (so guess it is to do with ALVR)
hm have tried reinstalling VR, might not be bothered with steam itself tho tbh since i have a bunch of stuff on, and have tried integrity :/
eh idk. its aight if it doesnt work, just looks like a neat thing to try, just got the gear vr last week and have tried riftcat a bit. thanks a bunch of everyone's help tho

**Comment by limno97** [comment]
@crimson-woof  
sorry was that for OP or for me? i did kinda hijack the thread..

**Comment by vrokolos** [comment]
@limno97 try what @crimson-woof  said

**Comment by VRtinker** [comment]
Mind that even if the core of your Steam installation is on your D drive, you will still have a Steam folder in c:\program files(x86)\steam
You want the ALVR driver to get tied to the files in D:\Steam Games\steamapps\common\SteamVR, not the C: one

**Comment by limno97** [comment]
@VRtinker
oh, i dont actually have the steamVR folder in D:\Steam Games\steamapps\common\SteamVR

just saw your previous message. how do you modify the bat files?

**Comment by VRtinker** [comment]
You should still edit the bat files (even if you don't have two Steam folders like I do), since you don't have Steam installed at the default location. Just open each of them with notepad and modify the path hardcoded in them.

**Comment by limno97** [comment]
so i just change to like this?

@echo off
"D:\Steam Games\steamapps\common\SteamVR.exe" adddriver "%~dp0

**Comment by vrokolos** [comment]
I'm trying to understand your folder structure. You've got steam installed on c: but have another game library on d:?

and you've installed steam on c: and steamvr on d:? 

Why not install steamvr on c: and not change anything?

**Comment by limno97** [comment]
sorry for the confusion.
so steam is installed on c: and my games are installed on d: yea
though steamvr is installed in the commons in c: not with the games in d:
hope that makes sense

**Comment by polygraphene** [comment]
Can you try new alpha version?
https://github.com/polygraphene/ALVR/releases/tag/v2.2.0-alpha
It produces more error message so you can debug the problem.
You don't need to install client.

**Comment by limno97** [comment]
alright, should i delete the folder for the previous version?

**Comment by polygraphene** [comment]
Can you see crash log file on ALVR install folder?
If you have, please upload the file.

**Comment by limno97** [comment]
is it this?
[ALVR_CrashLog_20180627_231157.log](https://github.com/polygraphene/ALVR/files/2141006/ALVR_CrashLog_20180627_231157.log)

**Comment by polygraphene** [comment]
Yes!
Thank you.

It is caused by NVENC initialization code.
I added more detailed log about it.
Please try it and re-upload crash log.
https://github.com/polygraphene/ALVR/releases/tag/v2.2.1-alpha

**Comment by limno97** [comment]
Sorry for the delay, went to bed,

[ALVR_CrashLog_20180628_093106.log](https://github.com/polygraphene/ALVR/files/2143014/ALVR_CrashLog_20180628_093106.log)

**Comment by polygraphene** [comment]
Okay. I went to bed too.

Server won't work properly until remove this error.
Did you reboot the PC after graphic driver upgrade?

**Comment by limno97** [comment]
yea i restarted, just restarted again to make sure

**Comment by VRtinker** [comment]
> yea i restarted, just restarted again to make sure. not sure how to remove this error

Maybe try to uninstall the gpu drivers using [DDU](http://www.guru3d.com/files-details/display-driver-uninstaller-download.html) and then perform a "clean install". Looks like you might have been on the Windows default NVIDIA drivers earlier and maybe when you installed the package directly from Nvidia it didn't install/update the NVENC portion (spit-balling here, but it might be worth a try - it just costs 2 reboots)

**Comment by limno97** [comment]
oh wait, i just checked geforce again and there was another update or something so i just updated and restarted. now server is ready and am up to the step 'SteamVR's small window will appear. You should see a headset icon in the SteamVR status window that looks like a green block with a bold S in the middle' and am now hacing to run room setup. 

can update with how it goes

**Comment by vrokolos** [comment]
I saw lots of packet loss on your picture. Thats probably the reason for your black screen. Are you connected using 5 GHz? Try running iperf on your lan. What kind of packet loss do y ok u have?

**Comment by limno97** [comment]
yea im connected using 5 GHz on both laptop and the s8. by lan you mean connecting to ethernet cable? and is this the right thing for iperf? i can seem to open the application 
![iperf](https://user-images.githubusercontent.com/40625041/42018438-3991a9de-7b06-11e8-87bb-92fa35b4177d.PNG)

**Comment by vrokolos** [comment]
yeah sorry not lan. Just test your wifi udp speed and stability using any benchmark like iperf. Read some guides on it. I never used it myself.

**Comment by limno97** [comment]
ah, i cant open the iperf app tho

**Comment by limno97** [comment]
hm did just realise theres some stuff about packet on alvr? 
![packet](https://user-images.githubusercontent.com/40625041/42019982-ac5644da-7b0a-11e8-988b-e73783349d5a.PNG)

**Comment by polygraphene** [comment]
You get a lot of packet loss (or out-of-order packet).
You need some fix on Wi-Fi or to use USB tethering.
