### ISSUE TITLE
the edges of display are black on rotation

### ISSUE THREAD

**Issue by gb2111** [polygraphene/ALVR#99]
hi.
it seems there is effect that rotation if faster then rendering itself and as result during rotation of head we get black edges. is this possible to address this ?
it is not really a high priority for me but would make it much closed to other commercial headsets.
perhaps render a bit wider area so it can be used when rotating head?

g

**Comment by polygraphene** [comment]
We may get picture of wider area, how we put the texture for headset (Oculus Mobile SDK)?
I think we need to implement ATW like algorithm to properly slide the texture for SDK.
It is very hard work and takes very long time.

Reducing latency is also effective for this problem. ALVR work in following steps.
1. (Headset) Get and send tracking data
2. (Server) Receive tracking data and produce VSync event
3. (Server) Wait for game to render texture.
4. (Server) Compose texture and encode and send to headset
5. (Headset) Receive texture and decode and render

I think we can more tune around step 2.

**Comment by gb2111** [comment]
ok. thanks for clarification. 
i am not opting to do hard work on it. very happy with how it works now :)

**Comment by gb2111** [comment]
one solution for this could be to predict a little rotation of headset and display content for displayed rotation.
